Personal/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Answer__c.object
<CustomObject>
    <description>Captures the response for a Discovery Question to the respective Workbook and associated with a Project.</description>
    <fields>
        <fullName>Cloneable__c</fullName>
        <formula>Question__r.Cloneable__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cloneable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Currency_Answer__c</fullName>
        <label>Currency Answer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_Answer__c</fullName>
        <label>Number Answer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Category__c</fullName>
        <formula>&apos;Removed&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Discovery Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text_Answer__c</fullName>
        <label>Text Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>YesNo_Answer__c</fullName>
        <label>Yes/No Answer</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Discovery Answer</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Discovery_Workbook_Category__c.object
<CustomObject>
    <description>Contains the Workbook capturing questions, responses, interviewees, interviewers; and associated with a Project and Site.</description>
    <fields>
        <fullName>Question_Category__c</fullName>
        <label>Question Category</label>
        <referenceTo>Question_Category__c</referenceTo>
        <relationshipName>Discovery_Workbook_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site_Workbook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Workbook</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Site_Workbook__c</referenceTo>
        <relationshipLabel>Discovery Site Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Workbook</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Site Workbook Category</label>
    <nameField>
        <displayFormat>DW-{00000}</displayFormat>
        <label>Discovery Workbook Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbook Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Question__c.object
<CustomObject>
    <description>Contains the Questions used during Discovery with association to Dealership Need and Product.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cloneable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cloneable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Discovery Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Question_Category__c.object
<CustomObject>
    <description>Contains the categorization of Dealership Needs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field determines whether the Dealership Need is Active or not. Making it false logically logically deletes this record</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealership Need</label>
    <nameField>
        <label>Dealership Need Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealership Needs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Site_Workbook__c.object
<CustomObject>
    <description>Junction object to allow associating a Workbook with a Project and Site.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Discovery Site Workbooks</relationshipLabel>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Site Workbook</label>
    <nameField>
        <displayFormat>SW-{00000000}</displayFormat>
        <label>Site Workbook ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_CloneWorkbook_Test.cls
/*------------------------------------------------------------
Author: Rey Austral
Company: Cloud Sherpas
Description: Test class for IMP_CloneWorkbook_Helper
Test Class:
History
10/09/14    Rey Austral         Created
11/18/14    Samuel Oberes       Implemented IMP_TestFactory_Helper methods
------------------------------------------------------------*/
@isTest
public class IMP_CloneWorkbook_Test {
    /*static testMethod void cloneWorkbookPositiveTest()
    {
        Project__c proj = generate_Project();
        Account acc = generate_Account();
        Site_Workbook__c siteWorkbook = generate_SiteWorkbook(proj.Id,acc.Id);        
        Discovery_Workbook_Category__c wCategory = GenerateTestData_Project(siteWorkbook.Id);
        Account actTarget = IMP_TestFactory_Helper.buildAccount(); //Target Site
        Insert actTarget;
        
        IMP_CloneWorkbook_Helper clone = new IMP_CloneWorkbook_Helper();
        test.startTest();
        clone.cloneWorkBook(proj.Id, actTarget.Id, siteWorkbook.Id);
        test.stopTest();
        
        List<Question__c> nonCloneable = [Select Id,Name From Question__c where Cloneable__c = false];
        List<Question__c> Cloneable = [Select Id,Name From Question__c where Cloneable__c = true];
        List<Answer__c> ansNonCloneable = [Select Id,Name,Text_Answer__c From Answer__c where Discovery_Workbook_Category__c != :wCategory.id and Question__c In: nonCloneable and Text_Answer__c != null  ];
        List<Answer__c> ansCloneable = [Select Id,Name,Text_Answer__c From Answer__c where Discovery_Workbook_Category__c != :wCategory.id and Question__c In: Cloneable and Text_Answer__c != null  ];
        List<Answer__c> allTargetAns = [Select Id,Name,Text_Answer__c From Answer__c where Discovery_Workbook_Category__c != :wCategory.id ];
        List<Site_Workbook__c> targetSiteCreated = [Select Id,Name From Site_Workbook__c where Site__c != : actTarget.Id];
        //check if non-cloneable question has answer
        system.assertEquals(0, ansNonCloneable.size());
        //check if target question w/ cloneable has answer 
        system.assertEquals(3, ansCloneable.size());
        //check if all answer has been inserted
        system.assertEquals(10, allTargetAns.size());
        //check if target site is created
        system.assertEquals(1, targetSiteCreated.size());
    }
    
    static testMethod void cloneWorkbookSiteAlreadyExist()
    {
        Project__c proj = generate_Project();
        Account acc = generate_Account();
        Site_Workbook__c siteWorkbook = generate_SiteWorkbook(proj.Id,acc.Id);        
        GenerateTestData_Project(siteWorkbook.Id);
        
        IMP_CloneWorkbook_Helper clone = new IMP_CloneWorkbook_Helper();
        test.startTest();
        String result = clone.cloneWorkBook(proj.Id, acc.Id, siteWorkbook.Id);
        test.stopTest();
        system.assertEquals('The Site you have chosen already has a workbook for this project.  Please utilize it to continue your discovery, or if you intended to select a different site, please try selecting again.', result);
    }
    
    private static Project__c generate_Project()
    {
        Project__c proj = IMP_TestFactory_Helper.buildProject(0); //Project Test For Clone
        Insert proj;
        
        return proj;
    }
    
    private static Account generate_Account()
    {
        List<Account> insertAccount = new List<Account>();
        Account actSource = IMP_TestFactory_Helper.buildAccount(); //Source Site
        insertAccount.add(actSource);            
        
        
        return actSource;
    }
    
    private static Site_Workbook__c generate_SiteWorkbook(Id projectId, Id AccountId)
    {
        Site_Workbook__c siteWorkbook = IMP_TestFactory_Helper.buildSiteWorkbook(projectId);
        siteWorkbook.Site__c = AccountId;
        Insert siteWorkbook;  
        
        return siteWorkbook;
    }
    
    private static Discovery_Workbook_Category__c GenerateTestData_Project(Id siteWorkBookId)
    {   
        Question_Category__c qCategory = IMP_TestFactory_Helper.buildDealershipNeed();
        insert qCategory;
        
        Discovery_Workbook_Category__c wCategory = IMP_TestFactory_Helper.buildDiscoveryWorkbookCategory(qCategory.Id);
        wCategory.Site_Workbook__c = siteWorkBookId;
        Insert wCategory;
        
        List<Question__c> insertQuestion = new List<Question__c>();
        for (Integer ctr = 0; ctr< 10; ctr++) {
            Question__c quest = IMP_TestFactory_Helper.buildQuestion(qCategory.Id, 
                                                                     IMP_TestFactory_Helper.Enum_MarketList.MANUAL_INPUT_OF_DEFAULT_VALS, 
                                                                     IMP_TestFactory_Helper.Enum_ProjectTypeList.MANUAL_INPUT_OF_DEFAULT_VALS);
            quest.Active__c = true;
            quest.Question_Text__c = 'This is a test question for item ' + String.valueOf(ctr);
            
            if (math.mod(ctr, 3) == 0) {
                quest.Cloneable__c = false;
            } else {
                system.debug(ctr + ' - Clone Question');
                quest.Cloneable__c = true;
            }
            insertQuestion.add(quest);
        }
        
        insert insertQuestion;
        
        List<Answer__c> insertAnswer =  new List<Answer__c>();
        Integer ctr2 = 0;
        for (Question__c questions : insertQuestion)  {
            Answer__c ans = IMP_TestFactory_Helper.buildAnswer(wCategory.Id, questions.Id);
            if (math.mod(ctr2, 2) == 0) {
                system.debug(ctr2 + ' - w/Answer ' + questions.Id);
                ans.Text_Answer__c = 'Source Answer' + questions.Id;
            } else {
                ans.YesNo_Answer__c = null;
                ans.Number_Answer__c = null;                
                ans.Currency_Answer__c = null;
                ans.Text_Answer__c = null;
            }
            ctr2++;
            insertAnswer.add(ans);
        }
        Insert insertAnswer;
        
        return wCategory;
    }*/
}