Personal/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Account_Team__c.object
<CustomObject>
    <description>A custom object designed to mimic the standard account team, where all CRED is controlled by this object.</description>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>AccountTeamAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N40000001mDRREA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Advocate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Advisor - Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Services CAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Services GAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Digital Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Sales Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Baseline Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - CDP ISR Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Dealix Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Digital Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Enterprise Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Inside Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - National Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - NIADA Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Retail Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Saturn Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Telephony Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Analyst2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Regional Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Strategist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National/Enterprise DSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Forecasting Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Marketing (DAP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Improvement Consultant</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Team</label>
    <nameField>
        <displayFormat>Acct Member ID {0000000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/CMF_Info__c.object
<CustomObject>
    <description>Core BU based identifier numbers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CMF Info</relationshipLabel>
        <relationshipName>R00N40000001leBEEAY</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CMF_Replaced__c</fullName>
        <label>CMF Replaced</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_CMF__c</fullName>
        <externalId>true</externalId>
        <label>Ship CMF</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMF Info</label>
    <nameField>
        <label>CMF Info</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMF Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/CustomSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Centralized list of parameters to be modified when refreshing Training or FullDev sandboxes</description>
    <fields>
        <fullName>DS_SalesTeamTrigger_On__c</fullName>
        <defaultValue>true</defaultValue>
        <label>DS Sales Team Trigger On?</label>
        <type>Checkbox</type>
    </fields>
    <label>CustomSettings</label>
</CustomObject>

SF Primes/src/objects/Site_Type__c.object
<CustomObject>
    <description>List of possible Site Type attributes for an account</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Group Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Site Type</label>
    <nameField>
        <label>Site Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/System_at_Dealership__c.object
<CustomObject>
    <description>Systems identified at a specific dealership</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Systems at Dealership</relationshipLabel>
        <relationshipName>R00N40000001leejEAA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Type__c</fullName>
        <label>System Type</label>
        <picklist>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>Systems at Dealership (Vendor)</relationshipLabel>
        <relationshipName>R00N40000001lfXZEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System at Dealership</label>
    <nameField>
        <displayFormat>ID - {00000}</displayFormat>
        <label>Sys at Dealership</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems at Dealership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Systems__c.object
<CustomObject>
    <description>List of valid DMS/CRM/Leasing/Phone systems</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Systems</label>
    <nameField>
        <label>Vendor System</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DS_Opportunity_Handler_Test.cls
@IsTest
public class DS_Opportunity_Handler_Test 
{
    @testsetup static void setupTestData() {
       
       
        list<User> users = new list<User>();
        
        users.add(DS_TestObjects.NewUser());
        users.add(DS_TestObjects.NewUser());
        users[0].ProfileId = [SELECT Id from Profile Where Name Like '%Baseline%' LIMIT 1].Id;
        users[1].ProfileId = users[0].ProfileId;
        insert users;
        
         CustomSettings__c cs = new CustomSettings__c();
        cs.DS_SalesTeamTrigger_On__c = true;
        cs.Users_To_Exclude_CPQ_Approval__c = users[0].FirstName + ' ' + users[0].LastName ;
        insert cs; 
        
        Site_Type__c site = new Site_Type__c();
        site.Name = 'Group';
        site.Group_Flag__c = true;
        site.Active__c = true;
        insert site;
        
        //2017-04-21 ragashalini.koka@cdk.com - Added PartyID__c field for Account
        Account acct = new Account(Name='Test Acct 1');
        acct.Site_Type__c = site.Id;
        acct.PartyID__c = String.valueOf(Math.round(Math.random()*1000));
        insert acct;
       
        System.debug('test' + [select id,Dealer_Group_Name2__c from account where id=:acct.Id]);
        
        
        
        Account_Team__c atc1 = new Account_Team__c(
            Account__c = acct.Id, 
            Team_Member__c = users[0].Id, 
            Team_Role__c = 'Forecasting - Alliance Unhook', 
            Account_Access__c = 'Read Only', 
            Opportunity_Access__c = 'Read Only', 
            Case_Access__c = 'Read Only'
        ); insert atc1;
        
        Account_Team__c atc2 = new Account_Team__c(
            Account__c = acct.Id, 
            Team_Member__c = users[1].Id, 
            Team_Role__c = 'Forecasting - Alliance Upgrade', 
            Account_Access__c = 'Read Only', 
            Opportunity_Access__c = 'Read Only', 
            Case_Access__c = 'Read Only'
        ); insert atc2;
        
        Systems__c sys = DS_TestObjects.NewCRMSystem();
        insert sys;
        
        System_at_Dealership__c sat = new System_at_Dealership__c(
            Account__c = acct.Id, 
            Vendor__c = sys.Id, 
            System_Type__c = 'DMS'
        ); insert sat;
        
        String today = String.valueOf(DateTime.now().format('dd/MM/YYYY'));
        today = today.replaceAll('/','-');
        
        CMF_Info__c cmfRecord = DS_TestObjects.NewCMFInfo();
        cmfRecord.Account__c = acct.Id;
        cmfRecord.SLS_Baseline_CMF_Number__c = '1234';
        cmfRecord.Ship_CMF__c = '1234';
        cmfRecord.Status__c = 'A';
        cmfRecord.CMF_Replaced__c = 'Test';
        cmfRecord.SLS_Ownership_Change_Type__c = 'Test';
        insert cmfRecord;
        
        Map<Id,CMF_Info__c> CMFInfoMap = new Map<Id,CMF_Info__c>([
            SELECT Id, SLS_Baseline_CMF_Number__c, Ship_CMF__c, Account__c, CMF_Replaced__c 
            FROM CMF_Info__c 
            WHERE Status__c = 'A' AND CMF_Replaced__c != null AND 
            ((NOT SLS_Ownership_Change_Type__c LIKE '%Shared System%') OR SLS_Ownership_Change_Type__c = null)
            AND Account__c = :acct.Id
        ]);
	
        System.debug('CMF Info Map Test :' + CMFInfoMap);
        
    }
    public static testmethod void testUpdateOpp()
    {
      
        Account acct = [SELECT Id FROM Account LIMIT 1];
        User usr = [SELECT Id FROM User ORDER By CreatedDate desc LIMIT 1];
        System_at_Dealership__c sat = [SELECT Id FROM System_at_Dealership__c LIMIT 1];
        test.startTest();
         Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity 1', 
            AccountId = acct.Id, 
            DMS_Platform__c = 'Web 2k', 
            Type = 'Unhook', 
            CloseDate = Date.today(), 
            StageName = 'Plan', 
            ADP_Opportunity_Owner__c = usr.Id,
            CPQ_Data_Consent_Changes__c = acct.Id+'$,$1/06/2015$,$10/6/2016$,$Yes$,$FRONT OFFICE EDGE DATA CONSENT###'+
            acct.Id+'$,$1/06/2015$,$10/6/2016$,$Modified$,$MENU DATA CONSENT###',
            SLS_Buyer_Account__c = acct.Id
        ); insert testOpp;
        List<Opportunity_Location__c> oppLocationList = [select  Id, Site__r.Dealer_Group_Name2__c, Opportunity__r.SLS_Buyer_Account__r.Dealer_Group_Name2__c, Opportunity__r.AccountId 
                                                         from opportunity_location__c where opportunity__c=:testOpp.Id and RecordType.Name='Site'];
        //System.debug('opportunity locations :' + oppLocationList[0].Site__r.Dealer_Group_Name2__c + '----' + oppLocationList[0].Opportunity__r.SLS_Buyer_Account__r.Dealer_Group_Name2__c );
        testOpp.DMS_Platform__c = 'Web 1k';
        update testOpp;
        
        testOpp.DMS_Platform__c = 'Web 2k';
        update testOpp;
        
        delete sat;
        
        testOpp.DMS_Platform__c = 'Web 1k';
        update testOpp;
        test.stopTest();
        
    }
}