SF Primes/src/objects/Account_Plan__c.object
<CustomObject>
    <description>This object houses the Account Plan for a Digital Services specialist.  The Account Plan specifically pertains to the WebID object.  There may be multiple account plans across an account for a position if there is more than one webid, but there should only be one Account Plan per specialist per WebID.</description>
    <fields>
        <fullName>AA_Echelon_Level__c</fullName>
        <formula>WebID__r.AA_Echelon_Level__c</formula>
        <inlineHelpText>This is calculated from active installed base. If you see an echelon product that is active, have your manager submit an Inquiry - Service Reports &amp; Applications case with the webid and product.</inlineHelpText>
        <label>AA Echelon Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Advocate__c</fullName>
        <description>This field pulls the Advocate value from the Webid.</description>
        <formula>WebID__r.Account_Advocate__r.FirstName &amp; &quot; &quot; &amp; WebID__r.Account_Advocate__r.LastName &amp; 
IF( isblank(WebID__r.Account_Advocate__r.Extension ), &quot;&quot;, &quot; - Ext: &quot;&amp; WebID__r.Account_Advocate__r.Extension )</formula>
        <label>Account Advocate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BAC_Dealer_Code__c</fullName>
        <description>Pulls from the same field on the related WebID.</description>
        <formula>WebID__r.BAC_Dealer_Code__c</formula>
        <label>BAC/Dealer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DA_Echelon_Level__c</fullName>
        <formula>IF(OR( DA_Echelon_Manager_Override__c =&quot;&quot;, ISBLANK(DA_Echelon_Manager_Override__c )), TEXT(DA_Echelon_Spend_Level__c) , DA_Echelon_Manager_Override__c )</formula>
        <inlineHelpText>If the DA Echelon Manager Override field is filled out, that is the Echelon level, otherwise it is based on Spend.</inlineHelpText>
        <label>DA Echelon Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Group_Name__c</fullName>
        <formula>Account__r.Dealer_Group_Name2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Group Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field is maintained through the nightly process and may lag behind the WebID indicator by one day.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose a WebID on the Account Plan’s associated Account.</errorMessage>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Pulls Account zip code for OOS login.</description>
        <formula>Account__r.CBLTZip__c</formula>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/CustomSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Centralized list of parameters to be modified when refreshing Training or FullDev sandboxes</description>
    <fields>
        <fullName>CDK_Global_Account_Id__c</fullName>
        <description>Ignore Contact Duplicate Checking for this Account Id. Also, this Account Id is used to set the HR Default Case Account.</description>
        <inlineHelpText>Ignore Contact Duplicate Checking for this Account Id. Also, this Account Id is used to set the HR Default Case Account.</inlineHelpText>
        <label>CDK Global Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CustomSettings</label>
</CustomObject>

SF Primes/src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds global settings for the various triggers and apex jobs to function. The only thing that should be modified outside of a pod switch is the error reporting email, which is a comma separated list. Example: &apos;tlaporte@centerstance.com,psaini@cobaltgroup.com&apos;</description>
    <fields>
        <fullName>Email_2_Case_User__c</fullName>
        <description>Used in CB_UpdateContactAccount.trigger. This e-mail is the UserName (in the form of an e-mail address) for the e-mail to Case functionality.</description>
        <inlineHelpText>This e-mail is the UserName (in the form of an e-mail address) for the e-mail to Case functionality.</inlineHelpText>
        <label>Email 2 Case User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

SF Primes/src/objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>AA_Echelon_Level__c</fullName>
        <formula>IF( ProCare_Gold__c &gt; 0, &quot;Audience Optimization&quot;, IF( GM_Performance_ProCare__c &gt;0, &quot;GM Performance&quot;,IF( ProCare_Silver__c &gt;0,&quot;ProCare&quot;,IF( Procare_Product__c &gt;0,&quot;ProCare&quot;,&quot;No ProCare&quot;))))</formula>
        <inlineHelpText>This is based on active installed base. If you see a ProCare echelon product that is active in the installed base that is not represented, submit an Inquiry - Service Reports &amp; Applications case with the webid &amp; product as examples.</inlineHelpText>
        <label>AA Echelon Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Advocate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Advocate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Website</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BAC_Dealer_Code__c</fullName>
        <description>Text field for user to enter the dealer&apos;s BAC or dealer code. This is then used through the OOS button to populate the OOS login page.</description>
        <inlineHelpText>Enter the Dealer Code(BAC, if GM) here and it will auto-fill the OOS</inlineHelpText>
        <label>BAC/Dealer Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DA_Echelon_Level__c</fullName>
        <label>DA Echelon Level</label>
        <picklist>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platinum</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Group_Name__c</fullName>
        <formula>Account__r.Dealer_Group_Name2__c</formula>
        <label>Dealer Group Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Online_Marketing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Digital Advertising Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Website1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box when the Cobalt website is the dealer&apos;s primary website. Leave flag unchecked if the site is secondary.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Webnum__c</fullName>
        <label>Webnum</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Pulls account zip code</description>
        <formula>Account__r.CBLTZip__c</formula>
        <inlineHelpText>Account Zip Code. Used as the Dealer&apos;s OOS password.</inlineHelpText>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Personal/src/objects/Zip_Code__c.object
<CustomObject>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DSCB_CaseReferenceFields.cls
public class DSCB_CaseReferenceFields
{
    public static void SetCaseReferenceFields(list<Case> NewCaseList)
    {
        list<String> WebIds = New list<String>();
        list<String> AccountIds = new list<String>();
        set<ID> AccountPlanIDs = new set<ID>();
        
        for(Case c: NewCaseList) 
        {
            WebIds.add(c.WebID__c);
            AccountIds.add(c.AccountId);
            AccountIds.add(c.Destination_Account__c);
            AccountPlanIDs.add(c.Account_Plan__c);
        }
        
        system.debug(AccountPlanIDs);
        
        map<Id, WebID__c> WebIdMap = new map<Id, WebID__c>([
            select Id, BAC_Dealer_Code__c, Webnum__c, Online_Marketing_Specialist__r.FirstName, Online_Marketing_Specialist__r.lastName,
                Online_Marketing_Specialist__r.Extension, Primary__c, Account_Advocate__r.FirstName, Account_Advocate__r.LastName,
                Account_Advocate__r.Extension, AA_Echelon_Level__c, DA_Echelon_Level__c 
            From WebID__c 
            where Id IN :WebIds
        ]);
        
        // query account plans that are related to these trigger.new cases
        map<ID, Account_Plan__c> AccountPlanMap = new map<ID, Account_Plan__c>([
            select ID, Name, DA_Echelon_Level__c
            From Account_Plan__c
            Where ID IN :AccountPlanIDs
        ]);
        
        system.debug(AccountPlanMap);
        
        map<Id, Account> AccountIdMap = new map<Id, Account>([
            Select Id, name, Account_Number__c, Org_Key__c, CBLTZip__c //, Dealer_Group_Name2__c
            From Account 
            where Id IN :AccountIds
        ]);
        
        for(Case c : NewCaseList)
        {
            if(WebIdMap != null && !WebIdMap.IsEmpty() && WebIdMap.containskey(c.webid__c))
            {
                WebID__c w = WebIdMap.get(c.WebID__c);
                Account_Plan__c ap = AccountPlanMap.get(c.Account_Plan__c);
                system.debug(ap);
                
                if(w != null){ c.BAC_Dealer_Code__c = w.BAC_Dealer_Code__c;}
                if(w != null){ c.AA_Echelon_Level__c = w.AA_Echelon_Level__c;}                
                if(w != null){ c.DA_Echelon_Level__c = w.DA_Echelon_Level__c;} // getting this value from WebId instead of account plan changed to this after
                                                                               // the request RQ-03704
                
                if(w.Account_Advocate__r != null)
                {
                    if(w.Account_Advocate__r.Extension !=null) 
                    {
                        c.Account_Advocate__c 
                            = w.Account_Advocate__r.FirstName + ' ' 
                                + w.Account_Advocate__r.lastName 
                                + ' - Ext: ' + w.Account_Advocate__r.Extension;
                    }
                    else 
                    {
                        c.Account_Advocate__c 
                            = w.Account_Advocate__r.FirstName + ' ' 
                                + w.Account_Advocate__r.LastName;
                    }
                }
                else 
                {
                    c.Account_Advocate__c = '';
                }
               
                if(w.Online_Marketing_Specialist__r != null)
                {
                    if(w.Online_Marketing_Specialist__r.Extension != null) 
                    {
                        c.Online_Marketing_Specialist__c 
                            = w.Online_Marketing_Specialist__r.FirstName + ' ' 
                                + w.Online_Marketing_Specialist__r.lastName 
                                + ' - Ext: ' + w.Online_Marketing_Specialist__r.Extension;
                    }
                    else 
                    {
                        c.Online_Marketing_Specialist__c 
                            = w.Online_Marketing_Specialist__r.FirstName + ' ' 
                                + w.Online_Marketing_Specialist__r.lastName;
                    }
                }
                else 
                {
                    c.Online_Marketing_Specialist__c = '';
                }
                
                //if(w.Primary__c == True) {
                //    c.Primary_Site_Status__c = 'Primary';
                //}
                //else {
                //    c.Primary_Site_Status__c = 'Secondary';
                //}
                
                c.WebNum__c = w.Webnum__c;
            }
            
            if(AccountIdMap != null && !AccountIdMap.IsEmpty() 
            && AccountIdMap.containsKey(c.AccountId))
            {
                Account a = AccountIdMap.get(c.AccountId);
                
                c.Account_Number__c = a.Account_Number__c;
                //c.Dealer_Group_Name__c = a.Dealer_Group_Name2__c;
                c.Zip_Code__c = a.CBLTZip__c;
            }
            
            if(AccountIdMap != null && !AccountIdMap.IsEmpty() 
            && AccountIdMap.containsKey(c.Destination_Account__c))
            {
                Account a = AccountIdMap.get(c.Destination_Account__c);
                
                c.Destination_Oracle_Customer__c = a.Account_Number__c;
                c.Destination_Org_Key__c = a.Org_Key__c;   
            }
        }
    }
    
    public static void CaseDefaultAccount(list<Case> DefaultAccountCases)
    {
        // DS_CaseDefaultAccount        
        CustomSettings__c settings = CustomSettings__c.getInstance();
        
        if(settings.CDK_Global_Account_Id__c != null)
        {  
            if(DefaultAccountCases != null && !DefaultAccountCases.isEmpty())
            {                       
                for(Case c : DefaultAccountCases)
                {
                    c.AccountId = settings.CDK_Global_Account_Id__c;
                }
            }
        }                
    }
    
    public static void CaseUserManager(list<Case> UserManagerCases, Map<Id, Case> oldMap)
    {
        if(UserManagerCases != null && !UserManagerCases.isEmpty())
        {                   
            for(Case NewCase : UserManagerCases) 
            {
                Case OldCase = oldMap != null ? oldMap.get(NewCase.Id) : null;
                if(OldCase == null) { OldCase = new Case(); }
                
                // 2014-10-14 from Christy Silveira - upon Owner change 
                if(NewCase.OwnerId != OldCase.OwnerId)
                {
                    String NewCaseOwnerId = String.valueOf(NewCase.OwnerId);
                    String OldCaseOwnerId = String.valueOf(OldCase.OwnerId);
                    
                    // 2014-10-14 CS - update owner lookup with new owner
                    //   if new owner is not a queue then current Owner
                    if(NewCaseOwnerId != null && !NewCaseOwnerId.startsWith('00G')) { 
                        NewCase.Owner_Lookup__c = NewCase.OwnerId; }
                    else { // 2014-10-14 CS - if new owner is queue then NULL 
                        NewCase.Owner_Lookup__c = null; }
                }
            } 
        }
        
    }
    
    public static void UpdateContactAccount(map<string, list<Case>> FilteredTriggerNew)
    {
        // CB_UpdateContactAccount - pulled in, not a separate trigger/class
        
        // MK - 2012-08-16 - added global settings field for username
        // MK - 2013-08-14 - updated code to be more flexible and readable
        GlobalSettings__c gs = GlobalSettings__c.getInstance();
        String un = gs != null ? gs.Email_2_Case_User__c : null; 
        
        // only get a matching user if the Global Settings are set
        List<User> users = new List<User>();
        if(un != null) { users = [Select id from User where Username = :un]; }
        
        // u cannot be null because its properties are referenced later
        User u = users.isEmpty() ? new User() : users[0]; 
        
        // gather Email Addresses:
        //   if the Current User is the Email 2 Case User
        //   and an Email Address was supplied on the Case
        //     add the Email Address for processing
        Set<String> EmailAddresses = new Set<String>();
        
        list<Case> ContactAccountCases = FilteredTriggerNew.get('CB_UpdateContactAccount');    
        
        if(ContactAccountCases != null && !ContactAccountCases.isEmpty())
        {                   
            for (Case CurrentCase : ContactAccountCases) 
            {
                if(UserInfo.getUserId() == u.Id && CurrentCase.SuppliedEmail != null) 
                {
                    EmailAddresses.add(CurrentCase.SuppliedEmail);
                }
            }
        }
        
        List<Contact> MatchingContacts = new List<Contact>();
        if(!EmailAddresses.IsEmpty()) {
            MatchingContacts = [SELECT Email FROM Contact WHERE Email IN :EmailAddresses]; 
        }
        
        if(ContactAccountCases != null && ContactAccountCases.isEmpty())
        {
            for (Case CurrentCase : ContactAccountCases) 
            {
                // check for multiple matches
                Integer temp = 0;
                for(Contact CurrentContact : MatchingContacts) {
                    if(CurrentContact.Email == CurrentCase.SuppliedEmail) { temp++; } 
                }
                
                // if there is more than one match
                //   set these fields to a blank value
                if(temp > 1) 
                {
                    CurrentCase.ContactId = null;
                    CurrentCase.AccountId = null;
                    CurrentCase.WebID__c = null; 
                    system.debug(CurrentCase.WebID__c);
                    system.debug(CurrentCase.ContactId);
                }
            }
        }
        // end CB_UpdateContactAccount
        
    }
}