SF Primes/src/objects/Account_Plan__c.object
<CustomObject>
    <description>This object houses the Account Plan for a Digital Services specialist.  The Account Plan specifically pertains to the WebID object.  There may be multiple account plans across an account for a position if there is more than one webid, but there should only be one Account Plan per specialist per WebID.</description>
    <fields>
        <fullName>AA_Account_Plan_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be updated by a stored procedure that looks at related Account Plan records with record type AA Account Plan on the webid.</description>
        <inlineHelpText>This link will open the Advocate’s Account Plan on this webid.</inlineHelpText>
        <label>AA Account Plan Link</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Creative_Case_Tally__c</fullName>
        <label>Creative Case Tally</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SEO_Decision_Made_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the person at the dealership who informed ADP/Cobalt that they will be using a 3rd Party or internal person for SEO.</inlineHelpText>
        <label>SEO Decision Made By</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a contact from the Account Plan&apos;s Account.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.Account.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose a WebID on the Account Plan’s associated Account.</errorMessage>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Creative_Case_Tally__c</fullName>
        <label>Creative Case Tally</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Docusign/src/classes/CB_CretiveCseTallyOnWebIdResetBatch_Test.cls
/*-----------------------------------------------------
* 08/03/2015  -Venkata Shrivol  -Created
* Description - Test class for CB_CreativeCaseTallyOnWebIdReset_Batch
* ----HISTORY------

-------------------------------------------------------*/
@isTest 
private class CB_CretiveCseTallyOnWebIdResetBatch_Test 
{
	static testMethod void prepareWebIDCaseAccPlanData()
	{
		//User u = DS_TestObjects.NewUser_Inserted();
    	Account acc = DS_TestObjects.NewAccount_Inserted();
    	
    	Contact testContact = new Contact();
    	testContact.FirstName = 'First';
    	testContact.LastName = 'Last';
    	testContact.AccountId = acc.Id;
    	insert testContact;
    	
    	list<WebID__c> testWebIdList = new list<WebID__c>();
    	for(integer i=0;i<2;i++)
    	{
    		WebID__c testId = new WebID__c();
	    	testId.Account__c = acc.Id;
	    	if(i==0){
	    		testId.Name = 'gmps-test';
                testId.Creative_Case_Tally__c = 5;
	    	}
	    	else{
	    		testId.Name = 'holden-test';
                testId.Creative_Case_Tally__c = 0;
	    	}
	    	testId.Status__c = 'Active';
	    	testWebIdList.add(testId);
    	}
    	insert testWebIdList;
    	
    	String caseRecordTypeId = ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('Case', 'Inquiry - Creative');
    	
    	list<Case> testCaseList = new list<Case>();
    	for(integer j=0;j<testWebIdList.size();j++)
    	{
    		for(integer k=0;k<5;k++)
    		{
    			Case testCase = new Case();
		    	testCase.RecordTypeId = caseRecordTypeId;
		    	testCase.AccountId = acc.Id;
		    	testCase.ContactId = testContact.Id;
		    	testCase.WebID__c= testWebIdList.get(j).Id;
		    	testCase.Problem_Code__c = 'Power Brand';
                if(j==0)
                {
                   testCase.Creative_Case_Tally__c = 5; 
                }
                else
                {
                    testCase.Creative_Case_Tally__c = 0;
                }
		    	testCase.Status = 'Open';
		    	testCaseList.add(testCase);
    		}
    	}
    	insert testCaseList;
    	
    	String accountPlanRecordTypeId = ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('Account_Plan__c', 'DAA Account Plan');
    	
    	list<Account_Plan__c> accPlanList = new list<Account_Plan__c>();
    	for(integer i=0;i<testWebIdList.size();i++)
    	{
    		Account_Plan__c testPlan = new Account_Plan__c();
	    	testPlan.WebID__c = testWebIdList.get(i).Id;
	    	testPlan.Account__c = acc.Id;
            if(i==0)
            {
                testPlan.Creative_Case_Tally__c = 5; 
            }
            else
            {
                testPlan.Creative_Case_Tally__c = 0;
            }
	    	accPlanList.add(testPlan);
    	}
    	insert accPlanList;
    	
    	//string testQuery = 'SELECT ID, Creative_Case_Tally__c, (Select Id,Creative_Case_Tally__c, RecordType.Name, WebId__c, Status from Cases__r), (Select Id,Creative_Case_Tally__c, RecordType.Name, WebId__c, Status from Account_Plans__r)  from WebID__c';
    	
    	Test.startTest();
    	CB_CreativeCaseTallyOnWebIdReset_Batch executeBatchTest = new CB_CreativeCaseTallyOnWebIdReset_Batch();
        //executeBatchTest.query = testQuery;
    	Database.executeBatch(executeBatchTest);
    	Test.stopTest();
	}

}