SF Primes/src/objects/Account_Team__c.object
<CustomObject>
    <description>A custom object designed to mimic the standard account team, where all CRED is controlled by this object.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>AccountTeamAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N40000001mDRREA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Advocate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Advisor - Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Services CAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Services GAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Digital Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Sales Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Baseline Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - CDP ISR Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Dealix Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Digital Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Enterprise Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Inside Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - National Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - NIADA Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Retail Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Saturn Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Telephony Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Analyst2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Regional Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Strategist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National/Enterprise DSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Forecasting Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Marketing (DAP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Improvement Consultant</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Team</label>
    <nameField>
        <displayFormat>Acct Member ID {0000000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/System_at_Dealership__c.object
<CustomObject>
    <description>Systems identified at a specific dealership</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Systems at Dealership</relationshipLabel>
        <relationshipName>R00N40000001leejEAA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Type__c</fullName>
        <label>System Type</label>
        <picklist>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>Systems at Dealership (Vendor)</relationshipLabel>
        <relationshipName>R00N40000001lfXZEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System at Dealership</label>
    <nameField>
        <displayFormat>ID - {00000}</displayFormat>
        <label>Sys at Dealership</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems at Dealership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Systems__c.object
<CustomObject>
    <description>List of valid DMS/CRM/Leasing/Phone systems</description>
    <fields>
        <fullName>SLXSystem_ID__c</fullName>
        <label>SLXSystem ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLXVendor_ID__c</fullName>
        <label>SLXVendor ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Systems</label>
    <nameField>
        <label>Vendor System</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/classes/SLS_CampaignLeadList_Test.cls
@IsTest
public class SLS_CampaignLeadList_Test 
{
 	@testSetup
    public static void testsetup()
    {
        Account accObj = DS_TestObjects.NewAccount_Inserted();
        Contact conObj = DS_TestObjects.NewContact();
        conObj.AccountId = accObj.Id;
        insert conObj;
        Systems__c sysObj  = new Systems__c();
        sysObj.SLXVendor_ID__c = 'Vendor Id';
        sysObj.type__C = 'DMS';
        sysObj.SLXSystem_ID__c = 'randomn';
        insert sysObj;
        System_at_Dealership__c sdObj = new System_at_Dealership__c();
        sdObj.System_Type__c = 'DMS';
        sdObj.Account__c = accObj.Id;
        sdObj.Vendor__c = sysObj.Id;
        insert sdObj;
        Account_Team__c at = new Account_Team__c();
        at.Team_Role__C = 'Forecasting - Inside Sales Rep';
        at.Account__C = accObj.Id;
        at.Team_Member__c = UserInfo.getUserId();
        insert at;
        Campaign camObj = DS_TestObjects.NewCampaign();
        insert camObj;
        List<Lead> leads = new List<Lead>();
        for(Integer i=0;i<3;i++)
        {
            Lead leadObj = DS_TestObjects.NewLead();
            leadObj.Current_Account__C = accObj.Id;
            leadObj.Contact__c = conObj.Id;
            leads.add(leadObj);
        }
        insert leads;     
        Task tskObj = DS_TestObjects.NewTask();
        tskObj.WhoId = leads[0].Id;
        insert tskObj;
        Event evntObj = new Event();
        evntObj.WhoId = leads[0].Id;
        evntObj.DurationInMinutes = 15;
        evntObj.ActivityDateTime = DateTime.now();
        insert evntObj;
    }
    public static testmethod void test1()
    {
        Account accObj = [SELECT id FROM Account LIMIT 1];
        Contact conObj = [SELECT id FROM Contact LIMIT 1];
        Campaign camObj = [SELECT id FROM Campaign LIMIT 1];
        Lead leadObj = [SELECT id FROM Lead LIMIT 1];
        SLS_CampaignLeadList_Controller.getLeadStatus();
        SLS_CampaignLeadList_Controller.getVendorSystem(accObj.Id);
        SLS_CampaignLeadList_Controller.getAccountDetails(accObj.Id);
        SLS_CampaignLeadList_Controller.getISR(accObj.Id);
        SLS_CampaignLeadList_Controller.getCurrentUser();
        SLS_CampaignLeadList_Controller.getContactDetails(conObj.Id);
        SLS_CampaignLeadList_Controller.getLeads(String.ValueOf(camObj.Id), new List<String>{'Not Yet Contacted By Rep'}, '',  1, 3);
        SLS_CampaignLeadList_Controller.getRecordsCount(String.ValueOf(camObj.Id), new List<String>{'Not Yet Contacted By Rep'},'');
        SLS_CampaignLeadList_Controller.getOpenActivities(accObj.Id, leadObj.Id, '');
        SLS_CampaignLeadList_Controller.getActivityHistory(accObj.Id, leadObj.Id, '');
        SLS_CampaignLeadList_Controller.updateStatus(String.ValueOf(camObj.Id), new List<String>{'Not Yet Contacted By Rep'}, '',new  List<String>{String.ValueOf(leadObj.Id)},'Contacted', 1, 3);
        
        SLS_CampaignLeadList_Controller.convertLeadToOpportunity(String.ValueOf(camObj.Id), new List<String>{'Not Yet Contacted By Rep'}, '',String.ValueOf(leadObj.Id), 1, 3);
    }
    
}