SF Primes/src/objects/Account_Plan__c.object
<CustomObject>
    <description>This object houses the Account Plan for a Digital Services specialist.  The Account Plan specifically pertains to the WebID object.  There may be multiple account plans across an account for a position if there is more than one webid, but there should only be one Account Plan per specialist per WebID.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Creative_Case_Limit__c</fullName>
        <label>Creative Case Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose a WebID on the Account Plan’s associated Account.</errorMessage>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Creative_Case_Limit__c</fullName>
        <label>Creative Case Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/CB_CretiveCseLimitUpdteWebIDCase_Test.cls
/* 
Test Class for CB_CretiveCseLimitUpdteWebIDCase_Handler
*/
@isTest
public class CB_CretiveCseLimitUpdteWebIDCase_Test {

    static testMethod void creativeCaseLimitUpdateTest() 
    {
        //User u = DS_TestObjects.NewUser_Inserted();
        Account acc = DS_TestObjects.NewAccount_Inserted();
        
        Contact testContact = new Contact();
        testContact.FirstName = 'First';
        testContact.LastName = 'Last';
        testContact.AccountId = acc.Id;
        insert testContact;
        
        // 2016-07-27 matt.keefe@cdk.com - added contact relationship for shared contacts (Case Lookup requires)
        Contact_Relationship__c cr1 = new Contact_Relationship__c(Contact__c = testContact.Id, Account__c = acc.Id);
        cr1.Role__c = 'Accountant';
        insert cr1;
        
        WebID__c testId = new WebID__c();
        testId.Account__c = acc.Id;
        testId.Name = 'gmps-test';
        insert testId;
        
        WebID__c testId2 = new WebID__c();
        testId2.Account__c = acc.Id;
        testId2.Name = 'kia-test';
        insert testId2;
        
        String caseRecordTypeId = ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('Case', 'Inquiry - Creative');
        
        Case testCase = new Case();
        testCase.RecordTypeId = caseRecordTypeId;
        testCase.AccountId = acc.Id;
        testCase.ContactId = testContact.Id;
        testCase.Creative_Case_Limit__c = 0;
        testCase.WebID__c= testId.Id;
        testCase.Status = 'Open';
        insert testCase;
        
        Account_Plan__c testPlan = new Account_Plan__c();
        //testPlan.RecordType.Name= 'DAA Account Plan';
        testPlan.Creative_Case_Limit__c = 10;
        testPlan.WebID__c = testId.Id;
        testPlan.Account__c = acc.Id;
        insert testPlan;
    
        Map<Id,decimal> testLimitMap = new Map<Id,decimal>();
        testLimitMap.put(testPlan.WebID__c, testPlan.Creative_Case_Limit__c);
        
        CB_CretiveCseLimitUpdteWebIDCase_Handler.creativeCaseLimitUpdate(testLimitMap);
        testLimitMap.clear();
        
        testPlan.Creative_Case_Limit__c = 12;
        update testPlan;
        testLimitMap.put(testPlan.WebID__c, testPlan.Creative_Case_Limit__c);
        CB_CretiveCseLimitUpdteWebIDCase_Handler.creativeCaseLimitUpdate(testLimitMap);
        
        Account_Plan__c testPlan2 = new Account_Plan__c();
        testPlan2.WebID__c = testId2.Id;
        testPlan2.Account__c = acc.Id;
        insert testPlan2;
        testLimitMap.clear();
        testLimitMap.put(testPlan2.WebID__c, testPlan2.Creative_Case_Limit__c);
        CB_CretiveCseLimitUpdteWebIDCase_Handler.creativeCaseLimitUpdate(testLimitMap);
    }
}