SF Primes/src/objects/Account_Team__c.object
<CustomObject>
    <description>A custom object designed to mimic the standard account team, where all CRED is controlled by this object.</description>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>AccountTeamAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SForce_Account_Team_Id__c</fullName>
        <label>SForce Account Team Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N40000001mDRREA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Advocate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Advisor - Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Services CAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Services GAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Digital Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Sales Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Baseline Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - CDP ISR Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Dealix Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Digital Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Enterprise Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Inside Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - National Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - NIADA Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Retail Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Saturn Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Telephony Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Analyst2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Regional Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Strategist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National/Enterprise DSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Forecasting Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Marketing (DAP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Improvement Consultant</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Team</label>
    <nameField>
        <displayFormat>Acct Member ID {0000000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/Sales_Team__c.object
<CustomObject>
    <description>Custom sales team member linked to Opportunity team member via trigger</description>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N40000001lw8PEAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SForce_Sales_Team_Id__c</fullName>
        <label>SForce Sales Team Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Forecasting - Baseline Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - CDP ISR Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Dealix Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Digital Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Enterprise Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Inside Sales Laser Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Inside Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - National Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - NIADA Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Retail Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Saturn Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Telephony Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Forecasting Rep</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N40000001lw8AEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Team Member</label>
    <nameField>
        <displayFormat>ID {00000}</displayFormat>
        <label>Sales Team ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Docusign/src/classes/DS_CreateSForceSalesTeam.cls
public class DS_CreateSForceSalesTeam {
	public List<OpportunityTeamMember> insertSForceSalesTeam(List<Sales_Team__c> salesTeam){
		
		List<Id> opportunities = new List<Id>();
		for(Sales_Team__c st:salesTeam){
			opportunities.add(st.Opportunity__c);
		}
		
		Map<Id,Opportunity> opportunityOwners = new Map<Id,Opportunity>([select Id, OwnerId,Owner.IsActive from Opportunity where Id in :opportunities]);
		
		OpportunityTeamMember temp;
		OpportunityShare oppShare;
		List<OpportunityShare> opportunityShareList = new List<OpportunityShare>();
		List<OpportunityTeamMember> opportunityMembers = new List<OpportunityTeamMember>();
		for(Sales_Team__c teamMember:salesTeam){
			// CN 3/17 add only if it is present in oppOwners
			temp = new OpportunityTeamMember();
			temp.UserId=teamMember.User__c;
			temp.TeamMemberRole=teamMember.Team_Role__c;
			temp.OpportunityId=teamMember.Opportunity__c;
			temp.OpportunityAccessLevel=returnPickVal(teamMember.Opportunity_Access__c);
			System.debug('OA: '+teamMember.Opportunity_Access__c);
			System.debug('OA: '+returnPickVal(teamMember.Opportunity_Access__c));
			System.debug('OA: '+temp.OpportunityAccessLevel);
			System.debug('OA: '+temp);
			
			opportunityMembers.add(temp);
			System.debug('OA: '+opportunityMembers);
		
			oppShare = new OpportunityShare();
			oppShare.UserOrGroupId=teamMember.User__c;
			oppShare.OpportunityId=teamMember.Opportunity__c;
			
			oppShare.OpportunityAccessLevel=returnPickVal(teamMember.Opportunity_Access__c);
			
			if(opportunityOwners.get(teamMember.Opportunity__c)!=null && teamMember.User__c!=opportunityOwners.get(teamMember.Opportunity__c).OwnerId){
				
				opportunityShareList.add(oppShare);
			}
			else if(!opportunityOwners.get(teamMember.Opportunity__c).Owner.isActive)
			{
				opportunityShareList.add(oppShare);
				
			}
		}
		if(opportunityMembers.size()>0){
			insert opportunityMembers;
		}
		if(opportunityShareList.size()>0){
			insert opportunityShareList;	
		}

		return opportunityMembers;
	}
	public void deleteSForceSalesTeam(List<Sales_Team__c> salesTeam){
		Set<String> teamMembers = new Set<String>();
		for(Sales_Team__c teamMember:salesTeam){
			teamMembers.add(teamMember.SForce_Sales_Team_Id__c);		
		}
	
		List<OpportunityTeamMember> opportunityMembers = [select Id from OpportunityTeamMember where Id in :teamMembers];
		
		delete opportunityMembers;
	}
	public List<AccountTeamMember> insertAccountTeam(List<Account_Team__c> accountTeam){
		AccountTeamMember temp;
		AccountShare tempAccountShare;
		
		List<AccountShare> accountShareList = new List<AccountShare>();
		List<AccountTeamMember> accountMembers = new List<AccountTeamMember>();
		Set<Id> accounts = new Set<Id>();
		for(Account_Team__c tm:accountTeam){
			accounts.add(tm.Account__c);
		}

		Map<Id,Account> accountOwners = new Map<Id,Account>([select Id, OwnerId from Account where Id in :accounts]);
		
		for(Account_Team__c teamMember:accountTeam){
			temp = new AccountTeamMember();
			temp.UserId=teamMember.Team_Member__c;
			temp.TeamMemberRole=teamMember.Team_Role__c;
			temp.AccountId=teamMember.Account__c;
			temp.AccountAccessLevel=teamMember.Account_Access__c; system.debug(teamMember.Account_Access__c);

			accountMembers.add(temp);
			
			System.debug(teamMember.Team_Member__c+'=='+accountOwners.get(teamMember.Account__c).OwnerId);
			if(teamMember.Team_Member__c!=accountOwners.get(teamMember.Account__c).OwnerId){
				tempAccountShare=new AccountShare();
				tempAccountShare.UserOrGroupId=teamMember.Team_Member__c;
				tempAccountShare.AccountId=teamMember.Account__c;
				
				tempAccountShare.AccountAccessLevel=returnPickVal(teamMember.Account_Access__c);
				tempAccountShare.OpportunityAccessLevel=returnPickVal(teamMember.Opportunity_Access__c);
				tempAccountShare.CaseAccessLevel=returnPickVal(teamMember.Case_Access__c);
				accountShareList.add(tempAccountShare); 
			}
		}
		
		if(accountMembers.size()>0){
			system.debug(accountMembers);
			insert accountMembers;
		}
		if(accountShareList.size()>0){
			system.debug(accountShareList);
			insert accountShareList;	
		}
		
		return accountMembers;
	}
	public void deleteAccountTeam(List<Account_Team__c> accountTeam){
		Set<String> teamMembers = new Set<String>();
		for(Account_Team__c teamMember:accountTeam){
			teamMembers.add(teamMember.SForce_Account_Team_Id__c);		
		}
	
		List<AccountTeamMember> accountMembers = [select Id from AccountTeamMember where Id in :teamMembers];
		
		if(accountMembers.size()>0){
			delete accountMembers;
		}
	}
	public String returnPickVal(String val){
		if(val=='Private') return 'None';
		else if(val=='Read Only') return 'Read';
		else if(val=='Read/Write') return 'Edit';	
		
		return 'None';
	}
}