SF Primes/src/objects/Account_Team__c.object
<CustomObject>
    <description>A custom object designed to mimic the standard account team, where all CRED is controlled by this object.</description>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>AccountTeamAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N40000001mDRREA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Advocate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Advisor - Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Services CAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Services GAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Digital Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Sales Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Baseline Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - CDP ISR Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Dealix Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Digital Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Enterprise Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Inside Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - National Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - NIADA Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Retail Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Saturn Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Telephony Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Analyst2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Regional Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMA Strategist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National/Enterprise DSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Forecasting Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Marketing (DAP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Marketing Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Improvement Consultant</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Team</label>
    <nameField>
        <displayFormat>Acct Member ID {0000000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/ADP_Default_Team__c.object
<CustomObject>
    <description>ADP Default Team used for account or territory reallignment purposes.</description>
    <label>ADP Default Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADP Default Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/ADP_Default_Team_Members__c.object
<CustomObject>
    <description>Related list showing associated team members.</description>
    <fields>
        <fullName>ADP_Default_Team__c</fullName>
        <description>Parentid</description>
        <label>ADP_Default_Team</label>
        <referenceTo>ADP_Default_Team__c</referenceTo>
        <relationshipName>R00N40000001mWJMEA2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Full Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N40000001mWJPEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Forecasting - Baseline Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - CDP ISR Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Digital Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Enterprise Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Inside Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - National Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - NIADA Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Retail Solutions Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Saturn Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasting - Telephony Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Forecasting Rep</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>ADP Default Team Member</label>
    <nameField>
        <displayFormat>ID - {0000}</displayFormat>
        <label>ADP Default Team Members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADP Default Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/ALL_ADPDefaultTeamMembers_Handler.cls
//2016-11-09 - lalitha.adduru@cdk.com - created -  RQ-08111
public class ALL_ADPDefaultTeamMembers_Handler 
{
    //lalitha.adduru@cdk.com - when an CDK Default Team Member is inserted, add appropriate Account Teams to Relevant Accounts -  RQ-08111
    public static void addRequiredAccountTeams(List<ADP_Default_Team_Members__c> teamMemberList)
    {
        system.debug('************************ addRequiredAccountTeams started ********************');
        SET<Id> CDK_Default_Team_Ids = new Set<Id>();
        for(ADP_Default_Team_Members__c teamMember : teamMemberList)
        {
            CDK_Default_Team_Ids.add(teamMember.ADP_Default_Team__c);
        }
        
        // Map of CDK Default team to the Accounts that have this team 
        Map<Id, Set<Id>> teamToAccountIdsMap = new Map<Id, Set<Id>>();
        List<Account> accountList = new List<Account>();
        accountList = [
            SELECT Id, CDK_Default_Team__c
            FROM Account WHERE CDK_Default_Team__c in :CDK_Default_Team_Ids
        ];
        
        for(Account relevantAccount : accountList)
        {
            if(!teamToAccountIdsMap.containsKey(relevantAccount.CDK_Default_Team__c))
            {
                teamToAccountIdsMap.put(relevantAccount.CDK_Default_Team__c, new Set<Id>{relevantAccount.Id});
            }
            else
            {
                teamToAccountIdsMap.get(relevantAccount.CDK_Default_Team__c).add(relevantAccount.Id);
            }
        }
        
        // Map that maps an Account to its Account Teams member Ids and a Map that maps account to its account teams with role 'OEM Sales'
        Map<Id, Map<Id, Account_Team__c>> accountToAccountTeamMap = new Map<Id, Map<Id, Account_Team__c>>();
        Map<Id, Map<Id, Account_Team__c>> accountToOEMSalesMap = new Map<Id, Map<Id, Account_Team__c>>();
        Set<Account> accountSet = new Set<Account>();
        accountSet.addAll(accountList);
        accountToAccountTeamMap = ALL_Account_Handler.getAccountToAccountTeamMap(accountSet);
        for(Account requiredAccount : accountList)
        {
            List<Account_Team__c> accountTeams;
            accountTeams = accountToAccountTeamMap.get(requiredAccount.Id) != null ? accountToAccountTeamMap.get(requiredAccount.Id).values() : new List<Account_Team__c>();
            for(Account_Team__c accountTeam : accountTeams)
            {
                if(accountTeam.Team_Role__c == 'OEM Sales')
                {
                    if(accountToOEMSalesMap.containsKey(accountTeam.Account__c))
                    {
                        accountToOEMSalesMap.get(accountTeam.Account__c).put(accountTeam.Team_Member__c, accountTeam);
                    }
                    else
                    {
                        accountToOEMSalesMap.put(accountTeam.Account__c, new Map<Id, Account_Team__c>{accountTeam.Team_Member__c=>accountTeam});
                    }
                }
            }
        }
        system.debug('accountToAccountTeamMap --- >'+accountToAccountTeamMap);
        
        // add new account teams on relevant accounts wherever required
        List<Account_Team__c> accountTeamsToBeInserted = new List<Account_team__c>();
        
        if(teamToAccountIdsMap != null && !teamToAccountIdsMap.isEmpty())
        {
            for(ADP_Default_Team_Members__c teamMember : teamMemberList)
            {
                for(Id relevantAccountId : teamToAccountIdsMap.get(teamMember.ADP_Default_Team__c)==null?new Set<Id>():teamToAccountIdsMap.get(teamMember.ADP_Default_Team__c))
                {
                    Map<Id, Account_Team__c> existingTeamMemberToAccountTeamMap;
                    existingTeamMemberToAccountTeamMap = accountToAccountTeamMap.get(relevantAccountId) == null ? new Map<Id, Account_team__c>() : accountToAccountTeamMap.get(relevantAccountId);
                    if(existingTeamMemberToAccountTeamMap.isEmpty() || !existingTeamMemberToAccountTeamMap.keyset().contains(teamMember.Team_Member__c))
                    {
                        Account_Team__c newAccountTeam = new Account_Team__c();
                        newAccountTeam.Account__c = relevantAccountId;
                        newAccountTeam.Account_Access__c = teamMember.Account_Access__c;
                        newAccountTeam.Opportunity_Access__c = teamMember.Opportunity_Access__c;
                        newAccountTeam.Case_Access__c = teamMember.Account_Access__c;
                        newAccountTeam.Team_Member__c = teamMember.Team_Member__c;
                        newAccountTeam.Team_Role__c = 'OEM Sales';
                        accountTeamsToBeInserted.add(newAccountTeam);
                    }
                }
                
            }
        }
        if(!accountTeamsToBeInserted.isEmpty())
        {
            system.debug('accountTeamsToBeInserted --- >'+accountTeamsToBeInserted);
            insert accountTeamsToBeInserted;
        }
        system.debug('************************ addRequiredAccountTeams ended ********************');
    }
    
    //lalitha.adduru@cdk.com - when an CDK Default Team Member is delete, delete appropriate Account Teams from Relevant Accounts -  RQ-08111
    public static void deleteRelatedAccountTeams(List<ADP_Default_Team_Members__c> teamMemberList)
    {
        system.debug('************** deleteRelatedAccountTeams started ********************');
        List<Account_Team__c> accountTeamsToDelete = new List<Account_Team__c>();
        Set<Id> defaultTeamIds = new Set<Id>();
        Set<Id> teamMemberIds = new Set<Id>();
        system.debug('teamstobedeleted --> '+teamMemberList);
        for(ADP_Default_Team_Members__c teamMember : teamMemberList)
        {
            defaultTeamIds.add(teamMember.ADP_Default_Team__c);
            teamMemberIds.add(teamMember.Team_Member__c);
        }
        accountTeamsToDelete = [
            SELECT Id 
            from Account_Team__c where team_Role__c = 'OEM Sales' and Account__r.CDK_Default_Team__c in :defaultTeamIds and Team_Member__c in :teamMemberIds
        ];
        if(!accountTeamsToDelete.isEmpty())
        {
            delete accountTeamsToDelete;
        }
        system.debug('********************** deleteRelatedAccountTeams ended *****************');
    }
    
    //lalitha.adduru@cdk.com - when an CDK Default Team Member is updated, update/delete appropriate Account Teams on/from Relevant Accounts -  RQ-08111
    public static void updateRequiredAccountTeams(List<ADP_Default_Team_Members__c> newteamMemberList, Map<Id, ADP_Default_Team_Members__c> oldTeamMemberMap)
    {
        system.debug('******************** updateRequiredAccountTeams started *******************');
        Map<Id, Account_Team__c> accountTeamsToUpdate = new Map<Id, Account_Team__c>();
        Map<Id, Account_Team__c> accountTeamsToDelete = new Map<Id,Account_Team__c>();
        List<Account_Team__c> accountTeamsToInsert = new List<Account_Team__c>();
        List<ADP_Default_Team_Members__c> newUserTeamMember = new List<ADP_Default_Team_Members__c>();
        Map<Id, List<Account_Team__c>> memberToAccountTeamsMap = new Map<Id, List<Account_Team__c>>();
        memberToAccountTeamsMap = getMemberToAccountTeamMap(oldTeamMemberMap.values());
        system.debug('****************** memberToAccountTeamsMap ********************** '+memberToAccountTeamsMap);
        Set<Id> CDKDefaultTeamIds = new Set<Id>();
        for(ADP_Default_Team_Members__c teamMember : newteamMemberList)
        {
            CDKDefaultTeamIds.add(teamMember.ADP_Default_Team__c);
        }
        Set<Account> accountSet = new Set<Account>();
        for(List<Account_Team__c> accountTeamList : memberToAccountTeamsMap.values())
        {
            for(Account_Team__c accountTeam : accountTeamList)
            {
                accountSet.add(new Account(Id=accountTeam.Account__c));
            }
        }
		Map<Id, Map<Id, Account_Team__c>> accToTeamMemberMap = new Map<Id, Map<Id, Account_team__c>>();
        accToTeamMemberMap = ALL_Account_Handler.getAccountToAccountTeamMap(accountSet);
        Map<Id,Set<Account>> requiredAccounts = new Map<Id,Set<Account>>();
        requiredAccounts = getTeamToAccountsMap(CDKDefaultTeamIds);
        for(ADP_Default_Team_Members__c teamMember : newteamMemberList)
        {
            for(Account_Team__c accountTeam : memberToAccountTeamsMap.containsKey(teamMember.Id) ? memberToAccountTeamsMap.get(teamMember.Id) : new List<Account_Team__c>())
            {
                if(teamMember.Team_Member__c != oldTeamMemberMap.get(teamMember.Id).Team_Member__c)
                {
                    if(accToTeamMemberMap.get(accountTeam.Account__c)!= null && accToTeamMemberMap.get(accountTeam.Account__c).containsKey(teamMember.Team_Member__c))
                    {
                        accountTeamsToDelete.put(accountTeam.Id, accountTeam);
                    }
                    else
                    {
                        accountTeam.Team_Member__c = teamMember.Team_Member__c;
                    }
                }
                if(!accountTeamsToDelete.containsKey(accountTeam.Id))
                {accountTeam.Account_Access__c = teamMember.Account_Access__c;
                accountTeam.Case_Access__c = teamMember.Account_Access__c;
                accountTeam.Opportunity_Access__c = teamMember.Opportunity_Access__c;
                 accountTeamsToUpdate.put(accountTeam.Id, accountTeam);}
            }
            
            /*if(!memberToAccountTeamsMap.containsKey(teamMember.Id))
            {
                system.debug('member not present');
                for(Account requiredAccount : requiredAccounts.get(teamMember.ADP_Default_Team__c))
                {
                    if(!accToTeamMemberMap.containsKey(requiredAccount.Id) || !accToTeamMemberMap.get(requiredAccount.Id).containsKey(teamMember.Team_Member__c))
                    {
                        Account_Team__c newAccountTeam = new Account_Team__c();
                        newAccountTeam.Account__c = requiredAccount.Id;
                        newAccountTeam.Opportunity_Access__c = teamMember.Opportunity_Access__c;
                        newAccountTeam.Case_Access__c = teamMember.Account_Access__c;
                        newAccountTeam.Account_Access__c = teamMember.Account_Access__c;
                        newAccountTeam.Team_Member__c = teamMember.Team_Member__c;
                        accountTeamsToInsert.add(newAccountTeam);
                    }
                }
            }*/
             
        }
        if(!accountTeamsToInsert.isEmpty())
        {
            insert accountTeamsToInsert;
        }
		if(!accountTeamsToUpdate.isEmpty())
        {
            system.debug('***************** accountTeamsToUpdate ******************** '+accountTeamsToUpdate.values());
            update accountTeamsToUpdate.values();
        }
        if(!accountTeamsToDelete.isEmpty())
        {
            system.debug('***************** accountTeamsToDelete ********************* '+accountTeamsToDelete.values());
            delete accountTeamsToDelete.values();
        }
        system.debug('******************** updateRequiredAccountTeams ended *********************');
    }
    
    //lalitha.adduru@cdk.com - fetch Map of CDK Default Team Member => List of Account Teams created from it -  RQ-08111
    public static Map<Id, List<Account_Team__c>> getMemberToAccountTeamMap(List<ADP_Default_Team_Members__c> teamMemberList)
    {
        system.debug('*********************** getMemberToAccountTeamMap started ********************');
        Map<Id, List<Account_Team__c>> memberToAccountTeamMap = new Map<Id, List<Account_Team__c>>();
        Set<Id> CDKDefaultTeamIds = new Set<Id>();
        Set<Id> teamMemberUserIds = new Set<Id>();
        for(ADP_Default_Team_Members__c teamMember : teamMemberList)
        {
            CDKDefaultTeamIds.add(teamMember.ADP_Default_Team__c);
            teamMemberUserIds.add(teamMember.Team_Member__c);
        }
        List<Account_Team__c> accountTeamList = new List<Account_Team__c>();
        accountTeamList = [
            SELECT Account__r.CDK_Default_Team__c,Account__r.Name, Opportunity_Access__c, Case_Access__c, Account_Access__c, Team_Member__c,Team_Member__r.Name 
            FROM Account_Team__c WHERE Account__r.CDK_Default_Team__c in :CDKDefaultTeamIds and Team_Member__c in :teamMemberUserIds and Team_Role__c = 'OEM Sales'
        ];
        
        for(ADP_Default_Team_Members__c teamMember : teamMemberList)
        {
            for(Account_Team__c accountTeam : accountTeamList)
            {
                if(accountTeam.Team_Member__c == teamMember.Team_Member__c && accountTeam.Account__r.CDK_Default_Team__c == teamMember.ADP_Default_Team__c)
                {
                    if(memberToAccountTeamMap.containsKey(teamMember.Id))
                    {
                        memberToAccountTeamMap.get(teamMember.Id).add(accountTeam);
                    }
                    else
                    {
                        memberToAccountTeamMap.put(teamMember.Id, new List<Account_Team__c>{accountTeam});
                    }
                }
            }
        }
        system.debug('************* getMemberToAccountTeamMap ended *******************');
        return memberToAccountTeamMap;
        
    }
    
    //lalitha.adduru@cdk.com -  get a Map that maps a CDK Default team with a Map of Team_Member__c (user) to ADP_Default_Team_Members__c -  RQ-08111
    //'sampleCDKTeamId'=> ('TeamMemberUserId' => 'CDkDefaultTeamMemberRecord') 
    public static Map<Id, Map<Id, ADP_Default_Team_Members__c>> getDefTeamToTeamMemMap(Set<Id> CDKDefaultTeamIds)
    {
        system.debug('********************** getDefTeamToTeamMemMap started *********************');
        Map<Id, Map<Id, ADP_Default_Team_Members__c>> teamToMembersMap = new Map<Id, Map<Id, ADP_Default_Team_Members__c>>();
        List<ADP_Default_Team_Members__c> teamMembersList = new List<ADP_Default_Team_Members__c>();
        teamMembersList  = [
            SELECT id, ADP_Default_Team__c, Account_Access__c, Opportunity_Access__c, Team_Member__c, Team_Role__c,Title__c 
            FROM ADP_Default_Team_Members__c where ADP_Default_Team__c in :CDKDefaultTeamIds
        ];
        for(ADP_Default_Team_Members__c teamMember : teamMembersList)
        {
            if(teamToMembersMap.containsKey(teamMember.ADP_Default_Team__c))
            {
                teamToMembersMap.get(teamMember.ADP_Default_Team__c).put(teamMember.Team_Member__c,teamMember);
            }
            else
            {
                teamToMembersMap.put(teamMember.ADP_Default_Team__c, new Map<Id,ADP_Default_Team_Members__c>{teamMember.Team_Member__c=>teamMember});
            }
        }
        system.debug('teamToMembersMap --- > '+teamToMembersMap);
        system.debug('***************** getDefTeamToTeamMemMap ended *****************');
        return teamToMembersMap;
    }
    
    public static Map<Id, Set<Account>> getTeamToAccountsMap(Set<Id> CDKDefaultTeamIds)
    {
        system.debug('******************* getDefTeamToTeamMemMap started **********************');
        Map<Id, Set<Account>> teamToAccountsMap = new Map<Id, Set<Account>>();
        List<Account> accountList = new List<Account>();
        accountList = [
            SELECT id, CDK_Default_Team__c
            FROM Account where CDK_Default_Team__c in :CDKDefaultTeamIds
        ];
        for(Account requiredAccount : accountList)
        {
            if(teamToAccountsMap.containsKey(requiredAccount.CDK_Default_Team__c))
            {
                teamToAccountsMap.get(requiredAccount.CDK_Default_Team__c).add(requiredAccount);
            }
            else
            {
                teamToAccountsMap.put(requiredAccount.CDK_Default_Team__c, new Set<Account>{requiredAccount});
            }
        }
        system.debug('********************* getDefTeamToTeamMemMap ended *******************');
        return teamToAccountsMap;
    }
    

}