SF Primes/src/objects/Activity_Definition__c.object
<CustomObject>
    <description>Contains Offset Criteria, Offset days, Sequence and Terminal Activity associated with an Activity definition.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Activity Definition</label>
    <nameField>
        <displayFormat>AID-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activity Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/CustomSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Centralized list of parameters to be modified when refreshing Training or FullDev sandboxes</description>
    <fields>
        <fullName>Max_Milestone_Threshold__c</fullName>
        <label>Max Milestone Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CustomSettings</label>
</CustomObject>

SF Primes/src/objects/Project_Activity__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for an Activity associated with a Milestone.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Milestone__r.Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date_Final__c</fullName>
        <formula>IF(!ISBLANK(Actual_End_Date__c) &amp;&amp; (Total_Tasks__c - Total_Tasks_Closed__c == 0) &amp;&amp; Total_Tasks__c !=0, Actual_End_Date__c, null)</formula>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Current Max Project Task End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Activity Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Project_Milestone__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Project_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process_Step__c</fullName>
        <description>Represents the Process Step associated with parent Project Milestone.</description>
        <formula>TEXT(Milestone__r.Process_Step__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Step</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk_Gauge_Color__c</fullName>
        <formula>IF( Status__c = &apos;At Risk&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=01533000001pMAS&quot;, &apos;At Risk&apos;),  
IF(Status__c = &apos;Caution&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=01533000001pMAT&quot;, &apos;Caution&apos;),IMAGE(&quot;/servlet/servlet.FileDownload?file=01533000001pMAR&quot;, &apos;On Target&apos;)))</formula>
        <inlineHelpText>Red - At Risk
Yellow - Caution
Green - On Target</inlineHelpText>
        <label>Risk Gauge Color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Tasks__c == 0, &apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>AI-{000000000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Milestone__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for a Milestone associated with a SubProject.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Site__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date_Final__c</fullName>
        <formula>IF(!ISBLANK(Actual_End_Date__c) &amp;&amp; (Total_Activities__c - Total_Activities_Closed__c == 0) &amp;&amp; Total_Activities__c !=0, Actual_End_Date__c, null)</formula>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Current Max Project Activity End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Milestone Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>External_System_ID__c</fullName>
        <description>Field used to store IDs of external objects like LAO, NIS Mission etc as applicable for the Milestone</description>
        <label>External System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System_Name__c</fullName>
        <formula>External_System_New_Id__r.External_Entity_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External System Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process_Step__c</fullName>
        <description>Represents the step in the current 6 step process. The introduction of this attribute on the Milestone Definition object supports project milestone sorting, representing the primary sorting field in the View and Edit Milestone pages.</description>
        <label>Process Step</label>
        <picklist>
            <picklistValues>
                <fullName>01-Implementation Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02-Project Mapping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03-Site Readiness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04-CDK GoLive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05-Transition Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06-Ongoing Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_Gauge_Color__c</fullName>
        <formula>IF( Status__c = &apos;At Risk&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=01533000001pMAS&quot;, &apos;At Risk&apos;), 
IF(Status__c = &apos;Caution&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=01533000001pMAT&quot;, &apos;Caution&apos;),IMAGE(&quot;/servlet/servlet.FileDownload?file=01533000001pMAR&quot;, &apos;On Target&apos;)))</formula>
        <inlineHelpText>Red - At Risk 
Yellow - Caution 
Green - On Target</inlineHelpText>
        <label>Risk Gauge Color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SubProject__c</field>
                <operation>equals</operation>
                <valueField>SubProjectSite__c.SubProject__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubProjectSite__c</referenceTo>
        <relationshipLabel>Project Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Sequence__c</fullName>
        <label>Sort Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Activities__c == 0,&apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <displayFormat>MID-{000000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Project_Activity__r.Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Task Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Activity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project Activity</label>
        <referenceTo>Project_Activity__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Status_Not_Applicable__c = true,&apos;Not Applicable&apos;,
IF(!ISBLANK(Actual_End_Date__c),&apos;Complete&apos;,
IF(!ISBLANK(Actual_Start_Date__c) &amp;&amp; ISBLANK(Actual_End_Date__c),&apos;In Progress&apos;,
IF(!ISBLANK( CDK_Assignee__c ),&apos;Assigned&apos;,
IF(ISBLANK( CDK_Assignee__c ),&apos;Unassigned&apos;,
null
)))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <displayFormat>TI-{000000000}</displayFormat>
        <label>Project Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Input scope details and notes (i.e. HOLD information, contacts w/o workspace, etc.)</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Task_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project Task Definition</label>
    <nameField>
        <displayFormat>TID-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Task Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Docusign/src/classes/IMP_Milestone_Controller_2015.cls
/*------------------------------------------------------------
  Author: Rey Austral
  Company: Cloud Sherpas
  Description: Controller for IMP_Milestone Component
  Test Class:
  History
  10/30/14     Rey Austral      Created
  11/03/14     Rey Austral      Add Update and Delete Function
  12/05/14     Rey Austral      Add Non-standard activity function
  12/24/14     Rey Austral      Add field update
  02/03/15     Rey Austral      Add task
  04/09/15     Rey Austral      Remove the edit function
  ------------------------------------------------------------*/
public class IMP_Milestone_Controller_2015
{
    public Id objectId { get; set; }
    public Boolean hasPermission { get; set; }
    public Boolean hasAddPermission { get; set; }
    public Boolean hasDeletePermission { get; set; }
    public Decimal milestoneSizeToEdit { get; set; }
    public List<MilestoneWrapper> milestoneContentList { get; set; }
    public Boolean toDisplay { get; set; }
    //Phase 2 Rel 1 begin
    public IMP_Milestone_Controller_2015()
    {
        try
        {
            objectId = ApexPages.currentPage().getParameters().get('id');
        }
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, IMP_String_Utility.NO_ASSOCIATE_SUBPROJECT_RECORD));
        }
        hasPermission = true;

        //Check if the user has Edit Permission
        if (!IMP_Project_Utility.checkUserPermission('Project_Milestone__c', 'PermissionsEdit'))
        {
            hasPermission = false;
        }

        //Check if the user has Edit Permission
        if (!IMP_Project_Utility.checkUserPermission('Project_Activity__c', 'PermissionsEdit'))
        {
            hasPermission = false;
        }
        hasAddPermission = true;
        //Check if the user has Create/Add Permission
        if (!IMP_Project_Utility.checkUserPermission('Project_Activity__c', 'PermissionsCreate'))
        {
            hasAddPermission = false;
        }

        hasDeletePermission = true;
        if (!IMP_Project_Utility.checkUserPermission('Project_Task__c', 'PermissionsDelete') ||
            !IMP_Project_Utility.checkUserPermission('Project_Activity__c', 'PermissionsDelete') ||
            !IMP_Project_Utility.checkUserPermission('Project_Milestone__c', 'PermissionsDelete'))
        {
            hasDeletePermission = false;
        }

        CustomSettings__c cs = CustomSettings__c.getInstance();
        milestoneSizeToEdit = 4;
        if (cs.Max_Milestone_Threshold__c != null)
        {
            milestoneSizeToEdit = cs.Max_Milestone_Threshold__c;
        }

        //Retrieve Milestones , Project Activies and Project Task
        resetWrapperDataAndExtensionField(retrieveMilestoneRecords());
    }
    //Phase 2 Rel 1 end
    /*------------------------------------------------------------
      Author: Rey Austral
      Company: Cloud Sherpas
      Description: Retrieve the record in the database
      Inputs: 
      Returns: List<Project_Milestone__c>
      History
      10/30/14    Rey Austral      Created
      12/24/14    Rey Austral      Remove the population in the wrapper
      ------------------------------------------------------------*/
    public List<Project_Milestone__c> retrieveMilestoneRecords()
    {
        //Retrieve related milestones 
        String milestoneOrderQuery = IMP_Project_Utility.getOrderColumns(SObjectType.Project_Milestone__c.FieldSets.Milestone_Sort_Commons.getFields(), true);
        String activityOrderQuery = IMP_Project_Utility.getOrderColumns(SObjectType.Project_Activity__c.FieldSets.Activity_Sort_Commons.getFields(), true);

        String query = 'SELECT Actual_End_Date__c, Actual_End_Date_Final__c,Actual_Start_Date__c, Comments__c, Risk_Gauge_Color__c, Account__c ,' +
        'Process_Step__c,External_System_Name__c, Description__c, Planned_End_Date__c, Planned_Start_Date__c, ' +
        'Site__c, Status__c, Id, External_System_ID__c,Standard__c,Sort_Sequence__c,' +
        '(SELECT Activity_Definition__c,Actual_End_Date__c,Actual_End_Date_Final__c,Actual_Start_Date__c,CDK_Assignee__c, External_ID__c,' +
        'CDK_Assignee_Role__c,Client_Assignee__c,Department__c,Description__c,Display_on_PSR__c, Risk_Gauge_Color__c,' +
        'Planned_End_Date__c,Planned_Start_Date__c,Status__c,Comments__c,Standard__c,Sequence__c  FROM Project_Activities__r ' + activityOrderQuery + ') ' +
        'FROM Project_Milestone__c where SubProject__c =: objectId  ' + milestoneOrderQuery;

        return Database.query(query);
    }
    //Phase 2 Rel 1 begin
    /*------------------------------------------------------------
      Author: Rey Austral
      Company: Cloud Sherpas
      Description: Retrieve task record and create a map to link the activity
      Inputs: 
      Returns: 
      History   
      02/03/14    Rey Austral      Created
      ------------------------------------------------------------*/
    public Map<Id, List<Project_Task__c>> retrieveTaskRecords()
    {
        //for unknown reason the objectId is becoming 18 char id, need to get only 15 char id
        Map<Id, List<Project_Task__c>> completeTaskMap = new Map<Id, List<Project_Task__c>> ();
        if (objectId != null)
        {
            String subId = objectId;
            subId = subId.substring(0, 15);

            Map<Id, Project_Activity__c> activityMap = new Map<Id, Project_Activity__c> ([Select Id from Project_Activity__c where SubProject_ID__c = :subId]);
            Set<Id> activityIds = activityMap.keySet();

            String taskOrderQuery = IMP_Project_Utility.getOrderColumns(SObjectType.Project_Task__c.FieldSets.Task_Sort_Commons.getFields(), true);

            String query = 'SELECT Project_Activity__c,Task_Definition__c,Actual_End_Date__c,Actual_Start_Date__c,CDK_Assignee__c, External_ID__c, Expected_Time_Spent__c,' +
            'CDK_Assignee_Role__c,Client_Assignee__c,Description__c,Display_on_PSR__c, Actual_Time_Spent__c, Reason__c,  Migration_Status__c, Reason_Missed_Planned_End_Date__c ,' +
            'Planned_End_Date__c,Planned_Start_Date__c,Status__c,Comments__c,Standard__c,Sequence__c  FROM Project_Task__c where Project_Activity__c in : activityIds ' + taskOrderQuery;

            List<Project_Task__c> taskList = Database.query(query);

            //link the activity and the project task
            for (Project_Task__c tsk : taskList)
            {
                if (completeTaskMap.containsKey(tsk.Project_Activity__c))
                {
                    //add the task in the existing activity
                    //this automatically update the value in the completeTaskMap no need to re update the map
                    List<Project_Task__c> tskList = completeTaskMap.get(tsk.Project_Activity__c);
                    tskList.add(tsk);
                }
                else
                {
                    List<Project_Task__c> tskList = new List<Project_Task__c> ();
                    tskList.add(tsk);
                    completeTaskMap.put(tsk.Project_Activity__c, tskList);
                }
            }
        }
        return completeTaskMap;
    }
    //Phase 2 Rel 1 end
    //Phase 2 Rel 1 begin
    /*------------------------------------------------------------
      Author: Rey Austral
      Company: Cloud Sherpas
      Description: populate the data and reseting all the extension field
      Inputs: List<Project_Milestone__c>
      Returns: 
      History
      12/24/14    Rey Austral      Created
      02/03/14    Rey Austral      Add task
      ------------------------------------------------------------*/
    public void resetWrapperDataAndExtensionField(List<Project_Milestone__c> projectMilestones)
    {
        Map<Id, List<Project_Task__c>> completeTaskMap = retrieveTaskRecords();

        //populate the record in wrapper
        milestoneContentList = new List<MilestoneWrapper> ();
        for (Project_Milestone__c miles : projectMilestones)
        {
            MilestoneWrapper mWrapper = new MilestoneWrapper();
            mWrapper.projectMilestone = miles;
            //site have a different way to highlight in the field
            //it needs to be in a list of string
            mWrapper.projectActivity = new List<ActivityWrapper> ();

            //populate the activity and add in the milestone
            if (miles.Project_Activities__r != null)
            {
                for (Project_Activity__c act : miles.Project_Activities__r)
                {
                    ActivityWrapper aWrap = new ActivityWrapper();
                    aWrap.activity = act;


                    //populate the task and add in the activity
                    if (completeTaskMap.containsKey(act.id))
                    {
                        List<Project_Task__c> taskList = completeTaskMap.get(act.id);
                        aWrap.projectTask = new List<TaskWrapper> ();
                        for (Project_Task__c t : taskList)
                        {
                            TaskWrapper tWrap = new TaskWrapper();
                            tWrap.task = t;
                            tWrap.toDelete = false;
                            tWrap.hasError = false;
                            aWrap.projectTask.add(tWrap);
                        }
                    }

                    mWrapper.projectActivity.add(aWrap);
                }
            }
            milestoneContentList.add(mWrapper);
        }
    }

    //Phase 2 Rel 1 end

    //Phase 2 Rel 1 begin
    /*------------------------------------------------------------
      Author: Rey Austral
      Company: Cloud Sherpas
      Description: re - populate the record in the milestone but retain the expand and checkbox value
      Inputs: List<Project_Milestone__c>
      Returns: 
      History
      12/24/14    Rey Austral      Created
      02/03/14    Rey Austral      Add task
      ------------------------------------------------------------*/
    public void resetWrapperDataOnly(List<Project_Milestone__c> projectMilestonesList)
    {
        Map<Id, List<Project_Task__c>> completeTaskMap = retrieveTaskRecords();

        //get first the expandActivity  preserve the expand after refresh
        Map<Id, Id> expandIdMap = new Map<Id, Id> ();

        for (MilestoneWrapper miles : milestoneContentList)
        {
            if (miles.expandActivity == true)
            {
                expandIdMap.put(miles.projectMilestone.Id, miles.projectMilestone.Id);
            }

            //get the expand for the activity
            if (miles.projectActivity != null)
            {
                List<ActivityWrapper> activityList = miles.projectActivity;
                for (ActivityWrapper act : activityList)
                {
                    if (act.expandTask == true)
                    {
                        expandIdMap.put(act.activity.Id, act.activity.Id);
                    }
                }
            }
        }

        //populate the record in wrapper
        milestoneContentList = new List<MilestoneWrapper> ();
        for (Project_Milestone__c miles : projectMilestonesList)
        {
            MilestoneWrapper mWrapper = new MilestoneWrapper();
            mWrapper.projectMilestone = miles;
            //search if the expand is already been check
            if (expandIdMap.containsKey(miles.Id))
            {
                mWrapper.expandActivity = true;
            }

            //it needs to be in a list of string
            mWrapper.projectActivity = new List<ActivityWrapper> ();

            //populate the activity and add in the milestone
            if (miles.Project_Activities__r != null)
            {
                for (Project_Activity__c act : miles.Project_Activities__r)
                {
                    ActivityWrapper aWrap = new ActivityWrapper();
                    aWrap.activity = act;

                    //search if the expand is already been check
                    if (expandIdMap.containsKey(act.Id))
                    {
                        aWrap.expandTask = true;
                    }

                    //populate the task and add in the activity
                    if (completeTaskMap.containsKey(act.id))
                    {
                        List<Project_Task__c> taskList = completeTaskMap.get(act.id);
                        aWrap.projectTask = new List<TaskWrapper> ();
                        for (Project_Task__c t : taskList)
                        {
                            TaskWrapper tWrap = new TaskWrapper();
                            tWrap.task = t;
                            tWrap.toDelete = false;
                            tWrap.hasError = false;
                            aWrap.projectTask.add(tWrap);
                        }

                    }
                    mWrapper.projectActivity.add(aWrap);
                }
            }
            milestoneContentList.add(mWrapper);
        }
    }
    //Phase 2 Rel 1 end
    /*------------------------------------------------------------
      Author: Rey Austral
      Company: Cloud Sherpas
      Description: Make the view mode change to Edit mode
      Inputs: 
      Returns: 
      History
      10/30/14    Rey Austral      Created
      ------------------------------------------------------------*/
    public void refresh()
    {
        ApexPages.getMessages().clear();
        resetWrapperDataOnly(retrieveMilestoneRecords());
    }
    //5-20-2015 Rey Austral Added Delete Function 
    public void deleteMilestone()
    {
        ApexPages.getMessages().clear();
        List<Project_Milestone__c> toDeleteMilestoneList = new List<Project_Milestone__c> ();
        List<Project_Activity__c> toDeleteActivityList = new List<Project_Activity__c> ();
        List<Project_Task__c> toDeleteTaskList = new List<Project_Task__c> ();


        Map<Id, Id> mapActivityToExpand = new Map<Id, Id> ();
        Boolean hasErrors = false;
        Map<Id, Id> errorIdsMap = new Map<Id, Id> ();
        Map<Id, Id> toDeleteAllIdMap = new Map<Id, Id> ();

        for (MilestoneWrapper miles : milestoneContentList)
        {
            miles.hasError = false;

            //if milestone record is to be deleted, all activity related to that milestone will also be deleted 
            //even if the user did not select the activty                
            if (miles.toDelete == true)
            {
                toDeleteMilestoneList.add(miles.projectMilestone);
                toDeleteAllIdMap.put(miles.projectMilestone.Id, miles.projectMilestone.id);
                List<ActivityWrapper> activityList = miles.projectActivity;
                for (ActivityWrapper act : activityList)
                {
                    toDeleteActivityList.add(act.activity);
                    toDeleteAllIdMap.put(act.activity.Id, act.activity.id);
                    if (act.projectTask != null)
                    {
                        List<TaskWrapper> taskList = act.projectTask;
                        for (TaskWrapper tsk : taskList)
                        {
                            toDeleteTaskList.add(tsk.Task);
                            toDeleteAllIdMap.put(tsk.Task.Id, tsk.Task.id);
                        }
                    }
                }
            }
            else
            {
                List<ActivityWrapper> activityList = miles.projectActivity;

                //there are specific condition to be consider when deleting an activity
                //please check the method for more details
                if (checkIfValidForDeletion(activityList, miles.projectMilestone.Description__c) == true)
                {

                    Boolean hasActivityToDelete = false;
                    for (ActivityWrapper act : activityList)
                    {
                        act.hasError = false;
                        if (act.toDelete == true)
                        {
                            //store the id that will be deleted to a container
                            act.activity.Milestone__r = new Project_Milestone__c();
                            act.activity.Milestone__r.Description__c = miles.projectMilestone.Description__c;
                            act.activity.Milestone__r.Id = miles.projectMilestone.Id;
                            toDeleteActivityList.add(act.activity);
                            toDeleteAllIdMap.put(act.activity.Id, act.activity.id);
                            if (act.projectTask != null)
                            {
                                List<TaskWrapper> taskList = act.projectTask;
                                for (TaskWrapper tsk : taskList)
                                {
                                    toDeleteTaskList.add(tsk.Task);
                                    toDeleteAllIdMap.put(tsk.Task.Id, tsk.Task.id);
                                }
                            }

                            hasActivityToDelete = true;
                        }
                        else
                        {
                            //there are specific condition to be consider when deleting an task
                            //please check the method for more details
                            if (act.projectTask != null)
                            {
                                List<TaskWrapper> taskList = act.projectTask;
                                if (checkIfValidForDeletion(taskList, miles.projectMilestone.Description__c, act.activity.Description__c) == true)
                                {
                                    for (TaskWrapper tsk : taskList)
                                    {
                                        tsk.hasError = false;
                                        if (tsk.toDelete == true)
                                        {
                                            toDeleteTaskList.add(tsk.Task);
                                            toDeleteAllIdMap.put(tsk.Task.Id, tsk.Task.id);
                                        }
                                    }
                                }
                                else
                                {
                                    act.hasError = true;
                                    act.expandTask = true;
                                    hasErrors = true;
                                    errorIdsMap.put(act.activity.Id, act.activity.Id);
                                }
                            }
                        }
                    }

                    //this is used to expand the activity of the milestone which have a deleted record
                    if (hasActivityToDelete == true)
                    {
                        mapActivityToExpand.put(miles.projectMilestone.Id, miles.projectMilestone.Id);
                    }
                }
                else
                {
                    //this will highlight the row and expand the activity
                    miles.hasError = true;
                    miles.expandActivity = true;
                    hasErrors = true;
                    errorIdsMap.put(miles.projectMilestone.Id, miles.projectMilestone.Id);
                }
            }
        }

        //Deletion of Task Record
        if (!toDeleteTaskList.isEmpty())
        {
            Try
            {
                List<Database.DeleteResult> dsrsTaskList = Database.Delete(toDeleteTaskList, false);
                Integer ctr = 0;
                for (Database.DeleteResult dsr : dsrsTaskList)
                {
                    //Iterate over failure records
                    if (!dsr.isSuccess())
                    {
                        Project_Task__c tsk = toDeleteTaskList[ctr];

                        if (!checkDuplicateTriggerError(tsk.Description__c))
                        {
                            String[] arguments = new String[] { tsk.Description__c, dsr.getErrors() [0].getMessage() };
                            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, String.format(IMP_String_Utility.DML_TASK_ERROR, arguments));
                            ApexPages.addMessage(errMsg);
                        }
                        errorIdsMap.put(tsk.Id, tsk.Id);
                        hasErrors = true;
                    }
                    ctr++;
                }
            }
            catch(Exception ex)
            {
                ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage());
                ApexPages.addMessage(errMsg);
                hasErrors = true;
            }

        }

        //Deletion of Activity Record
        if (!toDeleteActivityList.isEmpty())
        {
            try
            {
                List<Database.DeleteResult> dsrsActivityList = Database.Delete(toDeleteActivityList, false);
                Integer ctr = 0;
                for (Database.DeleteResult dsr : dsrsActivityList)
                {
                    //Iterate over failure records
                    if (!dsr.isSuccess())
                    {
                        Project_Activity__c act = toDeleteActivityList[ctr];
                        if (!checkDuplicateTriggerError(act.Description__c))
                        {
                            String[] arguments = new String[] { act.Description__c, dsr.getErrors() [0].getMessage() };

                            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, String.format(IMP_String_Utility.DML_ACTIVITY_ERROR, arguments));
                            ApexPages.addMessage(errMsg);
                        }

                        errorIdsMap.put(act.Id, act.Id);
                        hasErrors = true;
                    }
                    ctr++;
                }
            }
            catch(Exception ex)
            {
                ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage());
                ApexPages.addMessage(errMsg);
                hasErrors = true;
            }

        }

        //Deletion of Milestone Record
        if (!toDeleteMilestoneList.isEmpty())
        {
            try
            {
                List<Database.DeleteResult> dsrsMilestoneList = Database.Delete(toDeleteMilestoneList, false);
                Integer ctrMiles = 0;

                for (Database.DeleteResult dsrM : dsrsMilestoneList)
                {
                    //Iterate over failure records
                    if (!dsrM.isSuccess())
                    {
                        Project_Milestone__c miles = toDeleteMilestoneList[ctrMiles];

                        if (!checkDuplicateTriggerError(miles.Description__c))
                        {
                            String[] arguments = new String[] { miles.Description__c, dsrM.getErrors() [0].getMessage() };

                            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, String.format(IMP_String_Utility.DML_MILESTONE_ERROR, arguments));
                            ApexPages.addMessage(errMsg);
                        }

                        errorIdsMap.put(miles.Id, miles.Id);
                        hasErrors = true;
                    }
                    ctrMiles++;
                }
            }
            catch(Exception ex)
            {
                ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage());
                ApexPages.addMessage(errMsg);
                hasErrors = true;
            }

        }

        if (hasErrors == true)
        {
            //highlight row for the milestone and activty with error in deletion
            addErrorInTheWrapper(errorIdsMap, toDeleteAllIdMap);
        }
        else if (hasErrors == false)
        {
            //refresh the record to remove the deleted record in the screen, and expand the activty for the affected milestone
            List<Project_Milestone__c> projectM = retrieveMilestoneRecords();
            resetWrapperDataOnly(projectM);
        }

    }
    //5-20-2015 Rey Austral Added Delete Function 
    @TestVisible private void addErrorInTheWrapper(Map<Id, Id> errorIdMap, Map<Id, Id> toDeleteAllIdMap)
    {
        //this will update the hasError to highlight the row using css
        //this also expand the activity if the activity has one or more error
        if (!errorIdMap.isEmpty())
        {
            List<Integer> milestoneToRemoveFromEditPageList = new List<Integer> ();
            Integer cntMiles = 0;
            for (MilestoneWrapper miles : milestoneContentList)
            {
                if (errorIdMap.containsKey(miles.projectMilestone.Id))
                {
                    miles.hasError = true;
                }
                else if (toDeleteAllIdMap.containsKey(miles.projectMilestone.Id))
                {
                    //store the index of the record that has been successfully deleted in the database
                    miles.toDelete = false;
                    milestoneToRemoveFromEditPageList.add(cntMiles);
                }


                List<Integer> activityToRemoveFromEditPageList = new List<Integer> ();
                List<ActivityWrapper> activityList = miles.projectActivity;
                Integer cntAct = 0;
                for (ActivityWrapper act : activityList)
                {
                    if (errorIdMap.containsKey(act.activity.Id))
                    {
                        act.hasError = true;
                        miles.expandActivity = true;
                    }
                    else if (toDeleteAllIdMap.containsKey(act.activity.Id))
                    {
                        //store the index of the record that has been successfully deleted in the database
                        act.toDelete = false;
                        activityToRemoveFromEditPageList.add(cntAct);
                    }

                    //Only process the task when there are no activity selected
                    if (act.projectTask != null)
                    {
                        List<Integer> taskToRemoveFromEditPageList = new List<Integer> ();
                        List<TaskWrapper> taskList = act.projectTask;
                        Integer cntTask = 0;
                        for (TaskWrapper task : taskList)
                        {

                            if (errorIdMap.containsKey(task.task.Id))
                            {
                                task.hasError = true;
                                miles.expandActivity = true;
                            }
                            else if (toDeleteAllIdMap.containsKey(task.task.Id))
                            {
                                //store the index of the record that has been successfully deleted in the database
                                task.toDelete = false;
                                taskToRemoveFromEditPageList.add(cntTask);
                            }

                            cntTask++;
                        }

                        if (taskToRemoveFromEditPageList.size() > 0)
                        {
                            //iterate the list to remove the deleted task record in the task wrapper class
                            taskToRemoveFromEditPageList.sort();
                            for (Integer indexTask = taskToRemoveFromEditPageList.size() - 1; indexTask >= 0; indexTask--)
                            {
                                taskList.remove(taskToRemoveFromEditPageList[indexTask]);
                            }
                        }
                    }

                    cntAct++;

                }
                if (activityToRemoveFromEditPageList.size() > 0)
                {
                    //iterate the list to remove the deleted activity record in the activity wrapper class
                    activityToRemoveFromEditPageList.sort();
                    for (Integer indexAct = activityToRemoveFromEditPageList.size() - 1; indexAct >= 0; indexAct--)
                    {
                        activityList.remove(activityToRemoveFromEditPageList[indexAct]);
                    }
                }

                cntMiles++;
            }
            if (milestoneToRemoveFromEditPageList.size() > 0)
            {
                //iterate the list to remove the deleted milestone record in the milestone wrapper class\
                milestoneToRemoveFromEditPageList.sort();
                for (Integer indexMiles = milestoneToRemoveFromEditPageList.size() - 1; indexMiles >= 0; indexMiles--)
                {
                    milestoneContentList.remove(milestoneToRemoveFromEditPageList[indexMiles]);
                }
            }
        }
    }

    @TestVisible private Boolean checkIfValidForDeletion(List<ActivityWrapper> activityList, String MilestoneDescription)
    {
        Boolean result = true;
        Integer ctr = 0;
        Boolean haveTerminal = false;
        for (ActivityWrapper act : activityList)
        {
            //count the number of record that will be deleted
            if (act.toDelete == true)
            {
                ctr++;
            }

        }

        String[] arguments = new String[] { MilestoneDescription };
        if (activityList.size() == ctr)
        {
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, String.format(IMP_String_Utility.DELETE_TERMINAL_ACTIVITY, arguments));
            ApexPages.addMessage(errMsg);
            result = false;
        }

        return result;
    }

    @TestVisible private Boolean checkIfValidForDeletion(List<TaskWrapper> taskList, String MilestoneDescription, String ActivityDescription)
    {
        Boolean result = true;
        Integer ctr = 0;
        Boolean haveTerminal = false;

        for (TaskWrapper tsk : taskList)
        {
            //count the number of record that will be deleted
            if (tsk.toDelete == true)
            {
                ctr++;
            }
        }

        String[] arguments = new String[] { MilestoneDescription, ActivityDescription };
        if (taskList.size() == ctr)
        {
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, String.format(IMP_String_Utility.DELETE_TERMINAL_TASK, arguments));
            ApexPages.addMessage(errMsg);
            result = false;
        }

        return result;
    }

    public Boolean checkDuplicateTriggerError(String description)
    {
        Boolean result = false;
        List<Apexpages.Message> errorMessagesList = ApexPages.getMessages();

        if (errorMessagesList != null)
        {
            for (Apexpages.Message msg : errorMessagesList)
            {
                String[] arguments = new String[] { description };
                String errMilestone = String.format(IMP_String_Utility.NO_BYPASS_TODELETE_ACTIVITY, arguments);
                String errActivity = String.format(IMP_String_Utility.NO_BYPASS_TODELETE_MILESTONE, arguments);
                String errTask = String.format(IMP_String_Utility.NO_BYPASS_TODELETE_TASK, arguments);

                if (msg.getDetail() == errMilestone ||
                    msg.getDetail() == errActivity ||
                    msg.getDetail() == errTask)
                {
                    result = true;
                }
            }
        }
        return result;
    }
    //2015-8-3 Rey Austral - This method is used to highlight the error in the list
    public void updateAllDisplayPSR()
    {
        ApexPages.getMessages().clear();
        List<Project_Milestone__c> toUpdateMilestoneList = new List<Project_Milestone__c> ();
        List<Project_Activity__c> toUpdateActivityList = new List<Project_Activity__c> ();
        List<Project_Task__c> toUpdateTaskList = new List<Project_Task__c> ();
        Boolean hasError = false;
        //Update all Display_on_PSR__c field in Milestone,Activity And Task Record
        //Iterate all the milestone in the wrapper class
        for (MilestoneWrapper miles : milestoneContentList)
        {
            miles.hasError = false;
            //Update Display_on_PSR__c based on the button that the user click
            miles.projectMilestone.Display_on_PSR__c = toDisplay;
            //add the milestone record in the list to update
            toUpdateMilestoneList.add(miles.projectMilestone);
            //get the activity in the currrent milestone
            List<ActivityWrapper> activityList = miles.projectActivity;
            for (ActivityWrapper act : activityList)
            {
                //Update Display_on_PSR__c based on the button that the user click
                act.activity.Display_on_PSR__c = toDisplay;
                //add the activity record in the list to update
                toUpdateActivityList.add(act.activity);
                if (act.projectTask != null)
                {
                    //get the task in the currrent activity
                    List<TaskWrapper> taskList = act.projectTask;
                    for (TaskWrapper tsk : taskList)
                    {
                        tsk.Task.Display_on_PSR__c = toDisplay;
                        toUpdateTaskList.add(tsk.Task);
                    }
                }
            }
        }
        Map<Id, Id> errorIdsMap = new Map<Id, Id> ();
        if (!toUpdateMilestoneList.isEmpty())
        {
            List<Database.SaveResult> dsrsMilestoneList = Database.Update(toUpdateMilestoneList, false);
            Integer ctrMiles = 0;

            //get all the id of the error milestone and activity to be used in hightlighting the row
            for (Database.SaveResult dsrM : dsrsMilestoneList)
            {
                //Iterate over failure records
                if (!dsrM.isSuccess())
                {
                    Project_Milestone__c miles = toUpdateMilestoneList[ctrMiles];
                    String[] arguments = new String[] { miles.Description__c, dsrM.getErrors() [0].getMessage() };

                    ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, String.format(IMP_String_Utility.DML_MILESTONE_ERROR, arguments));
                    ApexPages.addMessage(errMsg);
                    hasError = true;
                    errorIdsMap.put(miles.Id, miles.Id);
                }
                ctrMiles++;
            }

        }
        if (!toUpdateActivityList.isEmpty())
        {
            List<Database.UpsertResult> dursActivityList = Database.Upsert(toUpdateActivityList, false);
            Integer ctr = 0;

            for (Database.UpsertResult dsr : dursActivityList)
            {
                //Iterate over failure records
                Project_Activity__c act = toUpdateActivityList[ctr];
                if (!dsr.isSuccess())
                {
                    String[] arguments = new String[] { act.Milestone__r.Description__c, act.Description__c, dsr.getErrors() [0].getMessage() };

                    ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, String.format(IMP_String_Utility.DML_ACTIVITY_ERROR, arguments));
                    ApexPages.addMessage(errMsg);
                    hasError = true;
                    errorIdsMap.put(act.Id, act.Id);
                }

                ctr++;
            }
        }
        if (!toUpdateTaskList.isEmpty())
        {
            List<Database.UpsertResult> dsrsTaskList = Database.Upsert(toUpdateTaskList, false);
            Integer ctr = 0;
            for (Database.UpsertResult dsr : dsrsTaskList)
            {
                //Iterate over failure records
                if (!dsr.isSuccess())
                {
                    Project_Task__c tsk = toUpdateTaskList[ctr];
                    String[] arguments = new String[] { tsk.Description__c, dsr.getErrors() [0].getMessage() };

                    ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, String.format(IMP_String_Utility.DML_TASK_ERROR, arguments));
                    ApexPages.addMessage(errMsg);
                    hasError = true;
                    errorIdsMap.put(tsk.Id, tsk.Id);
                }
                ctr++;
            }
        }

        if (!errorIdsMap.isEmpty())
        {
            //this will update hasError in the wrapper to highlight the row and expand it 
            addErrorInUpdate(errorIdsMap);
        }
    }
    //2015-8-3 Rey Austral - This method is used to highlight the error in the list
    @TestVisible private void addErrorInUpdate(Map<Id, Id> errorIdMap)
    {
        //this will update the hasError to highlight the row using css
        //this also expand the activity if the activity has one or more error
        if (!errorIdMap.isEmpty())
        {
            for (MilestoneWrapper miles : milestoneContentList)
            {
                if (errorIdMap.containsKey(miles.projectMilestone.Id))
                {
                    miles.hasError = true;
                }
                List<ActivityWrapper> activityList = miles.projectActivity;
                for (ActivityWrapper act : activityList)
                {
                    if (errorIdMap.containsKey(act.activity.Id))
                    {
                        act.hasError = true;
                        miles.expandActivity = true;
                    }

                    if (act.projectTask != null)
                    {
                        List<TaskWrapper> taskList = act.projectTask;
                        for (TaskWrapper task : taskList)
                        {
                            if (errorIdMap.containsKey(task.task.Id))
                            {
                                task.hasError = true;
                                miles.expandActivity = true;
                                act.expandTask = true;
                            }
                        }
                    }
                }
            }
        }
    }

    public class MilestoneWrapper
    {
        public Project_Milestone__c projectMilestone { get; set; }
        public List<ActivityWrapper> projectActivity { get; set; }
        public Boolean expandActivity { get; set; }
        public Boolean toDelete { get; set; }
        public Boolean hasError { get; set; }
    }

    public class ActivityWrapper
    {
        public Project_Activity__c activity { get; set; }
        public List<TaskWrapper> projectTask { get; set; }
        public Boolean toDelete { get; set; }
        public Boolean expandTask { get; set; }
        public Boolean hasError { get; set; }
    }

    public class TaskWrapper
    {
        public Project_Task__c task { get; set; }
        public Boolean toDelete { get; set; }
        public Boolean hasError { get; set; }
    }
}