SF Primes/src/objects/ADP_Product_Solution__c.object
<CustomObject>
    <description>List of product solutions used for competitive products.</description>
    <label>ADP Product Solution</label>
    <nameField>
        <label>ADP Product Solution</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADP Product Solution</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Competitive_Products_At_Dealership__c.object
<CustomObject>
    <description>The custom object/related list is needed to allow a user the ability to enter key information about a product that an account is using from a competitor.</description>
    <fields>
        <fullName>ADP_Product_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select an ADP like solution that matches the client’s product.</inlineHelpText>
        <label>ADP Product Name</label>
        <referenceTo>ADP_Product_Solution__c</referenceTo>
        <relationshipLabel>Competitive Products At Dealership</relationshipLabel>
        <relationshipName>Competitive_Products_At_Dealership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitive Products At Dealership</relationshipLabel>
        <relationshipName>Competitive_Products_At_Dealership</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competitive_Vendor_Name__c</fullName>
        <formula>IF(Competitive_Vendor__r.Competitive_Vendor_Name__c =  &apos;Other&apos;, Competitive_Vendor__r.Competitive_Vendor_Name__c + &apos; - &apos; +  Non_Listed_Vendor__c, Competitive_Vendor__r.Competitive_Vendor_Name__c)</formula>
        <label>Competitive Vendor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitive_Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Competitive Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Competitive_Vendor__c.ADP_Product_Solution__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.ADP_Product_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Competitive_Vendor__c</referenceTo>
        <relationshipLabel>Competitive Products At Dealership</relationshipLabel>
        <relationshipName>Competitive_Products_At_Dealership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Competitive Products At Dealership</label>
    <nameField>
        <displayFormat>CPD-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Products At Dealership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Competitive_Vendor__c.object
<CustomObject>
    <description>List of competitive vendors</description>
    <fields>
        <fullName>ADP_Product_Solution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADP Product Solution</label>
        <referenceTo>ADP_Product_Solution__c</referenceTo>
        <relationshipLabel>Competitive Vendor</relationshipLabel>
        <relationshipName>Competitive_Vendor</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitive_Vendor_Name__c</fullName>
        <label>Competitive Vendor Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Competitive Vendor</label>
    <nameField>
        <displayFormat>CV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Vendor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DS_CompetitiveProductsExtension.cls
public class DS_CompetitiveProductsExtension
{
    // variables
    public ApexPages.StandardController Controller;
    public Competitive_Products_At_Dealership__c Record;
    public List<Competitive_Vendor__c> Vendors;
    
    // properties
    public String ProductName {get;set;}
    public List<SelectOption> VendorOptions {get;set;}
    
    // constructor
    public DS_CompetitiveProductsExtension(ApexPages.StandardController ctr) 
    { 
        Controller = ctr; 
        
        // get the current record from the standard controller of the visualforce page
        Record = (Competitive_Products_At_Dealership__c)Controller.getRecord();
        
        // get the name of the Product Solution from the current record
        if(Record != null)
        {
            if(Record.ADP_Product_Name__c != null) { 
                ADP_Product_Solution__c p = [Select Name From ADP_Product_Solution__c Where Id = :Record.ADP_Product_Name__c Limit 1]; 
                if(p != null) { ProductName = p.Name; }
            }
        }
        
        String AccountId = ApexPages.currentPage().getParameters().get('aid');
        if(AccountId != null) { Record.Account__c = AccountId; }
        
        RefreshVendorOptions();
    }
    
    // Refresh Vendor method
    //  - called by an action function to refresh the picklist of Vendor options
    public void RefreshVendorOptions()
    {
    	// get all of the Competitive Vendors
    	Vendors = [Select Id, Name, Competitive_Vendor_Name__c, ADP_Product_Solution__r.Name, ADP_Product_Solution__c From Competitive_Vendor__c];
    	
        // get the current record from the standard controller of the visualforce page
        Record = (Competitive_Products_At_Dealership__c)Controller.getRecord();
        
        // if the record is not null, and the list of vendors is not null
        if(Record != null && Vendors != null)
        {
            VendorOptions = new List<SelectOption>();
            
            // loop through all vendors
            for(Competitive_Vendor__c v : Vendors)
            {
                if(v.ADP_Product_Solution__c != null)
                {
                    // if the vendor Product Solution equals the selected Product Solution on the
                    // Competitive Product at Dealership, add an option the the picklist
                    if(v.ADP_Product_Solution__r.Name == ProductName)
                    {
                        SelectOption opt = new SelectOption(v.Id, v.Competitive_Vendor_Name__c);
                        VendorOptions.add(opt);
                    }
                }
            }
        }
    }
    
    // Save and New functionality
    //  - There is no default Save and New action on Standard Controllers; so it must be custom
    public PageReference SaveAndNew()
    {
        try { this.Controller.Save(); }
        catch (Exception ex) { ApexPages.addMessages(ex); }
        
        // if there are error messages, return the current page (null)
        if(ApexPages.hasMessages()) { 
            return null; 
        }
        // if there were no error messages
        else { 
            // get the edit page URL for a new record, and return a PageReference for that URL
            String prefix = Competitive_Products_At_Dealership__c.sObjectType.getDescribe().getKeyPrefix(); 
            return new PageReference('/' + prefix + '/e?retURL=/' + prefix + (Record.Account__c != null ? '&aid=' + Record.Account__c : '')); 
        } 
    }
}