SF Primes/src/objects/ADP_Default_Team__c.object
<CustomObject>
    <description>ADP Default Team used for account or territory reallignment purposes.</description>
    <fields>
        <fullName>Key_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key_Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ADP_Default_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>ARG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heavy Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoffman Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Truck Dealers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NIADA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PFW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ADP Default Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADP Default Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Key_Rep_Changes__c.object
<CustomObject>
    <description>DS SalesOps objects to change ownership of accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Key Rep Changes</relationshipLabel>
        <relationshipName>Key_Rep_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Key_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Key Rep</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3 OR 4 OR 5 OR 6)</booleanFilter>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Forecasting_Channel__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>User.Non_Interactive_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <value>00540000000zry6AAA</value>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <value>00540000000zT4eAAE</value>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <value>005400000022z7vAAA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Key_Rep_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Key Rep Changes</label>
    <nameField>
        <displayFormat>KRC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Rep Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/classes/DS_KeyRepChange_Test.cls
//2016-01-21- anirudh.singh@cdk.com- Created this test class for handler DS_KeyRepChange_Handler 
//+ and bringing the Trigger DS_KeyRepChange upto standards it up to the Standards as per Request RQ-06024.
@isTest
public class DS_KeyRepChange_Test
{
    @TestSetup
    private static void setupData()
    {
        Account accountRecord=DS_TestObjects.NewAccount();
        accountRecord.Region__c='National';
        insert accountRecord;
    }
    
    private static testMethod void testPositive()
    {
        Account accountRecord=[SELECT Id FROM Account];
        
        List<User> userList=new List<User>();
        
        User userRecordOne=DS_TestObjects.NewUser();
        userRecordOne.Forecasting_Channel__c='National';
        userList.add(userRecordOne);
        
        User userRecordTwo=DS_TestObjects.NewUser();
        userRecordTwo.Forecasting_Channel__c='National';
        userList.add(userRecordTwo);
        
        insert userList;
        
        List<ADP_Default_Team__c> accountTeamList=new List<ADP_Default_Team__c>();
        
        ADP_Default_Team__c teamOne=new ADP_Default_Team__c();
        teamOne.Name=userRecordOne.Name+'Team';
        teamOne.Key_Rep__c=userRecordOne.Id;
        teamOne.Region__c='National';
        accountTeamList.add(teamOne);
        
        ADP_Default_Team__c teamTwo=new ADP_Default_Team__c();
        teamTwo.Name=userRecordOne.Name+'Team';
        teamTwo.Key_Rep__c=userRecordOne.Id;
        teamTwo.Region__c='National';
        accountTeamList.add(teamTwo);
        
        insert accountTeamList;
        
        test.startTest();
        List<Key_Rep_Changes__c> keyRepChangesList=new List<Key_Rep_Changes__c>();
        
        Key_Rep_Changes__c keyRepChangesRecOne=new Key_Rep_Changes__c();
        keyRepChangesRecOne.New_Key_Rep__c=userRecordOne.Id;
        keyRepChangesRecOne.Account__c=accountRecord.Id;
        keyRepChangesList.add(keyRepChangesRecOne);
        
        Key_Rep_Changes__c keyRepChangesRecTwo=new Key_Rep_Changes__c();
        keyRepChangesRecTwo.New_Key_Rep__c=userRecordOne.Id;
        keyRepChangesRecTwo.Account__c=accountRecord.Id;
        keyRepChangesList.add(keyRepChangesRecTwo);
        
        DS_KeyRepChange_Handler.addErrorToInsertedRecords(keyRepChangesList);
        
        try
        {
            insert keyRepChangesList;
        }
        catch(Exception e)
        {
            system.debug(e);
        }
        
        test.stopTest();
    }
    
    private static testMethod void testNegative()
    {
        Account accountRecord=[SELECT Id FROM Account];
        
        User userRecord=DS_TestObjects.NewUser();
        userRecord.Forecasting_Channel__c='National';
        insert userRecord;
        
        test.startTest();
        List<Key_Rep_Changes__c> keyRepChangesList=new List<Key_Rep_Changes__c>();
        
        Key_Rep_Changes__c keyRepChangesRec=new Key_Rep_Changes__c();
        keyRepChangesRec.New_Key_Rep__c=userRecord.Id;
        keyRepChangesRec.Account__c=accountRecord.Id;
        keyRepChangesList.add(keyRepChangesRec);
        
        DS_KeyRepChange_Handler.addErrorToInsertedRecords(keyRepChangesList);
        
        try
        {
            insert keyRepChangesList;
        }
        catch(Exception e)
        {
            system.debug(e);
        }
        test.stopTest();
    }
}