SF Primes/src/objects/ADP_Default_Team__c.object
<CustomObject>
    <description>ADP Default Team used for account or territory reallignment purposes.</description>
    <fields>
        <fullName>Key_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key_Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ADP_Default_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>ARG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heavy Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoffman Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Truck Dealers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NIADA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PFW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ADP Default Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADP Default Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Key_Rep_Changes__c.object
<CustomObject>
    <description>DS SalesOps objects to change ownership of accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Key Rep Changes</relationshipLabel>
        <relationshipName>Key_Rep_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Key_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Key Rep</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3 OR 4 OR 5 OR 6)</booleanFilter>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Forecasting_Channel__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>User.Non_Interactive_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <value>00540000000zry6AAA</value>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <value>00540000000zT4eAAE</value>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>equals</operation>
                <value>005400000022z7vAAA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Key_Rep_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Key Rep Changes</label>
    <nameField>
        <displayFormat>KRC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Rep Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Docusign/src/classes/DS_KeyRepChangeTest.cls
@IsTest
public class DS_KeyRepChangeTest 
{
    public static testmethod void Test()
    {
        User u = DS_TestObjects.NewUser();
        u.Forecasting_Channel__c = 'National';
        insert u;
        
        Account a = DS_TestObjects.NewAccount();
        a.Region__c = 'National';
        insert a;
        
        Key_Rep_Changes__c k = new Key_Rep_Changes__c();
        k.New_Key_Rep__c = u.Id;
        k.Account__c = a.Id;
        
        // this should throw an error due to Trigger validation
        try { insert k; } catch (Exception e) { system.debug(e); }
        
        ADP_Default_Team__c d = new ADP_Default_Team__c();
        d.Name = u.Name + 'Team';
        d.Key_Rep__c = u.Id;
        d.Region__c = 'National';
        insert d;
        
        // this should succeed (passing Trigger validation)
        try { insert k; } catch (Exception e) { system.debug(e); }
    }
}