SF Primes/src/objects/ADP_Product_Solution__c.object
<CustomObject>
    <description>List of product solutions used for competitive products.</description>
    <fields>
        <fullName>ADP_Product_Solution_ID__c</fullName>
        <externalId>true</externalId>
        <label>ADP Product Solution ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>ADP Product Solution</label>
    <nameField>
        <label>ADP Product Solution</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADP Product Solution</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Competitive_Products_At_Dealership__c.object
<CustomObject>
    <description>The custom object/related list is needed to allow a user the ability to enter key information about a product that an account is using from a competitor.</description>
    <fields>
        <fullName>ADP_Product_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select an ADP like solution that matches the client’s product.</inlineHelpText>
        <label>ADP Product Name</label>
        <referenceTo>ADP_Product_Solution__c</referenceTo>
        <relationshipLabel>Competitive Products At Dealership</relationshipLabel>
        <relationshipName>Competitive_Products_At_Dealership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitive Products At Dealership</relationshipLabel>
        <relationshipName>Competitive_Products_At_Dealership</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competitive_Vendor_Name__c</fullName>
        <formula>IF(Competitive_Vendor__r.Competitive_Vendor_Name__c =  &apos;Other&apos;, Competitive_Vendor__r.Competitive_Vendor_Name__c + &apos; - &apos; +  Non_Listed_Vendor__c, Competitive_Vendor__r.Competitive_Vendor_Name__c)</formula>
        <label>Competitive Vendor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitive_Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Competitive Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Competitive_Vendor__c.ADP_Product_Solution__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.ADP_Product_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Competitive_Vendor__c</referenceTo>
        <relationshipLabel>Competitive Products At Dealership</relationshipLabel>
        <relationshipName>Competitive_Products_At_Dealership</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Competitive Products At Dealership</label>
    <nameField>
        <displayFormat>CPD-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Products At Dealership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Competitive_Vendor__c.object
<CustomObject>
    <description>List of competitive vendors</description>
    <fields>
        <fullName>ADP_Product_Solution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADP Product Solution</label>
        <referenceTo>ADP_Product_Solution__c</referenceTo>
        <relationshipLabel>Competitive Vendor</relationshipLabel>
        <relationshipName>Competitive_Vendor</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitive_Vendor_Name__c</fullName>
        <label>Competitive Vendor Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Competitive Vendor</label>
    <nameField>
        <displayFormat>CV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Vendor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Docusign/src/classes/DS_CompetitiveProductsExtension_Test.cls
@IsTest
public class DS_CompetitiveProductsExtension_Test
{
    public static testmethod void Test()
    {
    	Account a = DS_TestObjects.NewAccount_Inserted();
    	
    	ADP_Product_Solution__c ProductSolution = new ADP_Product_Solution__c();
    	ProductSolution.Name = 'Test Product Solution';
    	ProductSolution.ADP_Product_Solution_ID__c = 100;
    	insert ProductSolution;
    	
    	List<Competitive_Vendor__c> CompetitiveVendors = new List<Competitive_Vendor__c>();
    	for(Integer i=0; i<5; i++) {
			CompetitiveVendors.add(new Competitive_Vendor__c(
				ADP_Product_Solution__c = ProductSolution.Id, 
				Competitive_Vendor_Name__c = 'Test Vendor Name ' + String.valueOf(i)
			));
		}
		insert CompetitiveVendors;
    	
    	Competitive_Products_At_Dealership__c CompetitiveProducts = new Competitive_Products_At_Dealership__c();
    	CompetitiveProducts.Account__c = a.Id;
    	CompetitiveProducts.ADP_Product_Name__c = ProductSolution.Id;
    	CompetitiveProducts.Competitive_Vendor__c = CompetitiveVendors[0].Id;
    	insert CompetitiveProducts;
    	
    	PageReference pg = Page.DS_CompetitiveProductsAtDealership_Edit;
        pg.getParameters().put('id',CompetitiveProducts.Id);
        Test.setCurrentPage(pg);
        Test.startTest();
        
        ApexPages.StandardController ctrlr = new ApexPages.StandardController(CompetitiveProducts);
        DS_CompetitiveProductsExtension CompetitiveProductsExtension = new DS_CompetitiveProductsExtension(ctrlr);
        CompetitiveProductsExtension.SaveAndNew();
    }
}