SF Primes/src/objects/ALL_Decision_Box_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Assignment_sObject__c</fullName>
        <label>Assignment sObject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition_Check__c</fullName>
        <label>Condition Check</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Assignment__c</fullName>
        <label>Value Assignment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ALL Decision Box Settings</label>
</CustomObject>

SF Primes/src/objects/Launch__c.object
<CustomObject>
    <description>Used by CB Services to track progress of website build in progress</description>
    <fields>
        <fullName>Account_Advocate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Advocate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Launch4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Advocate_Email__c</fullName>
        <description>This field is updated by a workflow with the Advocate email from the WebId object.</description>
        <label>Advocate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CAM_Email__c</fullName>
        <description>This email is updated by a workflow with the Digital Services Marketing Strategist email from the Account object. Do not display on page layout - this is intended for workflows</description>
        <label>Marketing Strategist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DSM_Email__c</fullName>
        <description>This email is updated by a workflow with the DSM email from the Account object.  Do not display on page layout - this is intended for workflows.</description>
        <label>DSM Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EMS_Email__c</fullName>
        <description>This field is updated by a workflow with the Email Marketing Specialist email from the WebId object.</description>
        <label>EMS Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OMS_Email__c</fullName>
        <description>This field is updated by a workflow with the Online Marketing Specialist (Digital Advertising Specialists) email from the WebId object.</description>
        <label>OMS Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Online_Marketing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DA Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Launch6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accessories Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Reputation Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Insights Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Insights Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Management Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Management Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Optimization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Tag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Svc&amp;Pts Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cobalt AutoShow for Exports Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Us Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core/ProSite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Email Aliases (each 10)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Buy/Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAP+Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Group Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Inventory Export Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Name Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain or Email Misc Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain or Email Misc One Time Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Hosting Upgrade (25 GB Increase)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Hosting Upgrade (Add&apos;l Mailboxes)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PowerSEO non-CDK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProCare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Essentials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VW Core</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>RMS_Email__c</fullName>
        <description>This field is updated by a workflow with the Reputation Management Specialist email from the WebId object.</description>
        <label>RMS Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Reputation_Management_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reputation Management Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Launch1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SEO_Email__c</fullName>
        <description>This field is updated by a workflow with the SEO Specialist email from the WebId object.</description>
        <label>SEO Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SEO_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SEO Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Launch5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMS_Email__c</fullName>
        <description>This field is updated by a workflow with the Social Media Specialist email from the WebId object.</description>
        <label>SMS Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Social_Media_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Social Marketing Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Launch2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Gathering Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress - Not Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle Order Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Closed Waiting on Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed w/ Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed w/o Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Preactivation Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed as Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activation Steps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Launch</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Launch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Launch</pluralLabel>
    <recordTypes>
        <fullName>Website_Launch</fullName>
        <active>true</active>
        <description>New websites launches including upgrades, downgrades and multi-brand.</description>
        <label>Website Launch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>Account_Advocate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Advocate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Website</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Online_Marketing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Digital Advertising Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Website1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OwnerMktg_Specialist_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Email Marketing Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Website2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reputation_Management_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reputation Management Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SEO_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SEO Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Websites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Social_Media_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Social Marketing Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WebIDs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DS_Launch_Handler.cls
//2016-05-27 - siva.pragada@cdk.com - added logic for replacing WebID AA with Launch AA
public class DS_Launch_Handler 
{
    // below static maps are queries in before trigger and are available in after trigger as well
    public static Map<Id, Account> staticAccountsMap = new Map<Id, Account>();
    public static Map<Id, WebID__c> staticWebIDsMap = new Map<Id, WebID__c>();
    
    public static void processLaunch2CaseLogic()
    {
        Try{
            list<Launch__c> launchList = (list<Launch__c>)Trigger.new;
            //map<ID, Launch__c> oldLaunchMap = (map<ID, Launch__c>)Trigger.oldMap;
            list<ALL_Decision_Box_Settings__c> decisionList = ALL_UtilitiesLogic.getRelevantDecisionBoxSettings('Launch__c', 'Case');
            GlobalSettings__c gs = GlobalSettings__c.getInstance();
            list<case> insertCasesList = new list<Case>();
            map<ID, Launch__c> helperLaunchMap = new map<ID, Launch__c>(launchList.deepClone(true, true, true));
            
            
            for(Launch__c newLaunch: launchList)
            {  
                WebID__c currentWebID = newLaunch.WebID__c != null ? staticWebIDsMap.get(newLaunch.WebID__c): null;
                Launch__c helperLaunch = helperLaunchMap.get(newLaunch.ID);
                helperLaunch.putSobject('WebID__r', currentWebID);
                
                if(!decisionList.isEmpty() && gs.Launch_Onboarding_Switch__c)
                {
                    for(ALL_Decision_Box_Settings__c dbs: decisionList)
                    {
                        //Launch__c oldLaunch = oldLaunchMap != null ? oldLaunchMap.get(newLaunch.ID) : null;
                        boolean fieldsValuesChanged = ALL_UtilitiesLogic.evaluatedExpressionsMap.get(dbs.Condition_Check__c);
                        
                        system.debug(dbs.Condition_Check__c);
                        system.debug(fieldsValuesChanged);
                        
                        if(fieldsValuesChanged == null)
                        {                
                            fieldsValuesChanged = ALL_UtilitiesLogic.getcompositeExpressionsEvaluatedValue(
                                dbs.Condition_Check__c, helperLaunch);
                        }
                        
                        system.debug(dbs.Condition_Check__c);
                        system.debug(fieldsValuesChanged);
                        //system.assertEquals(decisionList.size(),1);
                        if(fieldsValuesChanged != null && fieldsValuesChanged)
                        {
                            sObject newObject = ALL_UtilitiesLogic.createRecords(
                                dbs.Value_Assignment__c, dbs.Assignment_sObject__c, helperLaunch);
                            
                            Case newCase = (Case)newObject;                    
                            insertCasesList.add(newCase);
                        }
                        
                        //below makes sure the expression is not evaluated one more time consuming the browser limited time.
                        ALL_UtilitiesLogic.evaluatedExpressionsMap.put(dbs.Condition_Check__c, fieldsValuesChanged);
                    }
                }
            }
            
            //system.debug(insertCasesList);
            //system.debug(ALL_UtilitiesLogic.evaluatedExpressionsMap);
            
            //for(string s: ALL_UtilitiesLogic.allIdentifierTobooleanMap.keySet())
            //{
            //system.debug(s + ' : ' + ALL_UtilitiesLogic.allIdentifierTobooleanMap.get(s));
            //}
            //system.debug(ALL_UtilitiesLogic.allIdentifierTobooleanMap);
            
            //for(string key: ALL_UtilitiesLogic.evaluatedExpressionsMap.keySet())
            //{
            //system.debug(key + ' : ' + ALL_UtilitiesLogic.evaluatedExpressionsMap.get(key));
            //}
            
            if(!insertCasesList.isEmpty())
            {  
                insert insertCasesList;
            }
        }
        Catch(Exception exp)
        {
            All_UtilitiesMiscellaneous.logException(exp);
        }
    }
    
    public static void CB_LaunchUpdateEmails()
    {
        Try{
            map<ID, Launch__c> launchMap = null;
            
            if(Trigger.isUpdate)
            {
                launchMap = new map<ID, Launch__c>([
                    Select ID, Name, (Select ID, ParentID, oldValue, newValue, Field From Histories Where Field = 'Status__c') 
                    From Launch__c
                    Where ID IN :Trigger.new
                ]);
            }
            ID A_La_Carte_RecordType = ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('Launch__c', 'A La Carte Launch');
            ID website_Launch = ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('Launch__c', 'Website Launch');
            
            list<WebID__c> webIDsListUpdate = new list<WebID__c>();
            
            Set<Id> AccountsToQuery = new Set<Id>();
            Set<Id> WebIDsToQuery = new Set<Id>();
            list<Launch__c> newList = (List<Launch__c>) Trigger.new;
            
            // loop through updated records
            for(Launch__c l : newList) 
            {    
                if(l.Account__c != null) { AccountsToQuery.add(l.Account__c); }
                if(l.WebID__c != null) { WebIDsToQuery.add(l.WebID__c); }
            }
            
            system.debug(AccountsToQuery);
            
            // query the Account fields for the collected Launch Accounts
            
            if(!AccountsToQuery.IsEmpty()) 
            {
                staticAccountsMap = new Map<Id, Account>([
                    Select Id, Designated_DSM__r.Email, Digital_Services_CAM__r.Email 
                    From Account 
                    Where Id IN :AccountsToQuery
                ]); 
            }
            
            // query the WebID fields for the collected Launch WebIDs
            
            if(!WebIDsToQuery.IsEmpty()) 
            {
                staticWebIDsMap = new Map<Id, WebID__c>([
                    Select Id, Name, Status__c, Account_Advocate__c, Account_Advocate__r.Email, OwnerMktg_Specialist_lookup__r.Email,
                    Online_Marketing_Specialist__r.Email, Reputation_Management_Specialist__r.Email, 
                    SEO_Specialist__r.Email, Social_Media_Specialist__r.Email 
                    From WebID__c 
                    Where Id IN :WebIDsToQuery
                ]); 
            }
            
            if(!newList.IsEmpty()) 
            {
                for(Launch__c currentLaunch : newList)
                {
                    Account currentAccount = staticAccountsMap.get(currentLaunch.Account__c);
                    WebID__c currentWebID = staticWebIDsMap.get(currentLaunch.WebID__c);
                    object webIDAccountAdvocate;
                    object launchAccountAdvocate = currentLaunch.Account_Advocate__c;
                    
                    if(currentAccount != null)
                    {
                        currentLaunch.DSM_Email__c = currentAccount.Designated_DSM__r.Email; 
                        currentLaunch.CAM_Email__c = currentAccount.Digital_Services_CAM__r.Email;
                    }
                    
                    if(currentWebID != null)
                    {
                        currentLaunch.Advocate_Email__c = currentWebID.Account_Advocate__r.Email; 
                        currentLaunch.EMS_Email__c = currentWebID.OwnerMktg_Specialist_lookup__r.Email; 
                        currentLaunch.OMS_Email__c = currentWebID.Online_Marketing_Specialist__r.Email; 
                        currentLaunch.RMS_Email__c = currentWebID.Reputation_Management_Specialist__r.Email; 
                        currentLaunch.SEO_Email__c = currentWebID.SEO_Specialist__r.Email; 
                        currentLaunch.SMS_Email__c = currentWebID.Social_Media_Specialist__r.Email;
                        webIDAccountAdvocate = currentWebID.Account_Advocate__c;
                    }
                    
                    boolean statusClosedFirstTime = false;
                    
                    if(Trigger.isInsert && currentLaunch.Status__c != null && 
                       currentLaunch.Status__c.containsIgnoreCase('Closed'))
                    {
                        statusClosedFirstTime = true;
                    }
                    else if(Trigger.isUpdate && currentLaunch.Status__c != null && 
                            currentLaunch.Status__c.containsIgnoreCase('Closed'))
                    {
                        set<string> statusClosedSet = new set<string>();
                        list<Launch__History> launchHistories = launchMap.get(currentLaunch.ID).Histories;
                        if(!launchHistories.isEmpty())
                        {
                            for(Launch__History his: launchHistories)
                            {
                                statusClosedSet.add((string)his.newValue);
                                statusClosedSet.add((string)his.oldValue);
                            }
                            
                            if(!statusClosedSet.contains('Closed'))
                            {
                                statusClosedFirstTime = true;
                            }
                        }
                    }
                    
                    boolean conditionsMetForChangingAA = 
                        (currentLaunch.RecordTypeID == A_La_Carte_RecordType || currentLaunch.RecordTypeID == website_Launch) && 
                        ((currentLaunch.Product_Type__c != null && currentLaunch.Product_Type__c.containsIgnoreCase('ProCare')) || 
                         (currentLaunch.Add_Ons__c != null && currentLaunch.Add_Ons__c.containsIgnoreCase('ProCare'))) && 
                        currentWebID != null && launchAccountAdvocate != null && webIDAccountAdvocate == null;
                    
                    boolean conditionsMetForNullingSEOspecialist = (currentLaunch.RecordTypeID == A_La_Carte_RecordType || currentLaunch.RecordTypeID == website_Launch) &&
                        currentLaunch.Product_Type__c != null && (currentLaunch.Product_Type__c.containsIgnoreCase('Power SEO') || 
                                                                  currentLaunch.Product_Type__c.containsIgnoreCase('PowerSEO non-CDK') || 
                                                                  currentLaunch.Product_Type__c.containsIgnoreCase('ProCare') ||
                                                                  currentLaunch.Product_Type__c.containsIgnoreCase('SEO Essentials') ||
                                                                  currentLaunch.Product_Type__c.containsIgnoreCase('Performance') ||
                                                                  currentLaunch.Product_Type__c.containsIgnoreCase('PowerSEO non-CDK') ||
                                                                  currentLaunch.Product_Type__c.containsIgnoreCase('Audience Management Package') ||
                                                                  currentLaunch.Product_Type__c.containsIgnoreCase('VW Core') ||
                                                                  currentLaunch.Product_Type__c.containsIgnoreCase('VW Care'));
                        
                    
                    if(statusClosedFirstTime)
                    {
                        if(conditionsMetForChangingAA)
                        {
                            currentWebID.put('Account_Advocate__c', launchAccountAdvocate);
                            webIDsListUpdate.add(currentWebID);
                        }
                        
                        if(conditionsMetForNullingSEOspecialist)
                        {
                            currentLaunch.SEO_Specialist__c = null;
                        }
                    }
                    
                    if(currentWebID != null &&
                       ((currentLaunch.Product_Type__c != null && 
                         (
                             currentLaunch.Product_Type__c.containsIgnoreCase('Power SEO') || 
                             currentLaunch.Product_Type__c.containsIgnoreCase('PowerSEO non-CDK') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('SEO Essentials') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('ProCare') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('Audience Management Package') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('Audience Optimization') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('Base') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('Core/ProSite') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('Performance') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('PowerSEO non-CDK') ||
                             currentLaunch.Product_Type__c.containsIgnoreCase('VW Core')
                         )
                        ) ||
                        (currentLaunch.Add_Ons__c != null && 
                         (
                             currentLaunch.Add_Ons__c.containsIgnoreCase('Audience Optimization') ||
                             currentLaunch.Add_Ons__c.containsIgnoreCase('Power SEO') ||
                             currentLaunch.Add_Ons__c.containsIgnoreCase('ProCare') ||
                             currentLaunch.Add_Ons__c.containsIgnoreCase('SEO Essentials') ||
                             currentLaunch.Add_Ons__c.containsIgnoreCase('VW Care')
                         )
                        )) &&
                       currentLaunch.Status__c != null && 
                       currentLaunch.Status__c.containsIgnoreCase('Closed') &&
                       !currentLaunch.Send_SEO_Onboarding__c
                      )
                    {
                        currentWebID.put('SEO_Specialist__c', null);
                        webIDsListUpdate.add(currentWebID);
                    }
                }
            }
            
            if(!webIDsListUpdate.isEmpty())
            {
                ALL_UtilitiesData.SerializesObjectList(webIDsListUpdate, 'Update');
            }
        }
        Catch(Exception exp)
        {
            All_UtilitiesMiscellaneous.logException(exp);
        }
    }
}