SF Primes/src/objects/ALL_JSTree_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Condition_Field__c</fullName>
        <label>Condition Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_Field_Name__c</fullName>
        <label>Description Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Order_Set__c</fullName>
        <label>Field Order Set</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <label>Parent Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ALL JSTree Fields</label>
</CustomObject>

SF Primes/src/objects/ALL_JSTree_Relationship__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Child_Create_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Child Create Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Child_Description__c</fullName>
        <label>Child Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_DisableCheckField__c</fullName>
        <description>Name of the checkbox field on the child object driving functionality to perform a &apos;Read Only&apos; override of specified fields if the checkbox value is set to true.</description>
        <label>Child DisableCheckField</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_FieldOrderSet__c</fullName>
        <label>Child FieldOrderSet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Fieldset__c</fullName>
        <label>Child Fieldset</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_FieldstoDisableForRow__c</fullName>
        <description>Fields to disable on the child level of the parent/child controller, based upon the check field on the (child) object having its value set to true.</description>
        <label>Child FieldstoDisableForRow</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Object__c</fullName>
        <label>Child Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Relationship__c</fullName>
        <description>Field Name of the Relationship</description>
        <label>Child Relationship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Sort_Parent_Record__c</fullName>
        <label>Field To Sort Parent Record</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GrandParent_Relationship_Field__c</fullName>
        <label>GrandParent Relationship Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grandparent_Display_Field__c</fullName>
        <description>This field will contain the value of the Grandparent field API Name to be displayed as a picklist for selection by the User.</description>
        <label>Grandparent Display Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Create_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Parent Create Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Description__c</fullName>
        <label>Parent Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_DisableCheckField__c</fullName>
        <description>Name of the checkbox field on the parent object driving functionality to perform a &apos;Read Only&apos; override of specified fields if the checkbox value is set to true.</description>
        <label>Parent DisableCheckField</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_FieldOrderSet__c</fullName>
        <label>Parent FieldOrderSet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Fieldset__c</fullName>
        <label>Parent Fieldset</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_FieldstoDisableForRow__c</fullName>
        <description>Fields to disable on the parent level of the parent/child controller, based upon the check field on the (parent) object having its value set to true.</description>
        <label>Parent FieldstoDisableForRow</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <label>Parent Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Relationship_Field_Name__c</fullName>
        <label>Parent Relationship Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Requires_Children__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Parent Requires Children</label>
        <type>Checkbox</type>
    </fields>
    <label>ALL JSTree Relationship</label>
</CustomObject>

SF Primes/src/objects/CustomSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Centralized list of parameters to be modified when refreshing Training or FullDev sandboxes</description>
    <fields>
        <fullName>Max_Milestone_Tree_Threshold__c</fullName>
        <description>This field specifically enables a configurable maximum number of milestone-level tree-node selections within the All_JSTreeBasedNavigator in support of the CDK Expressway Milestone Edit page.</description>
        <label>Max Milestone Tree Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CustomSettings</label>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Activity__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for an Activity associated with a Milestone.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Activity Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Project_Milestone__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Project_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RMS_Owned_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the record originated (i.e. was originally created) from RMS.  If true, then the record can only allow certain fields to be updated from RMS.</description>
        <label>RMS Owned Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubProject_ID__c</fullName>
        <formula>Milestone__r.SubProject__r.Id</formula>
        <label>SubProject ID</label>
        <type>Text</type>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>AI-{000000000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Milestone__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for a Milestone associated with a SubProject.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Milestone Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RMS_Owned_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the record originated (i.e. was originally created) from RMS.  If true, then the record can only allow certain fields to be updated from RMS.</description>
        <label>RMS Owned Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <displayFormat>MID-{000000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Task Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Activity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project Activity</label>
        <referenceTo>Project_Activity__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMS_Owned_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the record originated (i.e. was originally created) from RMS.  If true, then the record can only allow certain fields to be updated from RMS.</description>
        <label>RMS Owned Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubProject_ID__c</fullName>
        <formula>Project_Activity__r.Milestone__r.SubProject__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubProject ID</label>
        <type>Text</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <displayFormat>TI-{000000000}</displayFormat>
        <label>Project Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/ALL_JSTreeBasedNavigator_Controller_Test.cls
/*------------------------------------------------------------
Author: Rey Austral
Company: Cloud Sherpas
Description: Test Class for ALL_JSTreeBasedNavigator_Controller
History
07/06/15     Rey Austral      Created
12/06/16     Venkata Shrivol  commented the project object reference RQ-08305
12/12/16     Venkata shrivol  commented the class as it is no longer required
------------------------------------------------------------*/
@isTest
public class ALL_JSTreeBasedNavigator_Controller_Test 
{
   /* private static final String GENERIC_MILESTONE_DESCRIPTION = 'TEST MILESTONE DESCRIPTION';    
    //private static final Project__c project { get; set; }
    private static final SubProject__c subProject { get; set; }
    
    static 
    {
        /*project = IMP_TestFactory_Helper.buildProject(0);
        insert project;
        
        subProject = IMP_TestFactory_Helper.buildSubProject();
        insert subProject;
        
    }
    
    static testMethod void constructorWithRecords_Test() 
    {
        // --------------------------------------------------------------------
        // INITIALIZATION
        
        createCustomSettings();
        Project_Milestone__c milestone = IMP_TestFactory_Helper.buildMilestoneNonStandard(subProject.Id, GENERIC_MILESTONE_DESCRIPTION);
        insert milestone;
        
        Project_Activity__c activity = IMP_TestFactory_Helper.buildProjectActivity(milestone.Id);
        insert activity;
        
        Project_Task__c task = IMP_TestFactory_Helper.buildProjectTask(activity.Id);
        //task.Terminal_Task__c = true;
        insert task;
        
        CustomSettings__c cust = IMP_TestFactory_Helper.buildCustomSettings();
        insert cust;
        // --------------------------------------------------------------------
        // TESTING PROPER
        
        PageReference pRef=Page.ALL_RecordsView;
        Test.setCurrentPage(pRef);
        
        Test.StartTest();
        ApexPages.CurrentPage().getParameters().put('id', subProject.Id);
        ApexPages.CurrentPage().getHeaders().put('User-Agent', 'MSIE');
        
        ALL_RecordsView_Controller controller = new ALL_RecordsView_Controller();    
       
        ALL_JSTreeBasedNavigator_Controller treeController = new ALL_JSTreeBasedNavigator_Controller();
        treeController.pageController = controller.getThis();
        treeController.key = 'treeComponent';
        
        treeController.triggerRefresh = true;
        Test.StopTest();
        //check if the variable generatedJSON in the ALL_JSTreeBasedNavigator_Controller has value
        system.assert(treeController.generatedJSON.contains(milestone.Description__c));
        //check of the maxSelectedRecord has the same value if the custom settings
        system.assertEquals(treeController.maxSelectedRecord, cust.Max_Milestone_Tree_Threshold__c);
    }
    
    static testMethod void selectTreeRecords_Test() 
    {
        // --------------------------------------------------------------------
        // INITIALIZATION
        
        createCustomSettings();
        Project_Milestone__c milestone = IMP_TestFactory_Helper.buildMilestoneNonStandard(subProject.Id, GENERIC_MILESTONE_DESCRIPTION);
        insert milestone;
        
        Project_Activity__c activity = IMP_TestFactory_Helper.buildProjectActivity(milestone.Id);
        insert activity;
        
        Project_Task__c task = IMP_TestFactory_Helper.buildProjectTask(activity.Id);     
        insert task;        
     
        Project_Milestone__c milestone2 = IMP_TestFactory_Helper.buildMilestoneNonStandard(subProject.Id, GENERIC_MILESTONE_DESCRIPTION);
        milestone2.Description__c = milestone2.Description__c + '123456789012345678901234567890';
        insert milestone2;
        
        Project_Activity__c activity2 = IMP_TestFactory_Helper.buildProjectActivity(milestone.Id);
        insert activity2;
        
        Project_Task__c task2 = IMP_TestFactory_Helper.buildProjectTask(activity.Id);        
        insert task2;
        
        IMP_TestFactory_Helper.buildCustomSettings();
        // --------------------------------------------------------------------
        // TESTING PROPER
        
        PageReference pRef=Page.ALL_RecordsView;
        Test.setCurrentPage(pRef);
        
        Test.StartTest();
        ApexPages.CurrentPage().getParameters().put('id', subProject.Id);
        ApexPages.CurrentPage().getHeaders().put('User-Agent', 'MSIE');
        
        ALL_RecordsView_Controller controller = new ALL_RecordsView_Controller();    
       
        ALL_JSTreeBasedNavigator_Controller treeController = new ALL_JSTreeBasedNavigator_Controller();
        treeController.pageController = controller.getThis();
        treeController.key = 'treeComponent';
        
        treeController.triggerRefresh = true;
        
        treeController.openedIds = milestone.id;
        treeController.parentObjectName = 'Project_Milestone__c';
        treeController.childObjectName = 'Project_Activity__c';
        treeController.checkedParentIds= milestone.id;
        treeController.checkedChildIds = activity.id;
        treeController.somethingSelected();
        
        treeController.triggerRefresh = true;
        Test.StopTest();
        //check if the varibale attributesCollection in ALL_RecordsView_Controller contains a value
        system.assertEquals('Project_Milestone__c', controller.attributesCollection.parentAPIName);
    }
    
    private static void createCustomSettings()
    {
        ALL_JSTree_Relationship__c rel = new ALL_JSTree_Relationship__c();
        rel.Name = 'MilestoneEdit_1';
        rel.Parent_Object__c = 'Project_Milestone__c';
        rel.Child_Relationship__c = 'Project_Activities__r';
        rel.Order__c = 1;
        rel.Key__c = 'Milestone';
        rel.Child_Object__c = 'Project_Activity__c';
        rel.Parent_Description__c = 'Milestones';
        rel.Child_Description__c = 'Activities';
        rel.Parent_Fieldset__c = 'Milestone_Edit_Common';
        rel.Child_Fieldset__c = 'Activity_Edit_Common';
        rel.Field_To_Sort_Parent_Record__c = 'Description__c';
        rel.Parent_Relationship_Field_Name__c = 'Milestone__c';
        rel.Parent_Requires_Children__c = true;
        //rel.Child_Requires_Children__c = true;
        rel.Parent_FieldOrderSet__c = 'Milestone_Sort_Commons';
        rel.Child_FieldOrderSet__c = 'Activity_Sort_Commons';
        rel.Parent_FieldstoDisableForRow__c = 'RMS_Owner_Disable_Fields_Set';
        rel.Child_FieldstoDisableForRow__c = 'RMS_Owner_Disable_Fields_Set';
        rel.Parent_DisableCheckField__c='RMS_Owned_Flag__c';
        rel.Child_DisableCheckField__c='RMS_Owned_Flag__c';
        insert rel;
        
        ALL_JSTree_Relationship__c rel2 = new ALL_JSTree_Relationship__c();
        rel2.Name = 'MilestoneEdit_2';
        rel2.Parent_Object__c = 'Project_Activity__c';
        rel2.Child_Relationship__c = 'Project_Tasks__r';
        rel2.Order__c = 2;
        rel2.Key__c = 'Milestone';
        rel2.Child_Object__c = 'Project_Task__c';
        rel2.Parent_Description__c = 'Activities';
        rel2.Child_Description__c = 'Tasks';
        rel2.Parent_Fieldset__c = 'Activity_Edit_Common';
        rel2.Child_Fieldset__c = 'Task_Edit_Commons';
        rel2.Field_To_Sort_Parent_Record__c = 'Description__c';
        rel2.Parent_Relationship_Field_Name__c = 'Project_Activity__c';
        rel2.Parent_Requires_Children__c = true;
        rel2.Parent_Create_Enabled__c = true;
        rel2.Child_Create_Enabled__c = true;
        rel2.GrandParent_Relationship_Field__c = 'Milestone__c';
        rel2.Parent_FieldOrderSet__c = 'Activity_Sort_Commons';
        rel2.Child_FieldOrderSet__c = 'Task_Sort_Commons';
        rel2.Grandparent_Display_Field__c = 'Description__c';
        rel2.Parent_FieldstoDisableForRow__c = 'RMS_Owner_Disable_Fields_Set';
        rel2.Child_FieldstoDisableForRow__c = 'RMS_Owner_Disable_Fields_Set';
        rel2.Parent_DisableCheckField__c='RMS_Owned_Flag__c';
        rel2.Child_DisableCheckField__c='RMS_Owned_Flag__c';
        insert rel2;
        
        ALL_JSTree_Fields__c field = new ALL_JSTree_Fields__c();
        field.Name = 'MilestoneEdit_1';
        field.Key__c = 'Milestone';
        field.Condition_Field__c = 'SubProject__c';
        field.Object_Name__c = 'Project_Milestone__c';
        field.Description_Field_Name__c = 'Description__c';
        field.Field_Order_Set__c = 'Milestone_Sort_Commons';
        
        insert field;
        
        ALL_JSTree_Fields__c field2 = new ALL_JSTree_Fields__c();
        field2.Name = 'MilestoneEdit_2';
        field2.Key__c = 'Milestone';
        field2.Condition_Field__c = 'SubProject_ID__c';
        field2.Object_Name__c = 'Project_Activity__c';
        field2.Description_Field_Name__c = 'Description__c';
        field2.Field_Order_Set__c = 'Activity_Sort_Commons';
        field2.Parent_Field_Name__c = 'Milestone__c';
        insert field2;
    }*/
}