SF Primes/src/objects/ALL_Field_Value_Assignment_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Conditions_Identifier__c</fullName>
        <label>Query Conditions Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Field_s__c</fullName>
        <label>Query Field(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_sObject__c</fullName>
        <label>Query sObject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiving_Field_Name__c</fullName>
        <label>Receiving Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiving_sObject__c</fullName>
        <label>Receiving sObject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ALL Field Value Assignment Settings</label>
</CustomObject>

SF Primes/src/objects/ALL_Query_Conditions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Describe_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Describe Call?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject__c</fullName>
        <label>sObject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ALL Query Conditions</label>
</CustomObject>

fulldev2/src/classes/DynamicSOQL_Test.cls
@isTest
public class DynamicSOQL_Test 
{
    @testSetUp static void setUpData()
    {  
        list<sObject> settingsObjects = new list<sObject>{
            new ALL_Query_Conditions__c(Name='002', sObject__c='Case', Key__c='Name', Operator__c='=', Value__c='Onboarding - OMS', 
                                            Class_Name__c='DynamicSOQL_Helper', Method_Name__c='getRecordTypeId()', Describe_Call__c=true, Identifier__c='002'),
            new ALL_Query_Conditions__c(Name='003', sObject__c='User', Key__c='	UserName', Operator__c='=', 
                                            Class_Name__c='DynamicSOQL_Helper', Method_Name__c='getAdminUser()', Identifier__c='003'),
            new ALL_Field_Value_Assignment_Settings__c(Name='002', 	Receiving_sObject__c='Case', Receiving_Field_Name__c='RecordTypeId', Query_Conditions_Identifier__c='002', 
                                                           Identifier__c='002'), 
            new ALL_Field_Value_Assignment_Settings__c(Name='003', 	Receiving_sObject__c='Case', Receiving_Field_Name__c='Requested_By__c', Query_Field_s__c='ID', 
                                                           Query_sObject__c='User', Query_Conditions_Identifier__c='003',Identifier__c='003')
       };           
       insert settingsObjects;
    }
    
    static testMethod void testForRouteToSpecificMethod()
    {
        ALL_Query_Conditions__c aqc_1 = ALL_Query_Conditions__c.getInstance('002');
        ALL_Query_Conditions__c aqc_2 = ALL_Query_Conditions__c.getInstance('003');
        
        ALL_Field_Value_Assignment_Settings__c afv_1 = ALL_Field_Value_Assignment_Settings__c.getInstance('002');
        ALL_Field_Value_Assignment_Settings__c afv_2 = ALL_Field_Value_Assignment_Settings__c.getInstance('003');
        
        DynamicSOQL_Helper.routeToSpecificMethod(aqc_1, afv_1);
        DynamicSOQL_Helper.routeToSpecificMethod(aqc_2, afv_2);
    }
    
    static testMethod void testForSmallMethods()
    {
        DynamicSOQL_Helper.getAdminUser();
        DynamicSOQL_Helper.getRecordTypeID('Case', 'Onboarding - OMS');
        DynamicSOQL_Helper.QueryValueMethod('DynamicSOQL_Helper', 'CurrentUserId()');
    }
    static testMethod void testForQueryConstructor()
    {
        DynamicSOQL_Helper.QueryConstructorCondition queryParameters = new DynamicSOQL_Helper.QueryConstructorCondition();
        queryParameters.order = 1;
        queryParameters.key = 'OwnerID';
        queryParameters.operator = '=';
        queryParameters.value = 'Dynamic';
        queryParameters.className = 'DynamicSOQL_Helper';
        queryParameters.methodName = 'CurrentUserId()';
        
        DynamicSOQL_Helper.QueryConditionsPacketClass conditionsPacket = new DynamicSOQL_Helper.QueryConditionsPacketClass();
        conditionsPacket.ConditionsList = new list<DynamicSOQL_Helper.QueryConstructorCondition>{ queryParameters };
        conditionsPacket.QueryConditionExpression = '1';
        
        DynamicSOQL_Helper.QueryConstructor(conditionsPacket);
        
    }
}