SF Primes/src/objects/Answer__c.object
<CustomObject>
    <description>Captures the response for a Discovery Question to the respective Workbook and associated with a Project.</description>
    <fields>
        <fullName>Discovery_Site_Workbook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Discovery Site Workbook</label>
        <referenceTo>Site_Workbook__c</referenceTo>
        <relationshipLabel>Discovery Answers</relationshipLabel>
        <relationshipName>Discovery_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Category__c</fullName>
        <formula>&apos;Removed&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Discovery Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Answer</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Discovery_Answer_Workbook_Category__c.object
<CustomObject>
    <description>Junction object between Discovery Answer and Discovery Site Workbook category</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Discovery Answer Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Answer_Workbook_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discovery_Workbook_Category__c</fullName>
        <label>Discovery Workbook Category</label>
        <referenceTo>Discovery_Workbook_Category__c</referenceTo>
        <relationshipLabel>Discovery Answer Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Answer_Workbook_Categories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discovery Answer Workbook Category</label>
    <nameField>
        <displayFormat>DAWC-{0000000}</displayFormat>
        <label>Discovery Answer Workbook Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Answer Workbook Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Discovery_Question_Product__c.object
<CustomObject>
    <description>Junction object to associate a Discovery Question with their relevant Product.</description>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Discovery Question Products</relationshipLabel>
        <relationshipName>Discovery_Question_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Discovery Question Products</relationshipLabel>
        <relationshipName>Discovery_Question_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <formula>Product__r.Solution__r.Name</formula>
        <label>Solution</label>
        <type>Text</type>
    </fields>
    <label>Discovery Question Product</label>
    <nameField>
        <displayFormat>PQ-{00000000}</displayFormat>
        <label>ProdQuest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Question Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Discovery_Workbook_Category__c.object
<CustomObject>
    <description>Contains the Workbook capturing questions, responses, interviewees, interviewers; and associated with a Project and Site.</description>
    <fields>
        <fullName>Count_of_Questions__c</fullName>
        <label>Count of Questions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Category__c</fullName>
        <label>Question Category</label>
        <referenceTo>Question_Category__c</referenceTo>
        <relationshipName>Discovery_Workbook_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site_Workbook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Workbook</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Site_Workbook__c</referenceTo>
        <relationshipLabel>Discovery Site Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Workbook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Discovery Site Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Site_Workbook_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Site Workbook Category</label>
    <nameField>
        <displayFormat>DW-{00000}</displayFormat>
        <label>Discovery Workbook Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbook Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Product__c.object
<CustomObject>
    <description>Contains the Products under each Solution.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Solution is not active.</errorMessage>
            <filterItems>
                <field>Solution__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Question__c.object
<CustomObject>
    <description>Contains the Questions used during Discovery with association to Dealership Need and Product.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Discovery Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Question_Category__c.object
<CustomObject>
    <description>Contains the categorization of Dealership Needs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field determines whether the Dealership Need is Active or not. Making it false logically logically deletes this record</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealership Need</label>
    <nameField>
        <label>Dealership Need Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealership Needs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Site_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProjectSite__c</fullName>
        <label>SubProjectSite</label>
        <referenceTo>SubProjectSite__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Product</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>ProdSite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Site_Workbook__c.object
<CustomObject>
    <description>Junction object to allow associating a Workbook with a Project and Site.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Discovery Site Workbooks</relationshipLabel>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Discovery Site Workbooks</relationshipLabel>
        <relationshipName>Discovery_Site_Workbooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discovery Site Workbook</label>
    <nameField>
        <displayFormat>SW-{00000000}</displayFormat>
        <label>Site Workbook ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Solution__c.object
<CustomObject>
    <description>Contains the categorization of Solutions under each Dealership Need.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Category__c</fullName>
        <label>Dealership Need</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Dealership Need is not active.</errorMessage>
            <filterItems>
                <field>Question_Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Question_Category__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProjectSite__c.object
<CustomObject>
    <description>Junction object to allow associating multiple Sites (Accounts) with a SubProject.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SubProject Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProjectSite</label>
    <nameField>
        <displayFormat>SPS-{000000000}</displayFormat>
        <label>SubProjectSite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjectSites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/classes/IMP_DeleteAnsOnSiteProdsDelete_Handler.cls
/*
*
* 05/18/2015    Venkata Shrivol - Created
* Description - Handler Class for IMP_SiteProds Trigger for deleting answer records on Discovery
*				site workbook category if any Products are deleted.
*-----HISTORY--------
* 06/08/15  Venkata Shrivol  Added Code for deleting SiteWkbks when its child siteWkbkCategories 
*							 are deleted. 
*
*/

public with sharing class IMP_DeleteAnsOnSiteProdsDelete_Handler 
{
	public static void deleteAnswers(Set<Id> siteProdIds)
	{
		//list<Site_Workbook__c> existingWorkbooks = [select Id from Site_Workbook__c where Project__c IN (select SubProject__r.Project__c from Site_Product__c where Id IN: siteProdIds)];
		set<Id> subProjectIds = new set<Id>();
		set<Id> questionIds = new set<Id>();
		set<Id> productIds = new set<Id>();
		set<Id> siteWorkbookIds = new set<Id>();
		set<Id> workbookCategoryIds = new set<Id>();
		set<Id> questionCategoryIds = new set<Id>();
		set<Id> accountIds = new set<Id>();
		set<Id> subProjectSiteIds = new set<Id>();
		set<Id> commonQuestionIds = new set<Id>(); 
		
		//list<sObject> recordsToDelete;
		list<Site_Workbook__c> existingWorkbooks;
		list<Discovery_Workbook_Category__c> existingWorkbookCategories;
		list<Answer__c> answersToDelete = new list<Answer__c>();
		list<Discovery_Answer_Workbook_Category__c> ansWkbkCategoriesToDelete = new list<Discovery_Answer_Workbook_Category__c>();
		list<Discovery_Workbook_Category__c> zeroAnswerWorkbookCategoryList = new list<Discovery_Workbook_Category__c>();
		list<Site_Workbook__c> emptySiteWkbksToDelete = new list<Site_Workbook__c>();
		list<Discovery_Workbook_Category__c> categoriesToUpdate = new list<Discovery_Workbook_Category__c>();
		
		map<Id,list<Answer__c>> categoryToAnswerMap = new map<Id, list<Answer__c>>();
		map<Id,list<Discovery_Answer_Workbook_Category__c>> siteWkbkCategoryToAnsWkbkCatMap = new map<Id, list<Discovery_Answer_Workbook_Category__c>>();
		
		list<Site_Product__c> deletingSiteProds = [select SubProject__c, Product__c, SubProjectSite__r.Account__c, SubProjectSite__c  from Site_Product__c where Id IN: siteProdIds];
		for(Site_Product__c sp:deletingSiteProds)
		{
			subProjectIds.add(sp.SubProject__c);
			accountIds.add(sp.SubProjectSite__r.Account__c);
			subProjectSiteIds.add(sp.SubProjectSite__c);
			productIds.add(sp.Product__c);
		}
		
		for(Discovery_Question_Product__c dqp:[select Question__c, Product__r.Solution__r.Question_Category__c 
											  from Discovery_Question_Product__c 
											  where Question__r.Active__c = true and Product__c IN:productIds])
		{
			questionIds.add(dqp.Question__c);
			questionCategoryIds.add(dqp.Product__r.Solution__r.Question_Category__c);
			
		}
		
		existingWorkbooks = [select Id from Site_Workbook__c where SubProject__c IN:subProjectIds and Site__c IN:accountIds];
		
		if(!existingWorkbooks.isEmpty())
		{
			for(Site_Workbook__c sw:existingWorkbooks)
			{
				siteWorkbookIds.add(sw.Id);
			}
			//questionIds = IMP_Project_Utility.getQuestionIds(siteProdIds);
			
			if(!subProjectIds.isEmpty())
			{
				existingWorkbookCategories = [
											  select Id, Count_of_Questions__c 
											  from Discovery_Workbook_Category__c 
											  where Site_Workbook__c IN :siteWorkbookIds
											 ];
			}
			if(existingWorkbookCategories!=null && !existingWorkbookCategories.isEmpty())
			{
				list<Answer__c> existingAnswers = [select Id, 
												   (select Id, Discovery_Workbook_Category__c from Discovery_Answer_Workbook_Categories__r 
												   where Discovery_Workbook_Category__c IN:existingWorkbookCategories and 
												   Discovery_Workbook_Category__r.Question_Category__c IN:questionCategoryIds
												   ) 
												   from Answer__c 
												   where Discovery_Site_Workbook__c IN:siteWorkbookIds and 
												   Question__c IN:questionIds];
				
				for(Answer__c ans:existingAnswers)
				{
					ansWkbkCategoriesToDelete.addAll(ans.Discovery_Answer_Workbook_Categories__r);
					//system.debug('-------ansWkbkCategoriesToDelete----'+ansWkbkCategoriesToDelete);
					for(Discovery_Answer_Workbook_Category__c dawkc:ans.Discovery_Answer_Workbook_Categories__r)
					{
						 
						list<Discovery_Answer_Workbook_Category__c> tempList  = siteWkbkCategoryToAnsWkbkCatMap.containsKey(dawkc.Discovery_Workbook_Category__c) ? 
																				siteWkbkCategoryToAnsWkbkCatMap.get(dawkc.Discovery_Workbook_Category__c) : 
																				new list<Discovery_Answer_Workbook_Category__c>();
                    	tempList.add(dawkc);
                    	siteWkbkCategoryToAnsWkbkCatMap.put(dawkc.Discovery_Workbook_Category__c, tempList);
					}	 
				}	  
				if(!ansWkbkCategoriesToDelete.isEmpty())
				{	
					for(Discovery_Workbook_Category__c dwc:existingWorkbookCategories)
					{
						if(siteWkbkCategoryToAnsWkbkCatMap.keySet().contains(dwc.Id))
						{
							if(dwc.Count_of_Questions__c >= siteWkbkCategoryToAnsWkbkCatMap.get(dwc.Id).size())
							{
								dwc.Count_of_Questions__c = dwc.Count_of_Questions__c - siteWkbkCategoryToAnsWkbkCatMap.get(dwc.Id).size();
								//system.debug('-------dwc.Count_of_Questions__c After Update--------'+dwc.Count_of_Questions__c);
								if(dwc.Count_of_Questions__c == 0)
								{
									zeroAnswerWorkbookCategoryList.add(dwc);
								}
								else 
								{
									categoriesToUpdate.add(dwc);
								}
							}
						}
					}
					//recordsToDelete.addAll(existingAnswers);
					try
					{
						delete ansWkbkCategoriesToDelete;
						if(!categoriesToUpdate.isEmpty())
						{
							update categoriesToUpdate;
						}
						
						//system.debug('-----zeroAnswerWorkbookCategoryList size before Delete------'+zeroAnswerWorkbookCategoryList.size());
						
						if(!zeroAnswerWorkbookCategoryList.isEmpty())
						{
							delete zeroAnswerWorkbookCategoryList;
						}
						for(Answer__c ans:[select Id, 
										   (select Id from Discovery_Answer_Workbook_Categories__r
										   ) 
										   from Answer__c 
										   where Discovery_Site_Workbook__c IN:siteWorkbookIds and 
										   Question__c IN:questionIds])
						{
							if(ans.Discovery_Answer_Workbook_Categories__r.isEmpty())
							{
								answersToDelete.add(ans);
							}
						}
						if(!answersToDelete.isEmpty())
						{
							delete answersToDelete;
						}
						
						list<Site_Workbook__c> updatedWorkbooks = [
						select Id,
						(select Id from Discovery_Workbook__r) 
						from Site_Workbook__c 
						where SubProject__c IN:subProjectIds and Site__c IN:accountIds];
						
						for(Site_Workbook__c sw:updatedWorkbooks)
						{
							system.debug('---SWKBKS to Delete----'+sw.Discovery_Workbook__r);
							if(sw.Discovery_Workbook__r.isEmpty())
							{
								emptySiteWkbksToDelete.add(sw);
							}
						}
						if(!emptySiteWkbksToDelete.isEmpty())
						{
							delete emptySiteWkbksToDelete;
						}			
					}
					catch(Exception e)
					{
						system.debug('-----Exception Caught------'+e);
					}		
				}
			}
		}
	}
/*
list<Discovery_Question_Product__c> existingDQPList = [select Question__c from Discovery_Question_Product__c where Question__r.Active__c = true and Product__c IN
															  (select Product__c from Site_Product__c where Id NOT IN:siteProdIds and SubProjectSite__c IN:subProjectSiteIds)];
		
		
		
		for(Discovery_Question_Product__c dqp:existingDQPList)
		{
			commonQuestionIds.add(dqp.Question__c);
		}
		
		list<Discovery_Question_Product__c> dqpList = [select Question__c 
                                                       from Discovery_Question_Product__c 
                                                       where Question__r.Active__c = true and Product__c IN 
                                                       (select Product__c from Site_Product__c where Id IN:siteProdIds)
                                                       and Question__c NOT IN:commonQuestionIds
                                                       ];
	        if(!dqpList.isEmpty())
	        {
	           for(Discovery_Question_Product__c dqp:dqpList)
	            {
	                questionIds.add(dqp.Question__c);
	            } 
	        }
			
			system.debug('---questionIds----'+questionIds.size());
		
*/
}