SF Primes/src/objects/Answer__c.object
<CustomObject>
    <description>Captures the response for a Discovery Question to the respective Workbook and associated with a Project.</description>
    <fields>
        <fullName>Any_Answer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Any Answer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Checkbox_Answer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checkbox Answer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cloneable__c</fullName>
        <formula>Question__r.Cloneable__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cloneable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Currency_Answer__c</fullName>
        <label>Currency Answer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Answer__c</fullName>
        <label>Date Answer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MultiSelect_Picklist_Answer__c</fullName>
        <label>MultiSelect Picklist Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_Answer__c</fullName>
        <label>Number Answer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picklist_Answer__c</fullName>
        <label>Picklist Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Category__c</fullName>
        <formula>&apos;Removed&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Discovery Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text_Answer__c</fullName>
        <label>Text Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>URL_Answer__c</fullName>
        <label>URL Answer</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>YesNo_Answer__c</fullName>
        <label>Yes/No Answer</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Discovery Answer</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Discovery_Workbook_Category__c.object
<CustomObject>
    <description>Contains the Workbook capturing questions, responses, interviewees, interviewers; and associated with a Project and Site.</description>
    <fields>
        <fullName>Count_of_Questions__c</fullName>
        <label>Count of Questions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Category__c</fullName>
        <label>Question Category</label>
        <referenceTo>Question_Category__c</referenceTo>
        <relationshipName>Discovery_Workbook_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site_Workbook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Workbook</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Site_Workbook__c</referenceTo>
        <relationshipLabel>Discovery Site Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Workbook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Discovery Site Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Site_Workbook_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Site Workbook Category</label>
    <nameField>
        <displayFormat>DW-{00000}</displayFormat>
        <label>Discovery Workbook Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbook Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Question__c.object
<CustomObject>
    <description>Contains the Questions used during Discovery with association to Dealership Need and Product.</description>
    <fields>
        <fullName>Cloneable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cloneable</label>
        <type>Checkbox</type>
    </fields>
    <label>Discovery Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Question_Category__c.object
<CustomObject>
    <description>Contains the categorization of Dealership Needs.</description>
    <label>Dealership Need</label>
    <nameField>
        <label>Dealership Need Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealership Needs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Site_Workbook__c.object
<CustomObject>
    <description>Junction object to allow associating a Workbook with a Project and Site.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Discovery Site Workbooks</relationshipLabel>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Discovery Site Workbooks</relationshipLabel>
        <relationshipName>Discovery_Site_Workbooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discovery Site Workbook</label>
    <nameField>
        <displayFormat>SW-{00000000}</displayFormat>
        <label>Site Workbook ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Docusign/src/classes/IMP_CloneWorkbook_Helper.cls
/*------------------------------------------------------------
Author:Rey Austral
Company: Cloud Sherpas       
Description: Clone Method for Discovery worbook. This is used to create copy of all the workbook of the selected site  including the answer
Test Class: IMP_CloneWorkbook_Test
History
08/28/14    Rey Austral          Created
09/08/14    Michael Lasala       Make checkIfSiteContainsWorkbook method as public
------------------------------------------------------------*/
public class IMP_CloneWorkbook_Helper {
    public String cloneWorkBook(Id projectId, Id accountId, Id sourceSiteWorkbookId)
    {
        String result = '';
        //check target site if the selected workbook is already exist 
        //if the workbook is already exist return an error message that will tell the user that the system is unable to clone a workbook because of this reason
       /* if (!checkIfSiteContainsWorkbook(projectId,accountId))
        {
            processCloningWorkbook(projectId,accountId,sourceSiteWorkbookId);
        }else
        {
            result = 'The Site you have chosen already has a workbook for this project.  Please utilize it to continue your discovery, or if you intended to select a different site, please try selecting again.';
        }*/
        
        return result; 
        
    }
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Used to check if the target site already contains a workbook
    Inputs: projectId, accountId
    Returns: Boolean
    History
    08/28/14      Rey Austral        Created
    09/08/14      Michael Lasala     Make method as public
    ------------------------------------------------------------*/
    public Boolean checkIfSiteContainsWorkbook(Id subProjectId, Id accountId)
    {
        //this method will search in the site_workbook object because this contains the workbook record per site and project                
        Boolean result = false;
        List<Site_Workbook__c> siteWorkbook = [ SELECT Id From Site_Workbook__c where Site__c =:accountId and SubProject__c =: subProjectId  ];
        if (!siteWorkbook.isEmpty())
        {
            result = true;
        }
        
        return result;
    }
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Perform the clonning function
    Inputs: projectId, accountId, sourceSiteWorkbookId
    Returns: None
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
    /*private void processCloningWorkbook(Id projectId, Id accountId, Id sourceSiteWorkbookId)
    {
         //retrieve the source workbook category values, the value will be copy to the target site
        Map<Id, Discovery_Workbook_Category__c> sourceWorkbookCategory = getProjectWorkbookstoClone(sourceSiteWorkbookId);
        if (!sourceWorkbookCategory.isEmpty()) 
        {
            //create a new site for the project
            Site_Workbook__c siteWorkBook = createSiteWorkBookc(projectId, accountId);      
            if (siteWorkBook.id != null)
            {
                //create a new workbook category based on the data of the source but different site
                List<Discovery_Workbook_Category__c> targetWorkbookCategory = cloneWorkbookCategory(sourceWorkbookCategory,siteWorkBook.id);        
                //get all question from the source site, to be used in mapping the old workbook category from the new category
                Map<Id,Question__c> allSourceQuestion = retreiveAllQuestions(sourceSiteWorkbookId);
                //get all cloneable question from the source site, to determine what answer will be copy
                Map<Id,Question__c> sourceCloneableQuestion = retreiveCloneableQuestions(sourceSiteWorkbookId);
                //get all answer from the source 
                List<Answer__c> sourceAnswer = getWorkbookAnswerstoClone(sourceWorkbookCategory);
                
                List<Answer__c> insertCloneableAnswer = new List<Answer__c>();
                List<Answer__c> insertNonCloneableAnswer = new List<Answer__c>();
                List<Answer__c> insertNullAnswer = new List<Answer__c>();
                //iterate all the answer of the source workbook
                for(Answer__c ans : sourceAnswer)
                {
                    //iterate the workbookcategory to map the answer to the category
                    for (Discovery_Workbook_Category__c workbookCategory : targetWorkbookCategory)
                    {
                        //the clone will copy the data of the source answer but need to replace the existing workbook category to the new category
                        //because we are looping the newly created workbook category we need to determine, is the answer belong to that category
                        //by comparing the old category to the new category , see the method for more details
                        if (isAnswerBelongToCategory(ans.Question__c,workbookCategory.Question_Category__c,allSourceQuestion))
                        {
                            //assign the category for each answer   
                            Answer__c newAnswer = new Answer__c();
                            newAnswer.Discovery_Workbook_Category__c = workbookCategory.id;
                            //Seperate the null answer, cloneable, non-cloneable w/ answer
                            if (isAnswerNull(ans) == true)
                            {
                                newAnswer.Question__c = ans.Question__c;                    
                                
                                if (sourceCloneableQuestion.containsKey(ans.Question__c))
                                { 
                                    newAnswer.Any_Answer__c = ans.Any_Answer__c;
                                }
                                insertNullAnswer.add(newAnswer);
                            }
                            else
                            {
                                //check if the source question is cloneable, sourceCloneableQuestion contains all cloneable question
                                //only cloneable answer can be copy to the target site
                                if (sourceCloneableQuestion.containsKey(ans.Question__c))
                                {                           
                                    newAnswer.Date_Answer__c = ans.Date_Answer__c;
                                    newAnswer.YesNo_Answer__c = ans.YesNo_Answer__c;
                                    newAnswer.Text_Answer__c = ans.Text_Answer__c;
                                    newAnswer.Number_Answer__c = ans.Number_Answer__c;                          
                                    newAnswer.Currency_Answer__c = ans.Currency_Answer__c;
                                    newAnswer.Checkbox_Answer__c = ans.Checkbox_Answer__c;
                                    newAnswer.Date_Answer__c = ans.Date_Answer__c;
                                    newAnswer.URL_Answer__c = ans.URL_Answer__c;
                                    newAnswer.MultiSelect_Picklist_Answer__c = ans.MultiSelect_Picklist_Answer__c;
                                    newAnswer.Picklist_Answer__c = ans.Picklist_Answer__c;
                                    newAnswer.Any_Answer__c = ans.Any_Answer__c;
                                    newAnswer.Question__c = ans.Question__c;
                                    insertCloneableAnswer.add(newAnswer);
                                }
                                else
                                {
                                    //do not save the answer of the question is non-cloneable                           
                                    newAnswer.Question__c = ans.Question__c;
                                    insertNonCloneableAnswer.add(newAnswer);
                                }
                            }
                        }
                    }
                }
                
                if (!insertCloneableAnswer.isEmpty())
                {
                    try
                    {
                        insert insertCloneableAnswer;
                    }        
                    catch (DmlException e){
                        ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.Error, e.getMessage()));
                        System.debug('$$$ insertCloneableAnswer DmlException: '+e);
                    }
                }
                
                if (!insertNonCloneableAnswer.isEmpty())
                {
                    try
                    {
                        insert insertNonCloneableAnswer;
                    }         
                    catch (DmlException e){
                        ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.Error, e.getMessage()));
                        System.debug('$$$ insertNonCloneableAnswer DmlException: '+e);
                    }
                }
                
                if (!insertNullAnswer.isEmpty())
                {
                    try
                    {
                        insert insertNullAnswer;
                    }
                    catch (DmlException e){
                        ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.Error, e.getMessage()));
                        System.debug('$$$ insertNullAnswer DmlException: '+e);
                    }
                }
            }else
            {
                ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, 'No Site has been created');
                ApexPages.addMessage(errMsg);
            }
        }else
        {
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, 'No Workbook Category Found');
            ApexPages.addMessage(errMsg);
        }
    }*/
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Create an entry for the target site
    Inputs: projectId, accountId
    Returns: Site_Workbook__c
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
    private Site_Workbook__c createSiteWorkBookc(Id projectId, Id accountId)
    {       
        Site_Workbook__c siteWorkbook = new Site_Workbook__c();
        siteWorkbook.Site__c = accountId;
        siteWorkbook.Project__c = projectId;
        try
        {
            Insert siteWorkbook;
        }        
        catch (DmlException e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.Error, e.getMessage()));
            System.debug('$$$ siteWorkbook DmlException: '+e);
        }
        
        return siteWorkbook;
    }
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Create a new workbook category entry for the target but copy the content from the source
    Inputs: sourceWorkbookCategory, siteId
    Returns: List<Discovery_Workbook_Category__c>
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
    private List<Discovery_Workbook_Category__c> cloneWorkbookCategory(Map<Id, Discovery_Workbook_Category__c> sourceWorkbookCategory,Id siteId)
    {       
        List<Discovery_Workbook_Category__c> newWorkbookCetegory = new List<Discovery_Workbook_Category__c>();
        for (Discovery_Workbook_Category__c sourceCategory : sourceWorkbookCategory.values())
        {
            Discovery_Workbook_Category__c newCategory = new Discovery_Workbook_Category__c();
            newCategory.Site_Workbook__c = siteId;
            newCategory.Question_Category__c = sourceCategory.Question_Category__c;
            newCategory.Count_of_Questions__c = sourceCategory.Count_of_Questions__c;
            newWorkbookCetegory.add(newCategory);
        }
        if (!newWorkbookCetegory.isEmpty())
        {
            try
            {
                insert newWorkbookCetegory;
            }
            catch (DmlException e){
                ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.Error, e.getMessage()));
                System.debug('$$$ newWorkbookCetegory DmlException: '+e);
            }
        }
        
        return newWorkbookCetegory;
    }
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Retrieve all the question category from the source but filter it isdeleted = false
    Inputs: sourceSiteWorkbookId
    Returns:  Map<Id, Discovery_Workbook_Category__c>
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
    private Map<Id, Discovery_Workbook_Category__c> getProjectWorkbookstoClone(Id sourceSiteWorkbookId)
    {       
        List<Discovery_Workbook_Category__c> lstCategory =  [ SELECT IsDeleted, Deleted__c, Name, LastModifiedById,  
                                                             Question_Category__c, Count_of_Questions__c, Id, Site_Workbook__c
                                                             FROM Discovery_Workbook_Category__c where  Site_Workbook__c = : sourceSiteWorkbookId and IsDeleted = false];
        //add to map for easy manipulation or comparing of data         
        Map<Id, Discovery_Workbook_Category__c> mapCategory = new Map<Id, Discovery_Workbook_Category__c>();
        if (!lstCategory.isEmpty())
        {
            for (Discovery_Workbook_Category__c category: lstCategory )
            {
                mapCategory.put(category.id,category);
            }
        }
        
        return mapCategory;
    }
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Get all the answer from the source
    Inputs: sourceWorkbookCategory
    Returns: List<Answer__c>
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
   /* private List<Answer__c> getWorkbookAnswerstoClone(Map<id,Discovery_Workbook_Category__c> sourceWorkbookCategory)
    {
        return [Select YesNo_Answer__c, Text_Answer__c,  Question__c, Number_Answer__c, Discovery_Workbook_Category__c , Date_Answer__c,
                Currency_Answer__c, Checkbox_Answer__c , Any_Answer__c, Picklist_Answer__c, MultiSelect_Picklist_Answer__c, URL_Answer__c
                From Answer__c where Discovery_Workbook_Category__c in : sourceWorkbookCategory.keySet() ];
    }
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Retrieve all the cloneable question from the source
    Inputs: sourceSiteWorkbookId
    Returns: Map<Id,Question__c>
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
    /*private Map<Id,Question__c> retreiveCloneableQuestions(Id sourceSiteWorkbookId)
    {       
        List<Question__c> lstQuestion=  [SELECT Id,Question_Category__c FROM Question__c 
                                         where Cloneable__c = true
                                         and Question_Category__c in 
                                         (Select Question_Category__c from Discovery_Workbook_Category__c  where Site_Workbook__c = : sourceSiteWorkbookId)];
        Map<Id, Question__c> mapQuestion = new Map<Id, Question__c>();
        if (!lstQuestion.isEmpty())
        {
            for (Question__c quest : lstQuestion)
            {
                mapQuestion.put(quest.id,quest);
            }
        }
        
        return mapQuestion;
    }*/
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Retreive all the question
    Inputs: sourceSiteWorkbookId
    Returns: Map<Id,Question__c>
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
    /*private Map<Id,Question__c> retreiveAllQuestions(Id sourceSiteWorkbookId)
    {       
        List<Question__c> lstQuestion=  [SELECT Id,Question_Category__c FROM Question__c 
                                         where Question_Category__c in 
                                         (Select Question_Category__c from Discovery_Workbook_Category__c  where Site_Workbook__c = : sourceSiteWorkbookId)];
        Map<Id, Question__c> mapQuestion = new Map<Id, Question__c>();
        if (!lstQuestion.isEmpty())
        {
            for (Question__c quest : lstQuestion)
            {
                mapQuestion.put(quest.id,quest);
            }
        }
        
        return mapQuestion;
    }*/
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Validate if the answer is null
    Inputs: ans
    Returns: Boolean
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
    private Boolean isAnswerNull(Answer__c ans)
    {       
        Boolean result = false;
        if (ans.YesNo_Answer__c == null && ans.Text_Answer__c == null && ans.Number_Answer__c == null && ans.Date_Answer__c == null && ans.Checkbox_Answer__c == false
            && ans.Currency_Answer__c == null && ans.URL_Answer__c == null && ans.MultiSelect_Picklist_Answer__c == null && ans.Picklist_Answer__c == null)
        {
            result = true;
        }
        return result;
    }
    /*------------------------------------------------------------
    Author: Rey Austral
    Company: Cloud Sherpas
    Description: Check if the answer belongs to the question category
    Inputs: answersQuestionId, targetWorkbookCategory_Question_CategoryId, questions
    Returns: Boolean
    History
    08/28/14      Rey Austral        Created
    ------------------------------------------------------------*/
    /*private Boolean isAnswerBelongToCategory(Id answersQuestionId, Id targetWorkbookCategory_Question_CategoryId, Map<Id,Question__c> questions)
    {
        Boolean result = false;
        //validate if the answer question id is still exist, to avoid error when the admin accidentally delete the question
        if (questions.containsKey(answersQuestionId))
        {
            //get the details of the question
            Question__c quest = questions.get(answersQuestionId);
            //check if the current item in the loop have the same question category of the workbook
            //we can only link the new category to the old answer by looking in the question category id of the question object
            if (quest.Question_Category__c == targetWorkbookCategory_Question_CategoryId)
            {
                result = true;
            }
        }
        
        return result;
    }*/
}