SF Primes/src/objects/Answer__c.object
<CustomObject>
    <description>Captures the response for a Discovery Question to the respective Workbook and associated with a Project.</description>
    <fields>
        <fullName>Question_Category__c</fullName>
        <formula>&apos;Removed&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Discovery Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Answer</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Discovery_Answer_Workbook_Category__c.object
<CustomObject>
    <description>Junction object between Discovery Answer and Discovery Site Workbook category</description>
    <fields>
        <fullName>Discovery_Workbook_Category__c</fullName>
        <label>Discovery Workbook Category</label>
        <referenceTo>Discovery_Workbook_Category__c</referenceTo>
        <relationshipLabel>Discovery Answer Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Answer_Workbook_Categories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discovery Answer Workbook Category</label>
    <nameField>
        <displayFormat>DAWC-{0000000}</displayFormat>
        <label>Discovery Answer Workbook Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Answer Workbook Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Discovery_Question_Product__c.object
<CustomObject>
    <description>Junction object to associate a Discovery Question with their relevant Product.</description>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Discovery Question Products</relationshipLabel>
        <relationshipName>Discovery_Question_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Discovery Question Products</relationshipLabel>
        <relationshipName>Discovery_Question_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <formula>Product__r.Solution__r.Name</formula>
        <label>Solution</label>
        <type>Text</type>
    </fields>
    <label>Discovery Question Product</label>
    <nameField>
        <displayFormat>PQ-{00000000}</displayFormat>
        <label>ProdQuest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Question Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Discovery_Workbook_Category__c.object
<CustomObject>
    <description>Contains the Workbook capturing questions, responses, interviewees, interviewers; and associated with a Project and Site.</description>
    <fields>
        <fullName>Count_of_Questions__c</fullName>
        <label>Count of Questions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Category__c</fullName>
        <label>Question Category</label>
        <referenceTo>Question_Category__c</referenceTo>
        <relationshipName>Discovery_Workbook_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site_Workbook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Workbook</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Site_Workbook__c</referenceTo>
        <relationshipLabel>Discovery Site Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Workbook</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Discovery Site Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Site_Workbook_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Site Workbook Category</label>
    <nameField>
        <displayFormat>DW-{00000}</displayFormat>
        <label>Discovery Workbook Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbook Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Product__c.object
<CustomObject>
    <description>Contains the Products under each Solution.</description>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Solution is not active.</errorMessage>
            <filterItems>
                <field>Solution__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Solution__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Site_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProjectSite__c</fullName>
        <label>SubProjectSite</label>
        <referenceTo>SubProjectSite__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Product</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>ProdSite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Site_Workbook__c.object
<CustomObject>
    <description>Junction object to allow associating a Workbook with a Project and Site.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Discovery Site Workbooks</relationshipLabel>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Discovery Site Workbooks</relationshipLabel>
        <relationshipName>Discovery_Site_Workbooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discovery Site Workbook</label>
    <nameField>
        <displayFormat>SW-{00000000}</displayFormat>
        <label>Site Workbook ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Solution__c.object
<CustomObject>
    <description>Contains the categorization of Solutions under each Dealership Need.</description>
    <fields>
        <fullName>Question_Category__c</fullName>
        <label>Dealership Need</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Dealership Need is not active.</errorMessage>
            <filterItems>
                <field>Question_Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Question_Category__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProject_Name__c</fullName>
        <label>SubProject Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProjectSite__c.object
<CustomObject>
    <description>Junction object to allow associating multiple Sites (Accounts) with a SubProject.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SubProject Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMF_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CMF Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMF_Info__c.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CMF_Info__c</referenceTo>
        <relationshipLabel>SubProjectSites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject_Name__c</fullName>
        <formula>SubProject__r.SubProject_Name__c</formula>
        <label>SubProject Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProjectSite</label>
    <nameField>
        <displayFormat>SPS-{000000000}</displayFormat>
        <label>SubProjectSite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjectSites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_AddAnsOnSiteProdsInsert_Test.cls
/*--------------------
06/23/2015    Venkata Shrivol - Created
Description - Test Class for IMP_AddAnsOnSiteProdsInsert_Handler
-----HISTORY--------
2016-12-05  -venkata.shrivol@cdk.com -commented the code as it is no longer required  
----------------------------------*/
@isTest
public class IMP_AddAnsOnSiteProdsInsert_Test {

	/*@testSetup static void prepareTestData()
	{
		Account testAccount = IMP_TestFactory_Helper.buildAccount();
		insert testAccount;
		
		Project__c testProject = IMP_TestFactory_Helper.buildProject(0);
        insert testProject;
        
        
        CMF_Info__c testCmfInfo = IMP_TestFactory_Helper.buildCMFInfo(testAccount.Id);
        insert testCmfInfo;
        
        SubProject__c testSubProject = IMP_TestFactory_Helper.buildSubProject(testProject.Id);
        insert testSubProject;
        
        SubProjectSite__c testSubProjectSite = IMP_TestFactory_Helper.buildSubProjectSite(testAccount.Id, testSubProject.Id, testCmfInfo.Id);
        insert testSubProjectSite;
        
        list<Question_Category__c> testDNeedList = createQCList();
        //IMP_TestFactory_Helper.buildDealershipNeed();
        //insert testDNeed;
        
        list<Solution__c> testSolutionList  = createSolutionList(testDNeedList);
        //IMP_TestFactory_Helper.buildSolution(testDNeed.Id);
        //insert testSolution;
        
       	list<Product__c> testProductList = createProductList(testSolutionList);
       	//IMP_TestFactory_Helper.buildProduct(testSolution.Id);
        //insert testProduct;
        
        Site_Workbook__c testSiteWorkbook = IMP_TestFactoryTemporary_Helper.buildSiteWorkbook(testProject.Id, testSubProject.Id);
        testSiteWorkbook.Site__c = testAccount.Id;
        insert testSiteWorkbook;
        
        Discovery_Workbook_Category__c testSiteWorkbookCategory = IMP_TestFactoryTemporary_Helper.buildDiscoveryWorkbookCategory(testDNeedList.get(0).Id);
        testSiteWorkbookCategory.Site_Workbook__c = testSiteWorkbook.Id;
        testSiteWorkbookCategory.Count_of_Questions__c = 0;
        insert testSiteWorkbookCategory;
        //list<Discovery_Workbook_Category__c> testSiteWorkbookCatList = createWkbkCategoryList(testDNeedList, testSiteWorkbook.Id);
        
        list<Question__c> testQuestionsList = createQuestionList();
        
        generateQuestionProducts(testProductList, testQuestionsList);
			
	}
	
	static testMethod void addSiteProductFromExistingCategory() 
	{
		SubProject__c thisSubProject = [
    		select Id,Name, 
    			(Select Id
             	from SubProjectSites__r) 
            from SubProject__c 
            where SubProject_Name__c='Test SubProject Name' limit 1];
        
        SubProjectSite__c thisSite = thisSubProject.SubProjectSites__r.size()>0 ? thisSubProject.SubProjectSites__r.get(0) : new SubProjectSite__c();
            
        list<Product__c> thisProductList = [select Id from Product__c where Name='Test Product 1' or Name ='Test Product 3' or Name='Test Product 2'];
        
        Site_Workbook__c thisSiteWorkbook = [select Id from Site_Workbook__c where SubProject__c =:thisSubProject.Id limit 1];
        
        //Discovery_Workbook_Category__c thisSWkbkCategory = [select Id from Discovery_Workbook_Category__c where Site_Workbook__c =:thisSiteWorkbook.Id];
		
        //Site_Product__c siteProdsToInsert = IMP_TestFactoryTemporary_Helper.buildSiteProduct(thisSite.Id, thisProduct.Id, thisSubProject.Id);
        
        list<Site_Product__c> siteProdsToInsert = new list<Site_Product__c>();
		for(Product__c prd:thisProductList)
		{
			Site_Product__c testSiteProd = IMP_TestFactoryTemporary_Helper.buildSiteProduct(thisSite.Id, prd.Id, thisSubProject.Id);
			siteProdsToInsert.add(testSiteProd);
		}
        insert siteProdsToInsert.get(0);
        
        siteProdsToInsert.remove(0);
        
        Test.startTest();
        	insert siteProdsToInsert;
        Test.stopTest();
    }
    
    /*static testMethod void addSProductToCreateNewSWCategory() 
	{
		SubProject__c thisSubProject = [
    		select Id,Name, 
    			(Select Id
             	from SubProjectSites__r) 
            from SubProject__c 
            where SubProject_Name__c='Test SubProject Name' limit 1];
        
        SubProjectSite__c thisSite = thisSubProject.SubProjectSites__r.size()>0 ? thisSubProject.SubProjectSites__r.get(0) : new SubProjectSite__c();
            
        list<Product__c> thisProductList = [select Id, Solution__r.Question_Category__c from Product__c where Name='Test Product 2' or Name = 'Test Product 3'];
        
        Site_Workbook__c thisSiteWorkbook = [select Id from Site_Workbook__c where SubProject__c =:thisSubProject.Id limit 1];
        
        system.debug('RAM'+thisProductList);
        
        //Discovery_Workbook_Category__c thisSWkbkCategory = [select Id from Discovery_Workbook_Category__c where Site_Workbook__c =:thisSiteWorkbook.Id];
		
		list<Site_Product__c> siteProdsToInsert = new list<Site_Product__c>();
		for(Product__c prd:thisProductList)
		{
			Site_Product__c testSiteProd = IMP_TestFactoryTemporary_Helper.buildSiteProduct(thisSite.Id, prd.Id, thisSubProject.Id);
			siteProdsToInsert.add(testSiteProd);
		}
        
        Test.startTest();
        	insert siteProdsToInsert;
        Test.stopTest();
        
        list<Answer__c> ansList = [select Id from Answer__c where Discovery_Site_Workbook__c =:thisSiteWorkbook.Id];
		
		//Inserted 2 Products -> 1 Question -> 1 Answer -> 2 Answkbk Categories
		system.assertEquals(1,ansList.size());
    }
    
    
    
	public static list<Question_Category__c> createQCList()
	{
		list<Question_Category__c> listToInsert = new list<Question_Category__c>();
		
		for(Integer i=1;i<4;i++)
		{
			Question_Category__c qcat = new Question_Category__c();
			qcat.Name = 'Test Dealership Need '+i;
			qcat.Active__c = true;
			listToInsert.add(qcat);
		}
		insert listToInsert;
		return listToInsert;
	}
	public static list<Solution__c> createSolutionList(list<Question_Category__c> qcList)
	{
		list<Solution__c> listToInsert = new list<Solution__c>();
		Integer i=1;
		for(Question_Category__c qc:qcList)
		{
			Solution__c sol = new Solution__c();
			sol.Name = 'Test Solution '+i;
			sol.Question_Category__c = qc.Id;
			sol.Active__c = true;
			listToInsert.add(sol);
			i++;
		}
		insert listToInsert;
		
		return listToInsert;
	}
	public static list<Product__c> createProductList(list<Solution__c> solList)
	{
		integer i=1;
		list<Product__c> listToInsert = new list<Product__c>();
		for(Solution__c sol:solList)
		{
			
			Product__c prd = new Product__c();
			prd.Name = 'Test Product '+i;
			prd.Active__c = true;
			prd.Solution__c = sol.Id;
			listToInsert.add(prd);
			i++;
		}
		insert listToInsert;
		
		return listToInsert;
	}
	public static list<Discovery_Workbook_Category__c> createWkbkCategoryList(list<Question_Category__c> qcList, Id testSiteWorkbookId)
	{
		list<Discovery_Workbook_Category__c> listToInsert = new list<Discovery_Workbook_Category__c>();
		for(Question_Category__c qc:qcList)
		{
			Discovery_Workbook_Category__c dwc = new Discovery_Workbook_Category__c();
			dwc.Question_Category__c = qc.Id;
			dwc.Site_Workbook__c = testSiteWorkbookId;
			listToInsert.add(dwc);
		}
		insert listToInsert;
		
		return listToInsert;
		
	} 
	public static list<Question__c> createQuestionList()
	{
		list<Question__c> questionListToInsert = new list<Question__c>();
		
		for(Integer i=1; i<3; i++)
		{
			Question__c quest = new Question__c();
            quest.Active__c = true;
            quest.Question_Text__c = 'This is a test question for item ' + i;
            //quest.Question_Category__c = qCategoryId;
            quest.Project_Type__c = 'Upgrade';
            quest.Market__c = 'Drive - Baseline';
            quest.Answer_Type__c = 'Text';
            quest.Cloneable__c = true;
            questionListToInsert.add(quest);
		}
		insert questionListToInsert;
		
		/*list<Answer__c> insertAnswerList = new list<Answer__c>();
		for(Question__c qs:questionListToInsert)
		{
			Answer__c ans = new Answer__c();
			ans.Discovery_Workbook_Category__c = wkbkCatId;
			ans.Question__c = qs.Id;
			ans.Discovery_Site_Workbook__c = siteWkbkId;
			insertAnswerList.add();
		}
		insert insertAnswerList;
		
		list<Discovery_Answer_Workbook_Category__c> insertList = new list<Discovery_Answer_Workbook_Category__c>();
		for(Answer__c ans:insertAnswerList)
		{
			Discovery_Answer_Workbook_Category__c dawc = new Discovery_Answer_Workbook_Category__c();
        	dawc.Answer__c = ans.Id;
        	dawc.Discovery_Workbook_Category__c = wkbkCatId;
        	insertAnswerWkbkCategoriesList.add(dawc);
		}
		insert insertAnswerWkbkCategoriesList;
		
		return questionListToInsert;
	}
	
	public static void generateQuestionProducts(list<Product__c> testProductList, list<Question__c> testQuestionsList)
	{
		list<Discovery_Question_Product__c> dqpToInsert = new list<Discovery_Question_Product__c>();
		integer i=0;
		for(Product__c prd:testProductList)
		{
			integer j=0;
			for(Question__c qs:testQuestionsList)
			{
				if(math.mod(j,2)==i)
				{
					Discovery_Question_Product__c dqp = new Discovery_Question_Product__c();
					dqp.Question__c=qs.Id;
					dqp.Product__c = prd.Id;
					dqpToInsert.add(dqp);
				}
				else if(i==2)
				{
					Discovery_Question_Product__c dqp = new Discovery_Question_Product__c();
					dqp.Question__c=qs.Id;
					dqp.Product__c = prd.Id;
					dqpToInsert.add(dqp);
					break;
				}
				j++;
			}
			i++;
		}
		insert dqpToInsert;
	}
	
    */
}