SF Primes/src/objects/AVP_RGM_Link__c.object
<CustomObject>
    <description>Added for AVP emails. BDC Communication Project</description>
    <fields>
        <fullName>AVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AVP_RGM_Link</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RGM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RGM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AVP_RGM_Link1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AVP - RGM Link</label>
    <nameField>
        <displayFormat>ARL-{0000}</displayFormat>
        <label>AVP - RGM Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AVP - RGM Link</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Deal_State__c.object
<CustomObject>
    <description>Deal Related information. BDC Communication Project</description>
    <fields>
        <fullName>Key_DOS__c</fullName>
        <formula>Opportunity__r.Account.Key_DOS__r.FirstName&amp;&quot; &quot;&amp;Opportunity__r.Account.Key_DOS__r.LastName</formula>
        <label>Key DOS</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal State</relationshipLabel>
        <relationshipName>Deal_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal State</label>
    <nameField>
        <displayFormat>DS - {000000}</displayFormat>
        <label>Deal State ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Finalized_Deal_NSA_Request__c.object
<CustomObject>
    <description>Finalized Deal NSA request. BDC Communication Project</description>
    <fields>
        <fullName>AVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Finalized_Deal_NSA_Request2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOS</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Finalized_Deal_NSA_Request1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal State</label>
        <referenceTo>Deal_State__c</referenceTo>
        <relationshipLabel>Finalized Deal NSA Request</relationshipLabel>
        <relationshipName>Finalized_Deal_NSA_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RGM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RGM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Finalized_Deal_NSA_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Finalized Deal NSA Request</label>
    <nameField>
        <displayFormat>FDNR-{00000}</displayFormat>
        <label>Finalized Deal NSA Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finalized Deal NSA Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DS_FinalizedDealNSARequest_Test.cls
@IsTest
public class DS_FinalizedDealNSARequest_Test 
{
    public static testmethod void NSATriggerTest()
    {
        //profile p = [Select Id, Name From Profile Limit 1];
        // insert a standard user
        User ManagerUser = DS_TestObjects.NewUser_Inserted();
        
        /* User ManagerUser = new User(
            Username = 'test12@cobalt.com', 
            Email = 'test11@cobalt.com', 
            LastName = 'user11', 
            FirstName = 'test21', 
            Alias = 'tsas1', 
            CommunityNickName = 'testNickName1', 
            TimeZoneSidKey = 'America/Los_Angeles', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            ProfileId = p.Id, 
            LanguageLocaleKey = 'en_US', 
            ADID__c = 'est1', 
            IsActive = true,
            FederationIdentifier = 'fdhgu7897'
        ); insert ManagerUser;*/
        
        /* User SubordinateUser = new User(
            Username = 'tt1@cobalt.com', 
            Email = 'te1@cobalt.com', 
            LastName = 'us1', 
            FirstName = 'tt123', 
            Alias = 'tsAnj1', 
            CommunityNickName = 'testjkName1', 
            TimeZoneSidKey = 'America/Los_Angeles', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            ProfileId = p.Id, 
            LanguageLocaleKey = 'en_US', 
            ADID__c = 'test1', 
            IsActive = true,
            FederationIdentifier = 'bhj783423'
        ); insert SubordinateUser;*/
        
        // insert another user who has the manager as ManagerUser
        User SubordinateUser = DS_TestObjects.NewSecondUser_Inserted();
        SubordinateUser.ManagerId = ManagerUser.Id;
        update SubordinateUser;
              
        // insert a new account 
        Account NewAccount = DS_TestObjects.NewAccount_Inserted();
        NewAccount.Key_DOS__c = SubordinateUser.Id;
        Update NewAccount;
        
        // insert a new Opportunity
        Opportunity NewOpportunity = DS_TestObjects.NewOpportunity();        
        NewOpportunity.AccountId = NewAccount.Id;
        Insert NewOpportunity;
        
        // insert a new Deal State
        Deal_State__c NewDealState = new Deal_State__c();
        NewDealState.Opportunity__c = NewOpportunity.Id;
        Insert NewDealState;
        
        // insert new AVP RGM link
        AVP_RGM_Link__c AvpRGMLink = new AVP_RGM_Link__c();
        AvpRGMLink.AVP__c = ManagerUser.Id;
        AvpRGMLink.RGM__c = SubordinateUser.Id;
        Insert AvpRGMLink;
        
        // insert a new Finalized deal NSA request
        Finalized_Deal_NSA_Request__c FinalDealNSARequest = new Finalized_Deal_NSA_Request__c();
        FinalDealNSARequest.DOS__c = SubordinateUser.Id;
        FinalDealNSARequest.AVP__c = SubordinateUser.ManagerId;
        FinalDealNSARequest.Deal_State__c = NewDealState.Id;
        insert FinalDealNSARequest;        
    }
}