SF Primes/src/objects/AVP_RGM_Link__c.object
<CustomObject>
    <description>Added for AVP emails. BDC Communication Project</description>
    <fields>
        <fullName>AVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AVP_RGM_Link</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RGM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RGM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AVP_RGM_Link1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AVP - RGM Link</label>
    <nameField>
        <displayFormat>ARL-{0000}</displayFormat>
        <label>AVP - RGM Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AVP - RGM Link</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Deal_State__c.object
<CustomObject>
    <description>Deal Related information. BDC Communication Project</description>
    <fields>
        <fullName>Alternate_DocuSign_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alternate DocuSign Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deal State</relationshipLabel>
        <relationshipName>Deal_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key_DOS__c</fullName>
        <formula>Opportunity__r.Account.Key_DOS__r.FirstName&amp;&quot; &quot;&amp;Opportunity__r.Account.Key_DOS__r.LastName</formula>
        <label>Key DOS</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal State</relationshipLabel>
        <relationshipName>Deal_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal State</label>
    <nameField>
        <displayFormat>DS - {000000}</displayFormat>
        <label>Deal State ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Finalized_Deal_NSA_Request__c.object
<CustomObject>
    <description>Finalized Deal NSA request. BDC Communication Project</description>
    <fields>
        <fullName>AVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Finalized_Deal_NSA_Request2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOS</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Finalized_Deal_NSA_Request1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal State</label>
        <referenceTo>Deal_State__c</referenceTo>
        <relationshipLabel>Finalized Deal NSA Request</relationshipLabel>
        <relationshipName>Finalized_Deal_NSA_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RGM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RGM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Finalized_Deal_NSA_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Finalized Deal NSA Request</label>
    <nameField>
        <displayFormat>FDNR-{00000}</displayFormat>
        <label>Finalized Deal NSA Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finalized Deal NSA Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DS_FinalizedDealNSARequest_Handler.cls
public class DS_FinalizedDealNSARequest_Handler 
{
    public static void FinalizedDealNSARequest(List<Finalized_Deal_NSA_Request__c> NewNSARequests)
    {
        Set<Id> DealStateIds =  new Set<Id>();                
        Set<String> Accountfield = new Set<String>();
        
        Map<Id, Finalized_Deal_NSA_Request__c> FinalizedDealsMap = new Map<Id, Finalized_Deal_NSA_Request__c>(
            [
                SELECT Id, Deal_State__r.Opportunity__r.Account.Key_DOS__r.ManagerId
                FROM Finalized_Deal_NSA_Request__c 
                WHERE Id 
                IN :NewNSARequests
            ]
        );
        
        
        List<Finalized_Deal_NSA_Request__c> FinalDealsToUpdate = new List<Finalized_Deal_NSA_Request__c>();
        
        // prepare query and collections for setting RGM
        Map<string, string> AVPToRGMMap =  new Map<string, string>();
        List<AVP_RGM_Link__c> AVP_RGMList = new List<AVP_RGM_Link__c>();
        
        AVP_RGMList = [Select Id, AVP__c, RGM__c From AVP_RGM_Link__c];
        
        for(AVP_RGM_Link__c a: AVP_RGMList){
            AVPToRGMMap.put(a.AVP__c, a.RGM__c);
        }
        
        System.debug(AVPToRGMMap);
        
        for(Id key : FinalizedDealsMap.KeySet())
        { 
            Finalized_Deal_NSA_Request__c FinalizedDealNSARequest = new Finalized_Deal_NSA_Request__c();
            Deal_State__c CurrentDealState = new Deal_State__c();
            Opportunity CurrentOpportunity = new Opportunity();
            Account CurrentAccount = new Account();
            User CurrentUser = new User();
            
            FinalizedDealNSARequest = FinalizedDealsMap.get(key);
            CurrentDealState = FinalizedDealNSARequest != null ? FinalizedDealNSARequest.Deal_State__r : null;
            CurrentOpportunity = CurrentDealState != null ? CurrentDealState.Opportunity__r : null;
            CurrentAccount = CurrentOpportunity != null ? CurrentOpportunity.Account : null;
            CurrentUser = CurrentAccount != null ? CurrentAccount.Key_DOS__r : null;
            
            System.debug(CurrentAccount);
            
            if(CurrentAccount != null) { 
                FinalizedDealNSARequest.DOS__c = CurrentAccount.Key_DOS__c; 
            }
            
            System.debug(CurrentUser);
            
            if(CurrentUser != null)
            {
                FinalizedDealNSARequest.AVP__c = CurrentUser.ManagerId;
                
                System.debug(AVPToRGMMap);
                System.debug(AVPToRGMMap.get(CurrentUser.ManagerId) != null);
                
                if(AVPToRGMMap != null && !AVPToRGMMap.isEmpty() && AVPToRGMMap.get(CurrentUser.ManagerId) != null) { 
                    FinalizedDealNSARequest.RGM__c = AVPToRGMMap.get(CurrentUser.ManagerId); 
                }
            }
            
            FinalDealsToUpdate.add(FinalizedDealNSARequest);
        }        
        
        update FinalDealsToUpdate;
    }
}