SF Primes/src/objects/AVP_RGM_Link__c.object
<CustomObject>
    <description>Added for AVP emails. BDC Communication Project</description>
    <fields>
        <fullName>Controller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Controller</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AVP_RGM_Link2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>ARG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DASH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoffman Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Truck Dealers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NIADA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PFW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>AVP - RGM Link</label>
    <nameField>
        <displayFormat>ARL-{0000}</displayFormat>
        <label>AVP - RGM Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AVP - RGM Link</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Sales_Discovery__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Sites__c</fullName>
        <label>Number of Sites ( *Required)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Discovery</relationshipLabel>
        <relationshipName>Sales_Discovery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sites_Involved_With_Request__c</fullName>
        <label>Sites Involved With Request (*Required)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sales Discovery</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>Sales Discovery ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Discovery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/ALL_SalesDiscovery_Test.cls
//2017-05-17 lalitha.adduru@cdk.com modified this test class to test RQ-09223
@IsTest
public class ALL_SalesDiscovery_Test 
{
    @Testsetup
    public static void setupData()
    {
        // added by lalitha
        Id userId = UserInfo.getUserId();
        AVP_RGM_Link__c link = new 	AVP_RGM_Link__c(ARM_Supervisor__c = userId,
                                                    Implementation_Director__c = userId,
                                                    Controller__c = userId,
                                                    Region__c = 'Division');
        insert link;
        
        Account accObj = new Account(Name='TestAccount');
        insert accObj;
        
        Opportunity oppObj = DS_TestObjects.NewOpportunity();
        oppObj.AccountId = accObj.Id;
        oppObj.Type = 'Unhook';
        insert oppObj;
        
        Sales_Discovery__c salesObj = new Sales_Discovery__c();
        salesObj.Opportunity__c = oppObj.Id;
        salesObj.Sites_Involved_With_Request__c = 'Sample';
        salesObj.Number_of_Sites__c = 12;
        insert salesObj;
    }
    
    public static testmethod void test1()
    {
        Sales_Discovery__c salesObjOne = [SELECT Id,Implementation_Director__c from Sales_Discovery__c ][0];
        system.assertEquals(UserInfo.getUserId(), salesObjOne.Implementation_Director__c);
        
        Opportunity oppObj = [SELECT Id FROM Opportunity LIMIT 1];
        Sales_Discovery__c salesObj = new Sales_Discovery__c();
        salesObj.Opportunity__c = oppObj.Id;
        salesObj.Sites_Involved_With_Request__c = 'Sample';
        salesObj.Number_of_Sites__c = 12;
        
        try
        {
            insert salesObj;
        }
        catch(Exception e)
        {
            System.assert(e.getMessage().contains('Sales Discovery already exists with given Opportunity'));
        }
    }
}