SF Primes/src/objects/Blacklisted_Word__c.object
<CustomObject>
    <description>The records which will contain the Words or Phrases that are not allowed according to Organization&apos;s policy.</description>
    <fields>
        <fullName>Prevent_Post_on_Breach__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, a post which hits a blacklist will not be posted to the chatter feed at all. Checking this box automatically enables the visual warning flag.</description>
        <label>Prevent Post on Breach</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RegexValue__c</fullName>
        <description>The RegexValue generated for the Blacklisted Word or Phrase.</description>
        <label>RegexValue</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Substitution__c</fullName>
        <defaultValue>&quot;****&quot;</defaultValue>
        <label>Substitution</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Blacklisted Word</label>
    <nameField>
        <displayFormat>BLW-{0000}</displayFormat>
        <label>Blacklisted Word Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blacklisted Words</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Docusign/src/classes/ALL_PatternHelperSerializable.cls
public class ALL_PatternHelperSerializable
{
    public String regexValue {set; get;}
    public String pRegEx {set; get;}
    public String substitutionValue {set; get;}
    public boolean preventPostOnMatch {set; get;}
    public Blacklisted_Word__c blacklistedWord {set; get;}
    public String origPostBody {set; get;}
    
    //Pass in Blacklisted word and also the regExPattern from the Pattern class.
    //Serializing the Pattern.class is not supported. We just need to pass the regEx representation of it.
    public ALL_PatternHelperSerializable(Blacklisted_Word__c word, String regExPattern, String originalPostBody)
    {
        regexValue=word.RegexValue__c;
        pRegEx=regExPattern;
        substitutionValue=word.Substitution__c;
        preventPostOnMatch=word.Prevent_Post_on_Breach__c;
        blacklistedWord=word;
        origPostBody=originalPostBody;
    }
}