SF Primes/src/objects/Business_Site__c.object
<CustomObject>
    <description>Digital list of OEMs belonging to each account.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>LMA Account No</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Sites</relationshipLabel>
        <relationshipName>Business_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Franchise__c</fullName>
        <label>Franchise</label>
        <picklist>
            <picklistValues>
                <fullName>Acura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aston Martin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bentley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CASE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadillac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chevrolet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chrysler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daewoo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dodge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferrari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUMMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyundai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infiniti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Isuzu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jeep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volkswagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volvo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LMA_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Sites (LMA Account)</relationshipLabel>
        <relationshipName>Business_Sites1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Business Site</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Business Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Sites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/CB_LMA_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Site_Type__r.Name</field>
                <operation>notEqual</operation>
                <value>Local Marketing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LMA Relationship (Dealer Account)</relationshipLabel>
        <relationshipName>LMA_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LMA_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMA Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Site_Type__r.Name</field>
                <operation>equals</operation>
                <value>Local Marketing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LMA Related Accounts</relationshipLabel>
        <relationshipName>LMA_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the LMAs</description>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>LMA Relationships</label>
    <nameField>
        <displayFormat>LMAR-{0000}</displayFormat>
        <label>LMA Relationships Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMA Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Service_Contract__c.object
<CustomObject>
    <description>Service Contracts from Oracle</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Contract</relationshipLabel>
        <relationshipName>Service_Contract</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Contract</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/ALL_BusinessSites_Handler.cls
//2016-04-20- fsalwen@salesforce.com- Updated to add in handling for syncing up the BrandRelationship records

public class ALL_BusinessSites_Handler 
{
    public static void fieldsettingMethod(map<ID, Business_Site__c> oldMap, list<Business_Site__c> newList)
    {
        map<string, string> ProductCodeToFranchise = new map<string, string>{ 'Chevrolet' => 'SC-14.437.01', 'Buick' => 'SC-14.488.00', 'Cadillac' => 'SC-14.527.00'};         
        set<string> accountNumberSet = new set<string>();
        set<ID> accountIDs = new set<ID>();
        map<ID, list<Service_Contract__c>> accountToServiceContracts = new map<ID, list<Service_Contract__c>>();
        list<CB_LMA_Relationship__c> toBeInsertedLMArelationships = new list<CB_LMA_Relationship__c>();
           
        if(Trigger.isDelete){ newList = oldMap.Values();}
        
        if(newList != null && !newList.isEmpty())
        {
            for(Business_Site__c bs: newList)
            {
                if(bs.LMA_Account__c != null)
                {
                    accountIDs.add(bs.LMA_Account__c);
                } 
                
                if(bs.Account__c != null)
                {
                    accountIDs.add(bs.Account__c);
                }
                
                if(bs.Account_Number__c != null)
                {                
                    accountNumberSet.add(bs.Account_Number__c);
                }
                
                if(oldMap != null)
                {
                    string accountNumber = oldMap.get(bs.ID).Account_Number__c;
                    
                    if(oldMap != null && !oldMap.isEmpty() && accountNumber != null)
                    {
                        accountNumberSet.add(accountNumber);
                    }
                }
            }
        }
        
        map<ID, Account> accountMap;
        map<ID, string> siteTypeMap = ALL_BusinessSites_Handler.getSiteTypeMap(new list<ID>(accountIDs));
        
        if(accountNumberSet != null && !accountNumberSet.isEmpty())
        {
            accountMap = new map<ID, Account>([
                Select ID, Name, Account_Number__c, Site_Type__r.Name
                //(Select Id, Name, Product_Code__c From Service_Contract__r)
                From Account
                Where ((Account_Number__c IN :accountNumberSet)
                       OR (ID IN :accountIDs)) 
                AND Account_Number__c != null
                AND isDeleted = false
            ]);
        }
        
        List<Service_Contract__c> ServiceContractList = [SELECT ID, Name, Product_Code__c, Account__c 
                                                         FROM Service_Contract__c
                                                         WHERE (Account__r.Account_Number__c IN : accountNumberSet OR Account__c IN :accountIDs)
                                                         AND Account__r.Account_Number__c != null
                                                         AND Account__r.isDeleted = false ];
        
        if(ServiceContractList != null && !ServiceContractList.isEmpty())
        {
            for(Service_Contract__c sc: ServiceContractList)
            {
                List<Service_Contract__c> ServiceContracts = accountToServiceContracts.get(sc.Account__c);
                
                if(ServiceContracts == null){ ServiceContracts = new List<Service_Contract__c>(); }
                ServiceContracts.add(sc);
                accountToServiceContracts.put(sc.Account__c, ServiceContracts);                
            }
        }
        
        map<string, Account> numberToAccount = new map<string, Account>(); 
        
        system.debug(accountMap);
        
        if(accountMap != null && !accountMap.isEmpty())
        {
            for(Account a: accountMap.values())
            {
                //accountToServiceContracts.put(a.ID, a.getSobjects('Service_Contract__r'));
                
                if(a.Account_Number__c != null)
                {
                    numberToAccount.put(a.Account_Number__c, a);
                }
            } 
        }
        
        system.debug(numberToAccount);
        
        if(Trigger.isInsert && Trigger.isBefore)
        {        
            for(Business_Site__c bs: newList)
            {
                if(bs.Account_Number__c != null)
                {
                    Account lmaAccount = numberToAccount.get(bs.Account_Number__c);
                    ID dealerAccountID = bs.Account__c != null?bs.Account__c:null;
                    
                    list<Service_Contract__c> serviceContracts;
                    if(dealerAccountID != null)
                    {
                        serviceContracts = accountToServiceContracts.get(dealerAccountID);
                    }
                    
                    CB_LMA_Relationship__c newCBLMArelation = new CB_LMA_Relationship__c();
                    
                    if(bs.Account__c != null)
                    {
                        newCBLMArelation.Dealer_Account__c = (siteTypeMap.get(bs.Account__c) != 'Local Marketing')?bs.Account__c:null;
                    }
                    newCBLMArelation.LMA_Account__c = (lmaAccount != null && lmaAccount.Site_Type__r.Name.equalsIgnoreCase('Local Marketing'))?lmaAccount.ID : null;
                    newCBLMArelation.Status__c = 'Inactive';
                    
                    
                    bs.LMA_Account__c = lmaAccount.ID;
                    
                    if(serviceContracts != null && !serviceContracts.isEmpty())
                    {
                        for(Service_Contract__c cs: serviceContracts)
                        {
                            if(bs.Franchise__c != null && cs.Product_Code__c == ProductCodeToFranchise.get(bs.Franchise__c))
                            {
                                newCBLMArelation.Status__c = 'Active'; break;
                            }
                        } 
                    }                        
                    toBeInsertedLMArelationships.add(newCBLMArelation);
                    
                }
            }
            
            if(toBeInsertedLMArelationships != null && !toBeInsertedLMArelationships.isEmpty())
            {
                insert toBeInsertedLMArelationships;
            }
        }
         
        if(Trigger.isUpdate && Trigger.isBefore)
        { 
            set<ID> BusinessAccounts = new set<ID>();
            for(Business_Site__c bs: newList)
            {  
                if(bs.LMA_Account__c != null)
                {
                    BusinessAccounts.add(bs.LMA_Account__c);
                }
                
                if(bs.Account__c != null)
                {
                    BusinessAccounts.add(bs.Account__c);
                }                
            }
            
            map<ID, CB_LMA_Relationship__c> LMArelationsMap;
            
            LMArelationsMap = new map<ID, CB_LMA_Relationship__c>([
                Select ID, Name, LMA_Account__c, Dealer_Account__c, Dealer_Account__r.Name
                From CB_LMA_Relationship__c
                Where LMA_Account__c IN :BusinessAccounts
            ]);
            
            map<ID, CB_LMA_Relationship__c> toBeDeletedRelations = new map<ID, CB_LMA_Relationship__c>();
            map<ID, CB_LMA_Relationship__c> toBeUpdatedRelations = new map<ID, CB_LMA_Relationship__c>();
            
            
            if(LMArelationsMap != null && !LMArelationsMap.isEmpty())
            {
                for(CB_LMA_Relationship__c LMArelation: LMArelationsMap.values())
                {
                    for(Business_Site__c bs: newList)
                    {
                        if(bs.Account_Number__c == null || 
                           (bs.Status__c != null && bs.Status__c.startsWithIgnoreCase('i') && bs.Account_Number__c != null))
                        {
                            bs.LMA_Account__c = null;
                            
                            if(bs.Account_Number__c != null)
                            {
                                Account lmaAccount = numberToAccount.get(oldMap.get(bs.ID).Account_Number__c);
                                
                                if(lmaAccount != null && 
                                   LMArelation.LMA_Account__c == lmaAccount.ID && bs.Status__c != null)
                                {
                                    toBeDeletedRelations.put(LMArelation.ID, LMArelation);
                                }
                            }
                        }
                        
                        //system.debug(bs.Status__c != null && bs.Status__c.startsWithIgnoreCase('a')); 
                        //system.debug(bs.Account_Number__c != null);
                        //system.debug(lmaRelation.LMA_Account__c == numberToAccount.get(bs.Account_Number__c).ID);
                        
                        if(bs.Status__c != null && bs.Status__c.startsWithIgnoreCase('a') && 
                           bs.Account_Number__c != null && numberToAccount.get(bs.Account_Number__c) != null &&
                           lmaRelation.LMA_Account__c == numberToAccount.get(bs.Account_Number__c).ID)
                        {
                            list<Service_Contract__c> serviceContracts;
                            Account lmaAccount;
                            ID dealerAccountID;
                            
                            if(LMArelation.LMA_Account__c != null)
                            {
                                lmaAccount = numberToAccount.get(LMArelation.LMA_Account__c);
                            }
                            
                            dealerAccountID = LMArelation.Dealer_Account__c != null ? LMArelation.Dealer_Account__c : null;
                            
                            if(dealerAccountID != null)
                            {
                                serviceContracts = accountToServiceContracts.get(dealerAccountID);
                            } 
                            
                            //system.debug(LMArelation.Dealer_Account__r.Name); system.debug(ServiceContracts.size());
                            
                            if(serviceContracts != null && !serviceContracts.isEmpty())
                            {
                                for(Service_Contract__c cs: serviceContracts)
                                {
                                    if(bs.Franchise__c != null && cs.Product_Code__c == ProductCodeToFranchise.get(bs.Franchise__c))
                                    {
                                        LMArelation.Status__c = 'Active'; toBeUpdatedRelations.put(LMArelation.ID, LMArelation); break;
                                    }
                                    else
                                    {
                                        LMArelation.Status__c = 'INACTIVE'; toBeUpdatedRelations.put(LMArelation.ID, LMArelation);
                                    }
                                } 
                            }                            
                        }
                    }
                }
            }
            
            if(toBeUpdatedRelations != null && !toBeUpdatedRelations.isEmpty())
            {
                Update toBeUpdatedRelations.values();
            }
            
            if(toBeDeletedRelations != null && !toBeDeletedRelations.isEmpty())
            {
                Delete toBeDeletedRelations.values(); 
            }            
        }
        
        if(Trigger.isDelete)
        {
            list<Business_site__c> oldList = oldMap.values();           
            set<ID> BusinessAccounts = new set<ID>();
            for(Business_Site__c bs: oldMap.values())
            {                
                if(bs.LMA_Account__c != null)
                {                    
                    BusinessAccounts.add(bs.LMA_Account__c);
                } 
                if(bs.Account__c != null)
                {
                    BusinessAccounts.add(bs.Account__c);
                }
            }
            
            map<ID, CB_LMA_Relationship__c> LMArelationsMap = new map<ID, CB_LMA_Relationship__c>([
                Select ID, Name, LMA_Account__c
                From CB_LMA_Relationship__c
                Where LMA_Account__c IN :BusinessAccounts
            ]);
            
            system.debug(LMArelationsMap);
            
            list<CB_LMA_Relationship__c> toBeDeletedRelations = new List<CB_LMA_Relationship__c>();
            if(LMArelationsMap != null && !LMArelationsMap.isEmpty())
            {
                for(CB_LMA_Relationship__c LMArelation: LMArelationsMap.values())
                {
                    for(Business_Site__c bs: oldMap.values())
                    {
                        Account a = numberToAccount.get(bs.Account_Number__c);
                        if(a != null && 
                           LMArelation.LMA_Account__c == a.ID)
                        {
                            toBeDeletedRelations.add(LMArelation);
                        }
                    }
                }
            }
            
            if(toBeDeletedRelations != null && !toBeDeletedRelations.isEmpty())
            {
                Delete toBeDeletedRelations; 
            } 
        }
    }
    
    public static map<ID, string> getSiteTypeMap(list<ID> accountIDsList)
    {
        map<ID, string> siteTypeIDtoName = new map<ID, string>();
        map<ID, Account> accountMap;
        
        if(!accountIDsList.isEmpty())
        {
           accountMap = new map<ID, Account>([
                Select ID, Name, Site_Type__r.Name 
                From Account
                Where ID IN :accountIDsList
            ]);
        }
        
        if(accountMap != null && !accountMap.isEmpty())
        {
            for(Account acc: accountMap.values())
            {
                siteTypeIDtoName.put(acc.ID, acc.Site_Type__r.Name);
            }
        }
        
        return siteTypeIDtoName;
    }
}