SF Primes/src/objects/Business_Site__c.object
<CustomObject>
    <description>Digital list of OEMs belonging to each account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Sites</relationshipLabel>
        <relationshipName>Business_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Franchise__c</fullName>
        <label>Franchise</label>
        <picklist>
            <picklistValues>
                <fullName>Acura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aston Martin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bentley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CASE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadillac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chevrolet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chrysler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daewoo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dodge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferrari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUMMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyundai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infiniti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Isuzu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jeep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volkswagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volvo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Business Site</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Business Site #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Sites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/CB_LMA_Mfgr_Record_Types__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CB LMA Mfgr Record Types</description>
    <fields>
        <fullName>Franchise__c</fullName>
        <description>Franchise</description>
        <label>Franchise</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>Record Type</description>
        <label>Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CB LMA Mfgr Record Types</label>
</CustomObject>

SF Primes/src/objects/CB_LMA_RFP_Models__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CB LMA RFP Models</description>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <description>Manufacturer</description>
        <label>Manufacturer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CB LMA RFP Models</label>
</CustomObject>

SF Primes/src/objects/LMA_RFP__c.object
<CustomObject>
    <fields>
        <fullName>LMA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>LMA Account cannot be changed once record is created.  Please click &apos;Cancel&apos; button to cancel the current record and create a new record.</inlineHelpText>
        <label>LMA Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LMA RFPs</relationshipLabel>
        <relationshipName>LMA_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_1__c</fullName>
        <label>Model 1</label>
        <picklist>
            <picklistValues>
                <fullName>Acadia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acadia Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canyon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canyon Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enclave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lacrosse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 1500 Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 2500 Denali HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 2500HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 3500 Denali HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 3500HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terrain Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corvette</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cruze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equinox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Impala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malibu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silverado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sonic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suburban</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tahoe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model_2__c</fullName>
        <label>Model 2</label>
        <picklist>
            <picklistValues>
                <fullName>Acadia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acadia Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canyon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canyon Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enclave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lacrosse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 1500 Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 2500 Denali HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 2500HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 3500 Denali HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sierra 3500HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terrain Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corvette</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cruze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equinox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Impala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malibu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silverado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sonic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suburban</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tahoe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>LMA RFP</label>
    <nameField>
        <displayFormat>RFP-{0000}</displayFormat>
        <label>LMA RFP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMA RFPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SF Primes/src/objects/Manufacturer_at_Dealership__c.object
<CustomObject>
    <description>Manufacturers identified at an account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Manufacturers at Dealership</relationshipLabel>
        <relationshipName>R00N40000001ldb7EAA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer</label>
        <referenceTo>Manufacturer__c</referenceTo>
        <relationshipLabel>Manufacturers at Dealership (Manufacturers)</relationshipLabel>
        <relationshipName>R00N40000001lfhBEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Manufacturer at Dealership</label>
    <nameField>
        <displayFormat>ID - {00000}</displayFormat>
        <label>Mfg at Dealer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manufacturers at Dealership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/CB_LMARFPCreate_Extension.cls
//Request - 04926: RFP to USIM contacts via VF Page and route to LMA Strategist
// 08/31/15 smitha.simhadri@cdk.com Created
// 2015-12-08 smitha.simhadri@cdk.com Updated RQ-05897 Alphabetize LMA drop down field
// 2016-06-15 matt.keefe@cdk.com, Lalitha.Adduru@cdk.com - updated contact references to contact relationship
public class CB_LMARFPCreate_Extension
{
	public LMA_RFP__c rfp { get; set; }

	public String selectedRecType { get; set; }
	public String selectedLMA { get; set; }
	public String selectedModelOne { get; set; }
	public String selectedModelTwo { get; set; }
	public String selectedModelThree { get; set; }
	public String selectedModelFour { get; set; }
	public Boolean ReadOnly { get; set; }
	public List<selectOption> LMAAccts { get; set; }
	public List<selectOption> LMAModels { get; set; }
	public set<Id> agencyIds;

	public CB_LMARFPCreate_Extension(ApexPages.StandardController stdCtrl)
	{
		rfp = (LMA_RFP__C) stdCtrl.getRecord();
	}

	public Set<String> rfpRecTypes
	{
		get {
			System.debug(UserInfo.getUserId());
			System.debug(UserInfo.getUserName());

			id userId = UserInfo.getUserId();

			//List<contact> agencyContacts = [
			//    select id, name, account.id, account.name 
			//    from contact 
			//    where user__r.id = :userId
			//    and account.name != 'CDK Global'
			//]; 

			// 2016-06-15 matt.keefe@cdk.com - added contact relationship subquery
			list<Contact> agencyContacts = [
			                                Select
			                                id, name, account.id, account.name,
			(Select
			 id, name, Account__c, Account__r.Name
			 From Contact_Relationships__r)
			                                From
			                                Contact
			                                Where user__r.id = :userId
			                                AND account.name != 'CDK Global'
			                               ];

			rfpRecTypes = new Set<String> ();
			agencyIds = new Set<Id> ();

			iF (agencyContacts != null && !agencyContacts.isEmpty())
			{
				for (Contact agencyContact : agencyContacts)
				{
					// 2016-06-15 matt.keefe@cdk.com - looping through contact relationships instead of contact
					for (Contact_Relationship__c cr : agencyContact.getSObjects('Contact_Relationships__r'))
					{
						agencyIds.add(cr.Account__c);

						// 2016-06-15 matt.keefe@cdk.com - instead of querying account, just get the data
						Account agencyAcct = new Account(id = cr.Account__c, Name = cr.Account__r.Name);

						if (cr.Account__c != null)
						{
							//2016-06-16 - lalitha.adduru@cdk.com - changed the below variable to list to avoid 'no rows for assignment error'
							list<Manufacturer_at_Dealership__C> mfgDlr = [
							                                              select id, name, account__r.name, account__r.id, manufacturer__r.id, manufacturer__r.name
							                                              from manufacturer_at_dealership__c
							                                              where account__r.id = :agencyAcct.id
							                                             ];

							if (mfgDlr != null && !mfgDlr.isEmpty())
							{
								for (Manufacturer_at_Dealership__C mfgDlrOne : mfgDlr)
								{
									String mfgName = mfgDlrOne.manufacturer__r.name;
									CB_LMA_MFgr_record_types__C recTypeCS = CB_LMA_MFgr_record_types__C.getInstance(mfgName);

									if (recTypeCS != null)
									{
										String recTypeVal = recTypeCS.record_type__c;
										rfpRecTypes.add(recTypeVal);
									}
								}
							}

						}
					}
				}

			}
			else
			{
				rfpRecTypes = null;
			}
			return rfpRecTypes;
		}
		set;
	}

	public List<SelectOption> getRFPrecTypeOptions()
	{
		List<SelectOption> RFPrecTypeOptions = new List<SelectOption> ();
		RFPrecTypeOptions.add(new SelectOption('', '---Select One---'));

		if (rfpRecTypes != null && !rfpRecTypes.isEmpty())
		{
			for (String rfpRecTypesOne : rfpRecTypes)
			{
				RFPrecTypeOptions.add(new SelectOption(rfpRecTypesOne, rfpRecTypesOne));
			}
		}
		return RFPrecTypeOptions;
	}

	public List<account> lmas
	{
		get {
			List<CB_LMA_MFgr_record_types__C> mfgRecTypesCS = [
			                                                   select name, franchise__c, Record_Type__c
			                                                   from CB_LMA_MFgr_record_types__C
			                                                   where record_type__c = :selectedRecType
                                                               ORDER BY Name DESC
			                                                  ];

			String mfgrNameCS;
			String franchise;

			if (mfgRecTypesCS != null && !mfgRecTypesCS.isEmpty())
			{
				for (CB_LMA_MFgr_record_types__C mfgRecTypesCSOne : mfgRecTypesCS)
				{
					mfgrNameCS = mfgRecTypesCSOne.name;
					franchise = mfgRecTypesCSOne.franchise__c;
				}
                
				List<manufacturer_at_dealership__c> mfgrParent = new List<manufacturer_at_dealership__c> ();
				mfgrParent = [
				              select id, name, account__r.id, account__r.name
				              from manufacturer_at_dealership__c
				              where manufacturer__r.name = :mfgrNameCS
				              and account__r.site_type__r.name = 'Advertisers'
				              and account__r.id in :agencyIds
				              LIMIT 1
				             ];
                
				if (mfgrParent != null && !mfgrParent.isEmpty())
				{
					lmas = [
					        select id, name
					        from account
					        where id IN(
					                    select account__c
					                    from business_site__c
					                    where franchise__c = :franchise
					                    and status__c = 'A'
					                    and account__r.parent.id = :mfgrParent[0].account__r.id
					                    and account__r.site_type__r.name = 'Local Marketing'
					                   )
					        //2015-12-08 smitha.simhadri@cdk.com Updated RQ-05897 Alphabetize LMA drop down field
					        order by name
					       ];
				  }
			}
			else
			{
				lmas = null;
			}
			return lmas;

		}
		set;
	}

	public void getlmaoptions()
	{ //Fetch all LMA Accounts of OEM/Record Type Selected
        try{
            String currLMAAcct;
            LMAAccts = new List<SelectOption> ();
            LMAAccts.add(new SelectOption('', '---Select One---'));
            
            if (selectedRecType != 'null' && lmas != null)
            {
                for (account lmaOne : lmas)
                {
                    LMAAccts.add(new SelectOption(lmaOne.name, lmaOne.name));
                }
            }
            
            //Fetch all models of OEM/Record Type selected
            LMAModels = new List<selectOption> ();
            LMAModels.add(new selectOption('', '--Select One--'));
            
            Set<String> modelNames = new Set<String> ();
            
            for (CB_LMA_RFP_Models__c model : CB_LMA_RFP_Models__c.getAll().values())
            {
                if (selectedRecType == model.manufacturer__c)
                {
                    modelNames.add(model.name);                   
                }
                
            }
            
            for (String modelNamesOne : modelNames)
            {
                LMAModels.add(new selectOption(modelNamesOne, modelNamesOne));
            }
        }
        catch(Exception exp)
        {
            ALL_UtilitiesMiscellaneous.logException(exp);
        }
	}
    
    public PageReference Save()
    {
        try
        {
            ID RecordTypeId = selectedRecType != null ? ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('LMA_RFP__c', selectedRecType) : null;
            
            rfp.RecordTypeId = RecordTypeId;
            
            
            list<Account>accList = [
                select id
                from account
                where name = :selectedLMA
                LIMIT 1
            ];
            
            
            id selLMAAcct = !accList.isEmpty() ? accList.get(0).id : null;
            
            rfp.LMA__c = selLMAAcct;
            
            rfp.Model_1__c = selectedModelOne;
            rfp.Model_2__c = selectedModelTwo;
            rfp.Model_3__c = selectedModelThree;
            rfp.Model_4__c = selectedModelFour;
            
            rfp.status__c = 'Created';
                      
            Database.saveResult result = database.insert(rfp);            
            
            if(!result.isSuccess())
            {
                for(Database.Error dr: result.getErrors())
                {
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, dr.getMessage());
                    ApexPages.addMessage(myMsg); system.debug(dr.getMessage());                    
                }
            }            
            
            PageReference PageRef = new PageReference('/apex/CB_LMARFPCreate?id=' + rfp.id);
            PageRef.setredirect(true);
            
            return PageRef;
        }
        Catch(Exception Exp)
        {
            ApexPages.addMessages(Exp);
        }
        return null;        
    }
}