SF Primes/src/objects/Clone_Profile_Access__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Clone Profile Access</label>
</CustomObject>

SF Primes/src/objects/Clone_Records_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>General settings for the Clone Anything app. Determines which objects can be cloned.</description>
    <label>Clone Records Settings</label>
</CustomObject>

sf_vishalhack/src/classes/DSCB_CloneAnythingPermissions.cls
public class DSCB_CloneAnythingPermissions 
{
    public map<Id, Profile> ProfileMap;
    public list<Profile> Profiles {get;set;}
    
    public map<String, Clone_Records_Settings__c> CloneSettings {get;set;}
    public map<String, Clone_Profile_Access__c> ProfileAccessSettings {get;set;}
    
    public DSCB_CloneAnythingPermissions()
    {
        ProfileMap = new map<Id, Profile>([Select Id, Name From Profile Order By Name]); 
        CloneSettings = Clone_Records_Settings__c.getAll();
        ProfileAccessSettings = Clone_Profile_Access__c.getAll().clone();
        
        if(ProfileMap != null && !ProfileMap.isEmpty())
        {
            Profiles = ProfileMap.values(); Profiles.sort();
            
            for(Id ProfileId : ProfileMap.keySet())
            {
                Profile CurrentProfile = ProfileMap.get(ProfileId);
                
                if(!ProfileAccessSettings.keySet().contains(ProfileId))
                {
                    ProfileAccessSettings.put(ProfileId, new Clone_Profile_Access__c(
                        Name=ProfileId,
                        Profile_Id__c=ProfileId, 
                        Profile_Name__c=CurrentProfile.Name
                    ));
                }
            }
        }
    }
    
    public void SavePermissions()
    {
        upsert ProfileAccessSettings.values();
    }
}