SF Primes/src/objects/CMF_Info__c.object
<CustomObject>
    <description>Core BU based identifier numbers</description>
    <fields>
        <fullName>Estimated_Install_Date__c</fullName>
        <label>Estimated Install Date</label>
        <type>Date</type>
    </fields>
    <label>CMF Info</label>
    <nameField>
        <label>CMF Info</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMF Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Laser_Artwork_Order__c.object
<CustomObject>
    <fields>
        <fullName>Client_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Forms_Order6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Install_Date__c</fullName>
        <label>Estimated Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Forms_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project # [Impact]</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roll_Call_Date__c</fullName>
        <label>Roll Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_CMF_Info__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship CMF Info</label>
        <referenceTo>CMF_Info__c</referenceTo>
        <relationshipName>R00N40000001m7zMEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Forms Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>Project_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHWEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-LAPALMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-PORTLAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-SOUTHEAST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Roll_Called__c</fullName>
        <label>Contract Roll Called</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go-Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjectsMgrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add-On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy / Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProject_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASP-US/Toronto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASP-US/Vancouver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_External_Reference__c.object
<CustomObject>
    <description>This object is used to store the Lookup relationships to external objects that are related to the Sub-Project like the Laser Artwork Order, NIS Mission etc.</description>
    <fields>
        <fullName>LAO_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the LAO Object</description>
        <label>FO ID</label>
        <referenceTo>Laser_Artwork_Order__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project (Pilot)</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject External Reference</label>
    <nameField>
        <displayFormat>SPER-{0000000}</displayFormat>
        <label>External Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject External References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA/src/classes/IMP_SubProjectOnFormsOrder_Test.cls
//2016-03-08- anirudh.singh@cdk.com- Created this test class for IMP_SubProjectOnFormsOrder_Extension as earlier, no test class was existing.
@isTest
public class IMP_SubProjectOnFormsOrder_Test
{
    @TestSetup
    private static void setupData()
    {
        Account accountRecord=IMP_TestFactory_Helper.buildAccount();
        insert accountRecord;
        
        Contact contactRecord=IMP_TestFactory_Helper.buildContact(accountRecord.Id);
        insert contactRecord;
        
        CMF_Info__c cmfInfoRecord=IMP_TestFactory_Helper.buildCMFInfo(accountRecord.Id);
        insert cmfInfoRecord;
        
        List<Laser_Artwork_Order__c> formsOrderList=new List<Laser_Artwork_Order__c>();
        Laser_Artwork_Order__c formsOrderRecordOne=IMP_TestFactory_Helper.buildLaserArtworkOrder(contactRecord.Id);
        formsOrderRecordOne.Ship_CMF_Info__c=cmfInfoRecord.Id;
        formsOrderList.add(formsOrderRecordOne);
        
        Laser_Artwork_Order__c formsOrderRecordTwo=IMP_TestFactory_Helper.buildLaserArtworkOrder(contactRecord.Id);
        formsOrderRecordTwo.Ship_CMF_Info__c=cmfInfoRecord.Id;
        formsOrderList.add(formsOrderRecordTwo);
        insert formsOrderList;
        
        Project__c projectRecord=IMP_TestFactory_Helper.buildProject(0);
        projectRecord.Project_Region__c='CANADA-EAST';
        insert projectRecord;
        
        SubProject__c subProjectRecord=IMP_TestFactory_Helper.buildSubProject(projectRecord.Id);
        subProjectRecord.SubProject_Region__c='CANADA-EAST';
        subProjectRecord.Confidential__c=false;
        subProjectRecord.Contract_Roll_Called__c=Null;
        insert subProjectRecord;
        
        SubProject_External_Reference__c subProjectExternalReferenceRecord=IMP_TestFactory_Helper.buildSubProjectExternalReference(formsOrderRecordOne.Id, 
                                                                                                                                   subProjectRecord.Id, 
                                                                                                                                   projectRecord.Id);
        insert subProjectExternalReferenceRecord;
    }
    
    private static testMethod void constructorTest()
    {
        Laser_Artwork_Order__c formsOrder=[
            SELECT ID, Go_Live_Date__c, Project_Manager__c, Subproject__c,Project_Type__c, 
            SubProject_Comments__c, Confidential__C, Client_Manager__c, Roll_Call_Date__c, 
            Impact_Project_Numbers__c, Estimated_Install_Date__c
            FROM Laser_Artwork_Order__c 
            LIMIT 1
        ];
        
        test.startTest();
        ApexPages.StandardController stdController=new ApexPages.StandardController(formsOrder);
        IMP_SubProjectOnFormsOrder_Extension formsOrderPage=new IMP_SubProjectOnFormsOrder_Extension(stdController);
        test.stopTest();
    }
    
    private static testMethod void fetchSubProjectDetailsTestOne()
    {
        Laser_Artwork_Order__c formsOrder=[
            SELECT ID, Go_Live_Date__c, Project_Manager__c, Subproject__c,Project_Type__c, 
            SubProject_Comments__c, Confidential__C, Client_Manager__c, Roll_Call_Date__c, 
            Impact_Project_Numbers__c, Estimated_Install_Date__c
            FROM Laser_Artwork_Order__c
            LIMIT 1
        ];
        
        test.startTest();
        ApexPages.StandardController stdController=new ApexPages.StandardController(formsOrder);
        IMP_SubProjectOnFormsOrder_Extension formsOrderPage=new IMP_SubProjectOnFormsOrder_Extension(stdController);
        
        formsOrderPage.fetchSubProjectDetails();
        System.assertNotEquals(Null, formsOrderPage.subProjectExternalReferenceRecord, 'Subproject External Reference Object Not Found');
        test.stopTest();
    }
    
    private static testMethod void fetchSubProjectDetailsTestTwo()
    {
        SubProject_External_Reference__c subProjectExternalReferenceRecord=[SELECT Id, LAO_ID__c FROM SubProject_External_Reference__c];
        
        Laser_Artwork_Order__c formsOrder=[
            SELECT Id 
            FROM Laser_Artwork_Order__c 
            WHERE Id!=:subProjectExternalReferenceRecord.LAO_ID__c 
            ORDER BY CreatedDate DESC 
            LIMIT 1
        ];
        
        test.startTest();
        ApexPages.StandardController stdController=new ApexPages.StandardController(formsOrder);
        IMP_SubProjectOnFormsOrder_Extension formsOrderPage=new IMP_SubProjectOnFormsOrder_Extension(stdController);
        
        formsOrderPage.fetchSubProjectDetails();
        System.assertEquals(Null, formsOrderPage.subProjectExternalReferenceRecord, 'Unexpected value for Subproject External Reference Object');
        test.stopTest();
    }
}