SF Primes/src/objects/CMF_Info__c.object
<CustomObject>
    <description>Core BU based identifier numbers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CMF Info</relationshipLabel>
        <relationshipName>R00N40000001leBEEAY</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMF Info</label>
    <nameField>
        <label>CMF Info</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMF Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Activity__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for an Activity associated with a Milestone.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Milestone__r.Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CDK_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CDK Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Activity Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Project_Milestone__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Project_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Tasks__c == 0, &apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>AI-{000000000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Milestone__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for a Milestone associated with a SubProject.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Site__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Milestone Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SubProject__c</field>
                <operation>equals</operation>
                <valueField>SubProjectSite__c.SubProject__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubProjectSite__c</referenceTo>
        <relationshipLabel>Project Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Activities__c == 0,&apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <displayFormat>MID-{000000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Project_Activity__r.Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CDK_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CDK Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Task Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Activity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project Activity</label>
        <referenceTo>Project_Activity__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Status_Not_Applicable__c = true,&apos;Not Applicable&apos;,
IF(!ISBLANK(Actual_End_Date__c),&apos;Complete&apos;,
IF(!ISBLANK(Actual_Start_Date__c) &amp;&amp; ISBLANK(Actual_End_Date__c),&apos;In Progress&apos;,
IF(!ISBLANK( CDK_Assignee__c ),&apos;Assigned&apos;,
IF(ISBLANK( CDK_Assignee__c ),&apos;Unassigned&apos;,
null
)))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <displayFormat>TI-{000000000}</displayFormat>
        <label>Project Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProjectSite__c.object
<CustomObject>
    <description>Junction object to allow associating multiple Sites (Accounts) with a SubProject.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SubProject Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProjectSite</label>
    <nameField>
        <displayFormat>SPS-{000000000}</displayFormat>
        <label>SubProjectSite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjectSites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/ALL_TreeGrid_Test.cls
/***********************************************************************************************
* RQ-04476  
* Author: Ragashalini.Koka@cdk.com
* Description: Test class for the ALL_TreeGridController_UIGrid
*
* History
* 2016-03-02   Ragashalini.Koka@cdk.com   modified test class using the IMP_TestFactory_Helper
* 2016-04-14   Ragashalini.Koka@cdk.com   added sortfieldset values in testSetup
* 2016-12-05   venkata.shrivol@cdk.com	  commented project object reference RQ-08305
* 2016-12-06   venkata.shrivol@cdk.com    temporarily commented the whole class
* 2016-12-07   ragashalini.koka@cdk.com   changed the SOQL queries using the Project reference
* *********************************************************************************************** */

@isTest
private class ALL_TreeGrid_Test {
    
   /* @testSetup static void setupTestData() {
        
        /*Project__c project = IMP_TestFactory_Helper.buildProject(1);
       
        insert project;*/
        
     /*   SubProject__c subProject =  IMP_TestFactory_Helper.buildSubProject();
        insert subProject;
        
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        CMF_Info__c cmfInfo = new CMF_Info__c();
        cmfInfo.Name = 'A Test CMF Info';
        cmfInfo.Account__c = acc.Id;
        cmfInfo.Status__c = 'A';
        insert cmfInfo;
        
        SubProjectSite__c subprojectSite = IMP_TestFactory_Helper.buildSubProjectSite(acc.Id, subProject.Id, cmfInfo.Id);
        subprojectSite.CMF_Numbers__c = '1234567';
        insert subprojectSite;
        List<Project_Milestone__c> milestoneList = new List<Project_Milestone__c>();
        for(Integer i=0; i<3; i++) {
            Project_Milestone__c milestone = IMP_TestFactory_Helper.buildMilestoneNonStandard(subProject.Id, 'Test Milestone Description '+i);
            milestoneList.add(milestone);
        }
        insert milestoneList;
        
        List<Project_Activity__c> activityList=new List<Project_Activity__c>();
        
        for(Project_Milestone__c ms: milestoneList) {
            Project_Activity__c activity = IMP_TestFactory_Helper.buildProjectActivity(ms.Id);
            activity.CDK_Assignee__c = UserInfo.getUserId();
            activityList.add(activity);
        }
        
        insert activityList;
        
        List<Project_Task__c> taskList=new List<Project_Task__c>();
        for(Project_Activity__c pa: activityList) {
           Project_Task__c task = IMP_TestFactory_Helper.buildProjectTask(pa.Id);
           taskList.add(task);
        }
        insert taskList;
        
        
        List<String> treeGridNameList = new List<String>{'Test-001','Test-002','Test-003'};
        List<String> treeGridObjectChildRelationshipNameList = new List<String>{'Project_Milestones__r','Project_Activities__r','Project_Tasks__r'};
        List<String> treeGridObjectParentAPINameList = new List<String>{'SubProject__c','Milestone__c','Project_Activity__c'};            
        List<String> treeGridObjectParentRelationshipNameList = new List<String>{'SubProject__r','Milestone__r','Project_Activity__r'};            
        String treeGridObjectTreeGridIdentifier= 'TEST';                
        List<String> treeGridObjectAPINameList = new List<String>{'Project_Milestone__c','Project_Activity__c','Project_Task__c'};            
        List<String> treeGridObjectDisplayNameList = new List<String>{'Project Milestone','Project Activity','Project Task'};            
        List<String> treeGridObjectParentNameList = new List<String>{null,'Project_Milestone__c','Project_Activity__c'};            
                    
        List<ALL_Treegrid_Object__c> treeGridObjectList  = new List<ALL_Treegrid_Object__c>();
        
        for(Integer i = 0; i < 3; i++) {
            ALL_Treegrid_Object__c treeGridObject = new ALL_Treegrid_Object__c();
            treeGridObject.Name = treeGridNameList[i];
            treeGridObject.ChildRelationshipName__c = treeGridObjectChildRelationshipNameList[i];
            treeGridObject.ParentAPIName__c = treeGridObjectParentAPINameList[i];
            treeGridObject.ParentRelationshipName__c = treeGridObjectParentRelationshipNameList[i];
            treeGridObject.TreegridIdentifier__c = treeGridObjectTreeGridIdentifier;
            treeGridObject.ObjectAPIName__c = treeGridObjectAPINameList[i];
            treeGridObject.DisplayName__c = treeGridObjectDisplayNameList[i];
            treeGridObject.ParentName__c = treeGridObjectParentNameList[i];
            treeGridObjectList.add(treeGridObject);
        }
        insert treeGridObjectList;
        
        List<ALL_TreeGrid_Field__c> treeGridFieldList  = new List<ALL_TreeGrid_Field__c>();
        List<String> fieldSetNamesList = new List<String>{'Milestone_UI_Grid','Activity_UI_Grid','Task_UI_Grid'};
        List<String> sortFieldsetList = new List<String>{'Milestone_Sort_Commons','Activity_Sort_Commons','Task_Sort_Commons'};    
            for(Integer i = 0; i < 3 ;i++) {
                ALL_TreeGrid_Field__c treeGridField = new ALL_TreeGrid_Field__c();
                treeGridField.Name = treeGridNameList[i];
                treeGridField.TreegridIdentifier__c = treeGridObjectTreeGridIdentifier;
                treeGridField.ObjectAPIName__c = treeGridObjectAPINameList[i];
                treeGridField.FieldSetName__c = fieldSetNamesList[i];
                treeGridField.Sort_Fieldset__c = sortFieldsetList[i];
                treeGridFieldList.add(treeGridField);
            }
        
        insert treeGridFieldList;
        
    }  
    
    static testmethod void validateInitialization() {
        
        Test.setCurrentPageReference(new PageReference('Page.ALL_TreeGrid'));
        
        String objectName = 'Project_Milestone__c';
        String treeGridIdentifier = 'TEST';
        SubProject__c subproject = [
            SELECT Id,  Project__r.Name
            FROM SubProject__c 
            LIMIT 1
        ];
        System.currentPageReference().getParameters().put('object',objectName);
        System.currentPageReference().getParameters().put('id',subProject.Id);
        System.currentPageReference().getParameters().put('treeId',treeGridIdentifier);
        
        
        ALL_TreeGridController_UIGrid treeGridObj = new ALL_TreeGridController_UIGrid(new ALL_AngularInputFields_Controller());
        
        
    }
    
    
    
    static testmethod void validateGetObjectName() {
        List<Project_Milestone__c> milestoneList = [
            SELECT Id 
            FROM Project_Milestone__c
            WHERE Description__c LIKE '%Test Milestone Description%'
            LIMIT 1
        ];
        test.startTest();
        if(milestoneList.size() > 0) {
            String actualObjectName = ALL_TreeGridController_UIGrid.getObjectName(new List<String>{String.valueOf(milestoneList[0].Id)});
            String expectedObjectName = milestoneList[0].Id.getSObjectType().getDescribe().getName();
            System.assertEquals(expectedObjectName, actualObjectName);
        }
        test.stopTest();
        
    }
    
    static testmethod void validateUpdateInsertRecords() {
        
        List<Project_Milestone__c> milestoneUpdateList = [
            SELECT Id,Description__c
            FROM Project_Milestone__c
            WHERE Description__c 
            LIKE '%Test Milestone Description%'
            LIMIT 2
        ];
        test.startTest();
        if(milestoneUpdateList.size() > 1) {
            String updatedDescription =  'Updated' + milestoneUpdateList[0].Description__c ;
            milestoneUpdateList[0].Description__c = updatedDescription;
            milestoneUpdateList[1].Description__c = '';
            
           SubProject__c subproject = [
            SELECT Id,  Project__r.Name
            FROM SubProject__c 
            LIMIT 1
        ];
            
            
            List<Project_Milestone__c> milestoneInsertList = new List<Project_Milestone__c>();
            Project_Milestone__c milestone1 = new Project_Milestone__c();
            Project_Milestone__c milestone2 = new Project_Milestone__c();
            milestone1.Description__c = 'Inserted Test Milestone Description';
            milestone1.SubProject__c=subProject.Id;
            
            milestoneInsertList.add(milestone1);
            milestoneInsertList.add(milestone2);
            
            ALL_TreeGridController_UIGrid.updateInsertRecords(JSON.serialize(milestoneUpdateList),JSON.serialize(milestoneInsertList));
            List<Id> milestoneUpdateIdList = new List<Id>{milestoneUpdateList[0].Id,milestoneUpdateList[1].Id};
                milestoneUpdateList = [
                    SELECT Id,Description__c
                    FROM Project_Milestone__c
                    WHERE Id IN : milestoneUpdateIdList
                    
                ];
            
            milestoneInsertList = [
                SELECT Id,Description__c 
                FROM Project_Milestone__c
                WHERE Description__c LIKE '%Inserted Test Milestone Description%'
            ];
            
            
            System.assertEquals(updatedDescription, milestoneUpdateList[0].Description__c);
            System.assertEquals(1,milestoneInsertList.size());
            test.stopTest();
            
        } 
        ALL_TreeGridController_UIGrid.updateInsertRecords('','');
    }
    
 /*   static testmethod void validateMassUpdateFields() {
        String objectName = 'Project_Milestone__c';
        String treeGridIdentifier = 'TEST';
        test.startTest();
        Map<String,ALL_TreeGridObject.ALL_TreeGridFields> fieldMap = ALL_TreeGridController_UIGrid.massUpdateFields(objectName,treeGridIdentifier);
        System.assert(fieldMap.size() > 0);
        test.stopTest();
    }*/
    
   /* static testmethod void validateDeleteRecords() {
        
        List<Project_Milestone__c> milestoneList = [
            SELECT Id 
            FROM Project_Milestone__c
            WHERE Description__c LIKE '%Test Milestone Description%'
            LIMIT 1
        ];
        
        SubProject__c subproject = [
            SELECT Id,  Project__r.Name
            FROM SubProject__c 
            LIMIT 1
        ];
        
        
        List<Project_Milestone__c> milestoneInsertList = new List<Project_Milestone__c>();
        Project_Milestone__c milestone1 = new Project_Milestone__c();
        milestone1.Description__c = 'Deleting Test Milestone Description';
        milestone1.SubProject__c=subProject.Id;
        milestoneInsertList.add(milestone1);
        insert milestoneInsertList;
        delete milestoneInsertList;
        List<Id> milestoneDeleteIdList = new List<Id>();
        if(milestoneList.size() > 0) {
            
            milestoneDeleteIdList.add(milestoneList[0].Id);
        }
        milestoneDeleteIdList.add(milestone1.Id);
        
        Test.startTest();
        ALL_TreeGridController_UIGrid.deleteRecords(milestoneDeleteIdList);
        milestoneDeleteIdList.clear();
        
        Test.stopTest(); 
    }
    //2016-06-30 ragashalini.koka@cdk.com commented as the function no longer exists in the class
   /* static testmethod void validateSearchRecords() {
        String objectName = 'Project_Activity__c';
        String treeGridIdentifier = 'TEST';
        String searchTxt = 'Test';
        
        Map<Id,Project_Milestone__c> milestoneMap = new Map<Id,Project_Milestone__c>([
            SELECT Id 
            From Project_Milestone__c
            WHERE Description__c LIKE '%Test Milestone Description%'
        ]);
        
        test.startTest();
        ALL_TreeGridController_UIGrid.searchRecords(searchTxt,new List<Id>(milestoneMap.keySet()), objectName, treeGridIdentifier);
        ALL_TreeGridController_UIGrid.searchRecords('koka',new List<Id>(milestoneMap.keySet()), objectName, treeGridIdentifier);
        objectName = 'Project_Milestone__c';
        ALL_TreeGridController_UIGrid.searchRecords(searchTxt,new List<Id>(milestoneMap.keySet()), objectName, treeGridIdentifier);
        objectName = 'Project Activity';
        ALL_TreeGridController_UIGrid.searchRecords(searchTxt,new List<Id>(milestoneMap.keySet()), objectName, treeGridIdentifier);
        test.stopTest();
        
        
    }*/
    
  /*  static testMethod void validateGetRecordsOfAllLevels() {
        
        String treeGridIdentifier = 'TEST';
        
       SubProject__c subproject = [
            SELECT Id,  Project__r.Name
            FROM SubProject__c 
            LIMIT 1
        ];
        
        test.startTest();
        
        ALL_TreeGridController_UIGrid.getRecordsOfAllLevels(treeGridIdentifier,subproject.id);
        ALL_TreeGridController_UIGrid.getRecordsOfAllLevels(treeGridIdentifier,'abc');
        test.stopTest();
        
        
    }
    
    static testmethod void validateGetLevelOneIds() {
          String treeGridIdentifier = 'TEST';
        
        SubProject__c subproject = [
            SELECT Id,  Project__r.Name
            FROM SubProject__c 
            LIMIT 1
        ];
        
        test.startTest();
        
        ALL_TreeGridController_UIGrid.getLevelOneIds(subproject.id,'Project_Milestone__c', treeGridIdentifier);
       
        test.stopTest();
        
        
    }
    
    static testmethod void validateGetFieldValueForHierarchy() {
         String treeGridIdentifier = 'TEST';
        
       SubProject__c subproject = [
            SELECT Id,  Project__r.Name
            FROM SubProject__c 
            LIMIT 1
        ];
        
        test.startTest();
        
        ALL_TreeGridController_UIGrid.getFieldValueForHierarchy(subproject,'Project__r.Name');
       
        test.stopTest();
    }
    
    static testmethod void validateAddNewContact() {
         String treeGridIdentifier = 'TEST';
        
        SubProject__c subproject = [
            SELECT Id,  Project__r.Name
            FROM SubProject__c 
            LIMIT 1
        ];
        
        test.startTest();
        
        ALL_TreeGridController_UIGrid.addNewContact('{"firstName":"test","lastName":"tetst","email":"","phone":"","accId":"0018A000001nHI2QAM","ctctRole":"Account Executive","projectRole":"Business Operations Advocate","subprojectId":"a428A000000N9crQAC"}');
       
        test.stopTest();
        
    }
    static testmethod void validateGetSiteValues() {
            String treeGridIdentifier = 'TEST';
        
        SubProject__c subproject = [
            SELECT Id,  Project__r.Name
            FROM SubProject__c 
            LIMIT 1
        ];
        
        test.startTest();
        
        ALL_TreeGridController_UIGrid.getSiteValues(subproject.Id);
        test.stopTest();
        
    }
   */ 
}