SF Primes/src/objects/CMF_Info__c.object
<CustomObject>
    <description>Core BU based identifier numbers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CMF Info</relationshipLabel>
        <relationshipName>R00N40000001leBEEAY</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_CMF__c</fullName>
        <externalId>true</externalId>
        <label>Ship CMF</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CMF Info</label>
    <nameField>
        <label>CMF Info</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMF Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Docusign/src/classes/DS_CMFNumberLookup_Test.cls
@IsTest(seeAllData=True)
public class DS_CMFNumberLookup_Test 
{
	public static testmethod void TestCMFNumberChanges() 
	{
		mpm3__Milestone1_Project__c p = new mpm3__Milestone1_Project__c(Name='Test Project T001');
		insert p;
		
		Account a = new Account(Name='Test Account T001');
		insert a;
		
		String TempCMFNumber = String.valueOf(DateTime.now().millisecond()*1234);
		
		CMF_Info__c cmf = new CMF_Info__c(Name='Test CMF Info T001', Account__c=a.Id, Ship_CMF__c=TempCMFNumber);
		insert cmf;
		
		p.CMF_Number__c = TempCMFNumber;
		update p;
		
		p.CMF_Number__c = 'ABCDEFGH'; // invalid number
		update p;
	}
}