SF Primes/src/objects/CustomSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Centralized list of parameters to be modified when refreshing Training or FullDev sandboxes</description>
    <fields>
        <fullName>CDK_Global_Account_Id__c</fullName>
        <description>Ignore Contact Duplicate Checking for this Account Id. Also, this Account Id is used to set the HR Default Case Account.</description>
        <inlineHelpText>Ignore Contact Duplicate Checking for this Account Id. Also, this Account Id is used to set the HR Default Case Account.</inlineHelpText>
        <label>CDK Global Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CustomSettings</label>
</CustomObject>

SF Primes/src/objects/Sandbox_Refresh_Update_Email_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting holds field api names and object  api names to update email Id with sandbox name .</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>field API Name</description>
        <inlineHelpText>field API Name</inlineHelpText>
        <label>Field API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>API name of the object</description>
        <inlineHelpText>API name of the object</inlineHelpText>
        <label>Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sandbox Refresh Update Email ID</label>
</CustomObject>

SF Primes/src/objects/Sandbox_Refresh_Update_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold field API name, Object API Name and Update value.</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>API name of the field</description>
        <inlineHelpText>API name of the field</inlineHelpText>
        <label>Field API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>API name of the object</description>
        <inlineHelpText>API name of the object</inlineHelpText>
        <label>Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value that needs to be update in the field. Leave it blank for updating the fields to null values.</description>
        <inlineHelpText>Value that needs to be update in the field .Leave it blank to update the fields to null values.</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sandbox Refresh Update Fields</label>
</CustomObject>

QA/src/classes/ALL_SandboxRefresh_Controller.cls
global class ALL_SandboxRefresh_Controller {
   
    global static List<ALL_ChainedJob> jobs = new List<ALL_ChainedJob>();
    global static boolean runAllTasks=false;
    global Static boolean runUpdateEmailIdBatch=false;
    global static boolean runUpdateFieldsBatch=false;
    global static boolean runDeleteHRCases=false;
    
    global static void execute()
    {
        if(runAllTasks)
        {
            updateEmailIdBatch();
            updateFieldsBatch();
            deleteHRCases();
        }
        else if(runUpdateEmailIdBatch)
        {
            updateEmailIdBatch();
        }
        else if(runUpdateFieldsBatch)
        {
            updateFieldsBatch(); 
        }
        else if(runDeleteHRCases)
        {
            deleteHRCases();
        }
        if(jobs.size()!=0)
        {
            ALL_ChainedJob.executeAsChain(jobs);
        }
       
    }
    
    private static void updateEmailIdBatch()
    {
            List<Sandbox_Refresh_Update_Email_ID__c> csList = Sandbox_Refresh_Update_Email_ID__c.getAll().values();
            
            for(Sandbox_Refresh_Update_Email_ID__c csObj : csList)
            {
                String query = 'SELECT ' + csObj.Field_Name__c +' FROM '+csObj.Object_Name__c;
                //Id batchInstanceId =  Database.executeBatch(new ALL_Update_Email_ID_Batch(query,csObj.Field_Name__c, csObj.Object_Name__c),20);
                jobs.add(new ALL_ChainedJob(new ALL_Update_Email_ID_Batch(query,csObj.Field_Name__c, csObj.Object_Name__c),1,'Updating Email ID'));
            }
    }
    private static void updateFieldsBatch()
    {
        List<Sandbox_Refresh_Update_Fields__c> csList = Sandbox_Refresh_Update_Fields__c.getAll().values();
        for(Sandbox_Refresh_Update_Fields__c csObj : csList)
        {
            String query = 'SELECT ' + csObj.Field_Name__c +' FROM '+csObj.Object_Name__c;
            //Id batchInstanceId =  Database.executeBatch(new ALL_Update_Fields_Batch(query,csObj.Field_Name__c, csObj.Object_Name__c,csObj.value__c),20);
            jobs.add(new ALL_ChainedJob(new ALL_Update_Fields_Batch(query,csObj.Field_Name__c, csObj.Object_Name__c,csObj.value__c),1,'Updating Fields'));
        }
    }
    private static void deleteHRCases()
    {
        try
        {
            CustomSettings__c settings = CustomSettings__c.getInstance();
            Id cdkGlobalAccount  =  settings.CDK_Global_Account_Id__c;
            List<Case> casesList = [
                select id 
                from Case 
                where recordType.Name like '%HR%' 
                and recordType.sObjectType='Case' 
                and AccountId=:cdkGlobalAccount 
                limit 10000
            ];
            if(casesList.size()!=0)
            {
                delete casesList;
            }
        }
        catch(Exception e)
        {
            ALL_UtilitiesMiscellaneous.showDebug = true;
            ALL_UtilitiesMiscellaneous.debug(e.getMessage());
        }
    }
}