SF Primes/src/objects/Deal_State__c.object
<CustomObject>
    <description>Deal Related information. BDC Communication Project</description>
    <fields>
        <fullName>CA_Approved_Date__c</fullName>
        <inlineHelpText>Central Time Zone (CST)</inlineHelpText>
        <label>CA Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal State</relationshipLabel>
        <relationshipName>Deal_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roll_Call_Date__c</fullName>
        <label>Roll Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SQT_Deal_ID__c</fullName>
        <label>SQT Deal ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Deal State</label>
    <nameField>
        <displayFormat>DS - {000000}</displayFormat>
        <label>Deal State ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Opportunity_Quotes__c.object
<CustomObject>
    <description>Link to SQT deals for a given opportunity</description>
    <fields>
        <fullName>Deal_ID__c</fullName>
        <externalId>true</externalId>
        <label>Deal ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Quotes</relationshipLabel>
        <relationshipName>Opportunity_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SQT_Deal_ID__c</fullName>
        <label>SQT Deal ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Quotes</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Contract_Roll_Called__c</fullName>
        <label>Contract Roll Called</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Id__c</fullName>
        <label>Deal Id</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA/src/classes/IMP_UpdateDealStateRollCallDate_Test.cls
//2016-03-03- anirudh.singh@cdk.com- Created this class for Request RQ-06018 Update Trigger on SubProject and SubProjectOpp so they follow current dev stds.
//                                   This is the test class for IMP_UpdateDealStateRollCallDate_Handler class.
@isTest
public class IMP_UpdateDealStateRollCallDate_Test
{
    @TestSetup
    private static void setupData()
    {
        Account accountRecord=IMP_TestFactory_Helper.buildAccount();   
        insert accountRecord;
        
        Opportunity opportunityRecord=IMP_TestFactory_Helper.buildOpportunity();
        opportunityRecord.AccountId=accountRecord.Id;
        insert opportunityRecord; 
        
        Opportunity_Quotes__c opportunityQuoteRecord=IMP_TestFactory_Helper.buildOpportunityQuotes(accountRecord.Id, opportunityRecord.Id);
        opportunityQuoteRecord.Deal_Id__c='12345';
        insert opportunityQuoteRecord;
        
        Deal_State__c dealStateRecord=new Deal_State__c();
        dealStateRecord.SQT_Deal_Id__c='12345';
        dealStateRecord.Opportunity__c=opportunityRecord.Id;
        dealStateRecord.CA_Approved_Date__c=datetime.now();
        insert dealStateRecord;
        
        Project__c projectRecord=IMP_TestFactory_Helper.buildProject(0);
        insert projectRecord;
        
        SubProject__c subProjectRecord=IMP_TestFactory_Helper.buildSubProject(projectRecord.Id);
        subProjectRecord.Deal_Id__c='12345';
        subProjectRecord.Project__c=projectRecord.Id;
        subProjectRecord.Contract_Roll_Called__c=date.newinstance(2016, 03, 14);
        insert subProjectRecord;
    }
    
    private static testMethod void updateRollCallDateTestOne()
    {
        SubProject__c subProjectRecord=[SELECT Id, Deal_Id__c, Project__c, Contract_Roll_Called__c FROM SubProject__c];
        Deal_State__c dealStateRecord=[SELECT Id, Roll_Call_Date__c FROM Deal_State__c];
        
        Map<String, Date> dealIdAndContractRollCalledMap=new Map<String, Date>();
        
        test.startTest();
        dealIdAndContractRollCalledMap.put(subProjectRecord.Deal_Id__c, date.newinstance(2016, 03, 16));
        IMP_UpdateDealStateRollCallDate_Handler.updateRollCallDate(dealIdAndContractRollCalledMap);
        
        Deal_State__c updatedDealStateRecord=[SELECT Id, Roll_Call_Date__c FROM Deal_State__c];
        system.assertNotEquals(dealStateRecord.Roll_Call_Date__c, updatedDealStateRecord.Roll_Call_Date__c, 'Roll Call Date Updated.');
        system.assertEquals(date.newinstance(2016, 03, 16), updatedDealStateRecord.Roll_Call_Date__c, 'Roll Call Date Updated.');
        test.stopTest();
    }
    
    private static testMethod void updateRollCallDateTestTwo()
    {
        Deal_State__c dealStateRecord=[SELECT Id FROM Deal_State__c];
        delete dealStateRecord;
        
        Opportunity_Quotes__c opportunityQuoteRecord=[SELECT Id FROM Opportunity_Quotes__c];
        delete opportunityQuoteRecord;
        
        test.startTest();
        IMP_UpdateDealStateRollCallDate_Handler.updateRollCallDate(Null);
        test.stopTest();
    }
}