SF Primes/src/objects/Deal_State__c.object
<CustomObject>
    <description>Deal Related information. BDC Communication Project</description>
    <fields>
        <fullName>Deal_State_Secured_Id__c</fullName>
        <label>Deal State Secured Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Deal State</label>
    <nameField>
        <displayFormat>DS - {000000}</displayFormat>
        <label>Deal State ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Deal_State_Secured__c.object
<CustomObject>
    <description>Any Internal Docs asscoiated to Deal State</description>
    <fields>
        <fullName>Deal_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal State</label>
        <referenceTo>Deal_State__c</referenceTo>
        <relationshipName>Deal_State_Secured_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal State-Secured</label>
    <nameField>
        <displayFormat>DSS - {000000}</displayFormat>
        <label>Deal State Secured ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State-Secured</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DS_DealStateSecured_Handler.cls
//2016-01-22- anirudh.singh@cdk.com- Created this Handler class for the Trigger DS_DealStateSecured to bring it up to Standards for Request RQ-06022.
public class DS_DealStateSecured_Handler
{
    public static void preventMultipleRecsOnParent(List<Deal_State_Secured__c> newdealStateSecuredList)
    {
        String pageErrorMessage='Only one Deal State Secured document may be added per Deal State';
        
        ALL_UtilitiesMiscellaneous.PreventMultipleOnParent(newdealStateSecuredList, 'Deal_State__c', 
                                                           'Deal_State__c', 'Deal_State_Secured_Docs__r', 
                                                           pageErrorMessage);
    }
    
    public static void updateDealStateRecords(List<Deal_State_Secured__c> newdealStateSecuredList)
    {
    	boolean bool = ALL_CheckRecursive.runCodeBlockOnce('updateDealStateRecords');
    	
        if(bool)
        {
            List<Deal_State__c> dealStatesToUpdate=new List<Deal_State__c>();   
            
            for(Deal_State_Secured__c dss: newdealStateSecuredList)
            {
                Deal_State__c currentDealState=new Deal_State__c(
                    Id=dss.Deal_State__c, 
                    Deal_State_Secured_Id__c=(String)dss.Id
                );
                dealStatesToUpdate.add(currentDealState);
            }
            
            if(!dealStatesToUpdate.isEmpty())
            {
                database.update(dealStatesToUpdate);
            }
        }
    }
}