SF Primes/src/objects/Deal_State__c.object
<CustomObject>
    <description>Deal Related information. BDC Communication Project</description>
    <fields>
        <fullName>Deal_Status__c</fullName>
        <label>Deal Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Deal Arrived</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rep Created SQT Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned - SCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Networking Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Networking Quote Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending SOW Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW Deal Change Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released To Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Sales Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval in SQT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed by All Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Deal Change Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send To CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send To Countersign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send To CRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Envelope Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent To Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent To Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description_of_Need__c</fullName>
        <label>Description of Item(s) Needed</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal State</relationshipLabel>
        <relationshipName>Deal_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal State</label>
    <nameField>
        <displayFormat>DS - {000000}</displayFormat>
        <label>Deal State ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA/src/classes/DS_OpportunityDealChange_Test.cls
@IsTest
public class DS_OpportunityDealChange_Test 
{
    public static testmethod void Test()
    {
        // test without existing deal state
        Opportunity opp1 = DS_TestObjects.NewOpportunity_Inserted();
        ApexPages.StandardController oppSC = new ApexPages.StandardController(opp1); // instantiate new standard controller
        DS_OpportunityDealChange_Extension OpportunityDealChangeExtension = new DS_OpportunityDealChange_Extension(oppSC);
        OpportunityDealChangeExtension.SaveDealChange();
        
        // test with existing deal state
        Opportunity opp2 = DS_TestObjects.NewOpportunity_Inserted();
        
        Deal_State__c DealState = new Deal_State__c();
        DealState.Opportunity__c = opp2.Id;
        DealState.Deal_Status__c = 'New Deal Arrived';
        DealState.Description_of_Need__c = 'Requested Changes from Opportunity Page';
        insert DealState;
        
        OpportunityDealChangeExtension.CurrentOpportunity = opp2;
        OpportunityDealChangeExtension.initialize();
        OpportunityDealChangeExtension.SaveDealChange();
        
        // test error case
        OpportunityDealChangeExtension.DealState = null;
        OpportunityDealChangeExtension.DealStateExists = false;
        OpportunityDealChangeExtension.SaveDealChange();
    }
}