SF Primes/src/objects/Deal_State__c.object
<CustomObject>
    <description>Deal Related information. BDC Communication Project</description>
    <fields>
        <fullName>CA_Approved_Date__c</fullName>
        <inlineHelpText>Central Time Zone (CST)</inlineHelpText>
        <label>CA Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal State</relationshipLabel>
        <relationshipName>Deal_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roll_Call_Date__c</fullName>
        <label>Roll Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SQT_Deal_ID__c</fullName>
        <label>SQT Deal ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Deal State</label>
    <nameField>
        <displayFormat>DS - {000000}</displayFormat>
        <label>Deal State ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Opportunity_Quotes__c.object
<CustomObject>
    <description>Link to SQT deals for a given opportunity</description>
    <fields>
        <fullName>Deal_ID__c</fullName>
        <externalId>true</externalId>
        <label>Deal ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Quotes</relationshipLabel>
        <relationshipName>Opportunity_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SQT_Deal_ID__c</fullName>
        <label>SQT Deal ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Quotes</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Log__c.object
<CustomObject>
    <description>Contains various types of Project Log including Action Items, Change Requests, Issues, Lessons Learned and Risks to associate with either a Project or SubProject.</description>
    <fields>
        <fullName>Lookup_Field_API_Name_to_Subproject__c</fullName>
        <formula>IF(NOT(ISBLANK(Sub_Project_Action_Items__c)) , &quot;Action_Items__c&quot;, 
  IF(NOT(ISBLANK(Sub_Project_Change_Request__c)) , &quot;Change_Request__c&quot;, 
    IF(NOT(ISBLANK(Sub_Project_Issue__c)) , &quot;Issue__c&quot;, 
      IF(NOT(ISBLANK(Sub_Project_Lessons_Learned__c)) , &quot;Lessons_Learned__c&quot;, 
        IF(NOT(ISBLANK(Sub_Project_Risk__c)) , &quot;Risk__c&quot;, 
          &quot;UNDEFINED&quot;
        )
      )
    )
  )
)</formula>
        <label>Lookup Field API Name to Subproject</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <formula>AI_Project_Manager__c &amp; &quot; &quot; &amp; Issue_Project_Manager__c &amp; &quot; &quot; &amp;  CR_Project_Manager__c</formula>
        <label>Project Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Retrieves Project Name based on Record Type.</description>
        <formula>CASE( Record_Type_Name__c , 
&quot;Action Item&quot;, Project_Action_Items__r.Name , 
&quot;Change Request&quot;, Project_Change_Request__r.Name ,
&quot;Issue&quot;, Project_Issue__r.Name ,
&quot;Lesson Learned&quot;, Project_Lessons_Learned__r.Name ,
&quot;Risk&quot;, Project_Risk__r.Name ,
&quot;&quot;)</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject_Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Confidential check box from parent Subproject which is populated from trigger</description>
        <label>SubProject Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <description>Retrieves SubProject Name based on Record Type</description>
        <formula>CASE( Record_Type_Name__c ,
&quot;Action Item&quot;,  Sub_Project_Action_Items__r.SubProject_Name__c ,
&quot;Change Request&quot;,  Sub_Project_Change_Request__r.SubProject_Name__c ,
&quot;Issue&quot;,  Sub_Project_Issue__r.SubProject_Name__c ,
&quot;Lesson Learned&quot;,  Sub_Project_Lessons_Learned__r.SubProject_Name__c ,
&quot;Risk&quot;,  Sub_Project_Risk__r.SubProject_Name__c ,
&quot;&quot;)</formula>
        <label>SubProject</label>
        <type>Text</type>
    </fields>
    <label>Project Log</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Logs</pluralLabel>
    <recordTypes>
        <fullName>Issue</fullName>
        <active>true</active>
        <description>Log an Issue encountered with the Project.</description>
        <label>Issue</label>
    </recordTypes>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <description>Log a Risk encountered with the Project.</description>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Milestone__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for a Milestone associated with a SubProject.</description>
    <fields>
        <fullName>Confidential__c</fullName>
        <description>The confidentiality check value of the parent subProject</description>
        <formula>SubProject__r.Confidential__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <displayFormat>MID-{000000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Roll_Called__c</fullName>
        <label>Contract Roll Called</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Id__c</fullName>
        <label>Deal Id</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjectsMgrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProject_Status__c</fullName>
        <label>SubProject Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold No Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Training_Implementation_Client_Mgr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training &amp; Implementation Client Mgr</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_SubProject_Test.cls
//2016-02-25- anirudh.singh@cdk.com- Created this test class for the Handler class IMP_SubProject_Handler as per Request RQ-06018.
//2016-06-06- venkata.shrivol@cdk.com - Modified this test class to fit for the Sharing Subproject request: RQ-05471
//2016-12-05 - venkata.shrivol@cdk.com - commented the project object reference RQ-08305
@isTest
public class IMP_SubProject_Test
{
    @TestSetup
    private static void setupData()
    {
        Account accountRecord=IMP_TestFactory_Helper.buildAccount();   
        insert accountRecord;
        
        Opportunity opportunityRecord=IMP_TestFactory_Helper.buildOpportunity();
        opportunityRecord.AccountId=accountRecord.Id;
        insert opportunityRecord; 
        
        List<Opportunity_Quotes__c> oppQuotesList=new List<Opportunity_Quotes__c>();
        Opportunity_Quotes__c opportunityQuoteRecordOne=IMP_TestFactory_Helper.buildOpportunityQuotes(accountRecord.Id, opportunityRecord.Id);
        opportunityQuoteRecordOne.Deal_Id__c='12345';
        oppQuotesList.add(opportunityQuoteRecordOne);
        
        Opportunity_Quotes__c opportunityQuoteRecordTwo=IMP_TestFactory_Helper.buildOpportunityQuotes(accountRecord.Id, opportunityRecord.Id);
        opportunityQuoteRecordTwo.Deal_Id__c='35462';
        oppQuotesList.add(opportunityQuoteRecordTwo);
        insert oppQuotesList;
        
        List<Deal_State__c> dealStateList=new List<Deal_State__c>();
        Deal_State__c dealStateRecordOne=new Deal_State__c();
        dealStateRecordOne.SQT_Deal_Id__c='35462';
        dealStateRecordOne.Opportunity__c=opportunityRecord.Id;
        dealStateRecordOne.CA_Approved_Date__c=datetime.now();
        dealStateList.add(dealStateRecordOne);
        
        Deal_State__c dealStateRecordTwo=new Deal_State__c();
        dealStateRecordTwo.SQT_Deal_Id__c='12345';
        dealStateRecordTwo.Opportunity__c=opportunityRecord.Id;
        dealStateRecordTwo.CA_Approved_Date__c=datetime.now()+2;
        dealStateList.add(dealStateRecordTwo);
        insert dealStateList;
        
        /*Project__c projectRecord=IMP_TestFactory_Helper.buildProject(0);
        insert projectRecord;*/
        
        //2016-06-06- venkata.shrivol@cdk.com - added an extra subproject rec to be used in afterUpdate method RQ-05471
        list<SubProject__c> subprojectList = new list<SubProject__c>();
        SubProject__c subProjectRecord=IMP_TestFactory_Helper.buildSubProject();
        subProjectRecord.Confidentiality_Status__c='Confidential';
        subProjectRecord.Deal_Id__c='12345;35462';
        subProjectRecord.Contract_Roll_Called__c=date.newinstance(2016, 03, 14);
        SubProject__c subProjectRecord2=IMP_TestFactory_Helper.buildSubProject();
        subProjectRecord2.Confidentiality_Status__c='Restricted';
        subprojectList.add(subProjectRecord);
        subprojectList.add(subProjectRecord2);
        insert subprojectList;
        
        Project_Milestone__c milestoneRecord=IMP_TestFactory_Helper.buildMilestoneNonStandard(subProjectRecord.Id, 'Test Description');
        insert milestoneRecord;
        
        List<Project_Log__c> projectLogsList=new List<Project_Log__c>();
        Project_Log__c issue=IMP_TestFactory_Helper.buildIssueLog(subProjectRecord.Id);
        issue.SubProject_Confidential__c=true;
        projectLogsList.add(issue);
        
        Project_Log__c risk=IMP_TestFactory_Helper.buildRiskLog(subProjectRecord.Id);
        risk.SubProject_Confidential__c=true;
        projectLogsList.add(risk);
        
        Project_Log__c action=IMP_TestFactory_Helper.buildActionItemLog(subProjectRecord.Id);
        action.SubProject_Confidential__c=true;
        projectLogsList.add(action);
        
        Project_Log__c change=IMP_TestFactory_Helper.buildChangeRequestLog(subProjectRecord.Id);
        change.SubProject_Confidential__c=true;
        projectLogsList.add(change);
        
        Project_Log__c lesson=IMP_TestFactory_Helper.buildLessonLearnedLog(subProjectRecord.Id);
        lesson.SubProject_Confidential__c=true;
        projectLogsList.add(lesson);
        insert projectLogsList;
    }
    
    private static testMethod void processSubProjectsBeforeUpdateTest()
    {
        list<SubProject__c> subProjectRecordList=[
            SELECT Id, Project_Manager__c, SubProject_Status__c, Confidential__c,Confidentiality_Status__c, 
            Training_Implementation_Client_Mgr__c
            //, Project__c
            FROM SubProject__c
        ];
        
        SubProject__c subProjectRecord = subProjectRecordList.size() > 0 ? subProjectRecordList.get(0) : new SubProject__c();
        
        List<Project_Log__c> projectLogsList=[
            SELECT SubProject_Confidential__c, SubProject_Confidentiality_Status__c 
            FROM Project_Log__c 
            ORDER BY Lookup_Field_API_Name_to_Subproject__c
        ];
        
        Profile profileRecord=[SELECT Id, Name FROM Profile WHERE Name='ADPDS - Implementation - PM' LIMIT 1];
        User projectmanager = DS_TestObjects.NewUser();
        projectmanager.ProfileId = profileRecord.Id;
        insert projectmanager;
        
        test.startTest();
        Map<Id, SubProject__c> oldSubProjectsMap=new Map<Id, SubProject__c>();
        oldSubProjectsMap.put(subProjectRecord.Id, subProjectRecord);
        
        //Creating a new Project.
        /*Project__c projectRecordNew=IMP_TestFactory_Helper.buildProject(0);
        projectRecordNew.Project_Status__c='Closed';
        insert projectRecordNew;*/
        
        SubProject__c newSubProjectRecord=new SubProject__c();
        newSubProjectRecord=subProjectRecord.clone(true);
        newSubProjectRecord.Project_Manager__c=projectmanager.Id;
        newSubProjectRecord.SubProject_Status__c='Closed';
        newSubProjectRecord.Confidentiality_Status__c='Restricted';
        //newSubProjectRecord.Project__c=projectRecordNew.Id;
        
        Map<Id, SubProject__c> newSubProjectsMap=new Map<Id, SubProject__c>();
        newSubProjectsMap.put(newSubProjectRecord.Id, newSubProjectRecord);
        
        IMP_SubProject_Handler.processSubProjectsBeforeUpdate(newSubProjectsMap, oldSubProjectsMap);
        
        List<Project_Log__c> updatedProjectLogsList=[
            SELECT SubProject_Confidential__c, SubProject_Confidentiality_Status__c 
            FROM Project_Log__c 
            ORDER BY Lookup_Field_API_Name_to_Subproject__c
        ];
        
        //2016-06-06- venkata.shrivol@cdk.com - Commented the below assertions as they are being done by a picklist field now RQ-05471
      //  system.assertEquals(false, updatedProjectLogsList[0].SubProject_Confidential__c, 'SubProject_Confidential__c field value updated on Action Item');
        system.assertNotEquals(projectLogsList[0].SubProject_Confidentiality_Status__c, updatedProjectLogsList[0].SubProject_Confidentiality_Status__c, 'Action Item Updated');
        
       // system.assertEquals(false, updatedProjectLogsList[1].SubProject_Confidential__c, 'SubProject_Confidential__c field value updated on Change Request');
        system.assertNotEquals(projectLogsList[1].SubProject_Confidentiality_Status__c, updatedProjectLogsList[1].SubProject_Confidentiality_Status__c, 'Change Request Updated');
        
       // system.assertEquals(false, updatedProjectLogsList[2].SubProject_Confidential__c, 'SubProject_Confidential__c field value updated on Issue');
        system.assertNotEquals(projectLogsList[2].SubProject_Confidentiality_Status__c, updatedProjectLogsList[2].SubProject_Confidentiality_Status__c, 'Issue Updated');
        
       // system.assertEquals(false, updatedProjectLogsList[3].SubProject_Confidential__c, 'SubProject_Confidential__c field value updated on Lessons Learned');
        system.assertNotEquals(projectLogsList[3].SubProject_Confidentiality_Status__c, updatedProjectLogsList[3].SubProject_Confidentiality_Status__c, 'Lessons Learned Updated');
        
        //system.assertEquals(false, updatedProjectLogsList[4].SubProject_Confidential__c, 'SubProject_Confidential__c field value updated on Risk');
        system.assertNotEquals(projectLogsList[4].SubProject_Confidentiality_Status__c, updatedProjectLogsList[4].SubProject_Confidentiality_Status__c, 'Risk Updated');
        
        test.stopTest();
    }
    
    private static testMethod void processSubProjectsAfterInsertTestOne()
    {
        list<SubProject__c> subProjectRecordList=[
            SELECT Id, Project_Manager__c, SubProject_Status__c, Confidential__c, Confidentiality_Status__c,
            Training_Implementation_Client_Mgr__c, 
            //Project__c, 
            Deal_Id__c, Contract_Roll_Called__c
            FROM SubProject__c
        ];
		
        SubProject__c subProjectRecord = subProjectRecordList.size() > 0 ? subProjectRecordList.get(0) : new SubProject__c();
        
        List<Deal_State__c> dealStateList=[SELECT Id, Roll_Call_Date__c FROM Deal_State__c];
        
        List<SubProject__c> newSubProjectsList=new List<SubProject__c>();
        newSubProjectsList.add(subProjectRecord);
        
        test.startTest();
        IMP_SubProject_Handler.processSubProjectsAfterInsert(newSubProjectsList, Null);
        
        List<Deal_State__c> updatedDealStateList=[SELECT Id, Roll_Call_Date__c FROM Deal_State__c];
        system.assertEquals(dealStateList[0].Roll_Call_Date__c, updatedDealStateList[0].Roll_Call_Date__c, 'Roll Call Date Not Updated.');
        test.stopTest();
    }
    
    private static testMethod void processSubProjectsAfterInsertTestTwo()
    {
        list<SubProject__c> subProjectRecordList=[
            SELECT Id, Project_Manager__c, SubProject_Status__c, Confidential__c, Confidentiality_Status__c,
            Training_Implementation_Client_Mgr__c, 
            //Project__c, 
            Deal_Id__c, Contract_Roll_Called__c
            FROM SubProject__c
        ];
        SubProject__c subProjectRecord = subProjectRecordList.size() > 0 ? subProjectRecordList.get(0) : new SubProject__c();
        
        List<Deal_State__c> dealStateList=[SELECT Id, Roll_Call_Date__c, SQT_Deal_Id__c FROM Deal_State__c];
        
        List<SubProject__c> subProjectsList=new List<SubProject__c>();
        subProjectsList.add(subProjectRecord);
        
        test.startTest();
        IMP_SubProject_Handler.processSubProjectsAfterInsert(subProjectsList, Null);
        
        SubProject__c newSubProjectRecord=new SubProject__c();
        newSubProjectRecord=subProjectRecord.clone(true);
        newSubProjectRecord.Deal_Id__c='12345';
        newSubProjectRecord.Contract_Roll_Called__c=date.newinstance(2016, 03, 16);
        
        List<SubProject__c> newSubProjectsList=new List<SubProject__c>();
        newSubProjectsList.add(newSubProjectRecord);
        
        IMP_SubProject_Handler.processSubProjectsAfterInsert(newSubProjectsList, Null);
        
        List<Deal_State__c> updatedDealStateList=[SELECT Id, Roll_Call_Date__c, SQT_Deal_Id__c FROM Deal_State__c];
        system.assertEquals(dealStateList[0].SQT_Deal_Id__c, updatedDealStateList[0].SQT_Deal_Id__c);
        system.assertNotEquals(dealStateList[0].Roll_Call_Date__c, updatedDealStateList[0].Roll_Call_Date__c, 'Roll Call Date Updated.');
        system.assertEquals(date.newinstance(2016, 03, 16), updatedDealStateList[0].Roll_Call_Date__c, 'Roll Call Date Updated.');
        test.stopTest();
    }
    
    private static testMethod void processSubProjectsAfterUpdateTest()
    {
        list<SubProject__c> subProjectRecordList=[
            SELECT Id, Project_Manager__c, SubProject_Status__c, Confidential__c,Confidentiality_Status__c, 
            Training_Implementation_Client_Mgr__c, 
            //Project__c,
             Deal_Id__c, Contract_Roll_Called__c
            FROM SubProject__c
        ];
        
        SubProject__c subProjectRecord = subProjectRecordList.size() > 0 ? subProjectRecordList.get(0) : new SubProject__c();
        
        SubProject__c subProjectRecord2 = subProjectRecordList.size() > 1 ? subProjectRecordList.get(1) : new SubProject__c();
        
        List<Deal_State__c> dealStateList=[SELECT Id, Roll_Call_Date__c, SQT_Deal_Id__c FROM Deal_State__c];
        
        test.startTest();
        Map<Id, SubProject__c> oldSubProjectsMap=new Map<Id, SubProject__c>();
        oldSubProjectsMap.put(subProjectRecord.Id, subProjectRecord);
        oldSubProjectsMap.put(subProjectRecord2.Id, subProjectRecord2);
        
        SubProject__c newSubProjectRecord=new SubProject__c();
        newSubProjectRecord=subProjectRecord.clone(true);
        newSubProjectRecord.Project_Manager__c=UserInfo.getUserId();
        newSubProjectRecord.Contract_Roll_Called__c=date.newinstance(2016, 03, 16);
        newSubProjectRecord.Confidentiality_Status__c = 'Restricted';
        
        SubProject__c newSubProjectRecord2=new SubProject__c();
        newSubProjectRecord2=subProjectRecord2.clone(true);
        newSubProjectRecord2.Confidentiality_Status__c = 'Confidential';
        
        Map<Id, SubProject__c> newSubProjectsMap=new Map<Id, SubProject__c>();
        newSubProjectsMap.put(newSubProjectRecord.Id, newSubProjectRecord);
        newSubProjectsMap.put(newSubProjectRecord2.Id, newSubProjectRecord2);
        
        IMP_SubProject_Handler.processSubProjectsAfterUpdate(newSubProjectsMap, oldSubProjectsMap);
        
        List<Deal_State__c> updatedDealStateList=[SELECT Id, Roll_Call_Date__c, SQT_Deal_Id__c FROM Deal_State__c];
        system.assertEquals(dealStateList[0].SQT_Deal_Id__c, updatedDealStateList[0].SQT_Deal_Id__c);
        system.assertNotEquals(dealStateList[0].Roll_Call_Date__c, updatedDealStateList[0].Roll_Call_Date__c, 'Roll Call Date Updated.');
        system.assertEquals(date.newinstance(2016, 03, 16), updatedDealStateList[0].Roll_Call_Date__c, 'Roll Call Date Updated.');
        
        system.assertEquals(dealStateList[1].SQT_Deal_Id__c, updatedDealStateList[1].SQT_Deal_Id__c);
        system.assertNotEquals(dealStateList[1].Roll_Call_Date__c, updatedDealStateList[1].Roll_Call_Date__c, 'Roll Call Date Updated.');
        system.assertEquals(date.newinstance(2016, 03, 16), updatedDealStateList[1].Roll_Call_Date__c, 'Roll Call Date Updated.');
        
        list<SubProject__Share> subProjectSharedOwnerList = [select Id from SubProject__Share where parentId =:subProjectRecord.Id];
        //Only the owner of a restricted subproject will have access to shared record.
        system.assertEquals(1, subProjectSharedOwnerList.size());
        
        
        /*Project__c projectRecordNew=IMP_TestFactory_Helper.buildProject(0);
        insert projectRecordNew;*/
        
        SubProject__c updatedSubProjectRecord=new SubProject__c();
        updatedSubProjectRecord=subProjectRecord.clone(true);
        updatedSubProjectRecord.Deal_Id__c='12345';
        updatedSubProjectRecord.Contract_Roll_Called__c=date.newinstance(2016, 03, 18);
        //updatedSubProjectRecord.Project__c=projectRecordNew.Id;
        
        Map<Id, SubProject__c> updatedSubProjectsMap=new Map<Id, SubProject__c>();
        updatedSubProjectsMap.put(updatedSubProjectRecord.Id, updatedSubProjectRecord);
        
        IMP_SubProject_Handler.processSubProjectsAfterUpdate(updatedSubProjectsMap, oldSubProjectsMap);
        
        List<Deal_State__c> updatedDealStateListTwo=[SELECT Id, Roll_Call_Date__c, SQT_Deal_Id__c FROM Deal_State__c];
        system.assertEquals(dealStateList[0].SQT_Deal_Id__c, updatedDealStateListTwo[0].SQT_Deal_Id__c);
        system.assertNotEquals(dealStateList[0].Roll_Call_Date__c, updatedDealStateListTwo[0].Roll_Call_Date__c, 'Roll Call Date Updated.');
        system.assertEquals(date.newinstance(2016, 03, 18), updatedDealStateListTwo[0].Roll_Call_Date__c, 'Roll Call Date Updated.');
        test.stopTest();
    }
}