SF Primes/src/objects/Deal_State__c.object
<CustomObject>
    <description>Deal Related information. BDC Communication Project</description>
    <fields>
        <fullName>Any_Other_Sites_Involved_With_Request__c</fullName>
        <label>Sites Involved With Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cash_Credit__c</fullName>
        <label>Cash/Credit</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract_Needed_By_Date__c</fullName>
        <label>Contract Needed By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Status__c</fullName>
        <label>Deal Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Deal Arrived</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rep Created SQT Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned - SCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Networking Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Networking Quote Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending SOW Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW Deal Change Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released To Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Sales Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval in SQT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed by All Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Deal Change Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send To CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send To Countersign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send To CRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Envelope Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent To Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent To Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description_of_Need__c</fullName>
        <label>Description of Item(s) Needed</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal State</relationshipLabel>
        <relationshipName>Deal_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_of_Sites__c</fullName>
        <label>Number of Sites</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Deal State</label>
    <nameField>
        <displayFormat>DS - {000000}</displayFormat>
        <label>Deal State ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA/src/classes/ALL_DocusignStatus_Test.cls
/*------------------------------------------------------------
Author:        Vishal Bandari
Description:   Unit Test for ALL_DocusignStatus_Handler
Created on:    9 October 2015.
Code Coverage: 100% 
------------------------------------------------------------
History
9 October 2015    Vishal Bandari      RQ-05276: Created
------------------------------------------------------------*/
@IsTest
public class ALL_DocusignStatus_Test {
    
    //To Create Sample Opportunity and Deal_State__c
    
	@testSetup
    public static void setupData()
    {     
        //Insert Sample Opportunity
        
        Opportunity opportunityObj = DS_TestObjects.NewOpportunity_Inserted();
     
        //Insert Sample Deal_State__c
        
        Deal_State__c dealStateObj = new Deal_State__c();
        dealStateObj.Opportunity__c = opportunityObj.Id;
        dealStateObj.Deal_Status__c = 'New Deal Arrived';
        dealStateObj.Quantity_of_Sites__c = 12;
        dealStateObj.Any_Other_Sites_Involved_With_Request__c = 'Site1';
        dealStateObj.Description_of_Need__c = 'Sample';
        dealStateObj.Cash_Credit__c = 'Cash';
        dealStateObj.Contract_Needed_By_Date__c = Date.today();
        insert dealStateObj;
    }
    
    //To test for update on Opportunity record
    
    public static testmethod void validate()
    {
        //Insert Sample dsfs__DocuSign_Status__c
        
        dsfs__DocuSign_Status__c docusignStatusObj = new dsfs__DocuSign_Status__c();
        String envelopId = String.valueof(Math.random());
        docusignStatusObj.dsfs__DocuSign_Envelope_ID__c = envelopId;
        
        Deal_State__c dealStateObj = [
            SELECT id,Opportunity__c 
            FROM deal_state__c
        ][0];
        
        
        docusignStatusObj.Deal_State__c = dealStateObj.Id;
        insert docusignStatusObj;
        
        //Test if Opportunity Object DocuSign_Envelope_ID__c field is Updated
        
        Opportunity opportunityObj = [
            SELECT id, DS_SLS_DocuSign_Envelope_ID__c 
            FROM Opportunity 
            WHERE id =: dealStateObj.Opportunity__c
        ];
        
        System.assertEquals(envelopId, opportunityObj.DS_SLS_DocuSign_Envelope_ID__c, 'Envelope Id is not updated');
        
        //Testing Voided the Envelope
        docusignStatusObj.dsfs__Envelope_Status__c = 'Voided';
        update docusignStatusObj;
        
        //Test if Opportunity Object DS_SLS_DocuSign_Envelope_ID__c field is Updated
        
        opportunityObj = [
            SELECT id, DS_SLS_DocuSign_Envelope_ID__c 
            FROM Opportunity 
            WHERE id =: dealStateObj.Opportunity__c
        ];
        
        System.assertEquals(null, opportunityObj.DS_SLS_DocuSign_Envelope_ID__c, 'Envelope Id is not updated when voided');
    }
    
    //To perform negitive Test
    
    public static testmethod void negitiveTest()
    {        
        ALL_DocusignStatus_Handler.updateOpporunity(null,false,false);
    }
}