SF Primes/src/objects/Deal_State__c.object
<CustomObject>
    <description>Deal Related information. BDC Communication Project</description>
    <fields>
        <fullName>ADP_Opportunity_Owner__c</fullName>
        <formula>Opportunity__r.ADP_Opportunity_Owner__r.FirstName &amp; &quot; &quot; &amp; Opportunity__r.ADP_Opportunity_Owner__r.LastName</formula>
        <label>CDK Opportunity Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CA_Approved_Date__c</fullName>
        <inlineHelpText>Central Time Zone (CST)</inlineHelpText>
        <label>CA Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contract_Number_s__c</fullName>
        <label>Contract Number(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Dealer_Group__c</fullName>
        <label>Dealer Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Number__c</fullName>
        <label>Impact Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal State</relationshipLabel>
        <relationshipName>Deal_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SQT_Deal_ID__c</fullName>
        <label>SQT Deal ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Deal State</label>
    <nameField>
        <displayFormat>DS - {000000}</displayFormat>
        <label>Deal State ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/IMPDS_SpereToDealState__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>list of entity types of spere object which are forwarded to deal state object</description>
    <label>IMPDS_SpereToDealState</label>
</CustomObject>

SF Primes/src/objects/Opportunity_Quotes__c.object
<CustomObject>
    <description>Link to SQT deals for a given opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Quotes</relationshipLabel>
        <relationshipName>Opportunity_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deal_ID__c</fullName>
        <externalId>true</externalId>
        <label>Deal ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Quotes</relationshipLabel>
        <relationshipName>Opportunity_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SQT_Deal_ID__c</fullName>
        <label>SQT Deal ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Quotes</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Deal_Id__c</fullName>
        <label>Deal Id</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_External_Related_Entity__c.object
<CustomObject>
    <description>Object used to store IDs of all External Related Entities like Impact Project Numbers, RMS Request IDs, Contract Numbers, CMF Numbers. Currently all of this information comes in through the IMPACT Integration</description>
    <fields>
        <fullName>Entity_Number__c</fullName>
        <label>Entity Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Impact Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RMS Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProject External Related Entities</relationshipLabel>
        <relationshipName>SubProject_External_Related_Entities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject External Related Entities</relationshipLabel>
        <relationshipName>SubProject_External_Related_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject External Related Entity</label>
    <nameField>
        <displayFormat>EXT-{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject External Related Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fulldev2/src/classes/IMP_UpdateEntityNumsOnDealState_Test.cls
/**------------------------------
 Test-Class for Updating entity numbers in DealState record from Implementation data
 i.e.., for IMP_UpdateEntityNumsOnDealState_Handler.cls

****HISTORY****
09/01/2015 - Venkata Shrivol - Renamed to IMP_UpdateEntityNumsOnDealState_Test  
							   and updated accordingly for modified handler class
-------------------------------------- */
@isTest
private class IMP_UpdateEntityNumsOnDealState_Test {

    @testSetup static void updateEntityNumbers_Test() 
    {
    		
    	User u = DS_TestObjects.NewUser_Inserted();
        Account acc = DS_TestObjects.NewAccount_Inserted(); 
        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Oppo1';
        opp.ADP_Opportunity_Owner__c = u.id;
        opp.CloseDate = Date.Today();
        opp.StageName = 'Plan';
        opp.Account = acc;
        insert opp; 
        
        Opportunity_Quotes__c oppQuote = new Opportunity_Quotes__c();
    	oppQuote.Deal_ID__c = '12345';
    	oppQuote.Opportunity__c =opp.id;
    	oppQuote.Account__c = acc.id;
    	insert oppQuote;
    	
    	Deal_State__c dealState = new Deal_State__c();
        dealState.SQT_Deal_ID__c = '12345';
        dealState.Opportunity__c = opp.id;
        //dealState.CA_Approved_Date__c = datetime.now();
        insert dealState;
        
        // Test
        list<IMPDS_SpereToDealState__c> customSettingsList = new list<IMPDS_SpereToDealState__c>();
        for(integer i=0;i<2;i++)
        {
            IMPDS_SpereToDealState__c testSetting = new IMPDS_SpereToDealState__c();
            if(i==0){
                testSetting.Name='Contract';
            }
            else{
              testSetting.Name='Impact Project';  
            }
            customSettingsList.add(testSetting);
        }
        insert customSettingsList;
        
        Project__c testProject = IMP_TestFactory_Helper.buildProject(0);
        //testProject.Dealer_Group__c = acc.Id;
        insert testProject;
        
        SubProject__c testSubProject = IMP_TestFactory_Helper.buildSubProject(testProject.Id);
        //testSubProject.Dealer_Group__c = acc.Id;
        testSubProject.Deal_Id__c = '12345';
        testSubProject.Project__c= testProject.id;
        insert testSubProject;
        
        list<SubProject_External_Related_Entity__c> entityList = new list<SubProject_External_Related_Entity__c>();
        for(integer i=2;i<6;i++)
        {
            SubProject_External_Related_Entity__c testEntity = IMP_TestFactory_Helper.buildSubProjectExternalRelatedEntity(testSubProject.Id);
            if(math.mod(i,2)==0){
                testEntity.Entity_Type__c = 'Contract';
            }
            else{
                testEntity.Entity_Type__c = 'Impact Project';
            }
            testEntity.Entity_Number__c = i+'8793323';
            testEntity.SubProject__c = testSubProject.id;
            testEntity.Project__c = testProject.id;
            entityList.add(testEntity);
        }
        insert entityList;
        
        entityList.clear();
        
        for(integer i=0;i<2;i++)
        {
            SubProject_External_Related_Entity__c testEntity = IMP_TestFactory_Helper.buildSubProjectExternalRelatedEntity(testSubProject.Id);
            if(i==0){
                testEntity.Entity_Type__c = 'Contract';
            }
            else{
                testEntity.Entity_Type__c = 'Impact Project';
            }
            testEntity.Entity_Number__c = i+'1231231';
            testEntity.SubProject__c = testSubProject.id;
            testEntity.Project__c = testProject.id;
            entityList.add(testEntity);
        }
        insert entityList;
        
        
        //system.debug('----entityList------------'+entityList);
    }
    
    static testMethod void updateOnDealStateTest()
    {
    	Deal_State__c ds = [select Contract_Number_s__c, Impact_Project_Number__c from Deal_State__c where SQT_Deal_ID__c = '12345' limit 1];
        system.assertNotEquals(null, ds.Contract_Number_s__c);
        system.assertNotEquals(null, ds.Impact_Project_Number__c);
        system.assertEquals(true, ds.Contract_Number_s__c.contains('8793323'));
        system.assertEquals(true, ds.Impact_Project_Number__c.contains('8793323'));
    }
}