SF Primes/src/objects/Discovery_Workbook_Category__c.object
<CustomObject>
    <description>Contains the Workbook capturing questions, responses, interviewees, interviewers; and associated with a Project and Site.</description>
    <fields>
        <fullName>Site_Workbook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Workbook</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Site_Workbook__c</referenceTo>
        <relationshipLabel>Discovery Site Workbook Categories</relationshipLabel>
        <relationshipName>Discovery_Workbook</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Site Workbook Category</label>
    <nameField>
        <displayFormat>DW-{00000}</displayFormat>
        <label>Discovery Workbook Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbook Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Log__c.object
<CustomObject>
    <description>Contains various types of Project Log including Action Items, Change Requests, Issues, Lessons Learned and Risks to associate with either a Project or SubProject.</description>
    <fields>
        <fullName>Project_Action_Items__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project - Action Items</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Project_Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Change_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project - Change Request</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Project_Change_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Issue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project - Issue</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Project_Issue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Lessons_Learned__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project - Lessons Learned</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Lessons Learned</relationshipLabel>
        <relationshipName>Project_Lessons_Learned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Risk__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project - Risk</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Project_Risk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Retrieves Project Name based on Record Type.</description>
        <formula>CASE( Record_Type_Name__c , 
&quot;Action Item&quot;, Project_Action_Items__r.Name , 
&quot;Change Request&quot;, Project_Change_Request__r.Name ,
&quot;Issue&quot;, Project_Issue__r.Name ,
&quot;Lesson Learned&quot;, Project_Lessons_Learned__r.Name ,
&quot;Risk&quot;, Project_Risk__r.Name ,
&quot;&quot;)</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Project Log</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Site_Workbook__c.object
<CustomObject>
    <description>Junction object to allow associating a Workbook with a Project and Site.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Discovery Site Workbooks</relationshipLabel>
        <relationshipName>Site_Workbooks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discovery Site Workbook</label>
    <nameField>
        <displayFormat>SW-{00000000}</displayFormat>
        <label>Site Workbook ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Site Workbooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_ProjectButtonActions_Handler.cls
/*------------------------------------------------------------
Author:      Samuel Oberes
Company:     Cloud Sherpas
Description: Handles the overriding of button actions
History
11/26/14     Samuel Oberes       Created
11/03/14     Venkata Shrivol     Commented out the code for Project_Checklist__c reference 
12/02/16     Venkata Shrivol	 commented the entire class as project object is getting deleted RQ-08305
------------------------------------------------------------*/
public class IMP_ProjectButtonActions_Handler {
    /*public static void removeAssociatedRecords(List<Project__c> listOfOldProjects){

        Set<Id> setOfOldProjectIDs = new Set<Id>();
        for (Project__c p : listOfOldProjects) {
            setOfOldProjectIDs.add(p.Id);
        }

        // generate a siteWBstoDeleteList by querying all records for Site_Workbook__c where matching Project__c
        List<Site_Workbook__c> siteWBstoDeleteList = new List<Site_Workbook__c>();
        // [SELECT Id FROM Site_Workbook__c WHERE Project__c IN :listOfOldProjects];
        siteWBstoDeleteList = IMP_Project_Utility.retrieveSiteWorkbooks(setOfOldProjectIDs);
        
        
        // generate a siteWBCatstoDeleteList by querying all records for Discovery_Workbook_Category__c where matching Site_Workbook__c
        List<Discovery_Workbook_Category__c> siteWBCatstoDeleteList = new List<Discovery_Workbook_Category__c>();
        // [SELECT Id FROM Discovery_Workbook_Category__c WHERE Site_Workbook__c IN :siteWBstoDeleteList];
        siteWBCatstoDeleteList = IMP_Project_Utility.retrieveWorkborkCategoryWithSubquery(siteWBstoDeleteList, null);

        
        // delete siteWBCatstoDeleteList in a try/catch block
        try {
            if (!siteWBCatstoDeleteList.isEmpty()) {
                delete siteWBCatstoDeleteList;
            }
        } catch (DmlException e) {
            System.debug('DBG: DELETION ERROR ON siteWBCatstoDeleteList');
            System.debug('DBG: MESSAGE: ' + e.getMessage());
            System.debug('DBG: STACKTRACE: ' + e.getStackTraceString());
        }

        
        // delete siteWBstoDeleteList in a try/catch block
        try {
            if (!siteWBstoDeleteList.isEmpty()) {
                delete siteWBstoDeleteList;
            }
        } catch (DmlException e) {
            System.debug('DBG: DELETION ERROR ON siteWBstoDeleteList');
            System.debug('DBG: MESSAGE: ' + e.getMessage());
            System.debug('DBG: STACKTRACE: ' + e.getStackTraceString());
        }


        // generate a checklisttoDeleteList by querying all records for Project_Checklist__c where matching Project__c
        //List<Project_Checklist__c> checklisttoDeleteList = new List<Project_Checklist__c>();
        // [SELECT Id FROM Project_Checklist__c WHERE Project__c IN :listOfOldProjects];
        //checklisttoDeleteList = IMP_Project_Utility.retrieveProjectCheckList(setOfOldProjectIDs);


        // delete checklisttoDeleteList in a try/catch block
        /*try {
            if (!checklisttoDeleteList.isEmpty()) {
                delete checklisttoDeleteList;
            }
        } catch (DmlException e) {
            System.debug('DBG: DELETION ERROR ON checklisttoDeleteList');
            System.debug('DBG: MESSAGE: ' + e.getMessage());
            System.debug('DBG: STACKTRACE: ' + e.getStackTraceString());
        }


        // generate a projectlogstoDeleteList by querying all records for Project_Log__c where matching Project__c
        List<Project_Log__c> projectlogstoDeleteList = new List<Project_Log__c>();
        projectlogstoDeleteList.addAll([SELECT Id 
                                          FROM Project_Log__c 
                                         WHERE (Project_Action_Items__c IN :listOfOldProjects) 
                                            OR (Project_Change_Request__c IN :listOfOldProjects)
                                            OR (Project_Issue__c IN :listOfOldProjects)
                                            OR (Project_Lessons_Learned__c IN :listOfOldProjects)
                                            OR (Project_Risk__c IN :listOfOldProjects)]);


        // delete projectlogstoDeleteList in a try/catch block
        try {
            if (!projectlogstoDeleteList.isEmpty()) {
                delete projectlogstoDeleteList;
            }
        } catch (DmlException e) {
            System.debug('DBG: DELETION ERROR ON projectlogstoDeleteList');
            System.debug('DBG: MESSAGE: ' + e.getMessage());
            System.debug('DBG: STACKTRACE: ' + e.getStackTraceString());
        }
    }*/
}