SF Primes/src/objects/Discovery_Question_Product__c.object
<CustomObject>
    <description>Junction object to associate a Discovery Question with their relevant Product.</description>
    <fields>
        <fullName>Active_Flag_for_Rollup__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active Flag for Rollup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Discovery Question Products</relationshipLabel>
        <relationshipName>Discovery_Question_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Discovery Question Products</relationshipLabel>
        <relationshipName>Discovery_Question_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discovery Question Product</label>
    <nameField>
        <displayFormat>PQ-{00000000}</displayFormat>
        <label>ProdQuest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Question Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Product__c.object
<CustomObject>
    <description>Contains the Products under each Solution.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Question__c.object
<CustomObject>
    <description>Contains the Questions used during Discovery with association to Dealership Need and Product.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Discovery Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discovery Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA/src/classes/IMP_CheckQuestionifActive_Handler.cls
/*------------------------------------------------------------
Author: Kimiko Roberto
Company: Cloud Sherpas
Description: Checks Question's Active field so we can set the value of the related
             Discovery_Question_Product's Active_Flag_for_Rollup__c field
Test Class:
History
10/21/14    Kimiko Roberto      Created
------------------------------------------------------------*/
public class IMP_CheckQuestionifActive_Handler{
    
    public static void checkActiveField(List<Question__c> questionList, Map<Id, Question__c> oldQuestionMap){
        List<Question__c> questionsToBeProcessed = new List<Question__c>();
        //get the updated questions to check if the active field changed; this and the product will determine the Active_Flag_for_Rollup__c value
        for(Question__c question : questionList){
            Question__c oldQuestion = oldQuestionMap.get(question.Id);
            //retrieve all questions where active field is not equal to it's old value;
            //this list will be used to get the product and set up Active_Flag_for_Rollup__c value
            if(question.Active__c != oldQuestion.Active__c){
                questionsToBeProcessed.add(question);
            }
        }
        if(!questionsToBeProcessed.isEmpty()){
            //get all the related Discovery_Question_Product__c from the updated questions so we can change the Active_Flag_for_Rollup__c value
            List<Discovery_Question_Product__c> dqpList = [SELECT Id,
                                                           Question__c,
                                                           Question__r.Active__c,
                                                           Product__c,
                                                           Product__r.Active__c,
                                                           Active_Flag_for_Rollup__c
                                                           FROM Discovery_Question_Product__c
                                                           WHERE Question__c IN: questionsToBeProcessed];
            if(!dqpList.isEmpty()){
                //we will iterate to the list of related Discovery_Question_Product__c to detrermine the value of 
                //the Active_Flag_for_Rollup__c depending if the question and product is active or not.
                for(Discovery_Question_Product__c dqp : dqpList){
                    if(dqp.Product__r.Active__c && dqp.Question__r.Active__c){
                        dqp.Active_Flag_for_Rollup__c = true;
                    }
                    else{
                        dqp.Active_Flag_for_Rollup__c = false;
                    }            
                }
                //update the changes made to the Discovery_Question_Product__c
                update dqpList;
            }
            
        }
        
        
    }
}