SF Primes/src/objects/EMP_IT_Support_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EMP IT Support List</label>
</CustomObject>

fulldev2/src/classes/EMP_ITSupport_General_Controller.cls
/*------------------------------------------------------------
Author: Rey Austral
Company: Cloud Sherpas
Description: 
Test Class: EMP_ITSupportGeneral_Test
History
12/11/14    Rey Austral      Created
------------------------------------------------------------*/
public class EMP_ITSupport_General_Controller {
    public List<EMP_IT_Support_List__c> listGeneralSection { get; set; }
    public EMP_ITSupport_General_Controller () {
          listGeneralSection  =  [Select Name, Url__c, Description__c from EMP_IT_Support_List__c where Section__c = 'IT Onboarding'];
    }
}