SF Primes/src/objects/EMP_Policy__c.object
<CustomObject>
    <description>This object will store if the user accepted ADP Dealer Services Policies</description>
    <fields>
        <fullName>Acknowledgement_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Acknowledgement Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content_Version_ID__c</fullName>
        <label>Content Version ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Acknowledgement__c</fullName>
        <label>Date of Acknowledgement</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Policy_Addition_Date__c</fullName>
        <label>Policy Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Policies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VersionNumber__c</fullName>
        <label>VersionNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Policy Acknowledgement</label>
    <nameField>
        <label>Policy Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Acknowledgements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Docusign/src/classes/EMP_PolicyAcknowledgementPageController.cls
public class EMP_PolicyAcknowledgementPageController {
    public String policy { get; set; }
    public ID selectedPolicy { get; set; }
    
    public Set<Id> cDoc = new Set<Id>();
    public Id usrID = userInfo.getUserId();
    public Map <Id, EMP_Policy__c> policyMap {get;set;}
    public List<EMP_Policy__c> policyList {get;set;}
    public List<EMP_Policy__c> policyAcknowList {get;set;}
    public List<EMP_Policy__c> policyNonAcknowList{get;set;}
    public Id policyID {get;set;}
    public String pID{get;set;}
    public Boolean showLink{get;set;}
    public Boolean showtable{get;set;}
    
    public EMP_PolicyAcknowledgementPageController(){
        policyMap = new Map <Id, EMP_Policy__c>();
        policyAcknowList = new  List<EMP_Policy__c>();
        policyNonAcknowList = new List<EMP_Policy__c>();
        policyList =[
            SELECT Acknowledgement_Status__c,
            Content_Version_ID__c,
            Date_of_Acknowledgement__c,
            Policy_Addition_Date__c,
            Name,
            VersionNumber__c
            FROM EMP_Policy__c
            WHERE User_Name__c =: usrID 
            ORDER BY Policy_Addition_Date__c DESC];
        for(EMP_Policy__c Policy : PolicyList){
            if(Policy.Acknowledgement_Status__c == true){
                policyAcknowList.add(Policy);
                showtable= true;
            }else{
                policyNonAcknowList.add(Policy);
            }
        }
    }
    
   public pageReference ContentLoad(){ 
        showlink = true;
        pageReference Pageref = new Pagereference('/apex/ContentPreview?contentId='+policyID);
        showlink=false;
        return PageRef;
        
    }
    public void acknowledge(){
        //this method will set the selected record as acknowledge
        List<EMP_Policy__c> updatePolicy = new List<EMP_Policy__c>();
        List<ContentVersion> cvList = new List<ContentVersion>();
        
        for(EMP_Policy__c policy : [
            SELECT Acknowledgement_Status__c,
            Content_Version_ID__c,
            Date_of_Acknowledgement__c,
            Policy_Addition_Date__c,
            Name,
            VersionNumber__c
            FROM EMP_Policy__c
            WHERE User_Name__c =: usrID
            AND Id =: policyID])
        { 
            if(policy.Acknowledgement_Status__c == false){
                policy.Acknowledgement_Status__c = true;
                policy.Date_of_Acknowledgement__c = dateTime.now();
                updatePolicy.add(policy);
            }
        }
        
        if(!updatePolicy.isEmpty() || updatePolicy.size()>0){       
            update updatePolicy;       
        } 
        
        policyList =[
            SELECT Acknowledgement_Status__c,
            Content_Version_ID__c,
            Date_of_Acknowledgement__c,
            Policy_Addition_Date__c,
            Name,
            VersionNumber__c
            FROM EMP_Policy__c
            WHERE User_Name__c =: usrID 
            ORDER BY Policy_Addition_Date__c DESC];
    }
}