SF Primes/src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds global settings for the various triggers and apex jobs to function. The only thing that should be modified outside of a pod switch is the error reporting email, which is a comma separated list. Example: &apos;tlaporte@centerstance.com,psaini@cobaltgroup.com&apos;</description>
    <fields>
        <fullName>DefaultCaseTeamMemberId__c</fullName>
        <label>DefaultCaseTeamMemberId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

SF Primes/src/objects/Launch__c.object
<CustomObject>
    <description>Used by CB Services to track progress of website build in progress</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Launch</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Launch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Launch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Order_Accuracy__c.object
<CustomObject>
    <description>This object is used in conjunction with the Launch object. IFS personnel enter/track how many times Sales to IFS launches result in missing or incorrect data for reporting to BPI.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>IF( ISBLANK( Launch__c ) ,  Case__r.Account.Name , Launch__r.Account__r.Name)</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Accuracy</relationshipLabel>
        <relationshipName>Order_Accuracy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Launch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Launch</label>
        <referenceTo>Launch__c</referenceTo>
        <relationshipLabel>Order Accuracy</relationshipLabel>
        <relationshipName>Order_Accuracy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDA_Incorrect_Data_Count__c</fullName>
        <label>MDA - Incorrect Data Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDA_Incorrect_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MDA - Incorrect Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OF_Incorrect_Data_Count__c</fullName>
        <label>Order Form - Incorrect Data Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OF_Incorrect_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Form - Incorrect Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recap_Incorrect_Data_Count__c</fullName>
        <label>Recap - Incorrect Data Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recap_Incorrect_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recap - Incorrect Data</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Accuracy</label>
    <nameField>
        <displayFormat>OA-{00000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Accuracy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/classes/DS_OrderAccuracyTrigger_Test.cls
//2015-11-27 : vishal.bandari@cdk.com    RQ-05289:changed UpdateFields method to add contact record type
@IsTest
public class DS_OrderAccuracyTrigger_Test
{
    public static testmethod void UpdateFields()
    {
        Launch__c NewLaunchNullAccount = DS_TestObjects.NewLaunch();
        NewLaunchNullAccount.Account__c = null;
        insert NewLaunchNullAccount;
        
        Order_Accuracy__c NewOrderAccuracy1 = new Order_Accuracy__c();
        NewOrderAccuracy1.MDA_Incorrect_Data__c = true;
        NewOrderAccuracy1.MDA_Incorrect_Data_Count__c = 1;
        NewOrderAccuracy1.OF_Incorrect_Data__c = true;
        NewOrderAccuracy1.OF_Incorrect_Data_Count__c = 1;
        NewOrderAccuracy1.Recap_Incorrect_Data__c = true;
        NewOrderAccuracy1.Recap_Incorrect_Data_Count__c = 1;
        NewOrderAccuracy1.Launch__c = NewLaunchNullAccount.Id;
        insert NewOrderAccuracy1;
        
        User CurrentUser = [Select Id from User where Id = :UserInfo.getUserId()];
        profile p = [Select Id, Name From Profile Limit 1];
        User DSMDOSUser = DS_TestObjects.NewUser(); DSMDOSUser.Title = 'DSM'; insert DSMDOSUser;
        User DSMNatEntUser = DS_TestObjects.NewUser(); DSMNatEntUser.Title = 'DSM'; DSMNatEntUser.ManagerId = DSMDOSUser.Id; insert DSMNatEntUser;
        User DSMUser = DS_TestObjects.NewUser(); DSMUser.Title = 'DSM'; DSMUser.ManagerId = DSMDOSUser.Id; insert DSMUser;
        User DSCUser = DS_TestObjects.NewUser(); insert DSCUser;
        User DigitalMarketingStrategist = DS_TestObjects.NewUser(); insert DigitalMarketingStrategist;
        
        Launch__c NewLaunch = DS_TestObjects.NewLaunch_Inserted();
        NewLaunch.Account__r.Designated_DSM__c = DSMUser.Id;
        NewLaunch.Account__r.Digital_Sales_Consultant__c = DSCUser.Id;
        NewLaunch.Account__r.Designated_DSM_Nat_Ent__c = DSMNatEntUser.Id;
        NewLaunch.Account__r.Digital_Services_CAM__c = DigitalMarketingStrategist.Id;
        update NewLaunch.Account__r;
        
        Order_Accuracy__c NewOrderAccuracy2 = new Order_Accuracy__c();
        NewOrderAccuracy2.MDA_Incorrect_Data__c = true;
        NewOrderAccuracy2.MDA_Incorrect_Data_Count__c = 1;
        NewOrderAccuracy2.OF_Incorrect_Data__c = true;
        NewOrderAccuracy2.OF_Incorrect_Data_Count__c = 1;
        NewOrderAccuracy2.Recap_Incorrect_Data__c = true;
        NewOrderAccuracy2.Recap_Incorrect_Data_Count__c = 1;
        NewOrderAccuracy2.Launch__c = NewLaunch.Id;
        insert NewOrderAccuracy2;
        
        WebId__c NewWebID = DS_TestObjects.NewWebID_Inserted();
        
        // Default Case Team Member
        CaseTeamRole ctr = new CaseTeamRole(Name='TEST Case Team Member', AccessLevel='Edit');
        system.runas(CurrentUser) { insert ctr; }
        
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.DefaultCaseTeamMemberId__c = ctr.Id;
        insert gs;
        
        contact con = DS_TestObjects.NewContact();
        con.AccountId = NewWebID.Account__c;
        //2015-11-27  vishal.bandari@cdk.com RQ-05289:added contact record type
        con.RecordTypeId = ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('Contact','Customer Contact');
        insert con;
        
        Case NewCase = new Case(); 
        NewCase.Subject = 'TEST Order Accuracy';
        NewCase.AccountId = NewWebID.Account__c;
        NewCase.WebID__c = NewWebID.Id;
        NewCase.Status = 'Open';
        NewCase.Product_Category__c = 'Email';
        NewCase.Priority = 'Standard';
        NewCase.Origin = 'Email';
        NewCase.Origin_Type__c = 'INB-Customer';
        NewCase.Dealer_Group_Contact__c = con.Id;
        NewCase.ContactId = con.Id;
        //NewCase.Escalation_Reason__c = 'Other Technical Issue';
        insert NewCase;
        
        NewOrderAccuracy1.Launch__c = null;
        NewOrderAccuracy1.Case__c = NewCase.Id;
        update NewOrderAccuracy1;
    }
}