SF Primes/src/objects/IMP_DataTableUISetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting for the Generic Data Table Component UI Setting</description>
    <fields>
        <fullName>MaxNumberOfSearchResults__c</fullName>
        <description>This controls the maximum records to be queried. Can be overridden by the component&apos;s query limit attribute.</description>
        <inlineHelpText>This controls the maximum records to be queried. Can be overridden by the component&apos;s query limit attribute.</inlineHelpText>
        <label>Max Number Of Search Results</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinNumberOfSearchCharacters__c</fullName>
        <label>Min Number Of Search Characters</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfRecordsPerObject__c</fullName>
        <description>This will control by the number of records to show per page of the table. This can be overridden by the component&apos;s rowsPerPage attribute</description>
        <inlineHelpText>This will control by the number of records to show per page of the table. This can be overridden by the component&apos;s rowsPerPage attribute</inlineHelpText>
        <label>Number Of Records Per Object</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IMP_DataTableUISetting</label>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHWEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-LAPALMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-PORTLAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-SOUTHEAST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>H_W_Specialist_PFW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>H/W Specialist (PFW)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjects_HW_Specialist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add-On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy / Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Secondary_Project_Type__c</fullName>
        <label>Secondary Project Type</label>
        <picklist>
            <controllingField>Project_Type__c</controllingField>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitive Buy-Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rush (&lt;30 Days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box / Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box w/Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Only / Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franchise Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS Only Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Merge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal with Add-On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts Copy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interfaces/Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL/Data Merge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Programming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Tapes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProject_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASP-US/Toronto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASP-US/Vancouver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/ALL_DataTableComponent_Extension_Test.cls
/*------------------------------------------------------------
Author:      Samuel Oberes
Company:     Cloud Sherpas
Description: ALL_DataTableComponent_Extension test class
History
03/24/15     Samuel Oberes       Created
08/10/15     Samuel Oberes       Updated saveAndClose_Test method. Replaced New IP Address field with H_W_Specialist_PFW__c because the former will already be removed.
07/25/16     Venkata Shrivol     Updated the code to remove the dependency on an label in assertion statement
------------------------------------------------------------*/
@isTest
private class ALL_DataTableComponent_Extension_Test 
{
    private static User vicUser;
    private static IMP_DataTableUISetting__c uiSetting;
    //private static Project__c project;
    private static SubProject__c subProject;
    private static EntitySubscription followedRecord;
    private static ALL_DataTableComponent_Controller csDataTableInstance;

    static 
    {
        vicUser = IMP_TestFactory_Helper.buildUserImplementationVIC();
        try
        {
            insert vicUser;
        }
        catch (DmlException e) 
        {
            System.debug('DBG: Error encountered >>> ' + e.getMessage());
        }

        uiSetting                                = new IMP_DataTableUISetting__c();
        uiSetting.MaxNumberOfSearchResults__c    = 10;
        uiSetting.MinNumberOfSearchCharacters__c = 5;
        uiSetting.NumberOfRecordsPerObject__c    = 20;
        try
        {
            insert uiSetting;
        }
        catch (DmlException e) 
        {
            System.debug('DBG: Error encountered >>> ' + e.getMessage());
        }

        /*project                     = IMP_TestFactory_Helper.buildProject(0);
        project.Name                = 'projectName';
        project.CMF_Numbers__c      = 'testCMFNumber';
        project.Project_Status__c   = 'Open';
        project.Project_Region__c   = 'ARG-CANADA';
        try
        {
            insert project;
        }
        catch (DmlException e) 
        {
            System.debug('DBG: Error encountered >>> ' + e.getMessage());
        }*/

        subProject                               = IMP_TestFactory_Helper.buildSubProject();
        subProject.SubProject_Region__c          = 'Alliance PC Solutions Admin';
        subProject.Secondary_Project_Type__c     = 'Competitive Buy-Sell';
        try
        {
            insert subProject;
        }
        catch (DmlException e) 
        {
            System.debug('DBG: Error encountered >>> ' + e.getMessage());
        }

        followedRecord              = new EntitySubscription();
        followedRecord.ParentId     = subProject.Id;
        followedRecord.SubscriberId = UserInfo.getUserId();
        try
        {
            insert followedRecord;
        }
        catch (DmlException e)
        {
            System.debug('DBG: Error encountered >>> ' + e.getMessage());
        }
        
        csDataTableInstance                         = new ALL_DataTableComponent_Controller();
        csDataTableInstance.objLabelName            = 'testObjectLabelName';
        csDataTableInstance.objApiName              = 'SubProject__c';
        csDataTableInstance.objIdPrefixCode         = '09213';
        csDataTableInstance.objEntityId             = '096171097412';
        csDataTableInstance.selectQueryString       = 'SELECT Id, Name, Project_Type__c, SubProject_Status__c, H_W_Specialist_PFW__c FROM SubProject__c';
        csDataTableInstance.selectWhereClauseString = 'WHERE Project_Type__c=\'' + subProject.Project_Type__c + '\'';
        csDataTableInstance.queryLimitNum           = 5;
        csDataTableInstance.selectOrderString       = 'ORDER BY Id DESC';
        csDataTableInstance.objConsoleOpenInSubTab  = true;
        csDataTableInstance.showFilter              = true;
        csDataTableInstance.filterFieldSetName      = 'SubProjectFilterFields';
        csDataTableInstance.columnFieldSetName      = 'SubProjectDataTableFields';
        csDataTableInstance.useAltColumns           = true;
        csDataTableInstance.altColumnsJSONString    = 'testAltColumnJSON';
        csDataTableInstance.recordsPerPage          = 10;
        csDataTableInstance.size                    = 10;
        csDataTableInstance.noOfRecords             = 10;
        csDataTableInstance.showEditAll             = true;

    }

    private static testmethod void randomNumberGeneration_Test() 
    {
        ALL_DataTableComponent_Extension ctrlr = new ALL_DataTableComponent_Extension(csDataTableInstance);
        Integer rnd = ctrlr.randomNumber;
        for (Integer i = 0; i < 3; i++) 
        {
           // System.assert(rnd > 0);
            System.assert(rnd < 1000);
        }
    }

    private static testmethod void editStatus_Test() 
    {
        ALL_DataTableComponent_Extension ctrlr = new ALL_DataTableComponent_Extension(csDataTableInstance);
        System.assertEquals(null, ctrlr.isEdit);
        ctrlr.edit();
        System.assertEquals(true, ctrlr.isEdit);
        ctrlr.cancelEdit();
        System.assertEquals(false, ctrlr.isEdit);
    }

    private static testmethod void refreshPage_Test() 
    {
        ALL_DataTableComponent_Extension ctrlr = new ALL_DataTableComponent_Extension(csDataTableInstance);
        System.assertEquals(null, ctrlr.refreshPage());
    }

    private static testmethod void saveAndClose_Test()
    {
        // INIT
        ALL_DataTableComponent_Extension dtcExt = new ALL_DataTableComponent_Extension(csDataTableInstance);

        // TESTS PROPER
        // --- POSITIVE
        String recordId           = (String)csDataTableInstance.recordsPerObj.selectSObjList.get(0).sObj.get('Id');
        String recordInitialValue = (String)csDataTableInstance.recordsPerObj.selectSObjList.get(0).sObj.get('H_W_Specialist_PFW__c');

        String VALID_VALUE = UserInfo.getUserId();
        csDataTableInstance.recordsPerObj.selectSObjList.get(0).sObj.put('H_W_Specialist_PFW__c', VALID_VALUE);

        dtcExt.saveAndClose();

        System.assertEquals(false, dtcExt.isEdit);
        System.assertEquals(0, ApexPages.getMessages().size());

        String queriedValue = [SELECT H_W_Specialist_PFW__c FROM SubProject__c WHERE Id = :recordId].H_W_Specialist_PFW__c;
        System.assertNotEquals(recordInitialValue, queriedValue);
        System.assertEquals(VALID_VALUE, queriedValue);

        // --- NEGATIVE
        String INVALID_VALUE = 'WRONG_ID';
        //07/25/16     Venkata Shrivol    Removed the field label inside the error message RQ-07456
        String ERROR_MESSAGE = 'id value of incorrect type';
        csDataTableInstance.recordsPerObj.selectSObjList.get(0).sObj.put('H_W_Specialist_PFW__c', INVALID_VALUE);

        dtcExt.saveAndClose();

        System.assertEquals(true, dtcExt.isEdit);
        System.assertEquals(1, ApexPages.getMessages().size());
        System.assertEquals(ApexPages.Severity.ERROR, ApexPages.getMessages().get(0).getSeverity());
        System.assertEquals(true, ApexPages.getMessages().get(0).getDetail().contains(ERROR_MESSAGE));
    }

    private static testmethod void followUnfollowItems_Test() 
    {
        ALL_DataTableComponent_Extension.followItem(subProject.Id);
        System.assertEquals(1, [SELECT COUNT() FROM EntitySubscription WHERE ParentId = :subProject.Id AND SubscriberId = :UserInfo.getUserId()]);

        ALL_DataTableComponent_Extension.unFollowItem(subProject.Id);
        System.assertEquals(0, [SELECT COUNT() FROM EntitySubscription WHERE ParentId = :subProject.Id AND SubscriberId = :UserInfo.getUserId()]);
    }

}