SF Primes/src/objects/IMP_DataTableUISetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting for the Generic Data Table Component UI Setting</description>
    <label>IMP_DataTableUISetting</label>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHWEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-LAPALMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-PORTLAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-SOUTHEAST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contract_Roll_Called__c</fullName>
        <label>Contract Roll Called</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_User_Connections__c</fullName>
        <label>Number of User Connections</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add-On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy / Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Secondary_Project_Type__c</fullName>
        <label>Secondary Project Type</label>
        <picklist>
            <controllingField>Project_Type__c</controllingField>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitive Buy-Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rush (&lt;30 Days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box / Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box w/Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Only / Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franchise Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS Only Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Merge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal with Add-On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts Copy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interfaces/Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL/Data Merge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Programming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Tapes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProject_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASP-US/Toronto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASP-US/Vancouver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProject_Status__c</fullName>
        <label>SubProject Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold No Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fulldev2/src/classes/ALL_DataTableComponent_Controller_Test.cls
/*------------------------------------------------------------
Author:      Jerick Lauio   
Company:     Cloud Sherpas
Description: [Phase 2 Rel 1]TestClass for ALL_DataTableSample_Controller
History
02/04/15     Jerick Laurio          Drafted
03/13/15     Jerick Laurio          Created
03/20/15     Jerick Laurio          Cleaned and refactored
------------------------------------------------------------*/

@isTest
private class ALL_DataTableComponent_Controller_Test
{

    /************************************************
     * Author: jlaurio@cloudsherpas.com
     * Date: 3/13/2015
     * Description: TestClass for ALL_DataTableSample_Controller
     ***********************************************/
    @isTest
    static void testDataTable_Test1()
    {

        IMP_DataTableUISetting__c uiSetting = IMP_TestFactory_Helper.createDataTableUISetting();
        insert uiSetting;

        Project__c testProject              = IMP_TestFactory_Helper.buildProject(1);
            testProject.CMF_Numbers__c      = 'testCMFNumber';
            testProject.Project_Status__c   = 'Open';
            testProject.Project_Region__c   = 'ARG-CANADA';
        insert testProject;

        SubProject__c subProjectRec             = IMP_TestFactory_Helper.buildSubProject(testProject.Id);
            subProjectRec.SubProject_Region__c  = 'Alliance PC Solutions Admin';
            subProjectRec.Number_of_User_Connections__c = 10;
            subProjectRec.Secondary_Project_Type__c     = 'Competitive Buy-Sell';
        insert subProjectRec;

        EntitySubscription followRec = IMP_TestFactory_Helper.createFollowedRecord(subProjectRec.Id);
        insert followRec;
        
        ALL_DataTableComponent_Controller csDataTableInstance = new ALL_DataTableComponent_Controller();
        csDataTableInstance.objLabelName            = 'testObjectLabelName';
        csDataTableInstance.objApiName              = 'SubProject__c';
        csDataTableInstance.objIdPrefixCode         = '09213';
        csDataTableInstance.objEntityId             = '096171097412';
        csDataTableInstance.selectQueryString       = 'select Id, Name, Project_Type__c, SubProject_Status__c From SubProject__c';
        csDataTableInstance.selectWhereClauseString = 'WHERE Project_Type__c=\'Unhook\'';
        csDataTableInstance.queryLimitNum           = 5;
        csDataTableInstance.selectOrderString       = 'ORDER BY Id DESC';
        csDataTableInstance.objConsoleOpenInSubTab  = true;
        csDataTableInstance.showFilter              = true;
        csDataTableInstance.filterFieldSetName      = 'SubProjectFilterFields';
        csDataTableInstance.columnFieldSetName      = 'SubProjectDataTableFields';
        csDataTableInstance.useAltColumns           = true;
        csDataTableInstance.altColumnsJSONString    = 'testAltColumnJSON';
        csDataTableInstance.recordsPerPage          = 10;
        csDataTableInstance.size                    = 10;
        csDataTableInstance.noOfRecords             = 10;
        csDataTableInstance.showEditAll             = true;
        
        Boolean isDisplayTable = csDataTableInstance.isDisplayTable;
        Map<String,List<IMP_Library.fieldAPILabelWrapper>> fieldsPerObjectMap = csDataTableInstance.fieldsPerObjectMap;
        IMP_Library.genericSObjectWrapper recordsPerObj = csDataTableInstance.recordsPerObj;
        List<IMP_Library.fieldAPILabelWrapper> filterFieldList = csDataTableInstance.filterFieldList;
        SObject filterObject = csDataTableInstance.filterObject;
        IMP_Library.fieldAPILabelWrapper fieldWrap = new IMP_Library.fieldAPILabelWrapper();
        filterObject.put('SubProject_Status__c', 'Open');
        
        csDataTableInstance.initializeTableObject();
        csDataTableInstance.initializeFilterObject();
        Boolean hasNext = csDataTableInstance.hasNext;
        Boolean hasPrevious = csDataTableInstance.hasPrevious;
        Integer pagenumber = csDataTableInstance.pageNumber;

        IMP_Library.fieldAPILabelWrapper apiWrap = new IMP_Library.fieldAPILabelWrapper(); 
        apiWrap.apiName = 'CreatedDate';
        apiWrap.label = 'Created Date';
        apiWrap.type = 'DateTime';
        filterFieldList.add(apiWrap);

        apiWrap.apiName = 'Contract_Roll_Called__c';
        apiWrap.label = 'Contract Roll Called';
        apiWrap.type = 'Date';
        filterFieldList.add(apiWrap);

        csDataTableInstance.filterFieldList = filterFieldList;
        
        filterObject.put('SubProject_Status__c', 'Open');
        filterObject.put('Contract_Roll_Called__c', Date.today());

        csDataTableInstance.filterObject = subProjectRec;
        csDataTableInstance.refreshQuery();
        csDataTableInstance.resetTable();
        csDataTableInstance.formatInteger(5);
        csDataTableInstance.formatDateTime(DateTime.now());

        system.assert(fieldsPerObjectMap!=null);
        system.assert(recordsPerObj!=null);
        system.assert(filterFieldList!=null);
        system.assert(filterObject!=null);
        system.assert(apiWrap!=null);
    }

    /************************************************
     * Author: jlaurio@cloudsherpas.com
     * Date: 3/13/2015
     * Description: TestClass for ALL_DataTableSample_Controller
     ***********************************************/
    @isTest
    static void testDataTable_Test2()
    {

        IMP_DataTableUISetting__c uiSetting = IMP_TestFactory_Helper.createDataTableUISetting();
        insert uiSetting;

        Project__c testProject              = IMP_TestFactory_Helper.buildProject(1);
            testProject.CMF_Numbers__c      = 'testCMFNumber';
            testProject.Project_Status__c   = 'Open';
            testProject.Project_Region__c   = 'ARG-CANADA';
        insert testProject;

        SubProject__c subProjectRec             = IMP_TestFactory_Helper.buildSubProject(testProject.Id);
            subProjectRec.SubProject_Region__c  = 'Alliance PC Solutions Admin';
            subProjectRec.Number_of_User_Connections__c = 10;
            subProjectRec.Secondary_Project_Type__c     = 'Competitive Buy-Sell';
        insert subProjectRec;

        EntitySubscription followRec = IMP_TestFactory_Helper.createFollowedRecord(subProjectRec.Id);
        insert followRec;
        
        ALL_DataTableComponent_Controller csDataTableInstance = new ALL_DataTableComponent_Controller();
        csDataTableInstance.objLabelName            = 'testObjectLabelName';
        csDataTableInstance.objApiName              = 'SubProject__c';
        csDataTableInstance.objIdPrefixCode         = '09213';
        csDataTableInstance.objEntityId             = '096171097412';
        csDataTableInstance.selectQueryString       = 'select Id, Name, Project_Type__c, SubProject_Status__c From SubProject__c';
        csDataTableInstance.selectWhereClauseString = 'WHERE Project_Type__c=\'Unhook\'';
        csDataTableInstance.selectOrderString       = 'ORDER BY Id DESC';
        csDataTableInstance.objConsoleOpenInSubTab  = true;
        csDataTableInstance.showFilter              = true;
        csDataTableInstance.filterFieldSetName      = 'SubProjectFilterFields';
        csDataTableInstance.columnFieldSetName      = 'SubProjectDataTableFields';
        csDataTableInstance.useAltColumns           = true;
        csDataTableInstance.altColumnsJSONString    = 'testAltColumnJSON';
        csDataTableInstance.recordsPerPage          = 10;
        csDataTableInstance.size                    = 10;
        csDataTableInstance.noOfRecords             = 10;
        csDataTableInstance.showEditAll             = true;
        
        Boolean isDisplayTable = csDataTableInstance.isDisplayTable;
        Map<String,List<IMP_Library.fieldAPILabelWrapper>> fieldsPerObjectMap = csDataTableInstance.fieldsPerObjectMap;
        IMP_Library.genericSObjectWrapper recordsPerObj = csDataTableInstance.recordsPerObj;
        List<IMP_Library.fieldAPILabelWrapper> filterFieldList = csDataTableInstance.filterFieldList;
        SObject filterObject = csDataTableInstance.filterObject;
        IMP_Library.fieldAPILabelWrapper fieldWrap = new IMP_Library.fieldAPILabelWrapper();
        filterObject.put('SubProject_Status__c', 'Open');
        
        csDataTableInstance.initializeTableObject();
        csDataTableInstance.initializeFilterObject();
        Boolean hasNext = csDataTableInstance.hasNext;
        Boolean hasPrevious = csDataTableInstance.hasPrevious;
        Integer pagenumber = csDataTableInstance.pageNumber;

        IMP_Library.fieldAPILabelWrapper apiWrap = new IMP_Library.fieldAPILabelWrapper(); 
        apiWrap.apiName = 'CreatedDate';
        apiWrap.label = 'Created Date';
        apiWrap.type = 'DateTime';
        filterFieldList.add(apiWrap);

        apiWrap.apiName = 'Contract_Roll_Called__c';
        apiWrap.label = 'Contract Roll Called';
        apiWrap.type = 'Date';
        filterFieldList.add(apiWrap);

        csDataTableInstance.filterFieldList = filterFieldList;
        
        filterObject.put('SubProject_Status__c', 'Open');
        filterObject.put('Contract_Roll_Called__c', Date.today());

        csDataTableInstance.filterObject = filterObject;
        csDataTableInstance.refreshQuery();
        csDataTableInstance.resetTable();
        csDataTableInstance.formatInteger(5);
        csDataTableInstance.formatDateTime(DateTime.now());

        system.assert(fieldsPerObjectMap!=null);
        system.assert(recordsPerObj!=null);
        system.assert(filterFieldList!=null);
        system.assert(filterObject!=null);
        system.assert(apiWrap!=null);
    }

    /************************************************
     * Author: jlaurio@cloudsherpas.com
     * Date: 3/13/2015
     * Description: TestClass for ALL_DataTableSample_Controller
     ***********************************************/
    @isTest
    static void testDataTableNoWhereClause()
    {
        
        IMP_DataTableUISetting__c uiSetting = IMP_TestFactory_Helper.createDataTableUISetting();
        insert uiSetting;

        Project__c testProject              = IMP_TestFactory_Helper.buildProject(1);
            testProject.CMF_Numbers__c      = 'testCMFNumber';
            testProject.Project_Status__c   = 'Open';
            testProject.Project_Region__c   = 'ARG-CANADA';
        insert testProject;

        SubProject__c subProjectRec             = IMP_TestFactory_Helper.buildSubProject(testProject.Id);
            subProjectRec.SubProject_Region__c  = 'Alliance PC Solutions Admin';
            subProjectRec.Number_of_User_Connections__c = 10;
            subProjectRec.Secondary_Project_Type__c     = 'Competitive Buy-Sell';
        insert subProjectRec;
        
        ALL_DataTableComponent_Controller csDataTableInstance = new ALL_DataTableComponent_Controller();
        csDataTableInstance.objLabelName            = 'testObjectLabelName';
        csDataTableInstance.objApiName              = 'SubProject__c';
        csDataTableInstance.selectQueryString       = 'select Id, Name, Project_Type__c, SubProject_Status__c From SubProject__c';
        csDataTableInstance.queryLimitNum           = 5;
        csDataTableInstance.selectWhereClauseString = null; 
        csDataTableInstance.showFilter              = true;
        csDataTableInstance.filterFieldSetName      = 'SubProjectFilterFields';
        csDataTableInstance.columnFieldSetName      = '';

        ApexPages.StandardSetController setCon = csDataTableInstance.setCon;
        Boolean isDisplayTable = csDataTableInstance.isDisplayTable;
        Map<String,List<IMP_Library.fieldAPILabelWrapper>> fieldsPerObjectMap = csDataTableInstance.fieldsPerObjectMap;
        IMP_Library.genericSObjectWrapper recordsPerObj = csDataTableInstance.recordsPerObj;
        List<IMP_Library.fieldAPILabelWrapper> filterFieldList = csDataTableInstance.filterFieldList;
        
        SObject filterObject = csDataTableInstance.filterObject;
        IMP_Library.fieldAPILabelWrapper fieldWrap = new IMP_Library.fieldAPILabelWrapper();

        
        csDataTableInstance.initializeTableObject();
        csDataTableInstance.initializeFilterObject();
        Boolean hasNext = csDataTableInstance.hasNext;
        Boolean hasPrevious = csDataTableInstance.hasPrevious;
        Integer pagenumber = csDataTableInstance.pageNumber;
        
        IMP_Library.fieldAPILabelWrapper apiWrap = new IMP_Library.fieldAPILabelWrapper(); 
        apiWrap.apiName = 'Contract_Roll_Called__c';
        apiWrap.label = 'Contract Roll Called';
        apiWrap.type = 'Date';
        filterFieldList.add(apiWrap);
        csDataTableInstance.filterFieldList = filterFieldList;
        
        filterObject.put('SubProject_Status__c', 'Open');
        filterObject.put('Contract_Roll_Called__c', Date.today());

        csDataTableInstance.filterObject = filterObject;
        csDataTableInstance.refreshQuery();
        csDataTableInstance.first();
        csDataTableInstance.last();
        csDataTableInstance.previous();
        csDataTableInstance.next();

        system.assert(apiWrap!=null);
    }

    /************************************************
     * Author: jlaurio@cloudsherpas.com
     * Date: 3/13/2015
     * Description: TestClass for ALL_DataTableSample_Controller
     ***********************************************/
    @isTest
    static void testDataTableNegativeTest()
    {
        
        IMP_DataTableUISetting__c uiSetting = IMP_TestFactory_Helper.createDataTableUISetting();
        insert uiSetting;

        Project__c testProject              = IMP_TestFactory_Helper.buildProject(1);
            testProject.CMF_Numbers__c      = 'testCMFNumber';
            testProject.Project_Status__c   = 'Open';
            testProject.Project_Region__c   = 'ARG-CANADA';
        insert testProject;

        SubProject__c subProjectRec             = IMP_TestFactory_Helper.buildSubProject(testProject.Id);
            subProjectRec.SubProject_Region__c  = 'Alliance PC Solutions Admin';
            subProjectRec.Number_of_User_Connections__c = 10;
            subProjectRec.Secondary_Project_Type__c     = 'Competitive Buy-Sell';
        insert subProjectRec;
        
        ALL_DataTableComponent_Controller csDataTableInstance = new ALL_DataTableComponent_Controller();
        csDataTableInstance.objLabelName            = 'testObjectLabelName';
        csDataTableInstance.objApiName              = 'SubProject__c';
        //csDataTableInstance.selectQueryString       = 'select Id, Name, Project_Type__c, SubProject_Status__c From SubProject__c';
        csDataTableInstance.selectWhereClauseString = null; 
        csDataTableInstance.showFilter              = false;
        //csDataTableInstance.filterFieldSetName      = 'SubProjectFilterFields';
        csDataTableInstance.columnFieldSetName      = '';

        ApexPages.StandardSetController setCon = csDataTableInstance.setCon;
        Boolean isDisplayTable = csDataTableInstance.isDisplayTable;
        Map<String,List<IMP_Library.fieldAPILabelWrapper>> fieldsPerObjectMap = csDataTableInstance.fieldsPerObjectMap;
        IMP_Library.genericSObjectWrapper recordsPerObj = csDataTableInstance.recordsPerObj;
        List<IMP_Library.fieldAPILabelWrapper> filterFieldList = csDataTableInstance.filterFieldList;
        
        SObject filterObject = csDataTableInstance.filterObject;
        IMP_Library.fieldAPILabelWrapper fieldWrap = new IMP_Library.fieldAPILabelWrapper();

        
        csDataTableInstance.initializeTableObject();
        try{
            csDataTableInstance.initializeFilterObject();
        }
        catch(Exception e){
            System.debug('\n\n*****Exception='+e);
        }
        Boolean hasNext = csDataTableInstance.hasNext;
        Boolean hasPrevious = csDataTableInstance.hasPrevious;
        Integer pagenumber = csDataTableInstance.pageNumber;
        
        csDataTableInstance.first();
        csDataTableInstance.last();
        csDataTableInstance.previous();
        csDataTableInstance.next();
        csDataTableInstance.formatDate(Datetime.now());
        //system.assert(apiWrap!=null);
    }
}