SF Primes/src/objects/IMP_DataTableUISetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting for the Generic Data Table Component UI Setting</description>
    <fields>
        <fullName>MaxNumberOfSearchResults__c</fullName>
        <description>This controls the maximum records to be queried. Can be overridden by the component&apos;s query limit attribute.</description>
        <inlineHelpText>This controls the maximum records to be queried. Can be overridden by the component&apos;s query limit attribute.</inlineHelpText>
        <label>Max Number Of Search Results</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfRecordsPerObject__c</fullName>
        <description>This will control by the number of records to show per page of the table. This can be overridden by the component&apos;s rowsPerPage attribute</description>
        <inlineHelpText>This will control by the number of records to show per page of the table. This can be overridden by the component&apos;s rowsPerPage attribute</inlineHelpText>
        <label>Number Of Records Per Object</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IMP_DataTableUISetting</label>
</CustomObject>

SF Primes/src/objects/IMP_FollowedRecordsSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This controls the object being displayed in the Followed Records Component</description>
    <fields>
        <fullName>SobjectFieldsetPair__c</fullName>
        <description>The objects and its fieldset that will be accessed. One API name and fieldset pair per line. e.g. CustomObject__c.FieldsetName</description>
        <label>SObject Fieldset Pair</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>IMP_FollowedRecordsDataTableSetting</label>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHWEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-LAPALMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-WEST-PORTLAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIONAL-SOUTHEAST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>CMF_Numbers__c</fullName>
        <label>CMF Number(s)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_User_Connections__c</fullName>
        <label>Number of User Connections</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Secondary_Project_Type__c</fullName>
        <label>Secondary Project Type</label>
        <picklist>
            <controllingField>Project_Type__c</controllingField>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitive Buy-Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rush (&lt;30 Days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box / Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Box w/Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Only / Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franchise Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCS Only Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Merge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal with Add-On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts Copy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interfaces/Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL/Data Merge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Programming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Tapes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubProject_Region__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALLIANCE-PC SOLUTIONS-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBURY ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASP-US/Toronto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASP-US/Vancouver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTONATION-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANADA-WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - ADMINISTRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - SOUTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENTERPRISE - WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group 1 - West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-ADMIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-CENTRAL-FLORENCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-NORTHEAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJOR-SOUTHEAST</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_FollowedRecords_Controller_Test.cls
/*------------------------------------------------------------
Author:      Jerick Laurio
Company:     Cloud Sherpas
Description: [Phase 2 Rel 1]Test Class for IMP_FollowedRecords_Controller
Test Class:  
History
03/12/15     Jerick Laurio          Created
03/20/15     Jerick Laurio          Cleaned and refactored
04/30/15     Jerick Laurio          Bug fixing
------------------------------------------------------------*/
@isTest
private class IMP_FollowedRecords_Controller_Test {
    
    /************************************************
    * Author: jlaurio@cloudsherpas.com
    * Date: 3/12/2015
    * Description: Positive scenario happy path
    **********************************************
    @isTest
    static void UnitTest_PositiveHappyPath()
    {
        // Given

        IMP_DataTableUISetting__c uiSetting = new IMP_DataTableUISetting__c();
        uiSetting.MaxNumberOfSearchResults__c = 5;
        uiSetting.NumberOfRecordsPerObject__c = 5;
        insert uiSetting;

        IMP_FollowedRecordsSetting__c frSetting = new IMP_FollowedRecordsSetting__c();
        frSetting.SobjectFieldsetPair__c = 'SubProject__c.SubProjectDataTableFields\nProject_Task__c.ProjectTaskDataTableFields\nProject_Log__c.ProjectLogDataTableFields'; 
        insert frSetting;

        Project__c testProject              = IMP_TestFactory_Helper.buildProject(1);
            testProject.CMF_Numbers__c      = 'testCMFNumber';
            testProject.Project_Status__c   = 'Open';
            testProject.Project_Region__c   = 'ARG-CANADA';
        insert testProject;

        EntitySubscription followRec1 = IMP_TestFactory_Helper.createFollowedRecord(testProject.Id);
        insert followRec1;

        SubProject__c subProjectRec             = IMP_TestFactory_Helper.buildSubProject(testProject.Id);
            subProjectRec.SubProject_Region__c  = 'Alliance PC Solutions Admin';
            subProjectRec.Number_of_User_Connections__c = 10;
            subProjectRec.Secondary_Project_Type__c     = 'Competitive Buy-Sell';
        insert subProjectRec;

        EntitySubscription followRec2 = IMP_TestFactory_Helper.createFollowedRecord(subProjectRec.Id);
        insert followRec2;

        // When
        PageReference pageRef = Page.IMP_HomePageFollowedTabSection;
        pageRef.getParameters().put('strIndex', '0');        
        Test.setCurrentPage(pageRef);
        IMP_FollowedRecords_Controller controller = new IMP_FollowedRecords_Controller();
        String selected = controller.selected;
        List<String> objectsToDisplayList = controller.objectsToDisplayList;
        controller.followedRecDTSetting = null;
        controller.objectsFieldSetMap = null;
        IMP_FollowedRecordsSetting__c userDTSetting = controller.userDTSetting;
        String selectedIndex = controller.selectedIndex;
        Map<String,String> objectsFieldSetMap = controller.objectsFieldSetMap;
        Set<Id> subProjectIds = new Set<Id>();
        subProjectIds.add(subProjectRec.Id);
        subProjectIds.add(testProject.Id);
        String createStringIdSet = controller.createStringIdSet(subProjectIds);
        controller.saveUserDataTableSetting();
        //String createSOQLSelect = controller.createSOQLSelect(Schema.FieldSet fieldSetName, String objectAPIName)SubProjectDataTableFields
        // Then
        System.debug('@#@#@#[TEST] controller.dataTableWrapper='+controller.dataTableWrapper);
        system.assert(controller.dataTableWrapper!=null);
    }

    /************************************************
    * Author: jlaurio@cloudsherpas.com
    * Date: 3/12/2015
    * Description: Negative scenario
    **********************************************
    @isTest
    static void UnitTest_PositiveNoSubscription()
    {
        // Given
        IMP_DataTableUISetting__c uiSetting = new IMP_DataTableUISetting__c();
        uiSetting.MaxNumberOfSearchResults__c = 5;
        uiSetting.NumberOfRecordsPerObject__c = 5;
        insert uiSetting;

        IMP_FollowedRecordsSetting__c frSetting = new IMP_FollowedRecordsSetting__c();
        frSetting.SobjectFieldsetPair__c = 'SubProject__c.SubProjectDataTableFields\nProject_Task__c.ProjectTaskDataTableFields\nProject_Log__c.ProjectLogDataTableFields'; 
        insert frSetting;

        // When
        IMP_FollowedRecords_Controller controller = new IMP_FollowedRecords_Controller();

        // Then
        System.debug('@#@#@#[TEST] controller.dataTableWrapper='+controller.dataTableWrapper);
        system.assert(controller.dataTableWrapper!=null);
    }*/
    
}