SF Primes/src/objects/IMP_ProfilesToByPass__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of profiles that will bypass checking of project type during site creation.</description>
    <fields>
        <fullName>Profile__c</fullName>
        <description>Bypassing profile</description>
        <label>Profile</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IMP_ProfilesToByPass</label>
</CustomObject>

SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Log__c.object
<CustomObject>
    <description>Contains various types of Project Log including Action Items, Change Requests, Issues, Lessons Learned and Risks to associate with either a Project or SubProject.</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Retrieves Project Name based on Record Type.</description>
        <formula>CASE( Record_Type_Name__c , 
&quot;Action Item&quot;, Project_Action_Items__r.Name , 
&quot;Change Request&quot;, Project_Change_Request__r.Name ,
&quot;Issue&quot;, Project_Issue__r.Name ,
&quot;Lesson Learned&quot;, Project_Lessons_Learned__r.Name ,
&quot;Risk&quot;, Project_Risk__r.Name ,
&quot;&quot;)</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <description>Retrieves SubProject Name based on Record Type</description>
        <formula>CASE( Record_Type_Name__c ,
&quot;Action Item&quot;,  Sub_Project_Action_Items__r.SubProject_Name__c ,
&quot;Change Request&quot;,  Sub_Project_Change_Request__r.SubProject_Name__c ,
&quot;Issue&quot;,  Sub_Project_Issue__r.SubProject_Name__c ,
&quot;Lesson Learned&quot;,  Sub_Project_Lessons_Learned__r.SubProject_Name__c ,
&quot;Risk&quot;,  Sub_Project_Risk__r.SubProject_Name__c ,
&quot;&quot;)</formula>
        <label>SubProject</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Risk__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Risk</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Log</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProject_Name__c</fullName>
        <label>SubProject Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_CDK_Contact__c.object
<CustomObject>
    <description>Junction Object to relate multiple CDK Contacts to a SubProject</description>
    <fields>
        <fullName>CDK_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CDK Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProject_CDK_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject CDK Contacts</relationshipLabel>
        <relationshipName>SubProject_CDK_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject CDK Contact</label>
    <nameField>
        <displayFormat>SPCDK-{000000000}</displayFormat>
        <label>SP-CDK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject CDK Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_SubProjectCDKContact_Test.cls
/*---------------------------------------
 * Test Class for : IMP_SubProjectCDKContact_Handler
------------------------------------------
2016-05-20 -venkata.shrivol@cdk.com -Created
2016-06-06 -venkata.shrivol@cdk.com -change the confidential boolean reference to confidentiality status field. 
2016-12-05 -venkata.shrivol@cdk.com -commented project object reference RQ-08305
----------------------------------------*/
@isTest
public class IMP_SubProjectCDKContact_Test 
{
	@testSetup
	static void prepareTestData()
	{
		//customSettings
		IMP_ProfilesToByPass__c imptoByPass = new IMP_ProfilesToByPass__c();
		imptoByPass.Name='SubProject_Sharing';
		imptoByPass.Profile__c = 'ADPDS - Admin - System Administrator,Cobalt Cast Iron Integration,ADPDS - Admin - System Administrator-fsalwen,ADPDS - Admin - Integration User';
		insert imptoByPass;
		
		list<User> testUsersList = new list<User>();
		User testUser1 = DS_TestObjects.NewUser();
		testUser1.FirstName = 'TestName1';
		testUsersList.add(testUser1);
		User testUser2 = DS_TestObjects.NewUser();
		testUser2.FirstName = 'TestName2';
		testUsersList.add(testUser2);	
		
		insert testUsersList;
		
		/*Project__c testProject = IMP_TestFactory_Helper.buildProject(0);
        insert testProject;*/
        
        list<Subproject__c> testSubList = new list<Subproject__c>();
        SubProject__c subprj1 = 	IMP_TestFactory_Helper.buildSubProject();
        subprj1.SubProject_Name__c = 'Test SubProject 1';
        subprj1.Confidentiality_Status__c = 'Restricted';
        testSubList.add(subprj1);
		SubProject__c subprj2 = 	IMP_TestFactory_Helper.buildSubProject();
		subprj2.SubProject_Name__c = 'Test SubProject 2';
		subprj2.Confidentiality_Status__c = 'Restricted';
		testSubList.add(subprj2);
        insert testSubList;
        
        Project_Log__c testLog = IMP_TestFactory_Helper.buildRiskLog(subprj1.Id);
        insert testLog;
        
        list<SubProject_CDK_Contact__c> cdkContactsList = new list<SubProject_CDK_Contact__c>();
        SubProject_CDK_Contact__c testCdkContact = new SubProject_CDK_Contact__c();
        testCdkContact.CDK_Contact__c = testUser1.Id;
        testCdkContact.SubProject__c = subprj1.Id;
        testCdkContact.User_Visibility_Enabled__c = true;
        insert testCdkContact;
        
        
	}

	static testMethod void testCDKContactInsert()
	{
		list<Project_Log__c> projLogList = [select Id, Sub_Project_Risk__c from Project_Log__c where Sub_Project_Risk__r.SubProject_Name__c='Test SubProject 1'];
		Project_Log__c thisLog = projLogList.size() > 0 ? projLogList.get(0) : new Project_Log__c();
		
		list<SubProject__Share> sharedSubProjectRecord = [
		select Id from SubProject__Share
		where parentId = :thisLog.Sub_Project_Risk__c];
		
		system.assertEquals(2, sharedSubProjectRecord.size());
		
	} 
	
	static testMethod void testCDKContactDelete()
	{
		
		list<SubProject_CDK_Contact__c> cdkConList = [
			select Id, SubProject__c from SubProject_CDK_Contact__c 
			where SubProject__r.SubProject_Name__c='Test SubProject 1'];
		SubProject_CDK_Contact__c thisCDKContact = cdkConList.size() > 0 ? cdkConList.get(0) : new SubProject_CDK_Contact__c();
		
		list<Project_Log__c> projLogList = [select Id, Sub_Project_Risk__c from Project_Log__c where Sub_Project_Risk__r.SubProject_Name__c='Test SubProject 1'];
		Project_Log__c thisLog = projLogList.size() > 0 ? projLogList.get(0) : new Project_Log__c();
		
		Test.startTest();
			delete thisCDKContact;
		Test.stopTest();
		
		list<SubProject__Share> sharedSubProjectRecord = [
		select Id, parentId, userOrGroupId from SubProject__Share
		where parentId = :thisLog.Sub_Project_Risk__c];
		
		system.assertEquals(1, sharedSubProjectRecord.size());	
		
	}  
	
	static testMethod void onUserVisibilityFieldUpdate()
	{
		list<SubProject_CDK_Contact__c> cdkConList = [
			select Id from SubProject_CDK_Contact__c 
			where SubProject__r.SubProject_Name__c='Test SubProject 1'];
		SubProject_CDK_Contact__c thisCDKContact = cdkConList.size() > 0 ? cdkConList.get(0) : new SubProject_CDK_Contact__c();
		
		Test.startTest();
			thisCDKContact.User_Visibility_Enabled__c =false;
			update thisCDKContact;
		Test.stopTest();
		
		list<SubProject__Share> sharedSubProjectRecord = [
		select Id, parentId, userOrGroupId from SubProject__Share
		where parentId = :thisCDKContact.SubProject__c];
		
		system.assertEquals(1, sharedSubProjectRecord.size());
	}  
	
	static testMethod void onSubProjectAndUserFieldChange()
	{
		list<SubProject__c> insertedSubProjects = [
			select Id,SubProject_Name__c, (select Id from SubProject_CDK_Contacts__r)
			from SubProject__c where SubProject_Name__c IN ('Test SubProject 1','Test SubProject 2')];
		
		map<string, SubProject__c> subProjectMap = new map<String,SubProject__c>();
		for(SubProject__c sub:insertedSubProjects)
		{
			subProjectMap.put(sub.SubProject_Name__c, sub);	
		}
		
		list<User> userList = [select Id,FirstName from User where FirstName ='TestName2'];
		User thisUser = userList.size() > 0 ? userList.get(0) : new User();
		
		
		list<SubProject_CDK_Contact__c> cdkConList = subProjectMap.get('Test SubProject 1').SubProject_CDK_Contacts__r != null ? 
													 subProjectMap.get('Test SubProject 1').SubProject_CDK_Contacts__r :
													 new list<SubProject_CDK_Contact__c>();
													 
		SubProject_CDK_Contact__c thisContact = cdkConList.size() > 0 ? cdkConList.get(0) : new SubProject_CDK_Contact__c();
		
		Test.startTest();
			if(subProjectMap.get('Test SubProject 2')!=null)
			{
				thisContact.SubProject__c = subProjectMap.get('Test SubProject 2').Id;
			}
			if(thisUser!=null)
			{
				thisContact.CDK_Contact__c = thisUser.Id;
			}
			upsert thisContact;
		Test.stopTest();
		
		list<SubProject__Share> sharedSubProjectRecord = [
		select Id, parentId, userOrGroupId from SubProject__Share
		where parentId = :subProjectMap.get('Test SubProject 1').Id
        or parentId = :thisContact.SubProject__c];
		
		system.assertEquals(3, sharedSubProjectRecord.size());
	}
	
}