SF Primes/src/objects/Laser_Artwork_Order__c.object
<CustomObject>
    <fields>
        <fullName>Last_Followup_Date__c</fullName>
        <label>Last Follow-up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_Follow_up_Calls__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Follow-up Calls</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold-Pre FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/S Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/S Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artwork to LFD Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proofs to LAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AWIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Mapping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms to LIS Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At LI Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval - ELF Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Data Mapping/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold-CDK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Collected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded/Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval-FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-FA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Forms Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DS_TaskRollUpHandler.cls
//2017-04-05 ragashalini.koka@cdk.com - Commented the class as the field Track_Follow_up_c is no longer used for RQ-08811
public class DS_TaskRollUpHandler 
{
    public static void TaskRollUp(list<task> newTasklist)
    { 
       /* set<ID> LaoIDs = new set<ID>();        
        for(task t: newTasklist)
        {
            if(t.WhatId != null)
            {
                LaoIDs.add(t.WhatId);                
            }
        }
        
        //query related LAO's
        map<ID, Laser_Artwork_Order__c> UniqueLaosMap;        
        if(LaoIDs != null && !LaoIDs.isEmpty())
        {
            UniqueLaosMap = new map<ID, Laser_Artwork_Order__c>([
                Select Id, Name, Number_Follow_up_Calls__c, Order_Status__c
                From Laser_Artwork_Order__c
                Where ID IN :LaoIDs
            ]);                
        } 
        
        for(Task t: newTasklist)
        {
            for(Laser_Artwork_Order__c lao: UniqueLaosMap.values())
            {
                if(t.WhatId != null  && t.WhatId == lao.Id)
                {
                    //if(t.Track_Follow_up__c)
                    //{
                        Laser_Artwork_Order__c UniqueLAO = UniqueLaosMap.get(t.WhatId);
                        
                        if(UniqueLAO.Number_Follow_up_Calls__c == null)
                        {
                            UniqueLAO.Number_Follow_up_Calls__c = 0;
                            UniqueLAO.Number_Follow_up_Calls__c += 1;
                        }
                        else
                        {
                            UniqueLAO.Number_Follow_up_Calls__c += 1;
                        }
                        
                        lao.Last_Followup_Date__c = DateTime.now();
                   // }            
                    //t.Track_Follow_up__c = false; //set it back to false
                }
            }
        }
            
        if(UniqueLaosMap.values() != null && !UniqueLaosMap.values().isEmpty())    
        {  
            try
            {
                ALL_UtilitiesData.SerializesObjectList(UniqueLaosMap.values(), 'update');
                //Update UniqueLaosMap.values();
            }Catch(DmlException dx)
            {
                if(newTasklist != null && newTasklist.size() == 1)
                {
                    newTasklist[0].addError('On the Related LAO record ' + dx.getDmlMessage(0));
                }
            }
        }    */        
        
    }      
}