SF Primes/src/objects/Laser_Artwork_Order__c.object
<CustomObject>
    <fields>
        <fullName>By_Pass_Forms_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>By Pass Forms Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Forms_Order6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Install_Date__c</fullName>
        <label>Estimated Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Forms_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roll_Call_Date__c</fullName>
        <label>Roll Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubProject_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Forms Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Input scope details and notes (i.e. HOLD information, contacts w/o workspace, etc.)</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Roll_Called__c</fullName>
        <label>Contract Roll Called</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Install_Date_EID__c</fullName>
        <label>Estimated Install Date (EID)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go-Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjectsMgrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add-On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy / Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Training_Implementation_Client_Mgr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training &amp; Implementation Client Mgr</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_External_Reference__c.object
<CustomObject>
    <description>This object is used to store the Lookup relationships to external objects that are related to the Sub-Project like the Laser Artwork Order, NIS Mission etc.</description>
    <fields>
        <fullName>LAO_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the LAO Object</description>
        <label>FO ID</label>
        <referenceTo>Laser_Artwork_Order__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject External Reference</label>
    <nameField>
        <displayFormat>SPER-{0000000}</displayFormat>
        <label>External Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject External References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fulldev2/src/classes/IMP_SubProjectExternalReference_Handler.cls
/*------------------------------------------------------------
Author:        Vishal Bandari
Description:   To Update Forms_Order__c when SubProject_External_Reference__c is inserted
Test Class:    IMP_SperToFormsOrderUpdate_Test
Created on:    07 September 2015.
Code Coverage: 100%
------------------------------------------------------------
History
07/15/15        Vishal Bandari          RQ-04982: Added updateFormOrders method
09/15/15        Siva Pragada            Added null checks for for loop lists and the objects obtained from the maps.
09/17/15        Venkata Shrivol         Added some touch-ups before update call to resolve test class error
2015-11-04      vishal.bandari@cdk.com  RQ-05690: Added code to update on Estimated_Install_Date__c field in Laser_Artwork_Order__c
2015-12-15      vishal.bandari@cdk.com  RQ-05934: Added code to update Subproject__c field in Laser_Artwork_Order__c
2015-12-15      vishal.bandari@cdk.com  RQ-05938: Added code to update Client_Manager__c field in Laser_Artwork_Order__c
2016-01-20      vishal.bandari@cdk.com  RQ-06056: Added code to update Project_type__c field in Laser_Artwork_Order__c
------------------------------------------------------------*/
global with sharing class IMP_SubProjectExternalReference_Handler 
{
    public static void beforeInsert(list<SubProject_External_Reference__c> newSObjects) 
    {
        //update the project field via trigger in the backend, rather than allowing the user 
        //to manually select the value of the project field while creating a new Project External Reference
        Set<Id> subProjectIds = new Set<Id>();
        List<SubProject_External_Reference__c> subprojectExternalToUpdate = new List<SubProject_External_Reference__c>();
        
        for(SubProject_External_Reference__c ser: newSObjects)
        {
            if(ser.SubProject__c != null)
            {
                subprojectExternalToUpdate.add(ser);
                
                //Add SubProject Id to set to be used for query in handler
                subProjectIds.add(ser.SubProject__c);
            }
        }
        
        //Process records
        if(!subprojectExternalToUpdate.isEmpty())
        {
            //Update Project value on SubProject External Reference based on SubProject's Project
            IMP_Project_Utility.updateProjectField(null, null,subprojectExternalToUpdate,null, subProjectIds);
        }
        
    }
    
    public static void beforeUpdate(list<SubProject_External_Reference__c> newSObjects, map<Id, SubProject_External_Reference__c> oldSObjectsById) 
    {
        
    }
    
    /*public static void beforeDelete(list<SubProject_External_Reference__c> oldSObjects, map<Id, SubProject_External_Reference__c> oldSObjectsById) 
    {
        
    }*/
    
    public static void afterInsert(list<SubProject_External_Reference__c> newSObjects) 
    {
        List<Id> laoIds = new List<Id>();
        List<Id> subprojectIds = new List<Id>();
        
        if(newSObjects != null && !newSObjects.isEmpty())
        {
            for(SubProject_External_Reference__c sper : newSObjects)
            {
                laoIds.add(sper.LAO_ID__c);
                subprojectIds.add(sper.SubProject__c);
            }
        }
        
        Map<Id,Subproject__c> subprojectMap = new Map<Id,Subproject__c>([
            SELECT Id, Name, Confidential__c, Go_Live_Date__c, Project_Manager__c,Project_Type__c,Comments__c, Contract_Roll_Called__c, Training_Implementation_Client_Mgr__c, Estimated_Install_Date_EID__c, Impact_Project_Numbers__c 
            FROM Subproject__c
            WHERE ID IN: subprojectIds
        ]);
        
        Map<Id,Laser_Artwork_Order__c> laoMap = new Map<Id,Laser_Artwork_Order__c>([
            SELECT Id, Confidential__c, Go_Live_Date__c, 
            Project_Manager__c, Roll_Call_Date__c, SubProject_Comments__c,
            Impact_Project_Numbers__c, By_Pass_Forms_Validation_Rules__c, Estimated_Install_Date__c, Client_Manager__c, Project_Type__c 
            FROM Laser_Artwork_Order__c
            WHERE ID IN: laoIds
        ]);
        
        if(newSObjects != null && !newSObjects.isEmpty() && laoMap != null && !laoMap.isEmpty())
        {
            for(SubProject_External_Reference__c sperObj : newSObjects)
            {
                Laser_Artwork_Order__c laoObj = laoMap.get(sperObj.LAO_ID__c);
                Subproject__c subProjectObj = subprojectMap.get(sperObj.SubProject__c);
                if(laoObj != null && subProjectObj != null)
                {
                    laoObj.By_Pass_Forms_Validation_Rules__c = !laoObj.By_Pass_Forms_Validation_Rules__c;
                    laoObj.Confidential__c = subProjectObj.Confidential__c;
                    laoObj.Go_Live_Date__c = subProjectObj.Go_Live_Date__c;
                    laoObj.Project_Manager__c = subProjectObj.Project_Manager__c;
                    laoObj.Roll_Call_Date__c = subProjectObj.Contract_Roll_Called__c;
                    laoObj.Impact_Project_Numbers__c = subProjectObj.Impact_Project_Numbers__c;
                    
                    //2015-11-04 vishal.bandari@cdk.com RQ-05690 added code to update on Estimated_Install_Date__c
                    laoObj.Estimated_Install_Date__c = subProjectObj.Estimated_Install_Date_EID__c;
                    
                    //2015-12-15 vishal.bandari@cdk.com RQ-05934 added code to update on Subproject__c
                    laoObj.SubProject__c                     = subProjectObj.Name;
                    
                    //2015-12-15 vishal.bandari@cdk.com RQ-05938 added code to update on Client_Manager__c
                    laoObj.Client_Manager__c = subProjectObj.Training_Implementation_Client_Mgr__c;
                    
                    //2016-01-20 vishal.bandari@cdk.com RQ-06056 added code to update on SubProject_Comments__c and Project_Type__c
                    laoObj.SubProject_Comments__c = subProjectObj.Comments__c;
                    laoObj.Project_Type__c = subProjectObj.Project_Type__c;
                    
                    laoMap.put(sperObj.LAO_ID__c,laoObj );
                }
            } 
        }
        if(laoMap != null && !laoMap.isEmpty())
        {
            update laoMap.values();
        } 
    }
    
    public static void afterUpdate(list<SubProject_External_Reference__c> newSObjects, map<Id, SubProject_External_Reference__c> oldSObjectsById) 
    {
        
    }
    
    /*public static void afterDelete(list<SubProject_External_Reference__c> oldSObjects, map<Id, SubProject_External_Reference__c> oldSObjectsById) 
    {
        
    }*/
    
    /*public static void afterUndelete(list<SubProject_External_Reference__c> newSObjects, map<Id, SubProject_External_Reference__c> oldSObjectsById) 
    {
        
    }*/
}