SF Primes/src/objects/Laser_Artwork_Order__c.object
<CustomObject>
    <fields>
        <fullName>LAO_Value__c</fullName>
        <label>Artwork Value $</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stock_Order_Total__c</fullName>
        <label>Stock Order-Total $</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Forms__c</fullName>
        <description>Total Number of Forms</description>
        <label>Total Number of Forms</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <summarizedField>Laser_Ordered_Forms__c.Unit_Price_Override__c</summarizedField>
        <summaryForeignKey>Laser_Ordered_Forms__c.Laser_Artwork_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Forms Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Laser_Ordered_Forms__c.object
<CustomObject>
    <description>Used by Laser group for forms ordered tracking</description>
    <fields>
        <fullName>Catalog_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Catalog Number</label>
        <referenceTo>Laser_Ordered_Forms_Catalog_Numbers__c</referenceTo>
        <relationshipLabel>Laser Ordered Forms</relationshipLabel>
        <relationshipName>Laser_Ordered_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Laser_Artwork_Order__c</fullName>
        <label>Laser Artwork Order</label>
        <referenceTo>Laser_Artwork_Order__c</referenceTo>
        <relationshipLabel>Laser Ordered Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Laser_Ordered_Forms__c</fullName>
        <label>ePayments Client</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>IF(NOT(ISBLANK(Quantity__c)), Quantity__c * IF(AND(NOT(ISBLANK( Unit_Price_Override__c )), Unit_Price_Override__c &gt;= 0), Unit_Price_Override__c, Unit_Price__c), 0)</formula>
        <label>Total$</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price_Override__c</fullName>
        <description>We need to implement a way of overriding the default price. There are specific clients that have discounted rates or receive changes free, as well as any contracted lines (which we collect from the contract)</description>
        <label>Unit Price (Override)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <formula>IF(NOT(ISBLANK(Laser_Artwork_Order__r.Ship_CMF_Business_Unit__c)) &amp;&amp; CONTAINS(Laser_Artwork_Order__r.Ship_CMF_Business_Unit__c, &quot;CANADA&quot;), Catalog_Number__r.CAN__c, Catalog_Number__r.US__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Laser Ordered Forms</label>
    <nameField>
        <displayFormat>LOF-{00000}</displayFormat>
        <label>Ordered Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Laser Ordered Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Laser_Ordered_Forms_Catalog_Numbers__c.object
<CustomObject>
    <description>Used by Laser group for setting up catalog numbers for Laser Ordered forms</description>
    <fields>
        <fullName>Exclude_from_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If either of these are checked then those catalog numbers would exclude from the rollups.</description>
        <label>Exclude from Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_from_SO_Total__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If either of these are checked then those catalog numbers would exclude from the rollups.</description>
        <label>Exclude from SO Total $</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_from_Total_Number_Of_Forms__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude from Total Number Of Forms</label>
        <type>Checkbox</type>
    </fields>
    <label>Laser Ordered Forms Catalog Numbers</label>
    <nameField>
        <label>Catalog Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Laser Ordered Forms Catalog Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fulldev2/src/classes/DS_LaserRollupTriggerHandler.cls
public class DS_LaserRollupTriggerHandler 
{   
        
    public static void RollupMethod(List<Laser_Ordered_Forms__c> NewList, List<Laser_Ordered_Forms__c> OldList)
    {
        //DS_LAO_SetFieldsBasedOnStatus.IsThisTrigger_LaserOrderForms = true;   
        
        if(Trigger.IsInsert || Trigger.IsUpdate) 
        {
            list<string> LaoIdList = new list<string> ();           
            
            for (Laser_Ordered_Forms__c l : NewList) 
            {
                LaoIdList.add(l.Laser_Artwork_Order__c);               
            }
            
            map<ID, Laser_Artwork_Order__c> laoMap;
            
            LaoMap = new map<ID, Laser_Artwork_Order__c>([
                select id, stock_Order_Total__c, Total_Number_of_Forms__c, LAO_Value__c,
                (select id, Laser_Artwork_Order__c, total__c, Quantity__c, Unit_Price__c, Unit_Price_Override__c,
                Catalog_Number__c, Catalog_Number__r.Exclude_from_SO_Total__c, 
                Catalog_Number__r.Exclude_from_Quote__c, Catalog_Number__r.Exclude_from_Total_Number_Of_Forms__c
                From Forms__r)
                From Laser_Artwork_Order__c 
                where id IN : LaoIdList
            ]);            
                     
            list<Laser_Ordered_Forms__c> LofList;
            
            for (Laser_Artwork_Order__c lao : LaoMap.Values()) 
            {
                LofList = new list<Laser_Ordered_Forms__c>();
                LofList = lao.Forms__r;
                
                for (integer i = 0; i < LofList.size(); i++) 
                {
                    if (LofList[i].Laser_Artwork_Order__c == lao.id) 
                    {
                        if (i == 0) 
                        {
                            LaoMap.get(LofList[i].Laser_Artwork_Order__c).Stock_Order_Total__c = 0;
                            LaoMap.get(LofList[i].Laser_Artwork_Order__c).Total_Number_of_Forms__c = 0;
                            LaoMap.get(LofList[i].Laser_Artwork_Order__c).LAO_Value__c = 0;
                        }                
                        
                        boolean Include_SoTotal_From_Catalog_number = true;
                        boolean Include_Quote_From_Catalog_Number = true;
                        boolean Include_Total_NumberOf_Forms_Catalog_Number = true;
                        
                        
                        Laser_Ordered_Forms_Catalog_Numbers__c CatalogNumberRecord = new Laser_Ordered_Forms_Catalog_Numbers__c();
                        //CatalogNumberRecord = LofCatalognumbersMap.get(LofList[i].Catalog_Number__c);
                        CatalogNumberRecord = LofList[i].Catalog_Number__r;
                        
                        system.debug(CatalogNumberRecord);
                        
                        if(CatalogNumberRecord != null)
                        {                            
                            if(LofList[i].Unit_Price_Override__c == null)
                            {
                                //getting Exclude_from_SO_Total__c field value from the catalog numbers object instead of laser order forms(
                                //Exclude_from_SO_Total__c is formula field in the laser order forms object)
                                if(CatalogNumberRecord.Exclude_from_SO_Total__c == true)
                                {
                                    Include_SoTotal_From_Catalog_number = false;
                                }
                            }
                            
                            if(CatalogNumberRecord.Exclude_from_Quote__c == true)
                            {
                                Include_Quote_From_Catalog_Number = false;
                            }
                            
                            if(CatalogNumberRecord.Exclude_from_Total_Number_Of_Forms__c == true)
                            {
                                Include_Total_NumberOf_Forms_Catalog_Number = false;
                            }
                            
                        }
                        
                        system.debug(Include_SoTotal_From_Catalog_number);
                        
                        LaoMap.get(LofList[i].Laser_Artwork_Order__c).Stock_Order_Total__c 
                            = LaoMap.get(LofList[i].Laser_Artwork_Order__c).Stock_Order_Total__c 
                            + (Include_SoTotal_From_Catalog_number == true ? LofList[i].total__c : 0);
                        
                        system.debug(LofList[i].total__c);
                        
                        LaoMap.get(LofList[i].Laser_Artwork_Order__c).Total_Number_of_Forms__c 
                            = LaoMap.get(LofList[i].Laser_Artwork_Order__c).Total_Number_of_Forms__c 
                            + (Include_Total_NumberOf_Forms_Catalog_Number == true ? LofList[i].Quantity__c : 0);
                        
                        LaoMap.get(LofList[i].Laser_Artwork_Order__c).LAO_Value__c 
                            = LaoMap.get(LofList[i].Laser_Artwork_Order__c).LAO_Value__c 
                            + (Include_Quote_From_Catalog_Number == true ? (LofList[i].Quantity__c * LofList[i].Unit_Price__c) : 0);
                    }
                }
            }
            
            
            try 
            {
                update LaoMap.values();
            } catch (DmlException e) 
            {
                for (Laser_Ordered_Forms__c l : NewList)
                    l.addError('There was an error updating the Laser Artwork Order. '
                         + 'Please go back to the the Laser Artwork Order parent record and re-save to correct the errors in that record. ');
            }
        }
        
        if (Trigger.IsDelete) 
        {
            list<string> LaoIds = new list<string> ();
            //set<ID> CatalogNumberIds = new set<ID>();
            
            if(OldList != null && !OldList.IsEmpty()) 
            {
                for (Laser_Ordered_Forms__c l : OldList) 
                { 
                    LaoIds.add(l.Laser_Artwork_Order__c);
                    //CatalogNumberIds.add(l.Catalog_Number__c);
                } 
            }
            
            map<ID, Laser_Artwork_Order__c> LaoMap;
            
            LaoMap = new map<ID, Laser_Artwork_Order__c>([
                select id, stock_Order_Total__c, Total_Number_of_Forms__c, LAO_Value__c,
                (select id, Laser_Artwork_Order__c, total__c, Quantity__c, Unit_Price__c, Unit_Price_Override__c,
                Catalog_Number__c, Catalog_Number__r.Exclude_from_SO_Total__c, 
                Catalog_Number__r.Exclude_from_Quote__c, Catalog_Number__r.Exclude_from_Total_Number_Of_Forms__c
                From Forms__r)
                From Laser_Artwork_Order__c 
                where id IN : LaoIds
            ]);           
            
            list<Laser_Ordered_Forms__c> LofList;
            
            for (Laser_Artwork_Order__c lao : LaoMap.values()) 
            {
                LofList = new list<Laser_Ordered_Forms__c> ();
                LofList = lao.Forms__r;
                
                for (integer i = 0; i < LofList.size(); i++) 
                {
                    if (LofList[i].Laser_Artwork_Order__c == lao.id) 
                    {
                        if (i == 0) 
                        {
                            LaoMap.get(LofList[i].Laser_Artwork_Order__c).Stock_Order_Total__c = 0;
                            LaoMap.get(LofList[i].Laser_Artwork_Order__c).Total_Number_of_Forms__c = 0;
                            LaoMap.get(LofList[i].Laser_Artwork_Order__c).LAO_Value__c = 0;
                        }
                        
                        boolean Include_SoTotal_From_Catalog_number = true;
                        boolean Include_Quote_From_Catalog_Number = true;
                        boolean Include_Total_NumberOf_Forms_Catalog_Number = true;
                        
                        Laser_Ordered_Forms_Catalog_Numbers__c CatalogNumberRecord = new Laser_Ordered_Forms_Catalog_Numbers__c();
                        //CatalogNumberRecord = LofCatalognumbersMap.get(LofList[i].Catalog_Number__c);
                        CatalogNumberRecord = LofList[i].Catalog_Number__r;
                        
                        if(CatalogNumberRecord != null)
                        {
                            if(LofList[i].Unit_Price_Override__c == null)
                            {
                                //getting Exclude_from_SO_Total__c field value from the catalog numbers object instead of laser order forms(
                                //Exclude_from_SO_Total__c is formula field in the laser order forms object)
                                if(CatalogNumberRecord.Exclude_from_SO_Total__c == true)
                                {
                                    Include_SoTotal_From_Catalog_number = false;
                                }
                            }
                            
                            if(CatalogNumberRecord.Exclude_from_Quote__c == true)
                            {
                                Include_Quote_From_Catalog_Number = false;
                            }
                            
                            system.debug(Include_SoTotal_From_Catalog_number);
                            
                            if(CatalogNumberRecord.Exclude_from_Total_Number_Of_Forms__c == true)
                            {
                                Include_Total_NumberOf_Forms_Catalog_Number = false;
                            }
                        }
                        
                        LaoMap.get(LofList[i].Laser_Artwork_Order__c).Stock_Order_Total__c 
                            = LaoMap.get(LofList[i].Laser_Artwork_Order__c).Stock_Order_Total__c 
                            + (Include_SoTotal_From_Catalog_number == true ? LofList[i].total__c : 0);
                        
                        system.debug(LofList[i].total__c);
                        
                        LaoMap.get(LofList[i].Laser_Artwork_Order__c).Total_Number_of_Forms__c 
                            = LaoMap.get(LofList[i].Laser_Artwork_Order__c).Total_Number_of_Forms__c 
                            + (Include_Total_NumberOf_Forms_Catalog_Number == true ? LofList[i].Quantity__c : 0);
                        
                        LaoMap.get(LofList[i].Laser_Artwork_Order__c).LAO_Value__c 
                            = LaoMap.get(LofList[i].Laser_Artwork_Order__c).LAO_Value__c 
                            + (Include_Quote_From_Catalog_Number == true ? (LofList[i].Quantity__c * LofList[i].Unit_Price__c) : 0);   
                    }
                }
            }            
            update LaoMap.values();
        }
    }
}