SF Primes/src/objects/Laser_Artwork_Order__c.object
<CustomObject>
    <fields>
        <fullName>Number_Follow_up_Calls__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Follow-up Calls</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold-Pre FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/S Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/S Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artwork to LFD Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proofs to LAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AWIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Mapping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms to LIS Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At LI Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval - ELF Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Data Mapping/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold-CDK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Collected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded/Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval-FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-FA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Forms Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Docusign/src/classes/DS_TaskRollUpHandler_Test.cls
@isTest
public class DS_TaskRollUpHandler_Test 
{
    public static testmethod void TaskRollUp()
    {  
        list<Laser_Artwork_Order__c> LaoListToInsert = new list<Laser_Artwork_Order__c>();
        
        Laser_Artwork_Order__c lao1 = DS_TestObjects.NewLaserArtworkOrder();
        lao1.Order_Status__c = 'ordered';
        lao1.Number_Follow_up_Calls__c = null;
        LaoListToInsert.add(lao1);
        
        Laser_Artwork_Order__c lao2 = DS_TestObjects.NewLaserArtworkOrder();
        lao2.Order_Status__c = 'awip';
        LaoListToInsert.add(lao2);
        
        insert LaoListToInsert;
        
        list<task> TaskListToInsert = new list<task>();
        
        Task t1 = new Task();
        t1.WhatId = lao1.Id;
        t1.status = 'open';
        t1.Track_Follow_up__c = true;
        t1.subject = 'Important task';
        TaskListToInsert.add(t1);
        
        
        Task t2 = new Task();
        t2.WhatId = lao2.Id;
        t2.status = 'open';
        t2.Track_Follow_up__c = true;
        t2.subject = 'proofs follow-up';
        TaskListToInsert.add(t2);
        
        insert TaskListToInsert;        
    }     
}