SF Primes/src/objects/Laser_Artwork_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approved_by_Client__c</fullName>
        <label>Approved by Client</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Artwork_to_LFD_Team__c</fullName>
        <label>Artwork to LFD Team</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Burn_Completed__c</fullName>
        <description>Burn Completed</description>
        <label>Burn Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N40000001lfVXEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_PO__c</fullName>
        <label>Contract/PO#</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forms_to_LIS_Team__c</fullName>
        <label>Forms to LIS Team</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LAS_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAS Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.(LAS Name)</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Specialists - LAS - Beczkiewicz</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Laser - RRP</value>
            </filterItems>
            <filterItems>
                <field>$User.Username</field>
                <operation>notContain</operation>
                <value>$User.Username,$Setup.GlobalSettings__c.Admin_Integration_Username__c</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Specialist - LAS - Bridgette</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>COE - LAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Laser_Artwork_Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LIS_Info_Received__c</fullName>
        <label>LIS Info Received</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Priority__c</fullName>
        <label>Order Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rush</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Same Day Rush</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold-Pre FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/S Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/S Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artwork to LFD Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proofs to LAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AWIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Mapping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms to LIS Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At LI Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval - ELF Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Data Mapping/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold-CDK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Collected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded/Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval-FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-FA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add/Change - CTW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Change - DASH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Change - ELF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Change - Elite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Change - eShowroom/Showroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Change - Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Change - FI/DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Change - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Change - WDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy/Sell - DASH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy/Sell - ELF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy/Sell - Elite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy/Sell - eShowroom/Showroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy/Sell - FI/DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy/Sell - Impact/Laser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy/Sell - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install Concurrent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install - CTW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install - DASH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install - ELF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install - Elite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install - eShowroom/Showroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install - FI/DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install - Impact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Install - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One-Eighty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PFW/CRM/Custom Pencil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade to DC - FI/DC</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proofs_to_Client__c</fullName>
        <label>Proofs to Client</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Proofs_to_LAS__c</fullName>
        <description>Proofs to LAS</description>
        <label>Proofs to LAS</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Quote_Sheet_Submitted__c</fullName>
        <label>Quote Sheet Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <label>Quote Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contracted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Framework</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Revision__c</fullName>
        <label>Revision #</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Forms Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Laser_Ordered_Forms__c.object
<CustomObject>
    <description>Used by Laser group for forms ordered tracking</description>
    <fields>
        <fullName>Laser_Artwork_Order__c</fullName>
        <label>Laser Artwork Order</label>
        <referenceTo>Laser_Artwork_Order__c</referenceTo>
        <relationshipLabel>Laser Ordered Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Laser Ordered Forms</label>
    <nameField>
        <displayFormat>LOF-{00000}</displayFormat>
        <label>Ordered Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Laser Ordered Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Laser_Ordered_Forms_Catalog_Numbers__c.object
<CustomObject>
    <description>Used by Laser group for setting up catalog numbers for Laser Ordered forms</description>
    <fields>
        <fullName>Exclude_from_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If either of these are checked then those catalog numbers would exclude from the rollups.</description>
        <label>Exclude from Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_from_SO_Total__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If either of these are checked then those catalog numbers would exclude from the rollups.</description>
        <label>Exclude from SO Total $</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_from_Total_Number_Of_Forms__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude from Total Number Of Forms</label>
        <type>Checkbox</type>
    </fields>
    <label>Laser Ordered Forms Catalog Numbers</label>
    <nameField>
        <label>Catalog Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Laser Ordered Forms Catalog Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA/src/classes/DS_LAO_SetFieldsBasedOnStatus_Test.cls
@IsTest
public class DS_LAO_SetFieldsBasedOnStatus_Test
{
    public static TestMethod Void Test()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='ADPDS - Inside Sales/Laser - LSR'];  
        // 2015-11-24 matt.keefe@cdk.com Changed query condition from Name = Timothy Woolley to Profile.Name = Laser - LAS
        User LASUser = [Select Id From User Where Profile.Name like '%Laser - LAS' And IsActive = true Limit 1];
        User TempRunAsUser = DS_TestObjects.NewUser();
        TempRunAsUser.ProfileId = p.Id;
        TempRunAsUser.FederationIdentifier = 'FederationId';
        Insert TempRunAsUser;
        
        system.RunAs(TempRunAsUser)
        {
            list<Laser_Artwork_Order__c> InsertList = new list<Laser_Artwork_Order__c>();
            
            set<String> StatusSet = new set<String> { 
                'Binder Sent', 'Proofs to LAS', 'Awaiting Approval', 
                'Approved', 'Burned', 'Installed', 
                'Artwork to LFD Team', 'Forms to LIS Team', 
                'Q/S Submitted', 'Q/S Approved', 'AWIP', 'At LI Team' 
            };
            
            Contact con = DS_TestObjects.NewContact_Inserted();
                
            for(String s : StatusSet)
            { 
                for(Integer i=0; i<StatusSet.size(); i++){ 
                    Laser_Artwork_Order__c lao = new Laser_Artwork_Order__c();
                    lao.Revision__c = String.ValueOf(i+1);
                    lao.LIS_Info_Received__c ='yes';
                    If(i==1){Lao.Order_Priority__c = 'Rush';Lao.Artwork_to_LFD_Team__c = System.now()+i;}
                    If(i==2){Lao.Order_Priority__c = 'Standard';Lao.Artwork_to_LFD_Team__c = System.now()+i;}                    
                    lao.Order_Status__c = s; 
                    lao.Artwork_to_LFD_Team__c = System.now()+i;
                    lao.Approved_by_Client__c = DateTime.now() - 2;
                    lao.Proofs_to_LAS__c = DateTime.now() - 2;
                    lao.Proofs_to_Client__c = DateTime.now() - 2;
                    lao.Forms_to_LIS_Team__c = DateTime.now() - 2;
                    lao.Burn_Completed__c = DateTime.now() - 2;
                    Lao.Quote_Sheet_Submitted__c = DateTime.now();
                    Lao.Contact__c = con.ID;
                    lao.Quote_Type__c = 'Contracted'; // 2016-02-24 -venkata.shrivol@cdk.com -added this to support validation rule
                    InsertList.add(lao);
                }
            }
            
            insert InsertList;
            
            list<Laser_Artwork_Order__c> UpdateList = new list<Laser_Artwork_Order__c>();
            
            for(Integer i=0; i<InsertList.Size(); i++) //Laser_Artwork_Order__c s:
            {    
                
                InsertList[i].Revision__c = InsertList[i].Order_Status__c!='Approved'?String.ValueOf(1): String.ValueOf(i+1);
                InsertList[i].LIS_Info_Received__c ='yes';
                InsertList[i].Artwork_to_LFD_Team__c = System.now()+i;
                InsertList[i].Contract_PO__c='12345'; // 2016-02-24 -venkata.shrivol@cdk.com -added this to support validation rule
                
                if(i!=3){InsertList[i].Order_Priority__c = 'Rush';InsertList[i].Artwork_to_LFD_Team__c = System.now()+i;}
                if(i==2){InsertList[i].Order_Priority__c = 'Standard';InsertList[i].Artwork_to_LFD_Team__c = System.now()+i;}
                If(i==0){InsertList[i].Order_Status__c = 'Forms to LIS Team';}
                If(i==1){InsertList[i].Order_Status__c = 'Proofs to LAS';}
                If(i==2){InsertList[i].Order_Status__c = 'Awaiting Approval';}
                If(i==3){InsertList[i].Order_Status__c = 'Approved';}
                If(i==4){InsertList[i].Order_Status__c = 'Burned';}
                If(i==5){InsertList[i].Order_Status__c = 'Installed';}
                If(i==6){/*InsertList[i].Order_Status__c = 'Artwork to LFD Team';*/  InsertList[i].Revision__c = null;}
                If(i==7){InsertList[i].Order_Status__c = 'AWIP'; InsertList[i].Revision__c = null;}
                If(i==8){InsertList[i].Order_Status__c = 'Q/S Submitted'; InsertList[i].Order_Type__c = 'Buy/Sell - Elite';InsertList[i].LAS_Name__c = LASUser.Id;}
                If(i==9){InsertList[i].Order_Status__c = 'Q/S Approved';}
                If(i==10){InsertList[i].Order_Status__c = 'Binder Sent';}
                
                UpdateList.add(InsertList[i]);  
            }  
            
            update UpdateList;
        }
    }
    
    public static TestMethod Void Test2()
    {   
        Contact con = DS_TestObjects.NewContact_Inserted();
        Laser_Artwork_Order__c lao = new Laser_Artwork_Order__c();
        lao.Order_Status__c = 'Artwork to LFD Team';        
        lao.Contact__c = con.ID;
        // 2016-02-24 -venkata.shrivol@cdk.com -added below two statments to support validation rule
        lao.Quote_Type__c = 'Contracted';
        lao.Contract_PO__c = '122345';
        insert lao;
        
        lao.Order_Status__c = 'AWIP';
        update lao;
        
        lao.Order_Status__c = 'Awaiting Approval';
        lao.Proofs_to_LAS__c = DateTime.now() - 2;
        update lao;
        
        lao.Order_Status__c = 'AWIP';
        update lao;
        
        lao.Order_Status__c = 'Binder Sent';
        update lao;
        
        lao.Order_Status__c = 'hold';
        lao.Revision__c = '1';
        update lao;
        
        lao.Order_Status__c = 'Artwork to LFD Team';
        lao.Revision__c = '1';
        update lao;
        
        lao.Order_Status__c = 'At LI Team';
        lao.Forms_to_LIS_Team__c = DateTime.now() - 2;
        Update lao;
        
        lao.Order_Status__c = 'Installed';
        lao.Order_Type__c = 'New Install - eShowroom/Showroom';
        Laser_Ordered_Forms_Catalog_Numbers__c catlog = new Laser_Ordered_Forms_Catalog_Numbers__c();
        catlog.Exclude_from_Quote__c = true;
        catlog.Exclude_from_SO_Total__c = true;
        catlog.Exclude_from_Total_Number_Of_Forms__c = true;
        insert catlog;
        
        Laser_Ordered_Forms__c lof = new Laser_Ordered_Forms__c();        
        lof.Laser_Artwork_Order__c = lao.Id;
        lof.Catalog_Number__c = catlog.Id;
        insert lof;
        
        lao.Quote_Sheet_Submitted__c = DateTime.now() - 5;
        lao.Quote_Sheet_Approved__c = DateTime.now() - 2;
        lao.Artwork_to_LFD_Team__c = DateTime.now();
        lao.Proofs_to_LAS__c = lao.Artwork_to_LFD_Team__c + 2;
        lao.Project__c = 'TBD';
        lao.Proofs_to_Client__c = lao.Proofs_to_LAS__c + 2;
        lao.Approved_by_Client__c = lao.Proofs_to_Client__c + 2;
        lao.Burn_Completed__c = lao.Approved_by_Client__c + 2;
        lao.Forms_Installed__c = lao.Burn_Completed__c + 4;
        lao.Revision__c = '2';
        
        update lao;
    }
    
    public static TestMethod Void TestForWeekendsAndHolidays()
    {
        Contact con = DS_TestObjects.NewContact_Inserted();
        Laser_Artwork_Order__c lao = new Laser_Artwork_Order__c();
        lao.Artwork_to_LFD_Team__c = Date.newInstance(2015, 07, 04);
        lao.Order_Priority__c = 'Rush';
        lao.Contact__c = con.ID; 
        insert lao;
        
        DS_LAO_SetFieldsBasedOnStatus.WeekendsAndHolidays(lao.Order_Priority__c);
     
        
        lao.Order_Priority__c = 'Standard';
        update lao;
        DS_LAO_SetFieldsBasedOnStatus.WeekendsAndHolidays(lao.Order_Priority__c);
        
        lao.Order_Priority__c = 'Same Day Rush';
        update lao;
        DS_LAO_SetFieldsBasedOnStatus.WeekendsAndHolidays(lao.Order_Priority__c);
    }
}