SF Primes/src/objects/Launch__c.object
<CustomObject>
    <description>Used by CB Services to track progress of website build in progress</description>
    <fields>
        <fullName>Account_Advocate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Advocate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Launch4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Add_Ons__c</fullName>
        <inlineHelpText>Please enter a value if the website order includes any of ala carte items.</inlineHelpText>
        <label>Add Ons</label>
        <picklist>
            <picklistValues>
                <fullName>Audience Optimization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Differentiator Pak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GM CCA Tire Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Sync</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProCare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reputation Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RM DAP 5 Star Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RM DAP 5 Star Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Essentials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VW Care</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Body_Shop_Budget__c</fullName>
        <inlineHelpText>Please Enter the Body Shop Budget OR N/A in this field.</inlineHelpText>
        <label>Body Shop Budget</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <inlineHelpText>Please select the brands that apply to Product Type(s) selected above.</inlineHelpText>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>BMW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buick/GMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadillac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chevrolet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyundai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lexus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MINI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volkswagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Budget_Amount__c</fullName>
        <label>Budget Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>Integration User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Budget__c</fullName>
        <inlineHelpText>Please fill out the value if the Core product is ordered.</inlineHelpText>
        <label>Core Budget</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Critical_Notes__c</fullName>
        <label>Critical Notes</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Marketing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Email Marketing Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Launch_Comments__c</fullName>
        <label>Special Instructions</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Maintenance_Repair_Budget__c</fullName>
        <inlineHelpText>Please Enter the Maintenance &amp; Repair Budget OR N/A in this field.</inlineHelpText>
        <label>Maintenance &amp; Repair Budget</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Recurring_Total__c</fullName>
        <label>Monthly Recurring Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Flex_Budget__c</fullName>
        <label>New Flex Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oracle_Order_Number__c</fullName>
        <inlineHelpText>Please enter all Oracle Order Numbers associated with this launch.  If there are multiple, please separate by commas.</inlineHelpText>
        <label>Oracle Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Marketing_Id__c</fullName>
        <label>Email Marketing Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parts_Accessories_Budget__c</fullName>
        <inlineHelpText>Please Enter the Parts &amp; Accessories Budget OR N/A in this field.</inlineHelpText>
        <label>Parts &amp; Accessories Budget</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accessories Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Reputation Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Insights Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Insights Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Management Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Management Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Optimization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Tag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Svc&amp;Pts Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cobalt AutoShow for Exports Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Us Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core/ProSite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Email Aliases (each 10)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Buy/Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAP+Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Group Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Inventory Export Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Name Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain or Email Misc Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain or Email Misc One Time Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Hosting Upgrade (25 GB Increase)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Hosting Upgrade (Add&apos;l Mailboxes)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Service</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>S_P_Flex_Budget__c</fullName>
        <inlineHelpText>Service &amp; Parts Flex Budget Amount</inlineHelpText>
        <label>S&amp;P Flex Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tires_Budget__c</fullName>
        <inlineHelpText>Please Enter the Tires Budget OR N/A in this field.</inlineHelpText>
        <label>Tires Budget</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Used_Flex_Budget__c</fullName>
        <label>Used Flex Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Launch</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Launch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Launch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>Account_Advocate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Advocate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Website</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/DSCB_CaseConcatenate_Handler.cls
//created - Siva.Pragada@cdk.com
//2017-02-17 - siva.pragada@cdk.com - added added Yext Partner Prodcut functionality for RQ-08653
public class DSCB_CaseConcatenate_Handler 
{
    public static map<string, ALL_Template_Values__c> allTemplateValuesMap = ALL_Template_Values__c.getAll();
    
    public static void ConcatenateTheFieldValues(list<Case> concatenateCases)
    {
        GlobalSettings__c gs = GlobalSettings__c.getInstance();
        
        if(gs.Launch_Onboarding_Switch__c)
        {
            list<ALL_Template_Decisionbox__c> allTemplateDecisionBoxSettings = ALL_Template_Decisionbox__c.getAll().Values();
            
            set<ID> launchIDset = new set<ID>();
            
            for(Case currentCase: concatenateCases)
            {
                launchIDset.add(currentCase.Launch__c);
            }
            
            map<ID, Launch__c> launchMap = new map<ID, Launch__c>([
                Select Id, Name, RecordType.Name, Product_Type__c, Add_Ons__c, Critical_Notes__c, Launch_Comments__c, Oracle_Order_Number__c,
                Monthly_Recurring_Total__c, Budget_Amount__c, Core_Budget__c, New_Flex_Budget__c, S_P_Flex_Budget__c, Used_Flex_Budget__c,
                Tires_Budget__c, Maintenance_Repair_Budget__c, Parts_Accessories_Budget__c, Body_Shop_Budget__c, WebID__c, WebID__r.Name,
                Account__c, Account__r.Name, Account__r.Dealer_Group_Name2__c, Brand__c, Contact__c, Contact__r.Name, Contact__r.Email, Contact__r.Phone,
                Account_Advocate__c, Account_Advocate__r.Name, Email_Marketing_Specialist__c, Email_Marketing_Specialist__r.Name, Owner_Marketing_Id__c,
                Account__r.CBLTBillState__c, Order_Type__c, Status__c, Activation_OM__c, Activation_OM__r.Name, Partner_Products__c
                
                From Launch__c
                Where ID
                IN :launchIDset
            ]);
            
            system.debug(launchMap);
            
            if(launchMap != null && !launchMap.isEmpty())
            {   
                
                for(Case currentCase: concatenateCases)
                { 
                    Launch__c currentLaunch = launchMap.get(currentCase.Launch__c);
                    
                    system.debug(currentLaunch);
                    
                    if(currentLaunch != null)
                    {
                        if(!allTemplateDecisionBoxSettings.isEmpty())
                        {
                            for(ALL_Template_Decisionbox__c atd: allTemplateDecisionBoxSettings)
                            {
                                boolean conditionCheck = ALL_UtilitiesLogic.getcompositeExpressionsEvaluatedValue(atd.Condition_Check__c, currentLaunch);
                                
                                system.debug(atd.Condition_Check__c);
                                system.debug(conditionCheck);
                                if(conditionCheck)
                                {
                                    string concatenatedString = DSCB_CaseConcatenate_Handler.concatenateFieldValues(atd.Value_Assignment__c, currentLaunch);
                                    currentCase.Description = concatenatedString;
                                }
                            }
                        }
                        
                        string LaunchProductType, CaseProductCategory, LaunchAddOns;
                        LaunchProductType = currentLaunch.Product_Type__c == null ? '' : currentLaunch.Product_Type__c;
                        CaseProductCategory = currentCase.Product_Category__c != null ? currentCase.Product_Category__c : '';
                        LaunchAddOns = currentLaunch.Add_Ons__c != null ? currentLaunch.Add_Ons__c: '';
                        string subject = 'Onboarding - ' + LaunchProductType + '; ' +LaunchAddOns;
                        
                        boolean yextConditionsMet = false;
                        
                        ID onboardPowerSEORecID = ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('Case', 'Onboarding - PowerSEO');
                        
                        
                        if(currentLaunch.Status__c == 'Closed' && 
                           currentLaunch.recordType.Name == 'A La Carte Launch' &&
                           currentCase.Partner_Products__c != null && currentCase.Partner_Products__c.equalsIgnoreCase('Yext') &&
                           currentCase.recordTypeID == onboardPowerSEORecID                            
                          )
                        {
                            yextConditionsMet = true;
                        }
                        
                        if(yextConditionsMet)
                        {
                            subject = 'Onboarding - ' + currentLaunch.Partner_Products__c;
                        }
                        
                        if(subject.length() > 255)
                        {
                            subject = subject.substring(0,254);
                        }
                        currentCase.Subject = subject;
                    }
                }
                //system.debug(concatenateCases);
            }
        }
    }
    
    public static string concatenateFieldValues(string valueAssignmentString, Launch__c currentLaunch)
    {
        list<string> Identifiers = valueAssignmentString.split('AND');
        string concatenatedString = '';
        
        if(Identifiers != null && !Identifiers.isEmpty())
        {
            for(integer i=0; i<Identifiers.size(); i++)
            {
                string s = Identifiers[i];
                s = s.normalizeSpace();
                ALL_Template_Values__c atv = allTemplateValuesMap.get(s);
                
                if(atv != null && atv.Label__c != 'next line' && atv.Label__c != 'Link to Launch')
                {
                    string fieldName = atv.Field_Name__c;
                    if(fieldName != null && fieldName.contains('.'))
                    {
                        object fieldValue = All_UtilitiesData.GetDataFromNestedFields(FieldName, currentLaunch);
                        string stringFieldValue = fieldValue != null ? string.valueOf(fieldValue) : '';
                        concatenatedString = concatenatedString + atv.Label__c + ': ' + stringFieldValue + ' \r\n';
                    }
                    else
                    {
                        object fieldValue = currentLaunch.get(fieldName);
                        string stringFieldValue = fieldValue != null ? string.valueOf(fieldValue) : '';
                        concatenatedString = concatenatedString + atv.Label__c + ': ' + stringFieldValue + ' \r\n';
                    }
                }
                if(atv != null && atv.Label__c == 'next line')
                {
                    concatenatedString = concatenatedString + ' \r\n';
                }
                if(atv != null && atv.Label__c == 'Link to Launch')
                {
                    string salesforceBaseURL = System.URL.getSalesforceBaseUrl().toExternalForm() + '/';                   
                    concatenatedString = concatenatedString + atv.Label__c + ': ' + salesforceBaseURL + currentLaunch.ID;
                    concatenatedString = concatenatedString + ' \r\n';
                }
                
            }
        }
        
        return concatenatedString;
    }
    
}