SF Primes/src/objects/Launch__c.object
<CustomObject>
    <description>Used by CB Services to track progress of website build in progress</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accessories Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Reputation Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Insights Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Insights Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Management Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Management Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Optimization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audience Tag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified Svc&amp;Pts Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cobalt AutoShow for Exports Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Us Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core/ProSite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Email Aliases (each 10)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Buy/Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAP+Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Group Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Inventory Export Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Name Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain or Email Misc Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain or Email Misc One Time Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Hosting Upgrade (25 GB Increase)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Hosting Upgrade (Add&apos;l Mailboxes)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Roll Video</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Send_Onboarding__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to help control the number of times an onboarding notification is sent to Service Ops (used in WF for all RT&apos;s but DAP, which is sent upon creation and does not need a control). This is not intended to display on the page layout.</description>
        <label>Send Onboarding</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WebID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WebID</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>WebID__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WebID__c</referenceTo>
        <relationshipLabel>Launch</relationshipLabel>
        <relationshipName>Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Launch</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Launch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Launch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/WebID__c.object
<CustomObject>
    <description>webIDs are the name given to website on an account</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <label>WebID</label>
    <nameField>
        <label>WebID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/CB_LaunchNotes_Test.cls
@isTest
public class CB_LaunchNotes_Test 
{
    static testMethod void insertLaunches()
    {
        string recordTypeID = (string)ALL_UtilitiesDescribe.getRecordTypeIdOfAnySObject('Launch__c', 'A La Carte Launch');
        Launch__c newLaunch = DS_TestObjects.NewLaunch();
        Account acc = (Account)newLaunch.getsObject('Account__r');
        WebID__c webID = DS_TestObjects.NewWebID();
        webID.Account__c = acc.ID;
        contact con  = DS_TestObjects.NewContact();
        con.AccountId = acc.ID;
        insert new list<sObject>{ webID, con };
        
        newLaunch.Product_Type__c = 'Pre-Roll Video';
        newLaunch.RecordTypeId = recordTypeID;
        newLaunch.Send_Onboarding__c = false;
        newLaunch.WebID__c = webID.ID;
        
        Insert newLaunch;
        
        Launch_Notes__c ln = new Launch_Notes__c();
        ln.Launch_Id__c = newLaunch.ID;
        ln.Notes__c = 'test notes';
        ln.Notes_Type__c = 'Designer';
        ln.Date__c = DateTime.now();
        
        CB_LaunchNotes_Handler.saveLaunchNotes(ln);
        CB_LaunchNotes_Handler.getAllLaunchNotes(ln.Launch_Id__c);
    }

}