SF Primes/src/objects/Manufacturer__c.object
<CustomObject>
    <description>List of core manufacturer&apos;s sales tracks and their associated attributes</description>
    <label>Manufacturer</label>
    <nameField>
        <label>Manufacturer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/Manufacturer_at_Dealership__c.object
<CustomObject>
    <description>Manufacturers identified at an account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Manufacturers at Dealership</relationshipLabel>
        <relationshipName>R00N40000001ldb7EAA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer</label>
        <referenceTo>Manufacturer__c</referenceTo>
        <relationshipLabel>Manufacturers at Dealership (Manufacturers)</relationshipLabel>
        <relationshipName>R00N40000001lfhBEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Manufacturer at Dealership</label>
    <nameField>
        <displayFormat>ID - {00000}</displayFormat>
        <label>Mfg at Dealer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manufacturers at Dealership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Docusign/src/classes/DS_CreateCompositeManufatDealerTest.cls
@isTest
public class DS_CreateCompositeManufatDealerTest {
    public static testmethod void testCompositeExtIdUpdateTrigger()
    {
        Account a = new Account(Name='testAccount');
        insert a;
        
        Manufacturer__c m = new Manufacturer__c();
        insert m;
        
        Manufacturer_At_Dealership__c md = new MAnufacturer_At_Dealership__c(Account__c = a.id, Manufacturer__c = m.id);
        insert md;
        
        Manufacturer__c m2 = new Manufacturer__c();
        insert m2;
        
        md.Manufacturer__c = m2.id;
        update md;
    }
}