SF Primes/src/objects/Manufacturer__c.object
<CustomObject>
    <description>List of core manufacturer&apos;s sales tracks and their associated attributes</description>
    <fields>
        <fullName>Ora_Manufacturers_Code__c</fullName>
        <label>Ora Manufacturers Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_Code__c</fullName>
        <label>Segment Code</label>
        <picklist>
            <picklistValues>
                <fullName>AUTG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PFW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Manufacturer</label>
    <nameField>
        <label>Manufacturer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/objects/Manufacturer_at_Dealership__c.object
<CustomObject>
    <description>Manufacturers identified at an account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Manufacturers at Dealership</relationshipLabel>
        <relationshipName>R00N40000001ldb7EAA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CompositeExtID__c</fullName>
        <description>Account ID + (Oracle) Manf. Code + Segment Code</description>
        <externalId>true</externalId>
        <label>CompositeExtID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Manufacturer_Dealer_Code__c</fullName>
        <label>Manufacturer Dealer Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer</label>
        <referenceTo>Manufacturer__c</referenceTo>
        <relationshipLabel>Manufacturers at Dealership (Manufacturers)</relationshipLabel>
        <relationshipName>R00N40000001lfhBEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Manufacturer at Dealership</label>
    <nameField>
        <displayFormat>ID - {00000}</displayFormat>
        <label>Mfg at Dealer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manufacturers at Dealership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fulldev2/src/classes/DS_ManufacturersAtDealership_Handler.cls
//2016-01-07- anirudh.singh@cdk.com- Created this handler class for the Trigger DS_CreateCompositeIDforManufacturersAtDealership.
public class DS_ManufacturersAtDealership_Handler
{
    //This method is being invoked from ALL_ManufacturersAtDealership Trigger.
    //All the processing of the Trigger has been done in this method.
    public static void processRecords(List<Manufacturer_at_Dealership__c> triggerNewRecords,  
                                      Map<Id, Manufacturer_at_Dealership__c> triggerOldRecordsMap)
    {
        system.debug('Start processRecords---->');
        createCompositeId(triggerNewRecords, triggerOldRecordsMap);
        system.debug('End processRecords---->');
    }
    
    //This method is being invoked from DS_CreateCompositeIDforManufacturersAtDealership Trigger.
    //All the processing of the Trigger has been done in this method.
    public static void createCompositeId(List<Manufacturer_at_Dealership__c> triggerNewRecords, 
                                         Map<Id, Manufacturer_at_Dealership__c> triggerOldRecordsMap)
    {
        system.debug('Start createCompositeId---->');
        //List to store updated records.
        List<Manufacturer_at_Dealership__c> updatedManufacturers=new List<Manufacturer_at_Dealership__c>();
        
        //List that stores newly inserted/updated records
        List<Manufacturer_at_Dealership__c> insertedManufacturers=new List<Manufacturer_at_Dealership__c>();
        
        if(triggerNewRecords!=Null)
        {
            insertedManufacturers=[
                SELECT Account__c, Manufacturer__r.Id, Manufacturer__r.Ora_Manufacturers_Code__c, 
                Manufacturer__r.Segment_Code__c, CompositeExtID__c, Id, Manufacturer_Dealer_Code__c 
                FROM Manufacturer_at_Dealership__c m 
                WHERE Id IN :triggerNewRecords
            ];
        }
        
        if(insertedManufacturers!=Null && insertedManufacturers.size()>0)
        {
            for(Manufacturer_at_Dealership__c md: insertedManufacturers)
            {
                if(md.Manufacturer__r!=Null)
                {
                    Manufacturer_at_dealership__c md_old=Null;
                    
                    if(triggerOldRecordsMap==Null)
                    {
                        md_old=new Manufacturer_at_dealership__c();
                    }
                    else
                    {
                        md_old=triggerOldRecordsMap.get(md.Id);
                    }
                    
                    // condition to make update trigger work only when there is a change in Account__c or Manufacturer__c
                    if((md.Account__c!=md_old.Account__c) || (md.Manufacturer__c!=md_old.Manufacturer__c))
                    {
                        md.CompositeExtID__c=
                            md.Account__c + '' + 
                            md.Manufacturer__r.Ora_Manufacturers_Code__c + '' +
                            md.Manufacturer__r.Segment_Code__c ; // added segment_code__c 
                        updatedManufacturers.add(md);
                    }
                }
            }
        }
        
        if(updatedManufacturers.size()>0)
        {
            update updatedManufacturers;
        }
        system.debug('End createCompositeId---->');
    }
}