SF Primes/src/objects/Project_Activity__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for an Activity associated with a Milestone.</description>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Current Max Project Task End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CDK_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CDK Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Remaining_Duration__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Expected Remaining Duration</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Time_Spent__c</fullName>
        <label>Expected Time Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Tasks__c == 0, &apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Actual_Time_Spent__c</fullName>
        <label>Total Actual Days Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Expected_Time_Spent__c</fullName>
        <label>Total Expected Time Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Tasks_Closed__c</fullName>
        <label>Total Tasks Closed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Tasks__c</fullName>
        <label>Total Tasks</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isActive</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isStatusComplete__c</fullName>
        <formula>IF( Status__c = &apos;Complete&apos;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isStatusComplete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>AI-{000000000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Time_Spent__c</fullName>
        <label>Actual Days Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDK_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CDK Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Time_Spent__c</fullName>
        <label>Expected Time Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Activity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project Activity</label>
        <referenceTo>Project_Activity__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Status_Not_Applicable__c = true,&apos;Not Applicable&apos;,
IF(!ISBLANK(Actual_End_Date__c),&apos;Complete&apos;,
IF(!ISBLANK(Actual_Start_Date__c) &amp;&amp; ISBLANK(Actual_End_Date__c),&apos;In Progress&apos;,
IF(!ISBLANK( CDK_Assignee__c ),&apos;Assigned&apos;,
IF(ISBLANK( CDK_Assignee__c ),&apos;Unassigned&apos;,
null
)))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <formula>IF(Status__c == &apos;Not Applicable&apos;,0,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isActive</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isStatusComplete__c</fullName>
        <formula>IF( Status__c = &apos;Complete&apos;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isStatusComplete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <displayFormat>TI-{000000000}</displayFormat>
        <label>Project Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_BuildActivityRollups_Handler.cls
/*------------------------------------------------------------
Author:      Kimiko Roberto
Company:     Cloud Sherpas
Description: Creates rollups for Project Activity
Inputs:      
Returns:     
History
02/19/15     Kimiko Roberto    Created
03/24/2016   ragashalini.koka@cdk.com  Added planned start date and planned end date to rollup
                                       Modified mergeRollup method to accept the changes done on any field
                                       Added createCDKAssgineeRollUp method to rollup changes on CDKAssginee
------------------------------------------------------------*/
public class IMP_BuildActivityRollups_Handler
{
    public static List<sObject> createActivityRollups(List<Project_Task__c> projectTaskList)
    {    
        List<sObject> parentList = new List<sObject>();
        
        //create and LREngine context assigning the child object and the parent object that will have the rollup values
        //add filters that will help determine rollup values
        ALL_LREngine.Context ctx = new ALL_LREngine.Context(Project_Activity__c.SobjectType, // parent object
                                                            Project_Task__c.SobjectType,  // child object
                                                            Schema.SObjectType.Project_Task__c.fields.Project_Activity__c,    // relationship field name
                                                            'Status__c != \'Not Applicable\''    //filter
                                                           ); 
        
        //assign the field that will get the rollup value, field that will be rolled up and rollup operation to be done.                                
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Activity__c.fields.Total_Expected_Time_Spent__c,
                Schema.SObjectType.Project_Task__c.fields.Expected_Time_Spent__c,
                ALL_LREngine.RollupOperation.Sum 
            ));                                         
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Activity__c.fields.Total_Actual_Time_Spent__c,
                Schema.SObjectType.Project_Task__c.fields.Actual_Time_Spent__c,
                ALL_LREngine.RollupOperation.Sum 
            ));   
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Activity__c.fields.Actual_Start_Date__c,
                Schema.SObjectType.Project_Task__c.fields.Actual_Start_Date__c,
                ALL_LREngine.RollupOperation.Min 
            ));  
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Activity__c.fields.Actual_End_Date__c,
                Schema.SObjectType.Project_Task__c.fields.Actual_End_Date__c,
                ALL_LREngine.RollupOperation.Max 
            ));
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Activity__c.fields.Total_Tasks_Closed__c,
                Schema.SObjectType.Project_Task__c.fields.isStatusComplete__c,
                ALL_LREngine.RollupOperation.Sum 
            ));
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Activity__c.fields.Total_Tasks__c,
                Schema.SObjectType.Project_Task__c.fields.isActive__c,
                ALL_LREngine.RollupOperation.Sum 
            )); 
        
        ctx.add(new ALL_LREngine.RollupSummaryField(
            Schema.SObjectType.Project_Activity__c.fields.Planned_Start_Date__c,
            Schema.SObjectType.Project_Task__c.fields.Planned_Start_Date__c,
            ALL_LREngine.RollupOperation.Min
        ));
        ctx.add(new ALL_LREngine.RollupSummaryField(
            Schema.SObjectType.Project_Activity__c.fields.Planned_End_Date__c,
            Schema.SObjectType.Project_Task__c.fields.Planned_End_Date__c,
            All_LREngine.RollupOperation.Max
        ));
        
        
        
        //get the list of parent records and rollup values to be stamped on parent record
        if(projectTaskList != null && !projectTaskList.isEmpty())
        {
            //get the list of parent records and rollup values to be stamped on parent record
            parentList = ALL_LREngine.rollUp(ctx, projectTaskList);            
        }  
        return parentList;
        
    }
    
    public static List<sObject> createExpectedDurationRollup(List<Project_Task__c> projectTaskList)
    {
        
        List<sObject> parentList2 = new List<sObject>();
        
        //create and LREngine context assigning the child object and the parent object that will have the rollup values
        //add filters that will help determine rollup values
        ALL_LREngine.Context ctx = new ALL_LREngine.Context(Project_Activity__c.SobjectType, // parent object
                                                            Project_Task__c.SobjectType,  // child object
                                                            Schema.SObjectType.Project_Task__c.fields.Project_Activity__c,   // relationship field name
                                                            //'Status__c != \'Complete\''
                                                            'Status__c != \'Not Applicable\' AND Status__c != \'Complete\''    //filter
                                                           );
        
        //assign the field that will get the rollup value, field that will be rolled up and rollup operation to be done.    
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Activity__c.fields.Expected_Remaining_Duration__c,
                Schema.SObjectType.Project_Task__c.fields.Expected_Time_Spent__c,
                ALL_LREngine.RollupOperation.Sum 
            ));  
        
        if(projectTaskList != null && !projectTaskList.isEmpty())
        {
            System.debug('createExpectedDurationRollup projectTaskList :' + projectTaskList);
            //get the list of parent records and rollup values to be stamped on parent record
            parentList2 = ALL_LREngine.rollUp(ctx, projectTaskList);     
            system.debug('parentList $$ : ' + parentList2);
        }
        return parentList2;
    }  
    
    //finds the task which is updated recently with CDK Assignee value for given set of activitites and rollsup the CDKAssignee
    public static List<SObject> createCDKAssgineeRollUp(Set<Id> projectActivityIdSet) {
        List<SObject> activityList = new List<SObject>();
        
        if(projectActivityIdSet.size() > 0) {
            
            activityList = [
                SELECT Id, CDK_Assignee__c,
                (
                    SELECT CDK_Assignee__c 
                    FROM Project_Tasks__r 
                    WHERE CDK_Assignee__c != NULL 
                    ORDER BY LastModifiedDate desc LIMIT 1
                )
                FROM Project_Activity__c 
                WHERE Id IN :projectActivityIdSet
            ];
            
            for(SObject activity : activityList ) {
                for(SObject prjTask : activity.getSObjects('Project_Tasks__r')) {
                    activity.put('CDK_Assignee__c', prjTask.get('CDK_Assignee__c'));
                }
            }
            
        }
        
        return activityList;
    }
    
    public static List<sObject> mergeRollup(List<sObject> activityRollupList, List<sObject> newactivityRollupList,String fieldAPIName) {
        //Map<Id, sObject> activityMap = new Map<id, sObject>(activityRollupList);
        Map<Id, sObject> newactivityRollupMap = new Map<id, sObject>(newactivityRollupList);
        system.debug('newactivityRollupList : ' + newactivityRollupList);
        List<sObject> mergeList = new List<sObject>();
        for (sObject act : activityRollupList)
        {
            Id activityId = (Id)act.get('Id');
            if (newactivityRollupMap.containsKey(activityId))
            {                
                sObject activityUpdatedExptected = newactivityRollupMap.get( activityId );
                system.debug('activityUpdatedExptected : ' + activityUpdatedExptected);
                act.put(fieldAPIName,activityUpdatedExptected.get(fieldAPIName) );                
                newactivityRollupMap.remove(activityId);
                system.debug('newactivityRollupMap :' + newactivityRollupMap);
            }           
            
            mergeList.add(act);
        }
        
        if (newactivityRollupMap != null && !newactivityRollupMap.isEmpty())
        {
            mergeList.addAll(newactivityRollupMap.values());
        }
        
        system.debug('mergeList  : ' + mergeList);
        return mergeList;
    }
}