SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/UnfollowRecords_Handler.cls
//2016-12-05 -venkata.shrivol@cdk.com -commented the whole class as project object is getting deleted RQ-08305	
public class UnfollowRecords_Handler
{
    //Author: Anirudh Singh
    //Dated: 16th April, 2015
    //Description: SubProject Records should be auto-unfollowed if Project is Closed.
   /* public static void unfollowSubProjects(List<Project__c> updatedProjectsList)
    {
        try
        {
            Set<Id> closedProjectsIds=new Set<Id>();
            
            for(Project__c pRef: updatedProjectsList)
            {
                if(pRef.Project_Status__c != null && pRef.Project_Status__c.toLowerCase() == 'closed')
                {
                    closedProjectsIds.add(pRef.Id);
                }
            }
            
            List<EntitySubscription> listSubscriptionOnSubProjects = [
                SELECT Id 
                FROM EntitySubscription 
                WHERE ParentId IN (
                    SELECT Id 
                    FROM SubProject__c 
                    WHERE Project__r.Id IN :closedProjectsIds
                )
            ];
            
            delete listSubscriptionOnSubProjects;
        }
        catch(Exception ex)
        {
            system.debug('Exception: '+ex.getMessage());
        }
    }*/
}