SF Primes/src/objects/Project_Activity__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for an Activity associated with a Milestone.</description>
    <fields>
        <fullName>Force_Rollup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A system administrator field to support forced rollups via the logical rollup engine.</description>
        <label>Force Rollup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubProject_ID__c</fullName>
        <formula>Milestone__r.SubProject__r.Id</formula>
        <label>SubProject ID</label>
        <type>Text</type>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>AI-{000000000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Count_of_Milestones_on_SubProject__c</fullName>
        <description>Rolup field to display the number of Milestone records on a SubProject</description>
        <label>Count of Milestones on SubProject</label>
        <summaryForeignKey>Project_Milestone__c.SubProject__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SubProject_Status__c</fullName>
        <label>SubProject Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold No Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/classes/IMP_ForceLogicalRollup_Batch.cls
/*------------------------------------------------------------
Author: Kimiko Roberto
Company: Cloud Sherpas
Description: 
Test Class: 
History
10/20/15    Kimiko Roberto      Created

------------------------------------------------------------*/
global class IMP_ForceLogicalRollup_Batch implements Database.Batchable<sObject>, Database.Stateful{
    
    
    public String query = 'Select Id, Force_Rollup__c,SubProject_ID__c from Project_Activity__c ';
    // public String statusNotEqualTo = '';
    public Integer milestoneCount;
    global List<Project_Activity__c> tempProjectActivityList {get;set;}
    
    //start
    global Database.QueryLocator start(Database.BatchableContext info)
    {
       // List<SubProject__c> subProjectIdList = [Select Id FROM SubProject__c WHERE SubProject_Status__c !=: statusNotEqualTo AND Count_of_Milestones_on_SubProject__c > :milestoneCount];
       List<SubProject__c> subProjectIdList = [Select Id FROM SubProject__c WHERE Count_of_Milestones_on_SubProject__c > :milestoneCount];
       Set<String> subProjectIdSet = new Set<String>();
       system.Debug('***subProjectIdList: '+ subProjectIdList);
       if(subProjectIdList != null && !subProjectIdList.isEmpty())
       {
           for(SubProject__c sp : subProjectIdList)
           {
               String tempIdString = sp.Id;
               tempIdString = tempIdString.substring(0,15);
               subProjectIdSet.add(tempIdString);
           }
           system.Debug('***subProjectIdSet: '+ subProjectIdSet);
           query += 'WHERE SubProject_ID__c IN: subProjectIdSet';
       }
       system.Debug('***query: '+ query);
       return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext info, List<Project_Activity__c> projectActivityList)
    {
        system.Debug('***projectActivityList: '+ projectActivityList); 
        tempProjectActivityList = new List<Project_Activity__c>();
        if(projectActivityList!= null && !projectActivityList.isEmpty())
        {
            
            for(Project_Activity__c pa: projectActivityList)
            {
                pa.Force_Rollup__c = true;
            }
                
            update projectActivityList;
            
            //update the force rollup again to false
            for(Project_Activity__c pa: projectActivityList)
            {
                pa.Force_Rollup__c = false;
            }
                
            update projectActivityList;
            
            tempProjectActivityList.addAll(projectActivityList);
            system.Debug('***tempProjectActivityList: '+ tempProjectActivityList);
        }
        
    }     
    
    global void finish(Database.BatchableContext info)
    {
       /* 
       system.Debug('*** before update tempProjectActivityList: '+ tempProjectActivityList);
       if(tempProjectActivityList != null && !tempProjectActivityList.isEmpty())
        {
            for(Project_Activity__c pa: tempProjectActivityList)
            {
                pa.Force_Rollup__c = false;
            }
                
            update tempProjectActivityList;
        }
        
        system.Debug('***after update tempProjectActivityList: '+ tempProjectActivityList);
        */
    }  
    
    
}