SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Log__c.object
<CustomObject>
    <description>Contains various types of Project Log including Action Items, Change Requests, Issues, Lessons Learned and Risks to associate with either a Project or SubProject.</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Retrieves Project Name based on Record Type.</description>
        <formula>CASE( Record_Type_Name__c , 
&quot;Action Item&quot;, Project_Action_Items__r.Name , 
&quot;Change Request&quot;, Project_Change_Request__r.Name ,
&quot;Issue&quot;, Project_Issue__r.Name ,
&quot;Lesson Learned&quot;, Project_Lessons_Learned__r.Name ,
&quot;Risk&quot;, Project_Risk__r.Name ,
&quot;&quot;)</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <description>Retrieves SubProject Name based on Record Type</description>
        <formula>CASE( Record_Type_Name__c ,
&quot;Action Item&quot;,  Sub_Project_Action_Items__r.SubProject_Name__c ,
&quot;Change Request&quot;,  Sub_Project_Change_Request__r.SubProject_Name__c ,
&quot;Issue&quot;,  Sub_Project_Issue__r.SubProject_Name__c ,
&quot;Lesson Learned&quot;,  Sub_Project_Lessons_Learned__r.SubProject_Name__c ,
&quot;Risk&quot;,  Sub_Project_Risk__r.SubProject_Name__c ,
&quot;&quot;)</formula>
        <label>SubProject</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Action_Items__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Action Items</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Sub_Project_Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Change_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Change Request</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Issue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Issue</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Lessons_Learned__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Lessons Learned</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Lessons Learned</relationshipLabel>
        <relationshipName>Sub_Project_Lessons_Learned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Risk__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Risk</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Log</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Logs</pluralLabel>
    <recordTypes>
        <fullName>Issue</fullName>
        <active>true</active>
        <description>Log an Issue encountered with the Project.</description>
        <label>Issue</label>
    </recordTypes>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <description>Log a Risk encountered with the Project.</description>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubProject_Name__c</fullName>
        <label>SubProject Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_ProjectLog_Test.cls
/*-----------------------------------------------------------
Test Class for  - IMP_ProjectLog_Handler

2015-12-23 - venkata.shrivol@cdk.com  - Created
2016-06-06 - venkata.shrivol@cdk.com - updated this test class from Confidential checkbox to
									   Confidentiality_Status field
2016-12-05 -venkata.shrivol@cdk.com -commented the project object reference RQ-08305
-------------------------------------------------------------*/
@isTest
public class IMP_ProjectLog_Test 
{
	static list<String> recordTypesList = new list<String>{'Issue', 'Risk','Action Item','Change Request','Lesson Learned'};
	@testSetup
	static void createTestData()
	{
		/*Project__c testProject = IMP_TestFactory_Helper.buildProject(0);
        insert testProject;*/
        
        list<Subproject__c> testSubList = new list<Subproject__c>();
        SubProject__c subprj1 = 	IMP_TestFactory_Helper.buildSubProject();
        subprj1.SubProject_Name__c = 'Test SubProject 1';
        subprj1.Confidentiality_Status__c ='Confidential';
		testSubList.add(subprj1);
		SubProject__c subprj2 = 	IMP_TestFactory_Helper.buildSubProject();
		subprj1.SubProject_Name__c = 'Test SubProject 2';
		testSubList.add(subprj2);
        insert testSubList;
        
        list<Project_Log__c> testLogList = new list<Project_Log__c>();
		Project_Log__c issueLogRecord =  IMP_TestFactory_Helper.buildIssueLog(subprj1.Id);
		Project_Log__c riskLogRecord =  IMP_TestFactory_Helper.buildRiskLog(subprj1.Id);
		Project_Log__c actionItemRecord =  IMP_TestFactory_Helper.buildActionItemLog(subprj2.Id);
		Project_Log__c changeRequestRecord =  IMP_TestFactory_Helper.buildChangeRequestLog(subprj2.Id);
		Project_Log__c lessonLearnedRecord =  IMP_TestFactory_Helper.buildLessonLearnedLog(null);
		testLogList.add(issueLogRecord);
		testLogList.add(riskLogRecord);
		testLogList.add(actionItemRecord);
		testLogList.add(changeRequestRecord);
		testLogList.add(lessonLearnedRecord);
		insert testLogList;
	}
	
	public static testMethod void projectLogHandlerInsertTest()
	{
		
		map<string, Project_Log__c> projectlogMapByRecType =	new map<string, Project_Log__c>();
		
		list<Project_Log__c> insertedTestRecords = 
		[
			select Id,RecordType.Name, SubProject_Confidentiality_Status__c, Sub_Project_Issue__r.Confidentiality_Status__c,
				Sub_Project_Risk__r.Confidentiality_Status__c,  Sub_Project_Action_Items__r.Confidentiality_Status__c,
				Sub_Project_Change_Request__r.Confidentiality_Status__c
			from Project_Log__c
			where  RecordType.Name IN :recordTypesList
		];	
		
		for(Project_Log__c plg:insertedTestRecords)
		{
			projectlogMapByRecType.put(plg.RecordType.Name, plg);	
		}
		
		system.assertEquals(projectlogMapByRecType.get('Issue').Sub_Project_Issue__r.Confidentiality_Status__c, 
				projectlogMapByRecType.get('Issue').SubProject_Confidentiality_Status__c);
		system.assertEquals(projectlogMapByRecType.get('Risk').Sub_Project_Risk__r.Confidentiality_Status__c,
		 		projectlogMapByRecType.get('Risk').SubProject_Confidentiality_Status__c);
		system.assertEquals(projectlogMapByRecType.get('Action Item').Sub_Project_Action_Items__r.Confidentiality_Status__c, 
				projectlogMapByRecType.get('Action Item').SubProject_Confidentiality_Status__c);
		system.assertEquals(projectlogMapByRecType.get('Change Request').Sub_Project_Change_Request__r.Confidentiality_Status__c, 
				projectlogMapByRecType.get('Change Request').SubProject_Confidentiality_Status__c);
		
		system.assertEquals(null, projectlogMapByRecType.get('Lesson Learned').SubProject_Confidentiality_Status__c);
		
	}
	
	public static testMethod void projectLogHandlerUpdateTest()
	{
		list<Project_Log__c> projLogList = [
			select Id, Sub_Project_Lessons_Learned__c
			from Project_Log__c 
			where recordType.Name= 'Lesson Learned'
			limit 1
		];
		Project_Log__c thisProjLog = projLogList.size()> 0 ? projLogList.get(0) : new Project_Log__c();
		
		list<SubProject__c> SubProjects = [
			select Id, Confidentiality_Status__c 
			from SubProject__c 
			where Confidentiality_Status__c = 'Confidential'
		];
		SubProject__c thisSubProject = SubProjects.size() > 0 ? SubProjects.get(0) : new SubProject__c();
		
		Test.startTest();
			thisProjLog.Sub_Project_Lessons_Learned__c = thisSubProject.Id;
			update thisProjLog;
		Test.stopTest();
		
		Project_Log__c updatedProjectLog = [
			select SubProject_Confidentiality_Status__c
			from Project_Log__c 
			where recordType.Name= 'Lesson Learned'
			limit 1
		];
		
		system.assertEquals(updatedProjectLog.SubProject_Confidentiality_Status__c, thisSubProject.Confidentiality_Status__c);
	}
	
	public static testMethod void subProjectUpdateTest()
	{
		
		list<SubProject__c> SubProjects = [
			select Id, Confidentiality_Status__c 
			from SubProject__c 
		];
		
		for(SubProject__c sub : SubProjects)
		{
			if(sub.Confidentiality_Status__c == 'Confidential')
			{
				sub.Confidentiality_Status__c = 'Restricted';	
			}
			else{
				sub.Confidentiality_Status__c = 'Confidential';
			}	
		}
		Test.startTest();
			update SubProjects;
		Test.stopTest();
		
		projectLogHandlerInsertTest();		 
	}    
}