SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_CDK_Contact__c.object
<CustomObject>
    <description>Junction Object to relate multiple CDK Contacts to a SubProject</description>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject CDK Contacts</relationshipLabel>
        <relationshipName>SubProject_CDK_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject CDK Contact</label>
    <nameField>
        <displayFormat>SPCDK-{000000000}</displayFormat>
        <label>SP-CDK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject CDK Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_Client_Contact__c.object
<CustomObject>
    <description>Junction Object to relate multiple Client Contacts to a SubProject</description>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject Client Contacts</relationshipLabel>
        <relationshipName>SubProject_Client_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject Client Contact</label>
    <nameField>
        <displayFormat>SPC-{000000000}</displayFormat>
        <label>SP-Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fulldev2/src/classes/IMP_CDFLinesCanvasAppViewExtension_Test.cls
// RQ-05791    - SubProject Home Page changes.
// Description - Test class for IMP_CDFLinesCanvasAppViewExtension 
// 2015-12-09  - Venkata.shrivol@cdk.com  - Created

@isTest
public class IMP_CDFLinesCanvasAppViewExtension_Test 
{
	static testMethod void canvasAppExtensionTest()
    {
        Project__c testProject = IMP_TestFactory_Helper.buildProject(0);
        insert testProject;
        
        SubProject__c testSubProject = IMP_TestFactory_Helper.buildSubProject(testProject.Id);
        insert testSubProject;
        
        SubProject_Client_Contact__c spclientCont = new SubProject_Client_Contact__c();
        spclientCont.SubProject__c = testSubProject.Id;
        insert spclientCont;
        
        SubProject_CDK_Contact__c spcdkCont = new SubProject_CDK_Contact__c();
        spcdkCont.SubProject__c = testSubProject.Id;
        insert spcdkCont;
        
        Test.startTest();
        IMP_CDFLinesCanvasAppView_Extension testExtension = new IMP_CDFLinesCanvasAppView_Extension(new ApexPages.StandardController(testSubProject));
        testExtension.getParameterString();
        Test.stopTest();
    }
}