SF Primes/src/objects/Project_Activity__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for an Activity associated with a Milestone.</description>
    <fields>
        <fullName>Actual_End_Date_Final__c</fullName>
        <formula>IF(!ISBLANK(Actual_End_Date__c) &amp;&amp; (Total_Tasks__c - Total_Tasks_Closed__c == 0) &amp;&amp; Total_Tasks__c !=0, Actual_End_Date__c, null)</formula>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Current Max Project Task End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Remaining_Duration__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Expected Remaining Duration</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Project_Milestone__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Project_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Tasks__c == 0, &apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Actual_Time_Spent__c</fullName>
        <label>Total Actual Days Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Expected_Time_Spent__c</fullName>
        <label>Total Expected Time Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Tasks__c</fullName>
        <label>Total Tasks</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isActive</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isStatusComplete__c</fullName>
        <formula>IF( Status__c = &apos;Complete&apos;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isStatusComplete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>AI-{000000000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Milestone__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for a Milestone associated with a SubProject.</description>
    <fields>
        <fullName>Actual_End_Date_Final__c</fullName>
        <formula>IF(!ISBLANK(Actual_End_Date__c) &amp;&amp; (Total_Activities__c - Total_Activities_Closed__c == 0) &amp;&amp; Total_Activities__c !=0, Actual_End_Date__c, null)</formula>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Current Max Project Activity End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Remaining_Duration__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Expected Remaining Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Activities__c == 0,&apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Activities_Closed__c</fullName>
        <label>Total Activities Closed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Activities__c</fullName>
        <label>Total Activities</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Actual_Time_Spent__c</fullName>
        <label>Total Actual Days Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Expected_Time_Spent__c</fullName>
        <label>Total Expected Time Spent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Tasks__c</fullName>
        <description>Represents the count of total grandchild Project Tasks</description>
        <label>Total Tasks</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Milestone</label>
    <nameField>
        <displayFormat>MID-{000000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fulldev2/src/classes/IMP_BuildMilestoneRollups_Handler.cls
/*------------------------------------------------------------
Author:      Kimiko Roberto
Company:     Cloud Sherpas
Description: Creates rollups for Project Milestones
Inputs:      
Returns:     
History
02/19/15     Kimiko Roberto    Created
10/19/15     Karl Simon        In the createMilestoneRollups  method, added a sum rollup for Total Tasks from Project Activity to Project Milestone.
------------------------------------------------------------*/
public class IMP_BuildMilestoneRollups_Handler
{
    
    public static List<sObject> createMilestoneRollups(List<Project_Activity__c> projectActivityList)
    {
        
        List<sObject> parentList = new List<sObject>();
        
        //create and LREngine context assigning the child object and the parent object that will have the rollup values
        //add filters that will help determine rollup values
        ALL_LREngine.Context ctx = new ALL_LREngine.Context(Project_Milestone__c.SobjectType, // parent object
                                                            Project_Activity__c.SobjectType,  // child object
                                                            Schema.SObjectType.Project_Activity__c.fields.Milestone__c,    // relationship field name
                                                            'Status__c != \'Not Applicable\'' //filter
                                                           ); 
        
        //assign the field that will get the rollup value, field that will be rolled up and rollup operation to be done.                                   
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Total_Expected_Time_Spent__c,
                Schema.SObjectType.Project_Activity__c.fields.Total_Expected_Time_Spent__c,
                ALL_LREngine.RollupOperation.Sum 
            ));                                         
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Total_Actual_Time_Spent__c,
                Schema.SObjectType.Project_Activity__c.fields.Total_Actual_Time_Spent__c,
                ALL_LREngine.RollupOperation.Sum 
            ));   
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Total_Activities_Closed__c,
                Schema.SObjectType.Project_Activity__c.fields.isStatusComplete__c,
                ALL_LREngine.RollupOperation.Sum 
            ));   
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Actual_Start_Date__c,
                Schema.SObjectType.Project_Activity__c.fields.Actual_Start_Date__c,
                ALL_LREngine.RollupOperation.Min 
            ));    
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Planned_Start_Date__c,
                Schema.SObjectType.Project_Activity__c.fields.Planned_Start_Date__c,
                ALL_LREngine.RollupOperation.Min 
            ));    
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Planned_End_Date__c,
                Schema.SObjectType.Project_Activity__c.fields.Planned_End_Date__c,
                ALL_LREngine.RollupOperation.Max 
            ));    
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Total_Activities__c,
                Schema.SObjectType.Project_Activity__c.fields.isActive__c,
                ALL_LREngine.RollupOperation.Sum 
            ));
        
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Total_Tasks__c,
                Schema.SObjectType.Project_Activity__c.fields.Total_Tasks__c,
                ALL_LREngine.RollupOperation.Sum 
            ));
        
        
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Actual_End_Date__c,
                Schema.SObjectType.Project_Activity__c.fields.Actual_End_Date_Final__c,
                ALL_LREngine.RollupOperation.Max 
            ));
        
        
        
        if(projectActivityList != null && !projectActivityList.isEmpty())
        {
            //get the list of parent records and rollup values to be stamped on parent record
            parentList = ALL_LREngine.rollUp(ctx, projectActivityList);
            
            system.debug('parent');
        }   
        return parentList;
    }
    
    public static List<sObject> createExpectedDurationRollup(List<Project_Activity__c> projectActivityList)
    {
        
        List<sObject> parentList = new List<sObject>();
        
        //create and LREngine context assigning the child object and the parent object that will have the rollup values
        //add filters that will help determine rollup values 
        ALL_LREngine.Context ctx = new ALL_LREngine.Context(Project_Milestone__c.SobjectType, // parent object
                                                            Project_Activity__c.SobjectType,  // child object
                                                            Schema.SObjectType.Project_Activity__c.fields.Milestone__c, // relationship field name
                                                            'Status__c != \'Complete\' AND Status__c != \'Not Applicable\''
                                                           ); 
        
        //assign the field that will get the rollup value, field that will be rolled up and rollup operation to be done.                                
        ctx.add(
            new ALL_LREngine.RollupSummaryField(
                Schema.SObjectType.Project_Milestone__c.fields.Expected_Remaining_Duration__c,
                Schema.SObjectType.Project_Activity__c.fields.Expected_Remaining_Duration__c,
                ALL_LREngine.RollupOperation.Sum 
            ));  
        
        
        
        if(projectActivityList != null && !projectActivityList.isEmpty())
        {
            //get the list of parent records and rollup values to be stamped on parent record
            parentList = ALL_LREngine.rollUp(ctx, projectActivityList);             
        }                                    
        return parentList;
    }
    
    public static List<sObject> mergeRollup(List<sObject> milestoneRollupList, List<sObject> expectedDurationList) {
        //Map<Id, sObject> milestoneMap = new Map<id, sObject>(milestoneRollupList);
        Map<Id, sObject> expectedDurationMap = new Map<id, sObject>(expectedDurationList);
        
        List<sObject> mergeList = new List<sObject>();
        for (sObject miles : milestoneRollupList)
        {
            Id milestoneId = (Id)miles.get('Id');
            if (expectedDurationMap.containsKey(milestoneId))
            {                
                sObject milestoneUpdatedExptected = expectedDurationMap.get( milestoneId );
                system.debug('milestone milestoneUpdatedExptected : ' + milestoneUpdatedExptected);
                miles.put('Expected_Remaining_Duration__c',milestoneUpdatedExptected.get('Expected_Remaining_Duration__c') );                
                expectedDurationMap.remove(milestoneId);
                system.debug('milestone expectedDurationMap :' + expectedDurationMap);
            }           
            
            mergeList.add(miles);
        }
        
        if (expectedDurationMap != null && !expectedDurationMap.isEmpty())
        {
            mergeList.addAll(expectedDurationMap.values());
        }
        
        system.debug('milestone mergeList  : ' + mergeList);
        
        return mergeList;
    }
}