SF Primes/src/objects/Project__c.object
<CustomObject>
    <description>Project encompasses discovery workbook, checklist, subprojects, sites, project logs and additional details.</description>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project (Pilot)</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Log__c.object
<CustomObject>
    <description>Contains various types of Project Log including Action Items, Change Requests, Issues, Lessons Learned and Risks to associate with either a Project or SubProject.</description>
    <fields>
        <fullName>Lookup_Field_API_Name_to_Subproject__c</fullName>
        <formula>IF(NOT(ISBLANK(Sub_Project_Action_Items__c)) , &quot;Action_Items__c&quot;, 
  IF(NOT(ISBLANK(Sub_Project_Change_Request__c)) , &quot;Change_Request__c&quot;, 
    IF(NOT(ISBLANK(Sub_Project_Issue__c)) , &quot;Issue__c&quot;, 
      IF(NOT(ISBLANK(Sub_Project_Lessons_Learned__c)) , &quot;Lessons_Learned__c&quot;, 
        IF(NOT(ISBLANK(Sub_Project_Risk__c)) , &quot;Risk__c&quot;, 
          &quot;UNDEFINED&quot;
        )
      )
    )
  )
)</formula>
        <label>Lookup Field API Name to Subproject</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Retrieves Project Name based on Record Type.</description>
        <formula>CASE( Record_Type_Name__c , 
&quot;Action Item&quot;, Project_Action_Items__r.Name , 
&quot;Change Request&quot;, Project_Change_Request__r.Name ,
&quot;Issue&quot;, Project_Issue__r.Name ,
&quot;Lesson Learned&quot;, Project_Lessons_Learned__r.Name ,
&quot;Risk&quot;, Project_Risk__r.Name ,
&quot;&quot;)</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject_Id__c</fullName>
        <formula>IF(NOT(ISBLANK(Sub_Project_Action_Items__c)) , Sub_Project_Action_Items__c, 
  IF(NOT(ISBLANK(Sub_Project_Change_Request__c)) , Sub_Project_Change_Request__c, 
    IF(NOT(ISBLANK(Sub_Project_Issue__c)) , Sub_Project_Issue__c, 
      IF(NOT(ISBLANK(Sub_Project_Lessons_Learned__c)) , Sub_Project_Lessons_Learned__c,
        IF(NOT(ISBLANK(Sub_Project_Risk__c)) , Sub_Project_Risk__c, 
          &quot;&quot;
        )
      )
    )
  )
)</formula>
        <label>SubProject Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <description>Retrieves SubProject Name based on Record Type</description>
        <formula>CASE( Record_Type_Name__c ,
&quot;Action Item&quot;,  Sub_Project_Action_Items__r.SubProject_Name__c ,
&quot;Change Request&quot;,  Sub_Project_Change_Request__r.SubProject_Name__c ,
&quot;Issue&quot;,  Sub_Project_Issue__r.SubProject_Name__c ,
&quot;Lesson Learned&quot;,  Sub_Project_Lessons_Learned__r.SubProject_Name__c ,
&quot;Risk&quot;,  Sub_Project_Risk__r.SubProject_Name__c ,
&quot;&quot;)</formula>
        <label>SubProject</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Action_Items__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Action Items</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Sub_Project_Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Change_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Change Request</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Issue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Issue</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Lessons_Learned__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Lessons Learned</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Lessons Learned</relationshipLabel>
        <relationshipName>Sub_Project_Lessons_Learned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Project_Risk__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-Project - Risk</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Log</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProjects</relationshipLabel>
        <relationshipName>SubProjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_External_Reference__c.object
<CustomObject>
    <description>This object is used to store the Lookup relationships to external objects that are related to the Sub-Project like the Laser Artwork Order, NIS Mission etc.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project (Pilot)</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject External Reference</label>
    <nameField>
        <displayFormat>SPER-{0000000}</displayFormat>
        <label>External Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject External References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_External_Related_Entity__c.object
<CustomObject>
    <description>Object used to store IDs of all External Related Entities like Impact Project Numbers, RMS Request IDs, Contract Numbers, CMF Numbers. Currently all of this information comes in through the IMPACT Integration</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>SubProject External Related Entities</relationshipLabel>
        <relationshipName>SubProject_External_Related_Entities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject External Related Entities</relationshipLabel>
        <relationshipName>SubProject_External_Related_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject External Related Entity</label>
    <nameField>
        <displayFormat>EXT-{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject External Related Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProjectOpp__c.object
<CustomObject>
    <description>Junction object to allow associating multiple Opportunities with a SubProject.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>SubProjectOpps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>SubProjectOpps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProjectOpp</label>
    <nameField>
        <displayFormat>SPO-{00000000}</displayFormat>
        <label>SubProjectOpp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjectOpps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProjectSite__c.object
<CustomObject>
    <description>Junction object to allow associating multiple Sites (Accounts) with a SubProject.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>SubProjectSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProjectSite</label>
    <nameField>
        <displayFormat>SPS-{000000000}</displayFormat>
        <label>SubProjectSite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjectSites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_ReParentingSubProject_Helper.cls
/*------------------------------------------------------------
Author: Rey Austral
Company: Cloud Sherpas       
Description: Changing the Project__c field value for all Subproject child object 
when the subproject is re-parent with a new project
Test Class: IMP_ReParentingSubProject_Test
History
11/13/14    Rey Austral             Created
01/15/15    Samuel Oberes           Refactored: Made the getSubProjectLog project log type agnostic
Introduced the updateSubProjectChildObject method that caters for all the subproject child objects
10/29/15    Venkata Shrivol			Added a null check for SubProject in  getSubProjectLog method.       
12/05/16    Venkata Shrivol			commented the below code as project object reference is deleted on subproject RQ-08305
------------------------------------------------------------*/
//2016-03-03- anirudh.singh@cdk.com- Modified this class for Request RQ-06018 Update Trigger on SubProject and SubProjectOpp so they follow current dev stds.
public class IMP_ReParentingSubProject_Helper
{
   /* public static void executeReParent(Map<Id, SubProject__c> filteredSubProjectMap, Map<Id, SubProject__c> oldSubProjectsMap)
    {
        system.debug('Start executeReParent---->');
        
        Set<Id> subProjectIds=new Set<Id>();
        Set<Id> projectIds=new Set<Id>();
        
        //Get all Ids of SubProject and Project that will be used in the query for selecting related record.
        for(SubProject__c subProjectRecord: filteredSubProjectMap.values())
        {
            subProjectIds.add(subProjectRecord.Id);
            
            projectIds.add(oldSubProjectsMap.get(subProjectRecord.Id).Project__c);
        }
        
        //get all records that have lookup in subproject and project object in preparation to update the project field
        List<SubProjectOpp__c> subProjectOppList=(List<SubProjectOpp__c>)fetchSubProjectChildObjectList(subProjectIds, filteredSubProjectMap, 'SubProjectOpp__c');
        
        List<SubProject_External_Related_Entity__c> subProjectExternalRelatedEntityList=(List<SubProject_External_Related_Entity__c>)fetchSubProjectChildObjectList(subProjectIds, filteredSubProjectMap, 'SubProject_External_Related_Entity__c');
        
        List<SubProject_External_Reference__c> subProjectExternalReferenceList=(List<SubProject_External_Reference__c>)fetchSubProjectChildObjectList(subProjectIds, filteredSubProjectMap, 'SubProject_External_Reference__c');
        
        List<SubProjectSite__c> subProjectSiteList=(List<SubProjectSite__c>)fetchSubProjectChildObjectList(subProjectIds, filteredSubProjectMap, 'SubProjectSite__c'); 
        
        //...in continuation of getting all records, we create separate lists for each of the Project log types
        //since each log record has Lookup fields to Subproject for each log type, but only 1 can be populated based upon type;
        //we're looking to match against subproject, and, it'll require 5 separate passes to cover the 5 types
        List<Schema.FieldSetMember> consolidatedFieldSetMembersList=new List<Schema.FieldSetMember>();
        consolidatedFieldSetMembersList.addAll(SObjectType.Project_Log__c.FieldSets.Action_Item_Commons.getFields());
        consolidatedFieldSetMembersList.addAll(SObjectType.Project_Log__c.FieldSets.Change_Request_Commons.getFields());
        consolidatedFieldSetMembersList.addAll(SObjectType.Project_Log__c.FieldSets.Issue_Commons.getFields());
        consolidatedFieldSetMembersList.addAll(SObjectType.Project_Log__c.FieldSets.Lesson_Learned_Commons.getFields());
        consolidatedFieldSetMembersList.addAll(SObjectType.Project_Log__c.FieldSets.Risk_Commons.getFields());
        
        Set<String> fieldSetMembersFieldPaths=new Set<String>();
        List<Schema.FieldSetMember> fieldSetMembersList=new List<Schema.FieldSetMember>();
        
        for(Schema.FieldSetMember fieldSetMemberRef: consolidatedFieldSetMembersList)
        {
            if(!fieldSetMembersFieldPaths.contains(fieldSetMemberRef.getFieldPath()))
            {
                fieldSetMembersList.add(fieldSetMemberRef);
                fieldSetMembersFieldPaths.add(fieldSetMemberRef.getFieldPath());
            }
        }
        
        // NOTE:
        //   - The last parameter('SubProject_Id__c') is the ID to be used in checking for equality against the first parameter(subProjectIds) in the predicate evaluation.
        //   - The last parameter is a field that contains an ID coming from 1 of the ff. if they are not null: 
        //     - 'Sub_Project_Action_Items__c'
        //     - 'Sub_Project_Change_Request__c'
        //     - 'Sub_Project_Issue__c'
        //     - 'Sub_Project_Lessons_Learned__c'
        //     - 'Sub_Project_Risk__c'
        
        List<Project_Log__c> projectLogsList=fetchSubProjectLog(subProjectIds, filteredSubProjectMap, fieldSetMembersList, 'SubProject_Id__c');
        
        //get projects that will be empty when its last subproject has ben moved in preparation to close it    
        List<Project__c> projectsList=fetchProjectsToClose(projectIds);     
        
        //2016-03-03- anirudh.singh@cdk.com- Added Null checks for all the below IF Blocks for updating records.
        if(subProjectOppList!=Null && !subProjectOppList.isEmpty())
        {
            update subProjectOppList;
        }
        
        if(subProjectExternalRelatedEntityList!=Null && !subProjectExternalRelatedEntityList.isEmpty())
        {
            update subProjectExternalRelatedEntityList; 
        }
        
        if(subProjectExternalReferenceList!=Null && !subProjectExternalReferenceList.isEmpty())
        {
            update subProjectExternalReferenceList; 
        }
        
        if(subProjectSiteList!=Null && !subProjectSiteList.isEmpty())
        {
            update subProjectSiteList;
        }
        
        if(projectLogsList!=Null && !projectLogsList.isEmpty())
        {
            update projectLogsList;
        }
        
        if(projectsList!=Null && !projectsList.isEmpty())
        {           
            update projectsList;
        }
        
        system.debug('End executeReParent---->');
    }
    
    private static List<sObject> fetchSubProjectChildObjectList(Set<Id> subProjectIds, Map<Id, SubProject__c> filteredSubProjectMap, String subProjectChildObject)
    {
        system.debug('Start fetchSubProjectChildObjectList---->');
        
        List<FieldSetMember> fieldSetMembersList;
        
        if(subProjectChildObject=='SubProjectOpp__c')
        {
            fieldSetMembersList=sObjectType.SubProjectOpp__c.FieldSets.SubProject_Opp_Commons.getFields();
        }
        else if(subProjectChildObject=='SubProject_External_Related_Entity__c')
        {
            fieldSetMembersList=sObjectType.SubProject_External_Related_Entity__c.FieldSets.External_Related_Entity_Commons.getFields();
        }
        else if(subProjectChildObject=='SubProject_External_Reference__c')
        {
            fieldSetMembersList=sObjectType.SubProject_External_Reference__c.FieldSets.External_Reference_Commons.getFields();
        }
        else
        {
            fieldSetMembersList=sObjectType.SubProjectSite__c.FieldSets.SubProject_Site_Common.getFields();
        }
        
        //get all subproject child objects 
        List<sObject> objectList=IMP_Project_Utility.queryRelatedRecords(fieldSetMembersList, subProjectChildObject, 'SubProject__c', 
                                                                         null, subProjectIds, null, null, true, 1000);         
        
        //change the value of the child object's project id to the new project id
        SubProject__c subProj;
        
        for(sObject obj: objectList)
        {
            subProj=filteredSubProjectMap.get((Id)obj.get('SubProject__c'));
            obj.put('Project__c', subProj.Project__c);
        }
        
        system.debug('End fetchSubProjectChildObjectList---->');
        return objectList;
    }
    
    private static List<Project_Log__c> fetchSubProjectLog(Set<Id> subProjectIds, Map<Id, SubProject__c> subProjectMap, List<Schema.FieldSetMember> fieldSetMembersList, String subProjectField)
    {
        system.debug('Start fetchSubProjectLog---->');
        
        // NOTE: DO NOT PASS A SET OF IDs TO THE QUERY BELOW, BECAUSE THE SET OF IDs WILL ALWAYS CONTAIN 18-DIGIT IDs
        //       INSTEAD, PASS A LIST OF STRINGS, WHEREIN THE STRINGS ARE ALREADY TRIMMED 15-CHARACTER STRING IDs.
        List<String> subProjectIdsList=new List<String>();
        
        for(Id idRef: subProjectIds)
        {
            subProjectIdsList.add(String.valueOf(idRef).substring(0, 15));
        }
        
        List<Project_Log__c> projectLogsList=(List<Project_Log__c>)IMP_Project_Utility.queryRelatedRecords(fieldSetMembersList, 'Project_Log__c', subProjectField, 
                                                                                                           null, null, subProjectIdsList, null, true, 1000);
        
        //change the value of project to the new project id
        SubProject__c subProjectRecord;
        String projectLogType;
        
        for(SObject projectLog: projectLogsList)
        {
            projectLogType=(String)projectLog.get('Lookup_Field_API_Name_to_Subproject__c');
            
            subProjectRecord=subProjectMap.get((Id)projectLog.get('Sub_Project_' + projectLogType));
            
            //Added this check because projectLogsList is retrieving the irrelevant project log records 
            //by matching first 15-digit string of subProjectID 
            if(subProjectRecord!=null)
            {
                projectLog.put('Project_'+projectLogType, subProjectRecord.Project__c);	
            }
        }   
        
        system.debug('End fetchSubProjectLog---->');
        return projectLogsList;
    }
    
    private static List<Project__c> fetchProjectsToClose(Set<Id> projectIds) 
    {
        system.debug('Start fetchProjectsToClose---->');
        
        //retrieve all subprojects of the source project
        List<SubProject__c> subProjectsList=(List<SubProject__c>)IMP_Project_Utility.queryRelatedRecords(SObjectType.SubProject__c.FieldSets.SubProject_Commons.getFields(), 'SubProject__c', 
                                                                                                         'Project__c', null, projectIds, null, null, true, 1000);         
        
        Set<Id> setForClosedProjectIds=new Set<Id>();
        
        //2016-03-03- anirudh.singh@cdk.com- Commented the below line. Now using Set as Map is irrelevant here and Set satisfies the purpose.
        //in the result query of subproject get all the project id
        //Map<Id, Id> mapSubProjectIds=getProjectIdFromSubProject(subProjectsList);
        
        //2016-03-03- anirudh.singh@cdk.com- Created this variable for using it instead of Map.
        Set<Id> subProjectIds=new Set<Id>();
        for(SubProject__c subProjectRecord: subProjectsList)
        {
            subProjectIds.add(subProjectRecord.Project__c);
        }
        
        //2016-03-03- anirudh.singh@cdk.com- Changed the use of Map and now using Set instead.
        //Iterate the source projectId
        for(Id idRef: projectIds)
        {
            //check the projectId is in the Set, if the id is not in the Set it means the project does not contain any subproject.
            if(!subProjectIds.contains(idRef))
            {
                //check the project id if already contains in the list to be closed.
                if(!setForClosedProjectIds.contains(idRef))
                {
                    setForClosedProjectIds.add(idRef);                     
                }
            }
        }
        
        List<Project__c> projectsList=new List<Project__c>();
        
        if(!setForClosedProjectIds.isEmpty())
        {
            //query the list of id to be closed
            projectsList=(List<Project__c>)IMP_Project_Utility.queryRelatedRecords(SObjectType.Project__c.FieldSets.Project_Commons.getFields(), 'Project__c', 'Id', 
                                                                                   null, setForClosedProjectIds, null, null, true, 1000);         
            
            if(!projectsList.isEmpty())
            {
                for(Project__c projectRecord: projectsList)
                {
                    projectRecord.Project_Status__c='Closed';
                }
            }
        }
        
        system.debug('End fetchProjectsToClose---->');
        return projectsList;
    }
    
    //2016-03-03- anirudh.singh@cdk.com- Commented this method as it was not needed.
    /*private static Map<Id, Id> getProjectIdFromSubProject(List<SubProject__c> subProjectsList)
    {
        system.debug('Start getProjectIdFromSubProject---->');
        Map<Id, Id> convertMap=new Map<Id, Id>();
        
        for(SubProject__c subProjectRecord: subProjectsList)
        {
            if(!convertMap.containsKey(subProjectRecord.Project__c)) 
            {
                convertMap.put(subProjectRecord.Project__c, subProjectRecord.Project__c);
            }
        }
        
        system.debug('End getProjectIdFromSubProject---->');
        return convertMap;
    }*/
}