SF Primes/src/objects/Project_Activity__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for an Activity associated with a Milestone.</description>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Current Max Project Task End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Activity Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>External_Activity_Name__c</fullName>
        <formula>Activity_Definition__r.External_Activity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External Activity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Project_Milestone__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Project_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Tasks__c == 0, &apos;Not Applicable&apos;,
IF( !ISBLANK(Actual_End_Date_Final__c) ,&apos;Complete&apos;, 
IF( ISBLANK(Planned_End_Date__c) ,&apos;On Target&apos;, 
IF( Duration_Buffer__c &lt;= 0,&apos;At Risk&apos;, 
IF( (Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &lt;= 1.25),&apos;Caution&apos;, 
IF((Duration_Buffer__c &gt; 0) &amp;&amp; ((Duration_Buffer__c + MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0))/MAX(DATETIMEVALUE(Planned_End_Date__c) - DATETIMEVALUE(TODAY()),0) &gt; 1.25),&apos;On Target&apos;, 
null 
))))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject_ID__c</fullName>
        <formula>Milestone__r.SubProject__r.Id</formula>
        <label>SubProject ID</label>
        <type>Text</type>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>AI-{000000000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Milestone__c.object
<CustomObject>
    <description>Contains Comments, Start, End Dates and relevant information for a Milestone associated with a SubProject.</description>
    <label>Project Milestone</label>
    <nameField>
        <displayFormat>MID-{000000000}</displayFormat>
        <label>Milestone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Task Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>External_Activity_Name__c</fullName>
        <formula>Project_Activity__r.External_Activity_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External Activity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Activity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project Activity</label>
        <referenceTo>Project_Activity__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Status_Not_Applicable__c = true,&apos;Not Applicable&apos;,
IF(!ISBLANK(Actual_End_Date__c),&apos;Complete&apos;,
IF(!ISBLANK(Actual_Start_Date__c) &amp;&amp; ISBLANK(Actual_End_Date__c),&apos;In Progress&apos;,
IF(!ISBLANK( CDK_Assignee__c ),&apos;Assigned&apos;,
IF(ISBLANK( CDK_Assignee__c ),&apos;Unassigned&apos;,
null
)))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubProject_ID__c</fullName>
        <formula>Project_Activity__r.Milestone__r.SubProject__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubProject ID</label>
        <type>Text</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <displayFormat>TI-{000000000}</displayFormat>
        <label>Project Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjectsMgrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject_Status__c</fullName>
        <label>SubProject Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold No Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_ProjectActivityCapture_Batch.cls
/*------------------------------------------------------------
Author: Michael Lasala
Company: Cloud Sherpas
Description: Batch implementation of ProjectActivity Capture Process
Test Class: 
History
09/24/14    Michael Lasala      Created
10/07/14    Michael Lasala      Added processing of records inside execute (previously in handler class), Added Database.Stateful to preserve global variables for finish processing
10/07/14    Michael Lasala      Added posting to Subproject chatter feed with mentioned SubProject Project Manager and Project Milestone and Project Activity error details on finish
03/31/15    Samuel Oberes       Replaced project activity references to project task
04/14/15    Samuel Oberes       Changed the query to be more selectable
04/20/15    Samuel Oberes       Fixed the error wherein the feed won't get posted whenever the project manager ID is not supplied
------------------------------------------------------------*/
global class IMP_ProjectActivityCapture_Batch implements Database.Batchable<sObject>, Database.Stateful
{
    //Used for dynamic handling for the handler calss
    global String recordTypeName;
    
    global Map<Id, Id> subProjectPMMap {get;set;}
    global Map<Id, String> subProjectNameMap {get;set;}
    global Map<Id, Map<Id, String>> milestoneMap {get;set;}
    global Map<Id, String> laoMap {get;set;}
    global Map<Id, List<String>> milestoneActivityMap {get;set;}
    
    global IMP_ProjectActivityCapture_Batch()
    {
        recordTypeName = '';
        subProjectPMMap = new Map<Id, Id>();
        subProjectNameMap = new Map<Id, String>();
        milestoneMap = new Map<Id, Map<Id, String>>();
        laoMap = new Map<Id, String>();
        milestoneActivityMap = new Map<Id, List<String>>();
    }
    
    global Database.QueryLocator start(Database.BatchableContext info)
    { 
        String query = '';
        //Retrieve SubProjects where Status != Closed
        if(Test.isRunningtest())
        {
            //Limit records if executing test
            //query = ('SELECT Id FROM SubProject__c WHERE SubProject_Status__c != \'Closed\' Order By CreatedDate desc Limit 50');
            query = ('SELECT SubProject_ID__c FROM Project_Task__C WHERE Project_Activity__r.Milestone__r.Status__c != \'Closed\' AND External_Activity_Name__c != null AND Actual_End_Date__c = null ORDER BY CreatedDate desc Limit 50');
        } 
        else 
        {
            //query = ('SELECT Id FROM SubProject__c WHERE SubProject_Status__c != \'Closed\'');
            query = ('SELECT SubProject_ID__c FROM Project_Task__c WHERE Project_Activity__r.Milestone__r.Status__c != \'Closed\' AND External_Activity_Name__c != null AND Actual_End_Date__c = null');
        }

        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext info, List<sObject> scope)
    { 
        Set<Id> subProjectSet = new Set<Id>();

        for(Sobject o: scope)
        {
            subProjectSet.add((Id)o.get('SubProject_ID__c'));
        }
        
        //Process records
        IMP_ProjectActivityCapture_Handler captureHandler = new IMP_ProjectActivityCapture_Handler();
        List<Project_Task__c> projectTasksForUpdate = captureHandler.IMP_ProjectActivityCapture_Handler(recordTypeName, subProjectSet);
        System.debug('$$$ projectTasksForUpdate: ' + projectTasksForUpdate.size());
        
        if(!projectTasksForUpdate.isEmpty())
        {
            //Used for getting Project Activity data 
            Integer i = 0;
            
            //Update activities, boolean parameter set to false so success records will update
            List<Database.SaveResult> dsrs = Database.Update(projectTasksForUpdate, false);
            
            for(Database.SaveResult dsr : dsrs)
            {
                //Iterate over failure records
                if(!dsr.isSuccess())
                {
                    //Key: Project Milestone Id, Value: Project Milestone Description
                    //Used for naming parent Project Milestone of processed Project Activities
                    Map<Id, String> tempMap = new Map<Id, String>();
                    tempMap.put(projectTasksForUpdate[i].Project_Activity__r.Milestone__c, projectTasksForUpdate[i].Project_Activity__r.Milestone__r.Description__c);
                    
                    //Key: SubProject Id, Value: SubProject Project Manager User Id
                    //Used for setting Chatter subjectId and mention (mentionSegmentInput.Id)
                    subProjectPMMap.put(projectTasksForUpdate[i].SubProject_ID__c, projectTasksForUpdate[i].Project_Activity__r.Milestone__r.SubProject__r.Project_Manager__c);
                    
                    //Key: SubProject Id, Value: SubProject Name
                    //Used for setting SubProject hyperlink on Chatter post
                    subProjectNameMap.put(projectTasksForUpdate[i].SubProject_ID__c, projectTasksForUpdate[i].Project_Activity__r.Milestone__r.SubProject__r.Name);
                    
                    //Key: SubProject Id, Value: Project Milestone map
                    //Used for identifying which Project Milestone belongs to which SubProject
                    if(milestoneMap.containsKey(projectTasksForUpdate[i].SubProject_ID__c))
                    {                        
                        milestoneMap.get(projectTasksForUpdate[i].SubProject_ID__c).put(projectTasksForUpdate[i].Project_Activity__r.Milestone__c, projectTasksForUpdate[i].Project_Activity__r.Milestone__r.Description__c);
                    } 
                    else 
                    {
                        milestoneMap.put(projectTasksForUpdate[i].SubProject_ID__c, tempMap);
                    }
                    
                    //Key: Milestone Id, Value: External System Name
                    //Used for identifying which Project Milestone External System Name belongs to which Project Milestone Id
                    laoMap.put(projectTasksForUpdate[i].Project_Activity__r.Milestone__c, projectTasksForUpdate[i].Project_Activity__r.Milestone__r.External_System_Name__c);
                    
                    //Construct string which consists of the Task Description along with it's error message
                    String taskDescriptionError = String.valueOf(projectTasksForUpdate[i].Description__c+' - '+dsr.getErrors()[0].getMessage());
                    
                    //Key: Project Milestone Id, Value: List<String> Project Activity + error message
                    //Used for identifying which Project Activity belongs to which Project Milestone
                    if(milestoneActivityMap.containsKey(projectTasksForUpdate[i].Project_Activity__r.Milestone__c))
                    {                        
                        milestoneActivityMap.get(projectTasksForUpdate[i].Project_Activity__r.Milestone__c).add(taskDescriptionError);
                    } 
                    else 
                    {
                        List<String> tempList = new List<String>();
                        tempList.add(taskDescriptionError);
                        milestoneActivityMap.put(projectTasksForUpdate[i].Project_Activity__r.Milestone__c, tempList);
                    }
                }
                i++;
            }
            
            System.debug('$$$ subProjectPMMap: ' + subProjectPMMap.keySet() + ', ' + subProjectPMMap.values());
            System.debug('$$$ milestoneMap: ' + milestoneMap.keySet() + ', ' + milestoneMap.values());
            System.debug('$$$ milestoneActivityMap: ' + milestoneActivityMap.keySet() + ', ' + milestoneActivityMap.values());
        }
    }     
    
    global void finish(Database.batchableContext info)
    {
        if(!subProjectPMMap.keySet().isEmpty())
        {
            //For bulk posting of Chatter feeds
            List<ConnectApi.BatchInput> batchInputList = new List<ConnectApi.BatchInput>();
            
            String baseURL = System.Url.getSalesforceBaseURL().toExternalForm();
            System.debug('$$$ baseURL: '+baseURL);
            
            //Iterate over each SubProject
            for(Id subProjectId: subProjectPMMap.keySet())
            {
                //Instantiate ConnectApi.FeedItemInput for posting on Chatter
                ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
                ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
                ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
                ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
                
                messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();
                
                //Assign SubProject Project Manager User Id for mention
                if (subProjectPMMap.get(subProjectId) != null) {
                    mentionSegmentInput.id = subProjectPMMap.get(subProjectId);
                    messageBodyInput.messageSegments.add(mentionSegmentInput);
                    System.debug('$$$ Project Manager: '+subProjectPMMap.get(subProjectId));
                }
                
                //Construct plain text to be included in the post
                String chatterPostText = '';
                chatterPostText = ' Activity Detail Capture Job Failure in '+subProjectNameMap.get(subProjectId)+': '+baseURL+'/'+subProjectId+'\n';
                
                //Iterate over parent Project Milestones of failed Project Activities 
                for(Id milestoneId: milestoneMap.get(subProjectId).keySet())
                {
                    
                    //Add Description for identification
                    chatterPostText += '\n Milestone: '+milestoneMap.get(subProjectId).get(milestoneId)+'\n';
                    System.debug('$$$ Project Milestone: '+milestoneMap.get(subProjectId).get(milestoneId));
                    
                    //Add External Id
                    chatterPostText += 'External ID: '+laoMap.get(milestoneId)+'\n';
                    System.debug('$$$ External Id: '+laoMap.get(milestoneId));
                    
                    chatterPostText += '\n Project Activity:';
                    
                    //Count for number of Project Activities involved
                    Integer count = 0;
                    
                    //Iterate over failed Project Activities
                    for(String activityString: milestoneActivityMap.get(milestoneId))
                    {
                        count++;
                        
                        //Add Description + error message
                        chatterPostText += '\n'+count+'. '+activityString;
                    }
                    System.debug('$$$: Activity: '+milestoneActivityMap.get(milestoneId));
                    
                    //Add line breaks if there are multiple Project Milestones
                    if(milestoneMap.get(subProjectId).keySet().size()>1)
                    {
                        chatterPostText += '\n';
                    }
                }
                System.debug('$$$: chatterPostText: '+chatterPostText);
                
                //Assign plain text value
                textSegmentInput.text = chatterPostText;
                messageBodyInput.messageSegments.add(textSegmentInput);
                
                feedItemInput.body = messageBodyInput;
                feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
                
                //Assign ParentId
                feedItemInput.subjectId = subProjectId;
                
                //Used for bulk posting of ConnectApi.FeedItemInput
                ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(feedItemInput);
                batchInputList.add(batchInput);
            }
            
            //Post Chatter feeds
            ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), batchInputList);
            System.debug('$$$ batchInputList: '+batchInputList.size());
        }
    }
}