SF Primes/src/objects/Request__c.object
<CustomObject>
    <description>Used by SF Admins to send configuration updates to Sales Automation</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending BU for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - In Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity - Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New - Under Review</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Unassigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Pre-Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Config / Dev - Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sprints - In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Brief Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SF Primes/src/classes/ALL_Request_Handler.cls
// Author : Lalitha Adduru
// Description : Handler class for All_Request Trigger. 

public class ALL_Request_Handler 
{

    // Unfollows all followers of a request when its status is changed to 'Completed'
    public static void unfollowOnCompletion(List<Request__c> requestList, Map<id, Request__c> oldRequestMap)
    {
        system.debug('unfollow on completion');
        List<Request__c> validRequestList = new List<Request__c>();
        if(requestList != null && requestList.size() > 0)
        {
            for(Request__c req : requestList)
            {
                if(req.Status__c == 'Completed' && req.Status__c != oldRequestMap.get(req.id).Status__c )
                {
                    system.debug('status changed to completed');
                	validRequestList.add(req);   
                }
            }
        } 
        if(validRequestList != null && validRequestList.size() > 0)
        {
            List<EntitySubscription> followers = new List<EntitySubscription>();
            followers = [
                select id 
                from EntitySubscription 
                where parentId in :validRequestList 
                LIMIT 1000
            ];
            
            if(followers.size() > 0)
            {
                try
                {
                    delete followers;
                }
                catch(Exception ex)
                {
                    system.debug('Exception at '+ ex.getLineNumber() + ': '+ex.getMessage());
                }
            }
        }
    }
}