SF Primes/src/objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_CDK_Contact__c.object
<CustomObject>
    <description>Junction Object to relate multiple CDK Contacts to a SubProject</description>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject CDK Contacts</relationshipLabel>
        <relationshipName>SubProject_CDK_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject CDK Contact</label>
    <nameField>
        <displayFormat>SPCDK-{000000000}</displayFormat>
        <label>SP-CDK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject CDK Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/SubProject_Client_Contact__c.object
<CustomObject>
    <description>Junction Object to relate multiple Client Contacts to a SubProject</description>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject Client Contacts</relationshipLabel>
        <relationshipName>SubProject_Client_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject Client Contact</label>
    <nameField>
        <displayFormat>SPC-{000000000}</displayFormat>
        <label>SP-Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject Client Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/IMP_CDFLinesCanvasAppViewExtension_Test.cls
// RQ-05791    - SubProject Home Page changes.
// Description - Test class for IMP_CDFLinesCanvasAppViewExtension 
// 2015-12-09  - Venkata.shrivol@cdk.com  - Created
//2016-12-05   -venkata.shrivol@cdk.com    -commented the project object reference RQ-08305
// 2017-03-01  - vishal.bandari@cdk.com - updated code to work with list of subproject Ids - RQ-08666
@isTest
public class IMP_CDFLinesCanvasAppViewExtension_Test 
{
	static testMethod void canvasAppExtensionTest()
    {
        
        SubProject__c testSubProject = IMP_TestFactory_Helper.buildSubProject();
        insert testSubProject;
        
        SubProject__c testSubProject2 = IMP_TestFactory_Helper.buildSubProject();
        insert testSubProject2;
        
        SubProject_Client_Contact__c spclientCont = new SubProject_Client_Contact__c();
        spclientCont.SubProject__c = testSubProject.Id;
        insert spclientCont;
        
        SubProject_CDK_Contact__c spcdkCont = new SubProject_CDK_Contact__c();
        spcdkCont.SubProject__c = testSubProject.Id;
        insert spcdkCont;
        
        Test.startTest();
        ApexPages.CurrentPage().getParameters().put('subProjectIds',testSubProject.Id+'|'+testSubProject2.Id);
        IMP_CDFLinesCanvasAppView_Extension testExtension = new IMP_CDFLinesCanvasAppView_Extension(new ApexPages.StandardController(testSubProject));
        testExtension.getParameterString();
        Test.stopTest();
    }
}