SF Primes/src/objects/System_at_Dealership__c.object
<CustomObject>
    <description>Systems identified at a specific dealership</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Systems at Dealership</relationshipLabel>
        <relationshipName>R00N40000001leejEAA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Install_Date__c</fullName>
        <label>Current Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLX_Sys_ID__c</fullName>
        <label>SLX Sys ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLX_Vendor_ID__c</fullName>
        <label>SLX Vendor ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Type__c</fullName>
        <label>System Type</label>
        <picklist>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>Systems at Dealership (Vendor)</relationshipLabel>
        <relationshipName>R00N40000001lfXZEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System at Dealership</label>
    <nameField>
        <displayFormat>ID - {00000}</displayFormat>
        <label>Sys at Dealership</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems at Dealership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Systems__c.object
<CustomObject>
    <description>List of valid DMS/CRM/Leasing/Phone systems</description>
    <fields>
        <fullName>SLXSystem_ID__c</fullName>
        <label>SLXSystem ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLXVendor_ID__c</fullName>
        <label>SLXVendor ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Systems</label>
    <nameField>
        <label>Vendor System</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Docusign/src/classes/DS_SystemAtDealerShipInsertTest.cls
public class DS_SystemAtDealerShipInsertTest {
	/*
    testMethod static void testSystemAtDealerShipInsert(){
    	Account acct = new Account(Name='Audi of Bensenville');
    	insert acct;
		Systems__c sys = new Systems__c(Name='ADP RON ASP');
			sys.SLXVendor_Id__c = 'RONADP123456';
			sys.SLXSystem_Id__c = 'RONADP987654';
			sys.Type__c = 'DMS';
		insert sys;
		System_at_Dealership__c dealerSys = new System_at_Dealership__c(Name='ID - 11111');
			dealerSys.Account__c = acct.Id;
			dealerSys.Vendor__c = sys.Id;
			dealerSys.Install_Date__c = Date.ValueOf('2009-01-27');
			dealerSys.System_Type__c = 'DMS';
			dealerSys.SLX_Vendor_ID__c = sys.SLXVendor_Id__c;
			dealerSys.SLX_Sys_ID__c = sys.SLXSystem_Id__c;
		insert dealerSys;
		Systems__c sys1 = new Systems__c(Name='ADP RON 9500');
			sys1.SLXVendor_Id__c = 'RONADP012345';
			sys1.SLXSystem_Id__c = 'RONADP098765';
			sys1.Type__c = 'DMS';
		insert sys1;
		System_at_Dealership__c dealerSys1 = new System_at_Dealership__c(Name='ID - 22222');
			dealerSys1.Account__c = acct.Id;
			dealerSys1.Vendor__c = sys1.Id;
			dealerSys1.Install_Date__c = Date.ValueOf('2009-01-28');
			dealerSys1.System_Type__c = 'DMS';
			dealerSys1.SLX_Vendor_ID__c = sys1.SLXVendor_Id__c;
			dealerSys1.SLX_Sys_ID__c = sys1.SLXSystem_Id__c;
		insert dealerSys1;
    }
    */
}