SF Primes/src/objects/Traver_Coaching__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>B4B Coaching</relationshipLabel>
        <relationshipName>B4B_Coaching</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_PSG__c</fullName>
        <label>Number of Days - PSG</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_Traver__c</fullName>
        <inlineHelpText>Number of Days</inlineHelpText>
        <label>Number of Days - Traver</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TRV_Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>TRV_Resource__c</referenceTo>
        <relationshipLabel>B4B Coaching (Completed By)</relationshipLabel>
        <relationshipName>TRV_Completed_By_B4BCoaching</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TRV_FRM_Resource_Name_onResource__c</fullName>
        <formula>TRV_Completed_By__r.TRV_Resource__r.FirstName + &apos; &apos; +  TRV_Completed_By__r.TRV_Resource__r.LastName</formula>
        <label>Resource Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRV_Resource_Email__c</fullName>
        <label>Resource Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Traver_Project__c</fullName>
        <label>Consulting Project</label>
        <referenceTo>Traver_Project__c</referenceTo>
        <relationshipLabel>B4B Coaching</relationshipLabel>
        <relationshipName>Traver_Onsite_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Visit_Start_Date__c</fullName>
        <label>Visit Start Date</label>
        <type>Date</type>
    </fields>
    <label>B4B Coaching</label>
    <nameField>
        <displayFormat>B4B-{00000}</displayFormat>
        <label>B4B Coaching ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B4B Coaching</pluralLabel>
    <recordTypes>
        <fullName>PSC_Visit</fullName>
        <active>true</active>
        <description>PSC Visit</description>
        <label>PSC Visit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process_Coach_Visit</fullName>
        <active>true</active>
        <description>Process Coach Visit</description>
        <label>Process Coach Visit</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Traver_Project__c.object
<CustomObject>
    <description>Project/Product object used by Traver Technologies</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Traver_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Consulting Project</label>
    <nameField>
        <displayFormat>Consulting# {00000}</displayFormat>
        <label>Consulting Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consulting Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf_vishalhack/src/classes/TRV_RenderB4BCoachingAsPDF_Controller.cls
//2017-05-02	lalitha.adduru@cdk.com	added frenchDocusignNeeded - RQ-08667
public class TRV_RenderB4BCoachingAsPDF_Controller {
    
    public Traver_Coaching__c objB4B {get;set;}
    public String DateOfVisit {get;set;}
    Public String NumberOfDays {get;set;}
    Public string deliveryLocation {get;set;}
    Public String processCoachVisitId;
    Public String pscVisitTypeId;
    public Boolean isDeliveryLocation{get;set;}
    public String linkToB4B {get;set;}
    public boolean frenchDocusignNeeded {get;set;} //added by lalitha RQ-08667
   
    public TRV_RenderB4BCoachingAsPDF_Controller(ApexPages.StandardController controller) {
        
         deliveryLocation= '';
                    
         for(RecordType objRecordType : [
                                            SELECT Id, DeveloperName, SobjectType 
                                            FROM RecordType 
                                            WHERE SobjectType = 'Traver_Coaching__c'
                                        ]) {
            
            if(objRecordType.DeveloperName == 'Process_Coach_Visit') {
                
                processCoachVisitId = objRecordType.Id;
            }
            
           
            if(objRecordType.DeveloperName == 'PSC_Visit') {
                
                pscVisitTypeId = objRecordType.Id;
            }
        }
		
        // lalitha included French_DocuSign_Needed__c in the query
        objB4B = [SELECT Id,Delivery_Location__c,RecordTypeId,Delivery_Location__r.BillingStreet,Delivery_Location__r.BillingCity,
                  Delivery_Location__r.BillingPostalCode,Delivery_Location__r.BillingState,
                  Traver_Project__r.Account__r.BillingAddress,Traver_Project__r.French_DocuSign_Needed__c,Traver_Project__c,TRV_Completed_By__c,
                  TRV_FRM_Resource_Name_onResource__c,TRV_Resource_Email__c,Visit_Start_Date__c,Number_of_Days_PSG__c,
                  Number_of_Days_Traver__c
                    FROM Traver_Coaching__c WHERE id=: controller.getRecord().Id];
        
        //lalitha - RQ-08667
        frenchDocusignNeeded = objB4B.Traver_Project__r.French_DocuSign_Needed__c == false ? false : true;
        
        DateOfVisit = String.ValueOf(Date.ValueOf(objB4B.Visit_Start_Date__c));
        if(objB4B.RecordTypeId == pscVisitTypeId)
            NumberOfDays = String.ValueOf(Integer.ValueOf(objB4B.Number_of_Days_PSG__c));
        else if(objB4B.RecordTypeId == processCoachVisitId) 
            NumberOfDays = String.ValueOf(Integer.ValueOf(objB4B.Number_of_Days_Traver__c));
         linkToB4B = System.URL.getSalesforceBaseURL().toExternalForm()+'/'+ objB4B.Id;   
          
       if(objB4B.Delivery_Location__c!= NULL) {
            isDeliveryLocation =true;
         
            if(!String.ISBLANK(objB4B.Delivery_Location__r.BillingStreet))
               deliveryLocation = objB4B.Delivery_Location__r.BillingStreet+', ';
            if(!String.ISBLANK(objB4B.Delivery_Location__r.BillingCity))
               deliveryLocation += objB4B.Delivery_Location__r.BillingCity+', ';
            if(!String.ISBLANK(objB4B.Delivery_Location__r.BillingState))
               deliveryLocation += objB4B.Delivery_Location__r.BillingState+' ';
            if(!String.ISBLANK(objB4B.Delivery_Location__r.BillingPostalCode))
               deliveryLocation += objB4B.Delivery_Location__r.BillingPostalCode;
        
       }
       else 
            isDeliveryLocation = false;
         //  deliveryLocation =  String.ValueOf(objB4B.Traver_Project__r.Account__r.BillingAddress);
          System.debug('--deliveryLocation--'+deliveryLocation);
    }


}