SF Primes/src/objects/Traver_Coaching__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agenda Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRV_Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>TRV_Resource__c</referenceTo>
        <relationshipLabel>B4B Coaching (Completed By)</relationshipLabel>
        <relationshipName>TRV_Completed_By_B4BCoaching</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TRV_Push_Reason__c</fullName>
        <label>Push Reason</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Traver_Project__c</fullName>
        <label>Consulting Project</label>
        <referenceTo>Traver_Project__c</referenceTo>
        <relationshipLabel>B4B Coaching</relationshipLabel>
        <relationshipName>Traver_Onsite_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X5_Star_Guarantee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>5 Star Guarantee</label>
        <type>Checkbox</type>
    </fields>
    <label>B4B Coaching</label>
    <nameField>
        <displayFormat>B4B-{00000}</displayFormat>
        <label>B4B Coaching ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B4B Coaching</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Traver_Project__c.object
<CustomObject>
    <description>Project/Product object used by Traver Technologies</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Traver_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Consulting Project</label>
    <nameField>
        <displayFormat>Consulting# {00000}</displayFormat>
        <label>Consulting Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consulting Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/TRV_Resource__c.object
<CustomObject>
    <description>Used to manage individuals who are resources on Travers projects.
This data is displayed/filtered on the Resource Manager Visualforce page</description>
    <fields>
        <fullName>TRV_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TRV_Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA/src/classes/TRV_RMHelper_Test.cls
// 2016-02-25 endiem@endiem.com - RQ-05509 - Test class for RM_Helper class
@isTest
private class TRV_RMHelper_Test {
    
    private static testMethod void test_Helper() {

        List<User> lstUser = [
            SELECT Id, Name 
            FROM User 
            WHERE Id =: UserInfo.getUserId()
        ];
        
        Account objAccount = new Account(Name = 'Test Account');
        
        Account objAccount1 = new Account(Name = 'Test 5star Account');
        insert new List<Account>{objAccount, objAccount1};

        Traver_Project__c objTraverProj = new Traver_Project__c(Account__c = objAccount.Id);
        
        Traver_Project__c objTraverProj1 = new Traver_Project__c(Account__c = objAccount1.Id);
        insert new List<Traver_Project__c>{objTraverProj, objTraverProj1};
        
        TRV_Resource__c objResource = new TRV_Resource__c(TRV_Resource__c = lstUser[0].Id);
        TRV_Resource__c objResource1 = new TRV_Resource__c(TRV_Resource__c = lstUser[0].Id, TRV_Termination_Date__c = Date.Today());
        insert new List<TRV_Resource__c>{objResource, objResource1};
        
        Traver_Coaching__c objTraverCoach = new Traver_Coaching__c(
            Status__c = 'Scheduled', 
            Traver_Project__c = objTraverProj.Id,
            TRV_Push_Reason__c = 'Test', 
            TRV_Completed_By__c = objResource.Id
        );
        
        Traver_Coaching__c objTraverCoach1 = new Traver_Coaching__c(
            Status__c = 'Scheduled', 
            Traver_Project__c = objTraverProj1.Id,
            TRV_Push_Reason__c = 'Test', 
            TRV_Completed_By__c = objResource.Id,
            X5_Star_Guarantee__c = true
        );
        insert new List<Traver_Coaching__c>{objTraverCoach, objTraverCoach1};

        ApexPages.currentPage().getParameters().put('resourceId', objResource.Id);
        ApexPages.currentPage().getParameters().put('visitStartDate', String.valueOf(Date.Today()));
        ApexPages.currentPage().getParameters().put('ExMajor', '');
        ApexPages.currentPage().getParameters().put('ExMinor', '');
        ApexPages.currentPage().getParameters().put('skLevMajor', '');
        ApexPages.currentPage().getParameters().put('skLevMinor', '');

        TRV_ResourceManagement_Helper autoCompleteObj = new TRV_ResourceManagement_Helper();
        autoCompleteObj.redirectToFlow();

        system.assertEquals(true, autoCompleteObj.bRenderFlow);
        system.assertEquals('', autoCompleteObj.getmyID());

        autoCompleteObj.getB4BId();
        
        system.assertEquals(new List<Traver_Project__c>(), TRV_ResourceManagement_Helper.searchProject('Consu', objAccount.Id));
        
        system.assertEquals(2, TRV_ResourceManagement_Helper.searchAccount('Tes').size());
        
        system.assertEquals(false, TRV_ResourceManagement_Helper.five_Star_Gaurantee_B4B(objAccount.Id, objResource.Id));
        
        system.assertEquals(true, TRV_ResourceManagement_Helper.five_Star_Gaurantee_B4B(objAccount1.Id, objResource.Id));
        
        ApexPages.currentPage().getParameters().put('resourceId', objResource1.Id);
        ApexPages.currentPage().getParameters().put('visitStartDate', String.valueOf(Date.Today()+2));
        ApexPages.currentPage().getParameters().put('ExMajor', '');
        ApexPages.currentPage().getParameters().put('ExMinor', '');
        ApexPages.currentPage().getParameters().put('skLevMajor', '');
        ApexPages.currentPage().getParameters().put('skLevMinor', '');

        TRV_ResourceManagement_Helper autoCompleteObj1 = new TRV_ResourceManagement_Helper();
        autoCompleteObj1.redirectToFlow();
    }
}