SF Primes/src/objects/Traver_Coaching__c.object
<CustomObject>
    <fields>
        <fullName>TRV_Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>TRV_Resource__c</referenceTo>
        <relationshipLabel>B4B Coaching (Completed By)</relationshipLabel>
        <relationshipName>TRV_Completed_By_B4BCoaching</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Traver_Project__c</fullName>
        <label>Consulting Project</label>
        <referenceTo>Traver_Project__c</referenceTo>
        <relationshipLabel>B4B Coaching</relationshipLabel>
        <relationshipName>Traver_Onsite_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X5_Star_Guarantee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>5 Star Guarantee</label>
        <type>Checkbox</type>
    </fields>
    <label>B4B Coaching</label>
    <nameField>
        <displayFormat>B4B-{00000}</displayFormat>
        <label>B4B Coaching ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B4B Coaching</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Traver_Project__c.object
<CustomObject>
    <description>Project/Product object used by Traver Technologies</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Traver_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>B4B_Account_Name__c</fullName>
        <label>B4B Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSG_FRM_of_Days_PSG_Used__c</fullName>
        <formula>IF( ISBLANK( Total_Days_Purchased_PSG__c ) || Total_Days_Purchased_PSG__c = 0, 0, (Onsite_Days_Used_PSG__c + PSG_Onsite_Days_Forfeited_PSG__c) /Total_Days_Purchased_PSG__c)</formula>
        <label>% of Days PSG Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <inlineHelpText>Project Status</inlineHelpText>
        <label>Consulting Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRV_Consulting_Project_Name__c</fullName>
        <label>Consulting Project Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRV_FRM_of_Day_Traver_Used__c</fullName>
        <formula>IF( ISBLANK( Total_Days_Contracted_Traver__c ) || Total_Days_Contracted_Traver__c = 0, 0, (Onsite_Days_Used_Traver__c + TRV_Onsite_Days_Forfeited_Traver__c) /Total_Days_Contracted_Traver__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% of Day Traver Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Consulting Project</label>
    <nameField>
        <displayFormat>Consulting# {00000}</displayFormat>
        <label>Consulting Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consulting Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/TRV_Resource__c.object
<CustomObject>
    <description>Used to manage individuals who are resources on Travers projects.
This data is displayed/filtered on the Resource Manager Visualforce page</description>
    <fields>
        <fullName>TRV_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TRV_Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/classes/TRV_ResourceManagement_Helper.cls
// 2015-12-3 endiem@endiem.com - RQ-05509 - This is helper class for creating B4B Coaching record from flow.
public with sharing class TRV_ResourceManagement_Helper {
    
    // Instance fields
    public String searchTerm {get; set;}                                            // Variable to store search Term for Consulting Project
    public String selectedProject {get; set;}                                       // Variable to store Selected Project Id
    public String searchAccountTerm {get; set;}                                     // Variable to store search Term for Account
    public String selectedAccount {get; set;}                                       // Variable to store Id for Selected Account
    public Flow.Interview.B4BCoaching_Record_Creation b4bCoachingRecord {get;set;}  // Variable to Store b4B Coaching Instance
    public Boolean bRenderFlow {get;set;}                                           // Boolean variable to render Flow section on page
    public String strResourceId {get;set;}                                          // To Store Resource Id passed from URL
    public String expertiseMajor {get;set;}                                         // To Store Expertise Major passed from URL           
    public String expertiseMinor {get;set;}                                         // To Store Expertise Minor passed from URL           
    public String skillLevelMajor {get;set;}                                        // To Store Skill Level Major passed from URL           
    public String skillLevelMinor {get;set;}                                        // To Store Skill Level Minor passed from URL           
    public Date strVisitStartDate {get;set;}                                        // To Store Resource Id passed from URL           
    public Boolean bCanCreateB4B {get;set;}

    private final static Integer PERCENT_OF_DAYS_USED = 100;                        // Constant Variable 

    /* Start - Constructor */
    public TRV_ResourceManagement_Helper(){

        bRenderFlow = false;
        bCanCreateB4B = false;
        strResourceId = expertiseMajor = expertiseMinor = skillLevelMajor = skillLevelMinor = '';
        strResourceId = ApexPages.currentPage().getParameters().get('resourceId');
        
        Date dt = Date.valueOf(ApexPages.currentPage().getParameters().get('visitStartDate'));
        List<TRV_Resource__c> lstResource = [   
            SELECT TRV_Termination_Date__c 
            FROM TRV_Resource__c 
            WHERE Id =: strResourceId
        ];
        
        if(lstResource[0].TRV_Termination_Date__c != null && dt >= lstResource[0].TRV_Termination_Date__c){

            bCanCreateB4B = true;
        }
        
    }
    /* End - Constructor */
    
    //This method is used to find out Consulting Project bassed on selected account
    @RemoteAction
    public static List<Traver_Project__c> searchProject(String searchTerm, String selectedAcc) { 
        
        String projectQuery = ' Select Id, Name, TRV_Consulting_Project_Name__c from Traver_Project__c where Project_Status__c IN (\'Active\',\'Backlog\') ' +
                              ' AND PSG_FRM_of_Days_PSG_Used__c <: PERCENT_OF_DAYS_USED AND TRV_FRM_of_Day_Traver_Used__c <: PERCENT_OF_DAYS_USED AND Account__c =: selectedAcc ' +
                              ' AND (B4B_Account_Name__c like \'%' + String.escapeSingleQuotes(searchTerm) + '%\' OR ' +
                              ' TRV_Consulting_Project_Name__c like \'%' + String.escapeSingleQuotes(searchTerm) + '%\')';

        List<Traver_Project__c> Project = Database.query(projectQuery);
        return Project;
    }

    //This method is used to search for account based on search Term.
    @RemoteAction
    public static List<Account> searchAccount(String searchTerm) {
        
        List<Account> acc = Database.query('Select Id, Name from Account where name like \'%' + String.escapeSingleQuotes(searchTerm) + '%\'');
        return acc;
    }

    //This method is to find out if there is any B4B Coaching record whose X5_Star_Guarantee__c is checked.
    @RemoteAction
    public static Boolean five_Star_Gaurantee_B4B(String accountId, String resourceId) {
        
        List<Traver_Coaching__c> lstTraverCoaching = [  
            SELECT Id 
            FROM Traver_Coaching__c 
            WHERE TRV_Completed_By__c =: resourceId 
            AND Traver_Project__r.Account__c =: accountId 
            AND X5_Star_Guarantee__c = TRUE
         ];

        if(lstTraverCoaching.isEmpty()){

            return false;
        }
        else {

            return true;
        }
    }
    
    //This method is used to set the URL parameters to getter setter variables.
    public void redirectToFlow() {
        
        bRenderFlow = true;
        strVisitStartDate = Date.valueOf(ApexPages.currentPage().getParameters().get('visitStartDate'));
        
        strResourceId = ApexPages.currentPage().getParameters().get('resourceId');
        expertiseMajor = ApexPages.currentPage().getParameters().get('ExMajor');
        expertiseMinor = ApexPages.currentPage().getParameters().get('ExMinor');
        skillLevelMajor = ApexPages.currentPage().getParameters().get('skLevMajor');
        skillLevelMinor = ApexPages.currentPage().getParameters().get('skLevMinor');   
        
    }

    //This method is used to fetch B4B record Id which is being created from Flow.
    public String getmyID() {
        
        if (b4bCoachingRecord == null) {
        
            return '';
        }
        else {
            
            return b4bCoachingRecord.B4BRecordId;
        }  
    }
    
    //This method will redirect the flow page to the standard edit page of B4B Coaching record page.
    public PageReference getB4BId() {
    
        PageReference p = new PageReference('/' + getmyID() + '/e?retURL=' + getmyID());
        p.setRedirect(true);
        
        return p;
    }

}