SF Primes/src/objects/Traver_Coaching__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Days_PSG__c</fullName>
        <label>Number of Days - PSG</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_Traver__c</fullName>
        <inlineHelpText>Number of Days</inlineHelpText>
        <label>Number of Days - Traver</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agenda Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TRV_Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>TRV_Resource__c</referenceTo>
        <relationshipLabel>B4B Coaching (Completed By)</relationshipLabel>
        <relationshipName>TRV_Completed_By_B4BCoaching</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TRV_Number_Of_Days_NonBillable__c</fullName>
        <label>Number Of Days - NonBillable</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Traver_Project__c</fullName>
        <label>Consulting Project</label>
        <referenceTo>Traver_Project__c</referenceTo>
        <relationshipLabel>B4B Coaching</relationshipLabel>
        <relationshipName>Traver_Onsite_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Visit_Start_Date__c</fullName>
        <label>Visit Start Date</label>
        <type>Date</type>
    </fields>
    <label>B4B Coaching</label>
    <nameField>
        <displayFormat>B4B-{00000}</displayFormat>
        <label>B4B Coaching ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B4B Coaching</pluralLabel>
    <recordTypes>
        <fullName>Non_Billable</fullName>
        <active>true</active>
        <description>Track non-billable hours</description>
        <label>Non-Billable</label>
    </recordTypes>
    <recordTypes>
        <fullName>PSC_Visit</fullName>
        <active>true</active>
        <description>PSC Visit</description>
        <label>PSC Visit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process_Coach_Visit</fullName>
        <active>true</active>
        <description>Process Coach Visit</description>
        <label>Process Coach Visit</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF Primes/src/objects/Traver_Project__c.object
<CustomObject>
    <description>Project/Product object used by Traver Technologies</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Traver_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Traver_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Consulting Project</label>
    <nameField>
        <displayFormat>Consulting# {00000}</displayFormat>
        <label>Consulting Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consulting Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF Primes/src/objects/TRV_Resource__c.object
<CustomObject>
    <description>Used to manage individuals who are resources on Travers projects.
This data is displayed/filtered on the Resource Manager Visualforce page</description>
    <fields>
        <fullName>TRV_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fulldev2/src/classes/TRV_B4BCoaching_Test.cls
// 2015-12-08 endiem@endiem.com - RQ-05509 - Test class for B4B Coaching trigger and handler
@isTest
private class TRV_B4BCoaching_Test {
    
    private static testmethod void testEventCreation() {
        
        Id processCoachVisitId;
        Id nonBillaleTypeId;
        Id pscVisitTypeId;
        
        for(RecordType objRecordType : [
                SELECT Id, DeveloperName, SobjectType 
                FROM RecordType 
                WHERE SobjectType = 'Traver_Coaching__c'
            ]) {
            
            if(objRecordType.DeveloperName == 'Process_Coach_Visit') {
                
                processCoachVisitId = objRecordType.Id;
            }
            
            if(objRecordType.DeveloperName == 'Non_Billable') {
                
                nonBillaleTypeId = objRecordType.Id;
            }
            
            if(objRecordType.DeveloperName == 'PSC_Visit') {
                
                pscVisitTypeId = objRecordType.Id;
            }
        }
        
        List<User> lstUser = [
            SELECT Id, Name 
            FROM User 
            WHERE Id =: UserInfo.getUserId()
        ];
        
        Account objAccount = new Account(Name = 'Test Account');
        insert objAccount;
        
        Contact objContact = new Contact(
            LastName = 'Test Last Contact', 
            FirstName = 'Test First Contact', 
            Email = 'test@test.com', 
            AccountId = objAccount.Id
        );
        insert objContact;
        
        Traver_Project__c objTraverProj = new Traver_Project__c(
            Account__c = objAccount.Id,
            Contact__c = objContact.Id
        );
        insert objTraverProj;
        
        TRV_Resource__c objResource = new TRV_Resource__c(TRV_Resource__c = lstUser[0].Id);
        insert objResource;
        
        Traver_Coaching__c objTraverCoach = new Traver_Coaching__c(
            Status__c = 'Scheduled', 
            Traver_Project__c = objTraverProj.Id,
            TRV_Completed_By__c = objResource.Id,
            Number_of_Days_PSG__c = 18
        );
        
        Traver_Coaching__c objTraverCoach1 = new Traver_Coaching__c(
            Status__c = 'Confirmed', 
            Traver_Project__c = objTraverProj.Id,
            TRV_Completed_By__c = objResource.Id,
            RecordTypeId = nonBillaleTypeId,
            TRV_Number_Of_Days_NonBillable__c = 5
        );
        
        Traver_Coaching__c objTraverCoach2 = new Traver_Coaching__c(
            Status__c = 'Confirmed', 
            Traver_Project__c = objTraverProj.Id,
            TRV_Completed_By__c = objResource.Id,
            RecordTypeId = pscVisitTypeId,
            Visit_Start_Date__c = Date.today(),
            Number_of_Days_PSG__c = 3
        );
        
        insert new List<Traver_Coaching__c>{objTraverCoach, objTraverCoach1, objTraverCoach2}; 
        
        system.assertEquals(0, [SELECT ActivityDate, WhatId FROM Event WHERE WhatId =:objTraverCoach.Id ].size());
        
        objTraverCoach.Status__c = 'Confirmed';
        objTraverCoach.Number_of_Days_Traver__c = 18;
        update objTraverCoach;
        
        objTraverCoach.Visit_Start_Date__c = Date.today() + 1; 
        update objTraverCoach;
        system.assertEquals(2, [SELECT ActivityDate, WhatId FROM Event WHERE WhatId =:objTraverCoach.Id ].size());
        
        objTraverCoach.Status__c = 'Cancelled'; 
        update objTraverCoach;
        
        system.assertEquals(0, [SELECT ActivityDate, WhatId FROM Event WHERE WhatId =:objTraverCoach.Id ].size());
        
        objTraverCoach.RecordTypeId = processCoachVisitId;
        objTraverCoach.Status__c = 'Completed';
        objTraverCoach.TRV_Completed_By__c = null;
        update objTraverCoach;
        
        objTraverCoach.TRV_Completed_By__c = objResource.Id;
        update objTraverCoach;
        
        objTraverCoach1.Visit_Start_Date__c = Date.today() + 2;
        update objTraverCoach1;
        
        objTraverCoach2.Visit_Start_Date__c = Date.today() + 3;
        update objTraverCoach2;
    }
}